### PR TITLE
Increase majc priority for tablets over file size threshold

### LINKED ISSUE #4610: Tablet with lots of file may not be readable on scan servers for long periods of time.
**Describe the bug**

Tablets can only be scanned when they have less than a configurable number of files.   Scan servers remember a tablets files for a configurable time period.  If a tablet has too many files to scan then it may be unreadable on a scan server for scan servers configured period to remember tablets files even if the tablet is compacted.    

This is a suspected bug, need to write a test to confirm.  

**To Reproduce**

The following outlines a possible test to confirm this problem.

 * Configure max files for scan to 20
 * Somehow temporarily disable compactions on a test table
 * Create greater than 20 files on tablet in the test table
 * Set the scan server tablet metadata cache timeout to 10 mins
 * Attempt to scan the tablet w/ >20 files on a scan server
 * Wait a little bit
 * enable compactions to reduce the number of files.
 * See what happens with the scan started prior to the compaction

**Expected behavior**

Ideally soon after a tablet is compacted to have less than the max files for scan it would be readable on a scan server.

### PR DESCRIPTION
**Pull request by dlmarion**
CompactionManager.mainLoop runs in the TabletServer looking for tablets that need to be compacted. It ends up calling CompactionService.submitCompaction at some interval for each hosted Tablet. CompactionService.getCompactionPlan will make a CompactionPlan for the tablet and log a warning if no CompactionPlan is created but the number of files is larger than TSERV_SCAN_MAX_OPENFILES. When there are no compactions running for the tablet and no plan is calculated, then DefaultCompactionPlanner.makePlan takes into account TABLE_FILE_MAX and TSERV_SCAN_MAX_OPENFILES and will create a system compaction that considers all of the files and calculates which ones need to be compacted to get below the limit. Finally, a priority is calculated by calling CompactionJobPrioritizer.createPriority. However, given that this compaction is a SYSTEM compaction it will have a lower priority than all current USER compactions and it's priority will still be based on the total number of files. Given that the TABLE_FILE_MAX is per-table it's possible to have two tablets from different tables and the tablet that is over the size threshold has a lower priority than the tablet that is not over the size threshold. This change modifies
CompactionJobPrioritizer.createPriority to take into account whether or not the tablet is over the threshold to give it a higher priority.

Closes #4610

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 1]
```diff
@@ -44,6 +49,11 @@ public static short createPriority(CompactionKind kind, int totalFiles, int comp
         return (short) prio;
       case SELECTOR:
       case SYSTEM:
+        // Given that tablets with too many files cause several problems,
+        // boost their priority to the maximum allowed value.
+        if (condition == Condition.TABLET_OVER_SIZE) {
+          return Short.MAX_VALUE;
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:55]: Could possibly increment a metric for this condition, although I'm not sure how useful it would be. I think knowing that all of the external compactors and compaction threads in the tservers are fully utilized, along with a backlog of waiting compactions, is a more useful indication that more capacity is needed.

[the remark this answers is not in the document]
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:55]: If this change were made in 4.0 then could add third min max range to the following code

https://github.com/apache/accumulo/blob/7673a666899d82ee6e2f3e595fb55c688edee4f3/core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java#L94-L100

**Comment by keith-turner** [comment]
May still want to leave #4610 open after merging this.  This change is nice in that it helps compactions run faster for tablets over the threshold.  There is still the problem that scan servers cache the file list.  So if a scan server caches the list of files of a tablet w/ too many files for 5 mins then that tablet can not be scanned for that 5 min period even if it does compact.  Not sure of the best way to handle this, scan servers could possibly poll the tablets files a bit more frequently when a tablet is in this condition.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java]: Backported the other ranges and implemented your suggestion in 30644f1

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 2]
```diff
@@ -19,42 +19,120 @@
...
+      new HashMap<>();
+  private static final Map<Pair<NamespaceId,CompactionKind>,
+      Pair<Short,Short>> ACCUMULO_NAMESPACE_RANGES = new HashMap<>();
+
+  // Create ranges of possible priority values where each range has
+  // 2000 possible values. Give higher priority to tables where
+  // they have more files than allowed, user compactions over system
+  // compactions, root table over metadata table, metadata table over
+  // other system tables and user tables.
+  private static final Short TABLE_OVER_SIZE_MAX = Short.MAX_VALUE;
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:53]: Not sure these compactions should be given higher priority than root and metadata compactions.  Maybe this range could be moved between SYSTEM_NS_SYSTEM_MAX and USER_TABLE_USER_MAX.  Then the TABLE_OVER_SIZE range would only be used non accumulo namespaces.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 3]
```diff
@@ -19,42 +19,120 @@
...
-        return (short) prio;
-      case SELECTOR:
-      case SYSTEM:
-        // system-initiated compactions will have a negative priority
-        // starting at -32768 and increasing based on number of files
-        // maxing out at -1
-        if (prio > Short.MAX_VALUE) {
-          return -1;
+      } else {
+        if (kind == CompactionKind.SYSTEM) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:127]: The following would line up with what the old code was doing.  May be able to revert some changes to one of the unit test with this change.

```suggestion
        if (kind == CompactionKind.SYSTEM || kind == CompactionKind.SELECTOR) {
```

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 4]
```diff
@@ -19,42 +19,120 @@
...
+  private static final Short ROOT_TABLE_USER_MAX = Short.MAX_VALUE - 2001;
+  private static final Short ROOT_TABLE_SYSTEM_MAX = (short) (ROOT_TABLE_USER_MAX - 2001);
+  private static final Short META_TABLE_USER_MAX = (short) (ROOT_TABLE_SYSTEM_MAX - 2001);
+  private static final Short META_TABLE_SYSTEM_MAX = (short) (META_TABLE_USER_MAX - 2001);
+  private static final Short SYSTEM_NS_USER_MAX = (short) (META_TABLE_SYSTEM_MAX - 2001);
+  private static final Short SYSTEM_NS_SYSTEM_MAX = (short) (SYSTEM_NS_USER_MAX - 2001);
+  private static final Short USER_TABLE_USER_MAX = (short) (SYSTEM_NS_SYSTEM_MAX - 2001);
+  private static final Short USER_TABLE_SYSTEM_MAX = 0;
+
+  static final Pair<Short,Short> TABLE_OVER_SIZE =
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:63]: Not sure if this would be an improvement.  Was wondering if creating a little inner class like the following and using that would clean up the code a bit over use Pair.

```java
static class PrioRange {
   final short min;
   final short max;
  PrioRange(short min, short max){this.min=min;this.max=max;}
}
```

File: core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlanner.java [hunk 5]
```diff
@@ -79,6 +81,8 @@ public interface InitParameters {
    */
   public interface PlanningParameters {
 
+    NamespaceId getNamespaceId() throws TableNotFoundException;
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/spi/compaction/CompactionPlanner.java:84]: This is SPI code so should add a since tag.

```suggestion
   /**
     * @since 2.1.4
     */
    NamespaceId getNamespaceId() throws TableNotFoundException;
```

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java (hunk 4 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:63]: I guess it depends on what kind of improvement you are looking for. I did look at [Pair](https://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/util/Pair.html) in commons-math3. There is also [Range](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/Range.html) in commons-lang. I'm thinking the latter might be a good replacement here.

**Comment by dlmarion** [comment]
@keith-turner  - I think I addressed all of your suggestions in the latest commit.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 6]
```diff
@@ -19,42 +19,167 @@
...
+  // user tables user initiated
+  // user tables system initiated
+  private static final Short ROOT_TABLE_USER_MAX = Short.MAX_VALUE;
+  private static final Short ROOT_TABLE_SYSTEM_MAX = (short) (ROOT_TABLE_USER_MAX - 2001);
+  private static final Short META_TABLE_USER_MAX = (short) (ROOT_TABLE_SYSTEM_MAX - 2001);
+  private static final Short META_TABLE_SYSTEM_MAX = (short) (META_TABLE_USER_MAX - 2001);
+  private static final Short SYSTEM_NS_USER_MAX = (short) (META_TABLE_SYSTEM_MAX - 2001);
+  private static final Short SYSTEM_NS_SYSTEM_MAX = (short) (SYSTEM_NS_USER_MAX - 2001);
+  private static final Short TABLE_OVER_SIZE_MAX = (short) (SYSTEM_NS_SYSTEM_MAX - 2001);
+  private static final Short USER_TABLE_USER_MAX = (short) (TABLE_OVER_SIZE_MAX - 2001);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:89]: It looks like each of these ranges are of size 2001, instead of 2000. It looks like 2000 was used to handle an edge case, but using it for every range seems incorrect. However, it might be correct, because later, the `PriorityRange.of` methods all have a `+ 1` in them.

All of it is very difficult to read.

I think it'd be much easier to read if these constants just got removed, and the PriorityRange objects were constructed with explicit integer literals, where it was clear what their ranges were. A unit test could trivially verify that they are adjacent and non-overlapping with a couple of lines of code.

Guava has a built-in Range type that would be perfect for these, so we don't need to use our own custom range type.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java]: I made this change in ff4b3d1, but I used commons-lang Range instead of Guava because it looked like a simpler implementation.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java (hunk 4 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java]: The improvement I Was thinking of was just making the code easier to read.   When reviewing the code I was like ok so what does getFirst() mean, oh that means getMin().  So just thought that min and max terminology instead of getFirst() and getSecond() would make the code easier to read.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java]: The latest changes have getMinimum and getMaximum which is much easier to read.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 7]
```diff
@@ -19,42 +19,127 @@
...
+      public Short apply(Range<Short> f) {
+        return (short) Math.min(f.getMaximum(),
+            f.getMinimum() + compactingFiles + (totalFiles - maxFilesPerTablet));
+      }
+    };
+
+    Range<Short> range = null;
+    Function<Range<Short>,Short> func = normalPriorityFunction;
+    if (Namespace.ACCUMULO.id() == nsId) {
+      // Handle system tables
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:120]: There could be chop compactions when merging the metadata table and these may end w/ a null range causing an exception. Need to add handling for kind of chop.   Will have to drop this in the 3.1 code.

File: core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java [hunk 8]
```diff
@@ -28,56 +37,133 @@
...
-
-    assertEquals((short) -32768,
-        CompactionJobPrioritizer.createPriority(CompactionKind.SYSTEM, 0, 0));
-    assertEquals((short) -22768,
-        CompactionJobPrioritizer.createPriority(CompactionKind.SYSTEM, 10000, 0));
-    assertEquals((short) -1,
-        CompactionJobPrioritizer.createPriority(CompactionKind.SYSTEM, 32767, 0));
-    assertEquals((short) -1,
-        CompactionJobPrioritizer.createPriority(CompactionKind.SYSTEM, Integer.MAX_VALUE, 0));
+  public void testRootTablePriorities() {
```
Comment (keith-turner) [inline core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java:66]: Can add chop compaction kind to these accumulo system table test.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 9]
```diff
@@ -19,42 +19,127 @@
...
+  // root table user initiated
+  // root table system initiated
+  // metadata table user initiated
+  // metadata table system initiated
+  // other tables in accumulo namespace user initiated
+  // other tables in accumulo namespace system initiated
+  // user tables that have more files that configured system initiated
+  // user tables user initiated
+  // user tables system initiated
+  static final Range<Short> ROOT_TABLE_USER = Range.of((short) 30768, (short) 32767);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:61]: I would be nice to ensure all of these ranges are non overlapping and cover everything from short min to short max.  This may already be happening indirectly in the unit test, so may not need an explicit test.

File: core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java [hunk 10]
```diff
@@ -28,56 +37,133 @@
...
+            CompactionKind.SYSTEM, 3000, 0, TABLET_FILE_MAX));
+  }
+
+  @Test
+  public void testSystemNamespacePriorities() {
+    TableId tid = TableId.of("someOtherSystemTable");
+    assertEquals(SYSTEM_NS_USER.getMinimum(), CompactionJobPrioritizer
+        .createPriority(Namespace.ACCUMULO.id(), tid, CompactionKind.USER, 0, 0, TABLET_FILE_MAX));
+    assertEquals(SYSTEM_NS_USER.getMinimum() + 1000, CompactionJobPrioritizer.createPriority(
+        Namespace.ACCUMULO.id(), tid, CompactionKind.USER, 1000, 0, TABLET_FILE_MAX));
```
Comment (keith-turner) [inline core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java:105]: A lot of test use zero for the num compacting files.  May be good to use something greater than zero to ensure its included in computation.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java]: In your changes to the monitor its now scanning the metadata table periodically.  In that scan it could compute the number of tablets over the max per table and display that on the monitor.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java (hunk 9 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:61]: Added at test for this in 74d66b2

File: core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java (hunk 8 above)
Comment (dlmarion) [reply core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java:109]: Added in 74d66b2

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java (hunk 7 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:127]: In 74d66b2 I added code to treat CHOP as USER compaction kind.

File: core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java [hunk 11]
```diff
@@ -19,42 +19,135 @@
...
+      public Short apply(Range<Short> f) {
+        return (short) Math.min(f.getMaximum(),
+            f.getMinimum() + compactingFiles + (totalFiles - maxFilesPerTablet));
+      }
+    };
+
+    // Handle the case of a CHOP compaction. For the purposes of determining
+    // a priority, treat them as a USER compaction.
+    CompactionKind calculationKind = kind;
+    if (kind == CompactionKind.CHOP) {
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/compaction/CompactionJobPrioritizer.java:120]: Implemented in 4c24262

File: core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java [hunk 12]
```diff
@@ -62,73 +66,138 @@ public CompactionJob createJob(CompactionKind kind, String tablet, int numFiles,
...
+    });
+    // check that the max of the previous range is one less than the
+    // minimum of the current range to make sure there are no holes.
+    short lastMax = Short.MIN_VALUE;
+    for (Range<Short> r : ranges) {
+      if (lastMax != Short.MIN_VALUE) {
+        assertTrue(r.getMinimum() - lastMax == 1);
+      }
+      lastMax = r.getMaximum();
+    }
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/test/java/org/apache/accumulo/core/util/compaction/CompactionPrioritizerTest.java:107]: Implemented in 4c24262
