### PR TITLE
Attempt to prevent half-closed Tablet due to failing minc

### LINKED ISSUE #3674: Invalid context causes minc to fail, leaving Tablet in CLOSED state on split
**Describe the bug**

Call chain:

AddSplitsCommand ->
TableOperationsImpl.addSplits (in a loop) ->
TabletClientHandler.splitTablet (throws NotServingTabletException) ->
TabletServer.splitTablet ->
Tablet.split ->
Tablet.initiateClose

On the first iteration of the loop in `TableOperationsImpl.addSplits`, `Tablet.initiateClose` sets the `closingState` to `CLOSING`, closes the Compactable, and kicks off a minc. The MinorCompactionTask fails to load the VolumeChooser due to a invalid classloader context being set on the table.

```
2023-07-31T20:56:08,007 [tablet.MinorCompactionTask] ERROR: Unknown error during minor compaction for extent: 1<<
java.lang.RuntimeException: Failed to create instance for 1 configured to use org.apache.accumulo.core.spi.fs.PreferredVolumeChooser via volume.chooser
        at org.apache.accumulo.core.spi.fs.DelegatingChooser.lambda$createVolumeChooser$0(DelegatingChooser.java:161) ~[accumulo-core-2.1.1.jar:2.1.1]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908) ~[?:?]
        at org.apache.accumulo.core.spi.fs.DelegatingChooser.createVolumeChooser(DelegatingChooser.java:142) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.spi.fs.DelegatingChooser.getVolumeChooserForTable(DelegatingChooser.java:95) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.spi.fs.DelegatingChooser.getDelegateChooser(DelegatingChooser.java:70) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.spi.fs.DelegatingChooser.choose(DelegatingChooser.java:59) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.server.fs.VolumeManagerImpl.choose(VolumeManagerImpl.java:479) ~[accumulo-server-base-2.1.1.jar:2.1.1]
        at org.apache.accumulo.tserver.tablet.Tablet.chooseTabletDir(Tablet.java:250) ~[accumulo-tserver-2.1.1.jar:2.1.1]
        at org.apache.accumulo.tserver.tablet.Tablet.getNextMapFilename(Tablet.java:258) ~[accumulo-tserver-2.1.1.jar:2.1.1]
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:79) ~[accumulo-tserver-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.1.jar:2.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.1.jar:2.1.1]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: Unknown context invalid
        at org.apache.accumulo.start.classloader.vfs.ContextManager.getClassLoader(ContextManager.java:166) ~[accumulo-start-2.1.1.jar:2.1.1]
        at org.apache.accumulo.start.classloader.vfs.AccumuloVFSClassLoader.getContextClassLoader(AccumuloVFSClassLoader.java:420) ~[accumulo-start-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory.getClassLoader(DefaultContextClassLoaderFactory.java:99) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.classloader.ClassLoaderUtil.getClassLoader(ClassLoaderUtil.java:79) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.classloader.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:87) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.conf.ConfigurationTypeHelper.getClassInstance(ConfigurationTypeHelper.java:199) ~[accumulo-core-2.1.1.jar:2.1.1]
        at org.apache.accumulo.server.ServiceEnvironmentImpl.instantiate(ServiceEnvironmentImpl.java:69) ~[accumulo-server-base-2.1.1.jar:2.1.1]
        at org.apache.accumulo.core.spi.fs.DelegatingChooser.lambda$createVolumeChooser$0(DelegatingChooser.java:154) ~[accumulo-core-2.1.1.jar:2.1.1]
```

`Tablet.split` then calls `Tablet.completeClose`which sets the `closeState` to `CLOSED`. I don't have enough information to know where this first iteration fails after this point, but I'm assuming that it does fail and the Tablet state is set to CLOSED. The first iteration ends in TableOperationsImpl.addSplits with an exception, which may not be logged on the client side, and then the operation is tried again. On the subsequent call to `Tablet.initiateClose` in `Tablet.split` an IllegalStateException is thrown because the Tablet is already `CLOSED`. `Tablet.split` logs `File 1<< not splitting : Tablet 1<< already CLOSING` and returns null. Returning null causes `TabletClientHandler.splitTablet` to throw a `NotServingTabletException` which is caught by `TableOperationsImpl.addSplits` and retried. It appears that this will retry *forever*.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.2-SNAPSHOT

**To Reproduce**
User was able to replicate the issue with the configuring Accumulo with:
```
general.volume.chooser=org.apache.accumulo.core.spi.fs.DelegatingChooser
general.custom.volume.chooser.default=org.apache.accumulo.core.spi.fs.PreferredVolumeChooser
general.custom.volume.preferred.default=hdfs://localhost:8020/accumulo
```

and then running the following in the shell:
```
root@uno> insert -t test1 a c1 q1 v1
root@uno> insert -t test1 b c1 q1 v1
root@uno> insert -t test1 c c1 q1 v1
root@uno> config -t test1 -s table.class.loader.context=invalid
root@uno> flush -t test1
2023-07-31T22:21:28,451 [shell.Shell] INFO : Flush of table test1  initiated...
root@uno> config -t test1 -d table.class.loader.context
root@uno> scan -t test1
a c1:q1 []	v1
b c1:q1 []	v1
c c1:q1 []	v1
root@uno> addsplits -t test1 b
```

### PR DESCRIPTION
**Pull request by dlmarion**
Prior to this change Tablet.initiateClose would close the compactable, wait for the current minor compaction to finish, and then kick off another minor compaction. In the case where minor compactions are failing, the compactable will get closed and the call to wait for the current minor compaction to finish will hang indefinitely leaving the Tablet in a half-closed state. Tablet.initiateClose is called when either the TabletServer is closing the Tablet (due to migration or shutdown) or on a Tablet split. Therefore, a failing minor compaction will prevent Tablet migration and split or normal TabletServer shutdown.

This change adds some logic at the start of Tablet.initiateClose to try and detect a currently or previously failing minor compaction. In these cases an exception is thrown before the compactable is closed to prevent the Tablet from being in a half-closed state. This prevents the Tablet from being closed until the cause for the failing minor compaction is corrected. Causes could be a bad iterator applied at minor compaction or a bad table configuration option (like classloader context). When the cause of the failing minor compaction is corrected, then the Tablet should be able to be closed normally allowing normal migration, split, and TabletServer shutdown.

Fixes #3674

### CODE REVIEW

**Comment by dlmarion** [comment]
Kicked off full IT build

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 1]
```diff
@@ -901,6 +903,47 @@ public void close(boolean saveState) throws IOException {
   void initiateClose(boolean saveState) {
     log.trace("initiateClose(saveState={}) {}", saveState, getExtent());
 
+    // Check to see if last or current minc is failing. If so, then thrown
```
Comment (ivakegg) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:906]: thrown -> throw

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 2]
```diff
@@ -901,6 +903,47 @@ public void close(boolean saveState) throws IOException {
...
+                + ". Tablet might be closed or deleting.";
+            log.warn(msg);
+            throw new RuntimeException(msg);
+          }
+          // Not calling getTabletMemory().waitForMinC(); as it will wait
+          // indefinitely for a successful minor compaction. It's possible
+          // that won't happen. We just want to know if the current minc
+          // fails.
+          while (isMinorCompactionRunning()) {
+            UtilWaitThread.sleepUninterruptibly(50, TimeUnit.MILLISECONDS);
```
Comment (ivakegg) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:932]: This could wait forever ?

File: server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java [hunk 3]
```diff
@@ -178,6 +178,14 @@ private static CompactionDispatcher createCompactionDispatcher(AccumuloConfigura
     CompactionDispatcher newDispatcher = Property.createTableInstanceFromPropertyName(conf,
         Property.TABLE_COMPACTION_DISPATCHER, CompactionDispatcher.class, null);
 
+    if (newDispatcher == null) {
+      // return early to prevent NPE
+      log.error(
```
[the remark this answers is not in the document]
Comment (ivakegg) [reply server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java:183]: Does it need to be an error however?  Could it be a debug or info?

[the remark this answers is not in the document]
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java:183]: In the case where an invalid classloader context is set, then `Property.createTableInstanceFromPropertyName` cannot even return the *default* CompactionDispatcher specified in `Property.TABLE_COMPACTION_DISPATCHER`. This being null is a symptom of a misconfiguration of the context class loader. I think it's correct to point out the error here.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java [hunk 4]
```diff
@@ -1473,6 +1473,13 @@ public CompactionServiceId getConfiguredService(CompactionKind kind) {
     try {
       var dispatcher = tablet.getTableConfiguration().getCompactionDispatcher();
 
+      if (dispatcher == null) {
+        log.error(
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java:1477]: Again, this points to an error in the classloader context configuration.

**Comment by dtspence** [comment]
@dlmarion We believe we found a code path that produces a test timeout. It appeared to be related to a minc thread exiting due to not being able to obtain a mapfile (i.e. volume chooser seeing invalid context). The code-path in the integration test saw an error within the `MinorCompactor` and logged a retrying minc operation (possibly leaving minc thread active).

The calling path that causes the thread to end (i.e. context error w/volume-chooser) logged the tablets were unable to unload.

The logs report the following (w/minc thread exit path) when attempting to shutdown:
```
2023-08-03T16:03:32,503 [tserver.UnloadTabletHandler] INFO : Tablet unload for extent 1<< requested.
2023-08-03T16:03:32,503 [tablet.Tablet] DEBUG: 1<< closeState OPEN tabletMemory.memoryReservedForMinC() true tabletMemory.getMemTable().getNumEntries() 0 updatingFlushID false
2023-08-03T16:03:32,503 [tablet.Tablet] WARN : Unable to initiate minc for close on 1<<. Tablet might be closed or deleting.
2023-08-03T16:03:32,503 [tserver.UnloadTabletHandler] ERROR: Failed to close tablet 1<<... Aborting migration
java.lang.RuntimeException: Unable to initiate minc for close on 1<<. Tablet might be closed or deleting.
        at org.apache.accumulo.tserver.tablet.Tablet.initiateClose(Tablet.java:925) ~[classes/:?]
        at org.apache.accumulo.tserver.tablet.Tablet.close(Tablet.java:898) ~[classes/:?]
        at org.apache.accumulo.tserver.UnloadTabletHandler.run(UnloadTabletHandler.java:92) [classes/:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

To replicate, the following is needed as base configuration:

```java
    @Override
    public void configureMiniCluster(MiniAccumuloConfigImpl cfg, Configuration coreSite) {
      cfg.setNumTservers(1);
      cfg.setProperty("general.volume.chooser", "org.apache.accumulo.core.spi.fs.DelegatingChooser");
      cfg.setProperty("general.custom.volume.chooser.default",
              "org.apache.accumulo.core.spi.fs.PreferredVolumeChooser");
      cfg.setProperty("general.custom.volume.preferred.default", "file:/home/dtspen2/dev/git/dlmarion/accumulo/test/target/mini-tests/org.apache.accumulo.test.functional.HalfClosedTabletIT_SharedMiniClusterBase/accumulo");
    }
```

Then a `flush()` operation which caused the minc thread to end:
```java
      tops.setProperty(tableName, Property.TABLE_CLASSLOADER_CONTEXT.getKey(), "invalid");

      tops.flush(tableName);

      Thread.sleep(500);

      // This should fail to split, but not leave the tablets in a state where they can't
      // be unloaded
      assertThrows(AccumuloServerException.class,
          () -> tops.addSplits(tableName, Sets.newTreeSet(List.of(new Text("b")))));

      tops.removeProperty(tableName, Property.TABLE_CLASSLOADER_CONTEXT.getKey());
```

**Comment by dlmarion** [comment]
I looked into this path where the minor compaction thread was dying because an invalid classloader context could not load the volume chooser to create the minor compaction output file.  The issue is more serious that what I initially thought, but thankfully the fix is easy.

TLDR - A failed minor compaction thread might likely mean that subsequent minor compactions for a Tablet will **not** occur.  The fix is to catch `Exception` rather than `IOException` in `MinorCompactionTask` when creating the output file as in this scenario a `RuntimeException` is thrown.


Longer analysis
---

`TableOperationsImpl.flush` calls `ManagerClientServiceHandler.initiateFlush` which increments
the value of the tables `ZTABLE_FLUSH_ID` node in ZooKeeper, and returns the new value. Then
`TableOperationsImpl.flush` calls `ManagerClientServiceHandler.waitForFlush` passing in the flushId.
`ManagerClientServiceHandler.waitForFlush` initially calls `TabletClientHandler.flush` on *every tablet server in the cluster*. If the client is not waiting for the flush to return then this returns and `TableOperationsImpl.flush` is done. If the client is waiting, then `ManagerClientServiceHandler` looks for tablets that are hosted or has walogs and whose flushId in the tablet metadata is less than the flushId returned from `initiateFlush`. Then `waitForFlush` continues to call `TabletClientHandler.flush` on the hosts that have tablets that meet this criteria for Long.MAX_VALUE iterations.

`TabletClientHandler.flush` does nothing if the TabletServer does not have any tablets for the table. Otherwise it gets the current value of the tables `ZTABLE_FLUSH_ID`, which should be the same as the flushId returned at the beginning of this process. `Tablet.flush` is called on each of the Tablets for the Table on this TabletServer.

If the Tablet has no entries in memory, then the tablet metadata is updated with the flushId and the variable `lastFlushID` is set to the flushId. If `Tablet.flush()` was called again on this Tablet with the same flushID, then it would do nothing.

If the Tablet has entries in memory, then `Tablet.initiateMinorCompaction` is called, which may or may not create a MinorCompactionTask. If one is created, then it is executed in the minorCompactionThreadPool. `Tablet.initiateMinorCompaction` will not return a MinorCompactionTask if the tablet is closing, is closed, if there are no entries in memory, if there is another thread updating `lastFlushID`, or if the Tablets memory is already reserved for a minor compaction (meaning if one is already running).

MinorCompactionTask when executed will create a new output file and call `TabletServer.minorCompactionStarted`, then it calls `Tablet.minorCompact()`. `Tablet.minorCompact` performs the minor compaction, then brings the minor compaction online by calling `DatafileManager.bringMinorCompactionOnline`, then calls `TabletMemory.finalizeMinC`. `DatafileManager.bringMinorCompactionOnline` sets `lastFlushID` and calls `Tablet.flushComplete` which sets `lastFlushID` and calls `TabletMemory.finishedMinC`.

If `TabletMemory.finalizeMinC` and `TabletMemory.finishedMinC` are not called, then it appears that the tablet memory is already reserved for a minor compaction and a subsequent minor compaction will *never* start. This appears to be what is happening when there is an invalid context on the table as the call to create a new output file returns a RuntimeException. Only IOExceptions are caught at this location and the Thread dies due to the uncaught exception.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 5]
```diff
@@ -901,6 +903,47 @@ public void close(boolean saveState) throws IOException {
...
+      if (!isLastMinCSuccessful()) {
+        if (isMinorCompactionRunning()) {
+          // Then current minor compaction is retrying and failure is being
+          // reported.
+          String msg = "Aborting close on " + extent
+              + " because last minor compaction was not successful. Check the server log.";
+          log.warn(msg);
+          throw new RuntimeException(msg);
+        } else {
+          // We don't know when the last minc occurred. Kick one off now.
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java]: This was reworked in 925e26e

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java (hunk 1 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java]: This was fixed in 925e26e

File: server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java:183]: GIven the changes in #3678 , this message should hopefully not appear that much anymore. I think it's fine to leave this at ERROR in this case because that would mean a failure of the check in #3678

**Review by EdColeman — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+import org.apache.accumulo.harness.SharedMiniClusterBase;
+import org.apache.accumulo.miniclusterImpl.MiniAccumuloConfigImpl;
+import org.apache.accumulo.test.util.Wait;
+import org.apache.hadoop.conf.Configuration;
+import org.apache.hadoop.io.Text;
+import org.junit.jupiter.api.AfterAll;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.Test;
+
+public class HalfClosedTablet2IT extends SharedMiniClusterBase {
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java:40]: The other IT got a javadoc, but it's not clear why this similarly named one exists in a separate file.

**Review by ctubbsii — COMMENTED** [review]
The approach here looks good to me.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java (hunk 6 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java:47]: comments added in 05cd496

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java [hunk 7]
```diff
@@ -0,0 +1,121 @@
...
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.Test;
+
+//This IT tests the cases seen in https://github.com/apache/accumulo/issues/3674
+//where a failing minor compaction causes a Tablet.initiateClose to leave the
+//Tablet in a half-closed state. The half-closed Tablet cannot be unloaded and
+//the TabletServer cannot be shutdown normally. Because the minor compaction has
+//been failing the Tablet needs to be recovered when it's ultimately re-assigned.
+//The test in this class sets up a VolumeChooser configuration on MiniAccumuloCluster
+//to test a specific code path that caused the minor compaction thread to die.
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTablet2IT.java:46]: My suggestion to make this description slightly more concise, and adding spaces after the double-slashes to conform to our normal comment style.

```suggestion
// This covers issues like that reported in https://github.com/apache/accumulo/issues/3674
// where a failing minor compaction leaves the Tablet in a half-closed state that prevents it
// from unloading and the TServer from shutting down normally.
// This test recreates that scenario by setting an invalid context and verifies that the
// tablet can recover and unload after the context is set correctly.
```

**Review by ctubbsii — COMMENTED** [review]
Small style and wording suggestion, but otherwise, seems fine to me.

**Review by ctubbsii — APPROVED** [review]

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java [hunk 8]
```diff
@@ -1473,6 +1473,13 @@ public CompactionServiceId getConfiguredService(CompactionKind kind) {
     try {
       var dispatcher = tablet.getTableConfiguration().getCompactionDispatcher();
 
+      if (dispatcher == null) {
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java:1476]: Was this if stmt added to avoid logging an NPE later in the code?

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java [hunk 9]
```diff
@@ -1473,6 +1473,13 @@ public CompactionServiceId getConfiguredService(CompactionKind kind) {
...
+        log.error(
+            "Failed to dispatch compaction {} kind:{} hints:{}, falling back to {} service. Check server log.",
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java:1478]:
```suggestion
            "Failed to dispatch compaction {} kind:{} hints:{}, falling back to {} service. Unable to instantiate dispatcher plugin.  Check server log.",
```

File: server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java (hunk 3 above)
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java:183]: Not sure if this matters.  The log level of error here does not match the log level of the message in `ConfigurationTypeHelper.getClassInstance()` which is warn.  The log message from `ConfigurationTypeHelper.getClassInstance()` will probably contain the information the user needs to determine why the compaction dispatcher plugin did not load.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java [hunk 10]
```diff
@@ -1009,6 +1009,9 @@ public void splitTablet(TInfo tinfo, TCredentials credentials, TKeyExtent tkeyEx
       } catch (IOException e) {
         log.warn("Failed to split " + keyExtent, e);
         throw new RuntimeException(e);
+      } catch (RuntimeException re) {
+        log.warn("Failed to split " + keyExtent, re);
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java:1013]: Was this code only added to log additional information?

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 11]
```diff
@@ -190,6 +190,7 @@ enum CompactionState {
   private CompactableImpl compactable;
 
   private volatile CompactionState minorCompactionState = null;
+  private volatile boolean lastMinCSuccessful = true;
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:193]: Could remove this if the code that checks it in close is removed.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 12]
```diff
@@ -0,0 +1,219 @@
...
+
+      Thread.sleep(500);
+
+      // This should fail to split, but not leave the tablets in a state where they can't
+      // be unloaded
+      assertThrows(AccumuloServerException.class,
+          () -> tops.addSplits(tableName, Sets.newTreeSet(List.of(new Text("b")))));
+
+      removeInvalidClassLoaderContextPropertyWithoutValidation(getCluster().getServerContext(),
+          tableId);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:120]: I tried removing the code in initiateClose and running the test locally.  Made the following changes to this test to get it running.

```suggestion
      Thread configFixer = new Thread(() -> {
        UtilWaitThread.sleep(3000);
        removeInvalidClassLoaderContextPropertyWithoutValidation(getCluster().getServerContext(),
                tableId);
      });

      // grab this time before starting the thread starts and before it sleeps.
      long t1 = System.nanoTime();
      configFixer.start();

      // The split will probably start running w/ bad config that will cause it to get stuck.  However once the config is fixed by the background thread it should continue.
      tops.addSplits(tableName, Sets.newTreeSet(List.of(new Text("b"))));
      long t2 = System.nanoTime();

      // expect that split took at least 3 seconds because that is the time it takes to fix the config
      assertTrue(TimeUnit.NANOSECONDS.toMillis(t2-t1) > 3000);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 13]
```diff
@@ -901,6 +902,39 @@ public void close(boolean saveState) throws IOException {
...
+      // minor compaction on the tablet before closing it.
+      if (!isLastMinCSuccessful()) {
+        String msg = "Aborting close on " + extent
+            + " because last minor compaction was not successful. Check the server log.";
+        log.warn(msg);
+        throw new RuntimeException(msg);
+      }
+
+    }
+
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:937]: > If we find more places where the minor compaction code could have retried and it did not, then I think we should modify that minor compaction code to make it retry there.

If we do that, and remove this check or something like it, then until we found and fixed all of the places where this happens Tablets could still get into a bad state where the only remedy is a restart of all TabletServers.

> This code has some race conditions, for example a minor compaction could fail in another thread right after the check in this function. So the checks here do not completely solve the problem.

Agreed, it's best effort. Maybe there is a way to fix the race condition and prevent another minc from starting?

File: server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java (hunk 3 above)
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java:183]: Before this change the log file was getting peppered with NPE stack traces from below. This change was to make a single line log entry. I can't tell if you are making a suggestion with your comment on changing the log level or removing this, or just stating that the user should be able to find the information in the log as suggested in this log entry.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java (hunk 10 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java:1013]: Yes, otherwise there is nothing in the log on the server side IIRC. The RuntimeException gets passed back to the client, but when that happens most of the detail is lost.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java (hunk 8 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java:1476]: Yes, when the context was invalid the logs were being polluted with stack traces.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 12 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:120]: My guess is that it works because I changed the catch clause in MinorCompactionTask from IOException to Exception. If you were to revert that single change, then I think this would fail and leave the tablet in a bad state.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:937]: > If I understand correctly, the observed issue was fixed by catching Exception instead of IOException in MinorCompaction task. If that is correct then I think it may be best to remove this code for the following reasons.

I believe that is true, I think that solved this specific issue. The code I added in `Tablet.initiateClose` was to try and prevent the tablet from getting into a bad state for some other unknown failure scenario. My concern is that a user could miss the fact that minor compactions are failing. Then, either due to a call to `split`, Tablet migration, or TabletServer close the Tablet gets put into a half-closed state because `compactable.close` is called. The only remedy for this situation currently is a hard shutdown of the TabletServer. The user does not have the option of fixing the issue and getting a successful minor compaction. Depending on how long this has been occurring, the recovery time could be lengthy. It this issue affects multiple TabletServers, then you could be looking at an entire system restart with a long recovery period.

[the remark this answers is not in the document]
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:937]: @EdColeman , @keith-turner , and I had a discussion about this. I'm going to remove this code from this PR and @keith-turner is going to evalutate doing something similar, but in a different manner.

[the remark this answers is not in the document]
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java]: Removed this code in 31260e0.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java (hunk 11 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java]: Removed in 31260e0

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 12 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java]: I made these changes in 9f84ed4, however 2/3 of these new tests no longer work. I believe that is because I merged 3678 into 2.1 and into this branch. The tests that are failing are setting an invalid context, and when ClassLoaderUtil.getClassLoader is called, the context is not valid, and the non-context aware classloader is returned instead of the code returning null or throwing an error.

**Comment by keith-turner** [comment]
#3685 moves the first minor compaction in tablet close to happen before any variables are set that begin the close process.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 12 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java]: @keith-turner - If #3683 is merged, then I think that these tests will work again.

**Comment by dlmarion** [comment]
I re-ran the tests after #3683 and #3685 were merged into 2.1. Everything appears to be working. However, it's possible that the tests could pass without the minor compactions failing. This could happen if, for example, the minor compaction kicks off before the tablet server gets the property update to set an invalid context. I verified via log inspection that failures were happening and that it recovered. It would be good in the future to add some metrics or something that can be checked in the test to confirm that failures do happen on the minc before the configuration is corrected.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 14]
```diff
@@ -0,0 +1,279 @@
...
+  }
+
+  public static void setInvalidClassLoaderContextPropertyWithoutValidation(ServerContext context,
+      TableId tableId) {
+    TablePropKey key = TablePropKey.of(context, tableId);
+    context.getPropStore().putAll(key,
+        Map.of(Property.TABLE_CLASSLOADER_CONTEXT.getKey(), "invalid"));
+  }
+
+  public static void removeInvalidClassLoaderContextPropertyWithoutValidation(ServerContext context,
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:256]: This comment is just a general question. Wondering if we need this method, it validation performed when a prop is deleted that prevents removal of a bad context config?  If so it seems like that could be a general problem.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:256]: I could try running it without this method. I think you might be correct, that it's not needed. It could also be removed and tested in a follow-on.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 15]
```diff
@@ -0,0 +1,279 @@
...
+      TableId tableId) {
+    TablePropKey key = TablePropKey.of(context, tableId);
+    context.getPropStore().removeProperties(key,
+        List.of(Property.TABLE_CLASSLOADER_CONTEXT.getKey()));
+  }
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:261]: I tried replacing this method locally w/ the following and changing the places where it was called and everything worked.

```suggestion
  public static void removeInvalidClassLoaderContextProperty(AccumuloClient client,
      String tableName) {
    try {
      client.tableOperations().removeProperty(tableName, Property.TABLE_CLASSLOADER_CONTEXT.getKey());
    } catch (AccumuloException | AccumuloSecurityException e) {
      throw new RuntimeException(e);
    }
  }
```

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 16]
```diff
@@ -0,0 +1,279 @@
...
+      try (BatchWriter bw = c.createBatchWriter(tableName)) {
+        Mutation m = new Mutation(new Text("r1"));
+        m.put("acf", tableName, "1");
+        bw.addMutation(m);
+      }
+
+      IteratorSetting setting = new IteratorSetting(50, "error", ErrorThrowingIterator.class);
+      setting.addOption(ErrorThrowingIterator.TIMES, "3");
+      c.tableOperations().attachIterator(tableName, setting, EnumSet.of(IteratorScope.minc));
+      c.tableOperations().compact(tableName, new CompactionConfig().setWait(true));
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:167]: I know this is the default, feel like it documents intent in the test.

```suggestion
      c.tableOperations().compact(tableName, new CompactionConfig().setWait(true).setFlush(true));
```

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 17]
```diff
@@ -0,0 +1,279 @@
...
+
+      try (BatchWriter bw = c.createBatchWriter(tableName)) {
+        Mutation m = new Mutation(new Text("r1"));
+        m.put("acf", tableName, "1");
+        bw.addMutation(m);
+      }
+
+      c.tableOperations().flush(tableName, null, null, false);
+
+      UtilWaitThread.sleepUninterruptibly(30, TimeUnit.SECONDS);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:217]: I think it would be ok to lower this time

```suggestion
      UtilWaitThread.sleepUninterruptibly(5, TimeUnit.SECONDS);
```

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 15 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:261]: Yeah, I guess we don't need to check the logs. If the property removal did not get picked up, then tests would not have passed. I'll apply.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 18]
```diff
@@ -0,0 +1,279 @@
...
+
+      // tell the server to take the table offline
+      tops.offline(tableName);
+
+      try {
+        // We are expecting this to fail, the table should not be taken offline
+        // because the bad iterator will prevent the minc from completing.
+        Wait.waitFor(() -> countHostedTablets(c, tid) == 0L, 120_000);
+        fail("Zero hosted tablets for table.");
+      } catch (IllegalStateException e) {}
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:230]: I think it would ok to lower this time and simplify it a bit.

```suggestion
      // the offine operation should not be able to complete because the tablet can not minor compact
      UtilWaitThread.sleepUninterruptibly(5, TimeUnit.SECONDS);

      assertTrue(countHostedTablets(c, tid) > 0);
```

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java [hunk 19]
```diff
@@ -0,0 +1,279 @@
...
+      // remove the bad iterator. The failing minc task is in a backoff retry loop
+      // and should pick up this change on the next try
+      c.tableOperations().removeIterator(tableName, BadIterator.class.getSimpleName(),
+          EnumSet.of(IteratorScope.minc));
+
+      // Minc should have completed successfully
+      Wait.waitFor(() -> tabletHasExpectedRFiles(c, tableName, 1, 1, 1, 1), 340_000);
+
+      // Taking the table offline should succeed normally
+      tops.offline(tableName);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:244]:
```suggestion
      // The previous operation to offline the table should be able to succeed after the minor compaction completed
```

**Review by keith-turner — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 17 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:217]: I opted for a larger time because sometimes tests run at different speeds on different machines. Lowering could cause intermittent failures.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 18 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:230]: This too could cause intermittent test failures. The `waitFor` still has an upper limit, but will wait longer than 5 seconds if needed.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 17 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:217]: Its not expected that the assertion after the sleep will fail no matter how long we sleep.

File: test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java (hunk 18 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:230]: No matter how long we sleep it's expected that there will be a non-zero tablets, so thinking we do not need to sleep that long.

Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/functional/HalfClosedTabletIT.java:230]: I updated the java comment in my first comment on this thread

**Comment by keith-turner** [comment]
> It would be good in the future to add some metrics or something that can be checked in the test to confirm that failures do happen on the minc before the configuration is corrected.

Wondering if a metric that counts failed minor compactions would be useful.  Should normally be zero.

**Comment by dlmarion** [comment]
> > It would be good in the future to add some metrics or something that can be checked in the test to confirm that failures do happen on the minc before the configuration is corrected.
> 
> Wondering if a metric that counts failed minor compactions would be useful. Should normally be zero.

Yeah, that's what I'm thinking.

**Comment by keith-turner** [comment]
> Yeah, that's what I'm thinking.

Ok, that is a good idea.  Are you going to open an issue?
