### PR TITLE
Fixed UpgradeIT

### LINKED ISSUE #5767: Broken test: UpgradeIT
**Test name(s)**
Both tests in UpgradeIT

**Describe the failure observed**
The tests in UpgradeIT start a subclass of Manager local to the test Thread so that the resulting exception that causes it to fail can be trapped and checked. In the tests the TestManager class is exiting and you can see the logging [here](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java#L280) in the logging for the test method. The exception should be caught by the uncaught exception handler [here](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java#L273), but it's not. If you modify [TraceWrappedRunnable.run](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/trace/TraceWrappedRunnable.java#L49-L54) to catch and log any Throwable then you will see the error that is supposed to be caught and checked, but it's being trapped somewhere.

**Testing Environment:**
 - Version of this project: 4.0.0-SNAPSHOT
 - First commit known to fail (or current commit): started failing recently
 - OS: Red Hat Enterprise Linux release 8.10
 - Java: 17.0.16
 - Maven: 3.9.9
 - Other environment details:

### PR DESCRIPTION
**Pull request by dlmarion**
Modified UpgradeIT to run test server implementations in their own thread. Also modified them to have their own ServerContext instead of sharing the one that Mini uses.

Closes #5767

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java [hunk 1]
```diff
@@ -139,14 +167,30 @@ public void testUpgradeManagerFailure() throws Exception {
...
+    final AtomicReference<Throwable> err = new AtomicReference<>();
+    Thread testMgrThread = new Thread() {
+      @Override
+      public void run() {
+        try {
+          List<String> args = new ArrayList<>();
+          args.add("--props");
+          args.add(getCluster().getAccumuloPropertiesPath());
+          TestManager mgr = new TestManager(args.toArray(new String[0]));
+          mgr.runServer();
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: What is the benefit of calling this code in another thread?

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: if the thread dies for some reason, then the test will fail instead of exiting like it's doing now.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: Also, the old code was part of the problem. Using a new ServerContext was not enough by itself. Using the old code here causes the test class to exit.

Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: The test was failing before because something was deleting the manager lock and that caused the process to halt.  I think the thread running this test thread was fine.  I changed TestManager constructor back to the following locally `super(new ConfigOpts(), (conf) -> getServerContext(), args)` and ran these updated test and it still fails because something halts the process.  So it seems that making that change to server context fixes the test, but I do not understand why.

File: test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java [hunk 2]
```diff
@@ -139,14 +167,30 @@ public void testUpgradeManagerFailure() throws Exception {
...
+          mgr.close();
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: mgr.close() will never be called when an exception is thrown from mgr.runServer().  Tried changing to the following and the test fails w/ the process halting.  Calling TestManager.close() seems to halt the test process.

```java
         try(TestManager mgr = new TestManager(args.toArray(new String[0]))) {
           mgr.runServer();
         }
```

File: test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java (hunk 1 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: Made a comment elsewhere about close and try w/ resources.  Not sure why, but it seems like not calling close in try w/ resource and the change to a different server context avoid halting the test process.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: > I changed TestManager constructor back to the following locally super(new ConfigOpts(), (conf) -> getServerContext(), args) and ran these updated test and it still fails

I have reproduced this locally as well.

Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: I suspect the thread code could be removed, simplifying the test.  Assuming the test thread called something that halted the process.  If there is an uncaught exception from the test, junit code should catch that and handle in its normal way.

File: test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java (hunk 2 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/upgrade/UpgradeIT.java]: We can remove the call to `mgr.close()` in these changes.

**Comment by dlmarion** [comment]
I'm still digging into why / where the lock for the TestManager class is being removed.

**Comment by dlmarion** [comment]
In 840385e I reverted some of the prior changes. I think the major issues stem from the shared ServerContext object. The test passes with the current changes.
