### PR TITLE
Make garbage collecting wal and recovery files faster

### LINKED ISSUE #5397: Garbage Collecting Write Ahead Logs can be slow for a large number of logs
**Describe the bug**
GarbageCollectWriteAheadLogs deletes walog files serially, where rfiles are deleted using a thread pool.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.3

### PR DESCRIPTION
**Pull request by dlmarion**
Uses the same property and technique used for deleting RFiles to delete wal and recovery files.

Closes #5397

### CODE REVIEW

**Comment by dlmarion** [comment]
Kicked off IT build

**Comment by dlmarion** [comment]
Full IT build successful

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 1]
```diff
@@ -266,37 +271,62 @@ private long removeTabletServerMarkers(Map<UUID,TServerInstance> uidMap,
...
-      log.error("Unable to delete wal {}", path, ex);
-    }
-
-    return 0;
+    });
   }
 
   private long removeFiles(Collection<Pair<WalState,Path>> collection, final GCStatus status) {
+
+    final ExecutorService deleteThreadPool = ThreadPools.getServerThreadPools()
```
Comment (ddanielr) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:293]: When deleting rfiles, the threadpool is created and shutdown for each delete pass to ensure that all rfiles are deleted before we remove the gcCandidates from their respective metadata location.

For WALs, the GC looks at each wal directory location to find files, then compares the file against the live tservers set, recovery operations, or dead tserver list to see if the file can be removed. 

Since we aren't processing gcCandidates, do we need to create and delete the threadpool on each removeFiles run?

If we made a longer lived pool then we could enable metrics on the threadpool and get more details about how many threads might be utilized.

Comment (ddanielr) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:293]: Started looking at the WALStateManager code and realized my understanding of the WAL log process was incorrect. While the GC does look at recovery directory locations, the rest of the WAL information is stored in ZK. 
After the WALs are processed, the WALStateManager is used to update ZK references to the WAL files.

So the existing threadpool start/shutdown pattern makes sense here.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 2]
```diff
@@ -266,37 +271,62 @@ private long removeTabletServerMarkers(Map<UUID,TServerInstance> uidMap,
...
-    return status.currentLog.deleted;
+
+    deleteThreadPool.shutdown();
+    try {
+      while (!deleteThreadPool.awaitTermination(1000, TimeUnit.MILLISECONDS)) { // empty
+      }
+    } catch (InterruptedException e1) {
+      log.error("{}", e1.getMessage(), e1);
+    }
+    return counter.get();
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:310]: The code was incrementing this deleted counter, should it still do that?

```suggestion
    status.currentLog.deleted += counter.get();
    return counter.get();
```

Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:310]: Yep, I forgot to increment the counter. I created it though, so I was half way there.

Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:310]: On second look, counter is being passed to removeFile, and incremented there.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 3]
```diff
@@ -266,37 +271,62 @@ private long removeTabletServerMarkers(Map<UUID,TServerInstance> uidMap,
...
+  private void removeFile(ExecutorService deleteThreadPool, Path path, AtomicLong counter,
+      String msg) {
+    deleteThreadPool.execute(() -> {
+      try {
+        log.debug(msg);
+        if (!useTrash || !fs.moveToTrash(path)) {
+          fs.deleteRecursively(path);
+        }
+        counter.incrementAndGet();
+      } catch (FileNotFoundException ex) {
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:283]: The previous code just bubbled the RuntimeExceptions up the call stack. I could call `submit` instead, test the futures, and return any errors up the stack.

[the remark this answers is not in the document]
Comment (cshannon) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:283]: If you used futures that might be better, you could wait for them to finish instead of relying on the thread pool to shutdown for completion. Either way could work, I just figured I'd mention it as I'm not too familiar with this code but I noticed we were only catching those specific exceptions so was curious if a random runtime exception would cause issues with the new thread pool.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 2 above)
Comment (keith-turner) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:310]: yeah counter is being incrementing removeFile, but the old code used to increment `status.currentLog.deleted` which may be used for display on the monitor and logging.  Seems like that is no longer incremented.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:286]: Updated to use futures in 7c54495

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 2 above)
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:330]: Updated in 7c54495

**Comment by dlmarion** [comment]
> 
> The only suggestion I have is using a separate `GC_WAL_DELETE_THREADS` property.
> 

Added in 7c54495

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 4]
```diff
@@ -283,42 +286,77 @@ private void removeFile(ExecutorService deleteThreadPool, Path path, AtomicLong
...
+    final Map<Path,Future<?>> futures = new HashMap<>(values.size());
     final AtomicLong counter = new AtomicLong();
 
     for (Path path : values) {
-      removeFile(deleteThreadPool, path, counter, "Removing recovery log " + path);
+      futures.put(path,
+          removeFile(deleteThreadPool, path, counter, "Removing recovery log " + path));
     }
 
+    while (!futures.isEmpty()) {
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:345]: The get() method in a future waits until its done or failed, so should be able to loop through all futures once calling get.

```java
futures.forEach((path,future)->{
             try {
            future.get();
          } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException("Uncaught exception deleting recovery log file" + path,
                e);
          }
});
```

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 5]
```diff
@@ -266,37 +274,97 @@ private long removeTabletServerMarkers(Map<UUID,TServerInstance> uidMap,
...
+            iter.remove();
+            f.getValue().get();
+          } catch (InterruptedException | ExecutionException e) {
+            throw new RuntimeException("Uncaught exception deleting recovery log file" + f.getKey(),
+                e);
+          }
+        }
+      }
+    }
+    deleteThreadPool.shutdown();
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:360]: If an exception is throw the pool would not be shut down.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 6]
```diff
@@ -266,37 +274,97 @@ private long removeTabletServerMarkers(Map<UUID,TServerInstance> uidMap,
...
+    try {
+      while (!deleteThreadPool.awaitTermination(1000, TimeUnit.MILLISECONDS)) { // empty
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:362]: Could remove this code now that futures are being waited on.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 4 above)
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:345]: I was thinking the faster I process the ones that are complete and remove from the map, the faster I'm giving back memory to the VM. I probably need to put a wait at the bottom of the loop though. If the first one the iterator returns is the last one submitted, then I would be waiting until they are all done.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 6 above)
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: Fixed in 93f5c6d

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 5 above)
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: Fixed this in 93f5c6d

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 4 above)
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: Added a sleep at the bottom of the while loop in 93f5c6d.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 7]
```diff
@@ -266,37 +273,102 @@ private long removeTabletServerMarkers(Map<UUID,TServerInstance> uidMap,
...
+    final AtomicLong counter = new AtomicLong();
+
     for (Path path : values) {
-      log.debug("Removing recovery log {}", path);
-      count += removeFile(path);
+      futures.put(path,
+          removeFile(deleteThreadPool, path, counter, "Removing recovery log " + path));
+    }
+
+    try {
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:346]: could move this try up to be immediately after the creation of deleteThreadPool

**Review by keith-turner — APPROVED** [review]

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 7 above)
Comment (dlmarion) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java:346]: smh, I did that on the other method. I'll fix.
