### PR TITLE
Fix #1628 add test where selector throws an error

### LINKED ISSUE #1628: Add test where compaction selector sporadically throws an exception.
Add test that does the following to org.apache.accumulo.test.CompactionIT

 * Create a compaction selector that only compacts file names that match a pattern and throws an exception randomly 50% of the time.
 * Initiate a compaction of a subset of file using above selector.  Confirm subset if compacted.
 * Add files and run above step a few times.

This test will ensure that compaction selector is retried when it throws an exception and a single exception does not cause compactions to hang.

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 1]
```diff
@@ -68,6 +116,54 @@ protected int defaultTimeoutSeconds() {
...
+
+      CompactionConfig config = new CompactionConfig()
+          .setSelector(new PluginConfig(RandomErrorThrowingSelector.class.getName(),
+              Map.of(RandomErrorThrowingSelector.FILE_LIST_PARAM, subset)))
+          .setWait(true);
+      c.tableOperations().compact(tableName, config);
+
+      List<String> files2 = FunctionalTestUtils.getRFileNames(c, tableName);
+      Assert.assertFalse(files2.contains(files.get(0)));
+      Assert.assertFalse(files2.contains(files.get(3)));
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:163]:
```suggestion
      Assert.assertFalse(files2.contains(files.get(0)));
      Assert.assertTrue(files2.contains(files.get(1)));
      Assert.assertTrue(files2.contains(files.get(2)));
      Assert.assertFalse(files2.contains(files.get(3)));
```

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 2]
```diff
@@ -68,6 +116,54 @@ protected int defaultTimeoutSeconds() {
     return 4 * 60;
   }
 
+  @Test
+  public void testBadSelector() throws Exception {
+    try (AccumuloClient c = Accumulo.newClient().from(getClientProps()).build()) {
+      final String tableName = getUniqueNames(1)[0];
+      c.tableOperations().create(tableName);
+      // Ensure compactions don't kick off
+      c.tableOperations().setProperty(tableName, Property.TABLE_MAJC_RATIO.getKey(), "10.0");
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:125]: setting these props are eventually consistent, so not sure when tserver will see the config update.  Could set the prop at table creation time instead, avoiding any possible race conditions in the test.

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 3]
```diff
@@ -68,6 +116,54 @@ protected int defaultTimeoutSeconds() {
...
+      CompactionConfig config = new CompactionConfig()
+          .setSelector(new PluginConfig(RandomErrorThrowingSelector.class.getName(),
+              Map.of(RandomErrorThrowingSelector.FILE_LIST_PARAM, subset)))
+          .setWait(true);
+      c.tableOperations().compact(tableName, config);
+
+      List<String> files2 = FunctionalTestUtils.getRFileNames(c, tableName);
+      Assert.assertFalse(files2.contains(files.get(0)));
+      Assert.assertFalse(files2.contains(files.get(3)));
+    }
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:164]: It would be nice to scan table and verify data is as expected.

File: test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java [hunk 4]
```diff
@@ -81,6 +83,19 @@ public static int countRFiles(AccumuloClient c, String tableName) throws Excepti
     }
   }
 
+  public static List<String> getRFileNames(AccumuloClient c, String tableName) throws Exception {
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java:86]: This name seems off.  Seems like its returning paths or URIs and not names.  Also could possible use Ample for this, but not quite sure. It may not be easy to use Ample unless you have a ServerContext.

**Comment by dlmarion** [comment]
QA build failed due to connection reset pulling down a jar - not related to the code changes.

**Review by keith-turner — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 5]
```diff
@@ -68,6 +115,67 @@ protected int defaultTimeoutSeconds() {
...
+          .setSelector(new PluginConfig(RandomErrorThrowingSelector.class.getName(),
+              Map.of(RandomErrorThrowingSelector.FILE_LIST_PARAM, subset)))
+          .setWait(true);
+      c.tableOperations().compact(tableName, config);
+
+      List<String> files2 = FunctionalTestUtils.getRFilePaths(c, tableName);
+      assertFalse(files2.contains(files.get(0)));
+      assertTrue(files2.contains(files.get(1)));
+      assertTrue(files2.contains(files.get(2)));
+      assertFalse(files2.contains(files.get(3)));
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:165]:
```suggestion
      // check that the subset of files selected are compacted, but the others remain untouched
      List<String> filesAfterCompact = FunctionalTestUtils.getRFilePaths(c, tableName);
      assertFalse(filesAfterCompact.contains(files.get(0)));
      assertTrue(filesAfterCompact.contains(files.get(1)));
      assertTrue(filesAfterCompact.contains(files.get(2)));
      assertFalse(filesAfterCompact.contains(files.get(3)));
```

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 6]
```diff
@@ -68,6 +115,67 @@ protected int defaultTimeoutSeconds() {
...
+      Mutation m3 = new Mutation("3");
+      m3.put("cf", "cq", new Value(new byte[0]));
+      bw.addMutation(m3);
+      bw.flush();
+      c.tableOperations().flush(tableName, new Text("0"), new Text("9"), true);
+      Mutation m4 = new Mutation("4");
+      m4.put("cf", "cq", new Value(new byte[0]));
+      bw.addMutation(m4);
+      bw.close();
+      c.tableOperations().flush(tableName, new Text("0"), new Text("9"), true);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:147]:
```suggestion
      try (BatchWriter bw = c.createBatchWriter(tableName)) {
        for (int i = 1; i <= 4; i++) {
          Mutation m = new Mutation(Integer.toString(i));
          m.put("cf", "cq", new Value());
          bw.addMutation(m);
          bw.flush();
          c.tableOperations().flush(tableName, null, null, true);
        }
      }
```

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 7]
```diff
@@ -68,6 +115,67 @@ protected int defaultTimeoutSeconds() {
...
+
+      List<Text> rows = new ArrayList<>();
+      rows.add(new Text("1"));
+      rows.add(new Text("2"));
+      rows.add(new Text("3"));
+      rows.add(new Text("4"));
+      c.createScanner(tableName).forEach((k, v) -> {
+        assertTrue(rows.remove(k.getRow()));
+      });
+      assertEquals(0, rows.size());
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:175]:
```suggestion
      List<String> rows = new ArrayList<>();
      c.createScanner(tableName).forEach((k, v) -> rows.add(k.getRow().toString()));
      assertEquals(List.of("1", "2", "3", "4"), actualRows);
```

**Review by ctubbsii — CHANGES_REQUESTED** [review]
Good test, but readability could be improved. I proposed some such improvements below.

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 8]
```diff
@@ -68,6 +115,50 @@ protected int defaultTimeoutSeconds() {
...
+      // check that the subset of files selected are compacted, but the others remain untouched
+      List<String> filesAfterCompact = FunctionalTestUtils.getRFilePaths(c, tableName);
+      assertFalse(filesAfterCompact.contains(files.get(0)));
+      assertTrue(filesAfterCompact.contains(files.get(1)));
+      assertTrue(filesAfterCompact.contains(files.get(2)));
+      assertFalse(filesAfterCompact.contains(files.get(3)));
+
+      List<String> rows = new ArrayList<>();
+      c.createScanner(tableName).forEach((k, v) -> rows.add(k.getRow().toString()));
+      assertEquals(List.of("1", "2", "3", "4"), actualRows);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:158]: Oops, my initial suggestion renamed this variable.

```suggestion
      assertEquals(List.of("1", "2", "3", "4"), rows);
```

**Review by ctubbsii — APPROVED** [review]
