### PR TITLE
fixes #518 ignore non rfiles in new bulk import

### LINKED ISSUE #518: New bulk importer fails if directory contains files other than RFiles
This may be intended behavior... I'm not sure.
I tried to convert some bulk import code from AuditMessageIT:

```java
auditConnector.tableOperations().importDirectory(THIRD_TEST_TABLE_NAME, exportDir.toString(), failDir.toString(), false);
```
to:
```java
auditConnector.tableOperations().addFilesTo(THIRD_TEST_TABLE_NAME).from(exportDir.toString()).load();
```

The former works fine with the `export` directory containing:
```
distcp.txt
exportMetadata.zip
tmp/
```
However, the latter failed because it did not recognize the `zip` file format. I'm not sure why this test is trying to bulk import from an `exportTable` directory, but it works fine using the old method (which seems to silently ignore unrecognized files... although I can't find the relevant filtering code).

Do we want the new bulk importer to ignore unrecognized files like the old method did, or not?

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/BulkLoadIT.java [hunk 1]
```diff
@@ -231,6 +232,11 @@ private void testBulkFile(boolean offline, boolean usePlan) throws Exception {
         hashes.put(endRow, new HashSet<>());
       }
 
+      // Add a junk file, should be ignored
+      FSDataOutputStream out = fs.create(new Path(dir + "/junk"));
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/BulkLoadIT.java]: I think that the `Paths.get(dir, "junk")` syntax might be a bit cleaner than the concatenation. Not a bug, but probably better, in that it's less platform dependent on the OS path separator char, and therefore a good habit to get into.
