### PR TITLE
Fixes #1488 - ManyWriteAheadLogsIT asserts open WALS equal to zero.

### LINKED ISSUE #1488: ManyWriteAheadLogsIT is flakey
While attempting to tune the timing of many of our ITs, I found that ManyWriteAheadLogsIT occassionally fails with an assertion error:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.762 s <<< FAILURE! - in org.apache.accumulo.test.functional.ManyWriteAheadLogsIT
[ERROR] testMany(org.apache.accumulo.test.functional.ManyWriteAheadLogsIT)  Time elapsed: 21.538 s  <<< FAILURE!
java.lang.AssertionError: Open WALs not in expected range 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.accumulo.test.functional.ManyWriteAheadLogsIT.addOpenWals(ManyWriteAheadLogsIT.java:167)
	at org.apache.accumulo.test.functional.ManyWriteAheadLogsIT.testMany(ManyWriteAheadLogsIT.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

This occurs on the 1.9 branch, at the very least, but probably also affects the master/2.1 branch.

### PR DESCRIPTION
**Pull request by jzgithub1**
CLOSED and UNREFERENCE WALS (not OPEN) causing open == 0

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java [hunk 1]
```diff
@@ -198,16 +198,33 @@ public void testMany() throws Exception {
...
+      }
+
+      if (!foundWal) {
+        Thread.sleep(50);
+        if (attempts % 50 == 0)
+          log.info("Has not found an open WAL in " + attempts + " attempts.");
       }
     }
 
+    log.debug("It took " + attempts + " attempt(s) to find an open WAL");
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java]:
```suggestion
    log.debug("It took {} attempt(s) to find {} open WALs", attempts, open);
```

File: test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java [hunk 2]
```diff
@@ -198,16 +198,33 @@ public void testMany() throws Exception {
...
+          foundWal = true;
+        } else {
+          log.error("The WalState is " + entry.getValue());// CLOSED or UNREFERENCED
+        }
+      }
+
+      if (!foundWal) {
+        Thread.sleep(50);
+        if (attempts % 50 == 0)
+          log.info("Has not found an open WAL in " + attempts + " attempts.");
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java]:
```suggestion
          log.debug("No open WALs found in {} attempts.", attempts);
```

File: test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java [hunk 3]
```diff
@@ -198,16 +198,33 @@ public void testMany() throws Exception {
...
+      attempts++;
+      Map<String,WalState> wals = WALSunnyDayIT._getWals(c);
+      Set<Entry<String,WalState>> es = wals.entrySet();
+      for (Entry<String,WalState> entry : es) {
+        if (entry.getValue() == WalState.OPEN) {
+          open++;
+          allWalsSeen.add(entry.getKey());
+          foundWal = true;
+        } else {
+          log.error("The WalState is " + entry.getValue());// CLOSED or UNREFERENCED
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java]: The formatter will reform that line, and possibly others. Try running `mvn clean verify -DskipTests` on this branch to run the code formatter, and to check for other style issues.

```suggestion
          log.debug("The WalState for {} is {}", entry.getKey(), entry.getValue()); // CLOSED or UNREFERENCED
```

**Comment by jzgithub1** [comment]
@ctubbsii ,  I accepted the requested changes.  I think we are done here.  Let me know if there is anything else you want me to do.
