### PR TITLE
Fixes serviceStatus json output

### LINKED ISSUE #6088: serviceStatus json output includes some redundant information and missing information
The following is an example snippet from the JSON output in 4.0:

```
        "T_SERVER": {
            "serviceType": "T_SERVER",
            "resourceGroups": {
                "default": 1
            },
            "serviceByGroups": {

            },
            "serviceCount": 0,
            "errorCount": 0
        }
```

Two issues:

  1. I don't think `serviceType` is needed
  2. `serviceByGroups` is empty.

### PR DESCRIPTION
**Pull request by dlmarion**
This change removes the StatusSummary.serviceType
field from the json serialization. The serviceType field is redundant in the json output as the same
information is used as the key in a map that contains the StatusSummary object.

This change also removes the StatusSummary.serviceByGroups field from the json serialization using a custom
ExclusionStrategy.

Closes #6088

### CODE REVIEW

**Comment by dlmarion** [comment]
The output before this change is shown at https://github.com/apache/accumulo/issues/6088#issuecomment-3818174941

The output after this change is below:

```
./accumulo admin serviceStatus --json
...
        "T_SERVER": {
            "resourceGroups": {
                "default": 1
            },
            "serviceCount": 1,
            "errorCount": 0
        }
...
```

```
./accumulo admin serviceStatus --json --showHosts
...
        "T_SERVER": {
            "resourceGroups": {
                "default": 1
            },
            "serviceByGroups": {
                "default": [
                    "localhost:9997"
                ]
            },
            "serviceCount": 1,
            "errorCount": 0
        }
...
```

File: server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReport.java [hunk 1]
```diff
@@ -26,19 +26,38 @@
...
 import com.google.gson.Gson;
+import com.google.gson.GsonBuilder;
 
 /**
  * Wrapper for JSON formatted report.
  */
 public class ServiceStatusReport {
 
+  private static class HostExclusionStrategy implements ExclusionStrategy {
+
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/util/serviceStatus/ServiceStatusReport.java]: Could add this constructor to check that the field actually exists.  Could make the field name a constant.

```suggestion
    public HostExclusionStrategy(){
        try {
            StatusSummary.class.getField("serviceByGroups");
        } catch (NoSuchFieldException e) {
            throw new IllegalStateException(e);
        }
    }
```

**Review by keith-turner — APPROVED** [review]
