### PR TITLE
Disallow setting table properties at system level

### LINKED ISSUE #4537: Disallow table configuration at the system level to avoid issues with system tables
The configuration hierarchy currently allows table configuration (`table.*` properties) to be set in the `conf/accumulo.properties` file (or on the command-line) and also in ZooKeeper at the system level. If set at either of these locations, they will apply to all tables in Accumulo, in all namespaces.

We have special exceptions for the metadata tables (or maybe all system tables?), to prevent certain table configurations from affecting the metadata table (I don't remember the details right now... maybe related to constraints?) because we know that they can be a problem. However, other table configuration can also be a problem, including setting iterators/filters, classloader contexts, etc. This can result in unexpected behavior, when a user clones a table and copies its configuration as well (raising the question: is it copying the effective configuration from the whole configuration hierarchy, or just that set on the table?).

To avoid many of these issues, we should disallow setting table configuration in a way that affects all tables. Namespaces are the appropriate place to configure table configuration to affect many tables at once, not the system level.

Table configuration should be ignored/disallowed from the SiteConfiguration (`accumulo.properties` and command-line) and the SystemConfiguration (in ZK). The shell should error when trying to set these, and any existing configuration should result in an ERROR or WARN message about it not having any effect.

We can add a warning about this in 2.1, and change the behavior in 3.1.

If there is still a use case for setting table properties in the `accumulo.properties` file, then we can consider adding that as a new feature to explicitly configure namespaces and/or tables, something along the lines of `table[mynamespace.mytable].someProp=someValue` to affect a specific table, and `table[mynamespace].someProp=someValue` to affect all tables in a namespace (`table[].someProp=someValue` to affect the default namespace). This is just one possibility. `commons-configuration2`, which we use for parsing the configuration, may have some useful features and a natural syntax for this, instead of the syntax I suggested here. It would be better to omit this feature entirely, if we don't actually need it. However, I think the main places where we might need it is for system tables on initial startup, to set certain things for the system tables, like per-table volume chooser, context, balancer, block cache configuration, HDFS replication factor, etc. that are useful to have set at system initialization, before any user tables are created. But, such things should be set on a specific namespace or table, not able to be set globally. So, maybe there's a way we can do that in the configuration instead of what we do now.

Another possibility is change the behavior so that such things *only* affect the accumulo system namespace (or *only* affect the default namespace), but I don't think that option is a good idea, because it could lead to a lot of confusion about what is affected, because it's a very different change in behavior for existing configuration. We should be very explicit in the ERROR/WARN messages about what is allowed, and the configuration should be very explicit about what we want it to affect, if we support it.

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #4537

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java [hunk 1]
```diff
@@ -1069,4 +1070,11 @@ default Stream<TabletInformation> getTabletInformation(final String tableName, f
     throw new UnsupportedOperationException();
   }
 
+  /**
+   * Returns the namespace for the given table name
+   *
+   * @param table fully qualified table name
+   * @return namespace id
+   */
+  NamespaceId getNamespace(String table);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: Needs a since tag

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java [hunk 2]
```diff
@@ -1069,4 +1070,11 @@ default Stream<TabletInformation> getTabletInformation(final String tableName, f
     throw new UnsupportedOperationException();
   }
 
+  /**
+   * Returns the namespace for the given table name
+   *
+   * @param table fully qualified table name
+   * @return namespace id
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: Couid document and test what runtime exceptions this could throw.

File: test/src/main/java/org/apache/accumulo/test/NamespacesIT_SimpleSuite.java [hunk 3]
```diff
@@ -871,78 +870,6 @@ public void testPermissions() throws Exception {
...
-    }
-
-    String t1 = "1";
-    String t2 = namespace + "." + t1;
-    c.tableOperations().create(t1);
-    c.namespaceOperations().create(namespace);
-    c.tableOperations().create(t2);
-
-    // verify iterator inheritance
-    _verifySystemPropertyInheritance(t1, t2, Property.TABLE_ITERATOR_PREFIX.getKey() + "scan.sum",
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/NamespacesIT_SimpleSuite.java:892]: May want to keep this test w/ different non table properties.  Will still have inheritance so its nice to test that.

File: test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java [hunk 4]
```diff
@@ -97,23 +97,32 @@ public void setTablePropTest() throws Exception {
     try (var client = Accumulo.newClient().from(getClientProps()).build()) {
 
       client.tableOperations().create(table);
+      NamespaceId nid = client.tableOperations().getNamespace(table);
 
       log.debug("Tables: {}", client.tableOperations().list());
 
-      // override default in sys, and then over-ride that for table prop
-      client.instanceOperations().setProperty(Property.TABLE_BLOOM_ENABLED.getKey(), "true");
+      // override default in namespace, and then over-ride that for table prop
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java]: could move this comment down a few lines

File: test/src/main/java/org/apache/accumulo/test/conf/util/ZooPropEditorIT_SimpleSuite.java [hunk 5]
```diff
@@ -67,13 +70,18 @@ public void modifyPropTest() throws Exception {
 
       LOG.debug("Tables: {}", client.tableOperations().list());
 
-      // override default in sys, and then over-ride that for table prop
-      client.instanceOperations().setProperty(Property.TABLE_BLOOM_ENABLED.getKey(), "true");
+      // override default in namespace, and then over-ride that for table prop
+      AccumuloException ae = assertThrows(AccumuloException.class, () -> client.instanceOperations()
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/conf/util/ZooPropEditorIT_SimpleSuite.java:77]: This is a super important test.  May be worthwhile to move it to its own test or duplicate this in its own test to make it less likely to be lost in test refactoring.  Its kinda hidden away in a test of other things.

In a stand alone test could try setting more table props and maybe some table prefix type props too.

File: server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java [hunk 6]
```diff
@@ -89,8 +89,10 @@ private static String validateSystemProperty(ServerContext context, SystemPropKe
       log.trace("Encountered error setting zookeeper property", iae);
       throw iae;
     }
-    if (Property.isValidTablePropertyKey(property)) {
-      PropUtil.validateProperties(context, key, Map.of(property, value));
+    if (property.startsWith(Property.TABLE_PREFIX.getKey())) {
+      throw new IllegalArgumentException(
+          "Table property " + property + " cannot be set at the system level."
+              + " Set table properties at the namespace or table level.");
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java]: Would be nice to somehow consolidate this exception message between the two places. Maybe could move this into a method in PropUtil, like PropUtil.checkForTablePropAtSystemLevel(property).  That method does the prefix check and throws the exception and both places can call it.

**Comment by dlmarion** [comment]
This PR will change if #5749 is merged. We probably want to wait to merge this until #5749 is in.

**Review by keith-turner — COMMENTED** [review]
Not changes for this PR, but looking at this was wondering about the following.

 * Can we make servers fail to start if there are table props at the site level?
 * Can we make the pre upgrade steps check for tables props at the system level to help ease the upgrade process?  Could prevent upgrade until these are remediated.

Overall this looks good to me.

File: server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java [hunk 7]
```diff
@@ -429,7 +429,8 @@ public void setSystemProperty(TInfo info, TCredentials c, String property, Strin
       SystemPropUtil.setSystemProperty(context, property, value);
     } catch (IllegalArgumentException iae) {
       Manager.log.error("Problem setting invalid property", iae);
-      throw new ThriftPropertyException(property, value, "Property is invalid");
+      throw new ThriftPropertyException(property, value,
+          "Property is invalid. message: " + iae.getMessage());
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java]: Not sure if this code is the same in 2.1.  If it is wondering if this change by itself in 2.1 would result in better error messages.

File: test/src/main/java/org/apache/accumulo/test/NamespacesIT_SimpleSuite.java (hunk 3 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/NamespacesIT_SimpleSuite.java:892]: or is it even possible test this?  w/ this change are the props that can be set at the system and table level now disjoint?

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/NamespacesIT_SimpleSuite.java:892]: > or is it even possible test this?

That's why I removed it. There is another test in this class named `verifyPropertyInheritance`, so I think this is just testing system level inheritance which no longer applies. Could modify this test after the resoruce group config PR is merged to add that test.

File: server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java (hunk 6 above)
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java]: Fixed this in 220b656

File: test/src/main/java/org/apache/accumulo/test/conf/util/ZooPropEditorIT_SimpleSuite.java (hunk 5 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/conf/util/ZooPropEditorIT_SimpleSuite.java:77]: Added new tests in ZooPropEditorIT and PropStoreConfigIT for this, in 220b656.

File: test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java (hunk 4 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java]: Fixed this in 220b656

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 2 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: Fixed this in 220b656

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: Fixed this in 220b656

**Comment by dlmarion** [comment]
> Not changes for this PR, but looking at this was wondering about the following.
> 
> * Can we make servers fail to start if there are table props at the site level?

That should be an easy addition to AbstractServer.

> * Can we make the pre upgrade steps check for tables props at the system level to help ease the upgrade process?  Could prevent upgrade until these are remediated.
> 

We could warn in the pre-upgrade step. There was discussion of moving the ZooKeeper related upgrade changes from the Upgrader to the start step, but that hasn't happened yet.

> Overall this looks good to me.

File: server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java (hunk 7 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java]: Created #5789 for this

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java [hunk 8]
```diff
@@ -1069,4 +1070,13 @@ default Stream<TabletInformation> getTabletInformation(final String tableName, f
...
+   * @throws IllegalArgumentException if table name is null, empty, or invalid format
+   * @since 4.0.0
+   */
+  NamespaceId getNamespace(String table);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: The impl of this seems to return the namespace name and not the id. Looking at the code that uses this it wants the name and not the id. 

```suggestion
  String getNamespaceName(String table);
```

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java [hunk 9]
```diff
@@ -438,4 +447,50 @@ void addTableMappingsToZooKeeper(ServerContext context) {
...
+
+  void moveTableProperties(ServerContext context) {
+    try {
+      final SystemPropKey spk = SystemPropKey.of();
+      final VersionedProperties sysProps = context.getPropStore().get(spk);
+      final Map<String,String> sysTableProps = new HashMap<>();
+      sysProps.asMap().entrySet().stream()
+          .filter(e -> e.getKey().startsWith(Property.TABLE_PREFIX.getKey()))
+          .forEach(e -> sysTableProps.put(e.getKey(), e.getValue()));
+      LOG.info("Adding the following table properties to namespaces unless overridden, {}",
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: logging an entire map in one line can be hard to read in the logs when its a large map, could log one line per prop

**Review by keith-turner — APPROVED** [review]
Everything looks good except for the namespace name vs id issue.

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 8 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: nice catch. Fixed in f452cae.

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java (hunk 9 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: Fixed in f452cae.

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java [hunk 10]
```diff
@@ -438,4 +447,51 @@ void addTableMappingsToZooKeeper(ServerContext context) {
...
+  void moveTableProperties(ServerContext context) {
+    try {
+      final SystemPropKey spk = SystemPropKey.of();
+      final VersionedProperties sysProps = context.getPropStore().get(spk);
+      final Map<String,String> sysTableProps = new HashMap<>();
+      sysProps.asMap().entrySet().stream()
+          .filter(e -> e.getKey().startsWith(Property.TABLE_PREFIX.getKey()))
+          .forEach(e -> sysTableProps.put(e.getKey(), e.getValue()));
+      LOG.info("Adding the following table properties to namespaces unless overridden:");
+      sysTableProps.forEach((k, v) -> LOG.info("{} -> {}", k, v));
```
Comment (kevinrr888) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: Avoids 2 iterations
```suggestion
      LOG.info("Adding the following table properties to namespaces unless overridden:");
      sysProps.asMap().entrySet().stream()
          .filter(e -> e.getKey().startsWith(Property.TABLE_PREFIX.getKey()))
          .forEach(e -> {
          sysTableProps.put(e.getKey(), e.getValue());
          LOG.info("{} -> {}", e.getKey(), e.getValue())
          });
      sysTableProps.forEach((k, v) -> LOG.info("{} -> {}", k, v));
```

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java [hunk 11]
```diff
@@ -438,4 +447,51 @@ void addTableMappingsToZooKeeper(ServerContext context) {
...
+            nsPropAdditions.put(e.getKey(), e.getValue());
+          }
+        }
+        try {
+          context.getPropStore().putAll(nsk, nsPropAdditions);
+          LOG.debug("Added table properties to namespace {}:", ns);
+          nsPropAdditions.forEach((k, v) -> LOG.debug("{} -> {}", k, v));
+        } catch (IllegalStateException e1) {
+          throw e1;
+        }
```
Comment (kevinrr888) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]:
```suggestion
          context.getPropStore().putAll(nsk, nsPropAdditions);
          LOG.debug("Added table properties to namespace {}:", ns);
          nsPropAdditions.forEach((k, v) -> LOG.debug("{} -> {}", k, v));
```

File: test/src/main/java/org/apache/accumulo/test/ComprehensiveTableOperationsIT_SimpleSuite.java [hunk 12]
```diff
@@ -746,6 +748,23 @@ public void test_setTabletAvailability_getTabletInformation() throws Exception {
     }
   }
 
+  @Test
+  public void test_getNamespace() throws Exception {
+    assertEquals(NamespaceId.of(Namespace.ACCUMULO.name()),
+        ops.getNamespace(SystemTables.METADATA.tableName()));
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/ComprehensiveTableOperationsIT_SimpleSuite.java]: Good to test for all sys tables
```suggestion
    for (var sysTable : SystemTables.tableNames()) {
        assertEquals(NamespaceId.of(Namespace.ACCUMULO.name()),
            ops.getNamespace(sysTable);
    }
```

File: test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java [hunk 13]
```diff
@@ -97,23 +99,32 @@ public void setTablePropTest() throws Exception {
     try (var client = Accumulo.newClient().from(getClientProps()).build()) {
 
       client.tableOperations().create(table);
+      NamespaceId nid = client.tableOperations().getNamespace(table);
 
       log.debug("Tables: {}", client.tableOperations().list());
 
-      // override default in sys, and then over-ride that for table prop
-      client.instanceOperations().setProperty(Property.TABLE_BLOOM_ENABLED.getKey(), "true");
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java:105]: How did you find which tests set a table prop at system level?

File: test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java [hunk 14]
```diff
@@ -97,23 +99,32 @@ public void setTablePropTest() throws Exception {
...
+          Property.TABLE_BLOOM_ENABLED.getKey(), "true");
       client.tableOperations().setProperty(table, Property.TABLE_BLOOM_ENABLED.getKey(), "false");
 
-      Wait.waitFor(() -> client.instanceOperations().getSystemConfiguration()
+      Wait.waitFor(() -> client.namespaceOperations().getConfiguration(nid.canonical())
           .get(Property.TABLE_BLOOM_ENABLED.getKey()).equals("true"), 5000, 500);
       Wait.waitFor(() -> client.tableOperations().getConfiguration(table)
           .get(Property.TABLE_BLOOM_ENABLED.getKey()).equals("false"), 5000, 500);
 
       // revert sys, and then over-ride to true with table prop
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java]:
```suggestion
      // revert namespace prop, and then over-ride to true with table prop
```

File: test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java (hunk 13 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java:105]: Ran a full IT build after changing the code, then went back and fixed the tests that failed.

Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/conf/PropStoreConfigIT_SimpleSuite.java:105]: Nice was hoping for that

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java [hunk 15]
```diff
@@ -899,4 +906,50 @@ public void removeScanServerRanges(ServerContext context) {
     }
   }
 
+  void moveTableProperties(ServerContext context) {
```
Comment (ctubbsii) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java:909]: Am I correct in understanding that this moves table properties from the system config to all currently existing namespaces?

**Review by ctubbsii — COMMENTED** [review]
Seems like a good approach. Would this also prevent them from being set on resource group configs?

**Comment by dlmarion** [comment]
> Seems like a good approach. Would this also prevent them from being set on resource group configs?

No. In fact I made the comment above that we should wait to merge in #5749 first, then update this PR to handle resource group configurations

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java (hunk 15 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java:909]: Yes, it moves the table properties in the system configuration to all known namespaces, unless the property already exists there with a different value.

**Comment by ctubbsii** [comment]
> > Seems like a good approach. Would this also prevent them from being set on resource group configs?
> 
> No. In fact I made the comment above that we should wait to merge in #5749 first, then update this PR to handle resource group configurations

By "handle", you mean that it *should* prevent using table properties in RG configs in addition to system level, once updated, right? I can't imagine that we would want to allow them in RG configs if we've disallowed them at the system level, since both are basically "process level" (properties files on classpath, or groups of processes in ZK),  configs rather than "data level" (table, namespace in ZK).

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java (hunk 10 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: I'm still seeing two iterations in your suggested change. Did you mean to include the last line?

**Comment by dlmarion** [comment]
> > > Seems like a good approach. Would this also prevent them from being set on resource group configs?
> > 
> > 
> > No. In fact I made the comment above that we should wait to merge in #5749 first, then update this PR to handle resource group configurations
> 
> By "handle", you mean that it _should_ prevent using table properties in RG configs in addition to system level, once updated, right? I can't imagine that we would want to allow them in RG configs if we've disallowed them at the system level, since both are basically "process level" (properties files on classpath, or groups of processes in ZK), configs rather than "data level" (table, namespace in ZK).

@ctubbsii  and I discussed this yesterday. I was originally thinking that #5749 would get merged in first to create the resource group configurations and then I would modify this PR to allow table properties at the resource group level. @ctubbsii suggested that we should not do this and only allow table properties at the table and namespace configuration layers, keeping properties that affect data at the table and namespace layer and properties that affect the instance and processes at the site, system, and resource group level. I'm good with @ctubbsii approach, does anyone else have thoughts about this?

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java (hunk 11 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: Fixed in 4908965

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java (hunk 10 above)
Comment (kevinrr888) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: yeah did not mean to include last line
