### PR TITLE
Change List to SortedSet in RecoveryLogsIterator

### LINKED ISSUE #3017: SortedLogRecoveryTest failures
**Describe the bug**
While attempting to run the Sunny profile,  the SortedLogRecoveryTests are failing. These tests are failing on my local development envrionment and on the Apache Jenkins server, but are passing on a Terraform created cluster that I had created.

The error first appears after commit b14df03bd7eee697fa9002832f03c2aaa7442695 that was added September 29th.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Running against the main branch of Accumulo repository.
 - OS:  Ubuntu 21.10

**To Reproduce**

Run the following test:

`
mvn clean -DfailIfNoTests=false -Dtest=org.apache.accumulo.tserver.log.SortedLogRecoveryTest test -am -pl server/tserver
`

**Expected behavior**
All tests should pass.

The stacktrace is listed below:
`
[ERROR] Errors: 
[ERROR]   SortedLogRecoveryTest.testSkipSuccessfulCompaction:392->recover:162->recover:203 » IllegalState First log entry is not OPEN /home/user/dev/accumulo/server/tserver/target/junit12172321873108158988/testSkipSuccessfulCompaction/testlog

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.474 s <<< FAILURE! - in org.apache.accumulo.tserver.log.SortedLogRecoveryTest
[ERROR] org.apache.accumulo.tserver.log.SortedLogRecoveryTest.testSkipSuccessfulCompaction  Time elapsed: 0.888 s  <<< ERROR!
java.lang.IllegalStateException: First log entry is not OPEN /home/user/dev/accumulo/server/tserver/target/junit12172321873108158988/testSkipSuccessfulCompaction/testlog
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.validateFirstKey(RecoveryLogsIterator.java:174)             
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.<init>(RecoveryLogsIterator.java:85)                    
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findMaxTabletId(SortedLogRecovery.java:107)             
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findLogsThatDefineTablet(SortedLogRecovery.java:147)    
        at org.apache.accumulo.tserver.log.SortedLogRecovery.recover(SortedLogRecovery.java:291)                    
        at org.apache.accumulo.tserver.log.SortedLogRecoveryTest.recover(SortedLogRecoveryTest.java:203)                     
        at org.apache.accumulo.tserver.log.SortedLogRecoveryTest.recover(SortedLogRecoveryTest.java:162)                            
        at org.apache.accumulo.tserver.log.SortedLogRecoveryTest.testSkipSuccessfulCompaction(SortedLogRecoveryTest.java:392)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                           
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)          
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
       at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:234)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:228)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:131)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SortedLogRecoveryTest.testSkipSuccessfulCompaction:392->recover:162->recover:203 » IllegalState First log entry is not OPEN /home/user/dev/accumulo/server/tserver/target/
junit12172321873108158988/testSkipSuccessfulCompaction/testlog
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
`

### PR DESCRIPTION
**Pull request by jmark99**
This ticket closes #3017 (SortedLogRecoveryTest failures).

That issue described a situation where a large number of tests within SortedLogRecoverTest.java were failing within certain environments. It failed consistently for me as well as on the Apache Jenkins server.

The problem was tracked down to a issue where the 'getFiles' method within RecoveryLogsIterator was returning a List of logFiles that were presumed to be in lexicographical order by file name. But on my particular instance (and presumably the Jenkins server), the files were not returned in that order. Therefore when 'validateFirstKey' retrieved the first file from the provided list, it was not actually checking the first key, but instead, whatever key was in the first file provided by the list. In cases where the order was not as assumed, the check failed and an exception was thrown.

The 'getFiles' method has been updated to return a SortedSet of files, thereby supplying 'validateFirstKey' with the logFiles in expected order. This change allowed all tests to pass without any additional code modification.

### CODE REVIEW

**Comment by jmark99** [comment]
@ctubbsii and @keith-turner, @dlmarion and I would like you to take a look at this change and see if you think it will affect any other code adversely.

**Comment by dlmarion** [comment]
The other thing to note here is that this worked previously because RecoveryLogsIterator used the client side RFile scanner which took all the files from `Filesystem.listFiles` and then looked at the first key (internally it must have done a merge-sort read). I modified RecoveryLogsIterator in [this](https://github.com/apache/accumulo/commit/b14df03bd7eee697fa9002832f03c2aaa7442695#diff-288f570b1f810a8673289600ce7e47e6ea5727a612de5f0e7acb84a5f319d957R166) commit to use the internal RFile reader because it supports the CryptoService. It only takes one file, and I gave it the first one thinking they were sorted.

**Comment by dlmarion** [comment]
I guess the question here is, "Is the OPEN in the first file when the files are sorted by name?" I think the answer is "yes", and it looks like OPEN is the first entry in any file created by DFSLogger.open(). SortedLogRecoveryTest.recover() uses LogSorter.writeBuffer to create the test WALs. It appears that it creates a new WAL file for each buffer written, but does not put an OPEN at the top of each file.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java [hunk 1]
```diff
@@ -77,7 +79,7 @@ public RecoveryLogsIterator(ServerContext context, List<Path> recoveryLogDirs, L
 
     for (Path logDir : recoveryLogDirs) {
       LOG.debug("Opening recovery log dir {}", logDir.getName());
-      List<Path> logFiles = getFiles(vm, logDir);
+      SortedSet<Path> logFiles = getFiles(vm, logDir);
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java:82]: I'm not sure the full implications here, but I would have assumed insert order, as they appear in the metadata, would be more important than ordering by path, which could vary due to hostname differences on the HDFS volume. If the files have unique 1-up sequence based names, you could use a custom comparator to order them that way in a set.

Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java:82]: From what I can tell, the naming convention for the files is [here](https://github.com/apache/accumulo/blob/main/server/tserver/src/main/java/org/apache/accumulo/tserver/log/LogSorter.java#L253).

**Comment by jmark99** [comment]
@ctubbsii , @dlmarion , would a change such as the following address your concerns?

Replace:

<pre>
    SortedSet<Path> logFiles = new TreeSet<>();
</pre>

within `getFiles` with:

<pre>
    // Path::getName compares the last component of each Path value. In this case, the last
    // component should always have the format 'part-r-XXXXX.rf', where XXXXX are one-up values.
    SortedSet<Path> logFiles = new TreeSet<>(Comparator.comparing(Path::getName));
</pre>

Therefore, only comparing the 'part-r-xxxxx.rf' portion of the filenames.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java (hunk 1 above)
Comment (jmark99) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java:82]: @ctubbsii , @dlmarion , would a change such as the following address your concerns?

Replace:

    SortedSet logFiles = new TreeSet<>();

within getFiles with:

    // Path::getName compares the last component of each Path value. In this case, the last
    // component should always have the format 'part-r-XXXXX.rf', where XXXXX are one-up values.
    SortedSet logFiles = new TreeSet<>(Comparator.comparing(Path::getName));

Therefore, only comparing the 'part-r-xxxxx.rf' portion of the filenames.

Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java:82]: yeah, that seem sane

**Review by dlmarion — APPROVED** [review]
LGTM, tests now pass on your machine?

**Comment by jmark99** [comment]
@dlmarion , yes. The tests pass on my local dev environment.
