### PR TITLE
Reduce logging when external compactions are cancelled

### LINKED ISSUE #3023: External Compaction cancellation due to tablet split is very verbose
External compactions are cancelled [here](https://github.com/apache/accumulo/blob/main/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L218) when a Tablet is split or merged. Calling JOB_HOLDER.cancel() in this case creates a lot of logging which ends up in the Monitor. This doesn't seem to be an exceptional case here, we might want to look at tuning the logging in this case and other cases where JOB_HOLDER.cancel is called.

Here's what the log looked like:

```
2022-10-14T15:00:07,822 [compaction.FileCompactor] ERROR: Interrupted while waiting for data to be acknowledged by pipeline
java.io.InterruptedIOException: Interrupted while waiting for data to be acknowledged by pipeline
        at org.apache.hadoop.hdfs.DataStreamer.waitForAckedSeqno(DataStreamer.java:937) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.flushInternal(DFSOutputStream.java:778) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:888) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:847) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.accumulo.core.file.streams.RateLimitedOutputStream.close(RateLimitedOutputStream.java:54) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Writer.close(BCFile.java:368) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.RFile$Writer.close(RFile.java:635) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:393) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:234) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.compactor.Compactor.lambda$createCompactionJob$7(Compactor.java:569) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-10-14T15:00:07,874 [server.GarbageCollectionLogger] DEBUG: gc G1 Young Generation=18.05(+0.08) secs G1 Old Generation=0.00(+0.00) secs freemem=81,075,656(-64,866,976) totalmem=268,435,456
2022-10-14T15:00:07,878 [compaction.FileCompactor] WARN : name=RFile.index
org.apache.accumulo.core.file.rfile.bcfile.MetaBlockAlreadyExists: name=RFile.index
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Writer.prepareMetaBlock(BCFile.java:386) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Writer.prepareMetaBlock(BCFile.java:410) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.RFile$Writer.close(RFile.java:606) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:275) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.compactor.Compactor.lambda$createCompactionJob$7(Compactor.java:569) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-10-14T15:00:07,878 [compactor.Compactor] ERROR: Compaction failed
org.apache.accumulo.server.compaction.FileCompactor$CompactionCanceledException: null
        at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:401) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:234) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.compactor.Compactor.lambda$createCompactionJob$7(Compactor.java:569) ~[accumulo-compactor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-10-14T15:00:07,885 [compactor.Compactor] INFO : Cancelling compaction ECID:00c58155-52e5-4948-b2df-77c082cffd1d that no longer has a metadata entry at 1;1ccd3;199999999999999c
2022-10-14T15:00:07,885 [compactor.Compactor] WARN : Compaction thread was interrupted, sending CANCELLED state
```

And the section of the monitor showing logs:

image

### PR DESCRIPTION
**Pull request by cshannon**
Also only shows stack traces in FileCompactor on file writer close errors when debug is enabled.

This closes #3023

### CODE REVIEW

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java [hunk 1]
```diff
@@ -280,7 +280,10 @@ public CompactionStats call() throws IOException, CompactionCanceledException {
           }
         }
       } catch (IOException | RuntimeException e) {
-        log.warn("{}", e.getMessage(), e);
+        log.warn("{}", e.getMessage());
+        if (log.isDebugEnabled()) {
+          log.debug(e.getMessage(), e);
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:285]: This is a safer version, in case there's any braces in the message that could be misinterpreted as a string interpolation.

```suggestion
          log.debug("{}", e.getMessage(), e);
```

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java [hunk 2]
```diff
@@ -392,7 +395,10 @@ private void compactLocalityGroup(String lgName, Set<ByteSequence> columnFamilie
             try {
               mfw.close();
             } catch (IOException e) {
-              log.error("{}", e.getMessage(), e);
+              log.error("{}", e.getMessage());
+              if (log.isDebugEnabled()) {
+                log.debug(e.getMessage(), e);
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:400]:
```suggestion
                log.debug("{}", e.getMessage(), e);
```

File: server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java [hunk 3]
```diff
@@ -578,6 +578,8 @@ protected Runnable createCompactionJob(final TExternalCompactionJob job,
         TCompactionStatusUpdate update2 = new TCompactionStatusUpdate(TCompactionState.SUCCEEDED,
             "Compaction completed successfully", -1, -1, -1);
         updateCompactionState(job, update2);
+      } catch (FileCompactor.CompactionCanceledException cce) {
+        LOG.debug("Compaction canceled {} ", job.getExternalCompactionId());
```
Comment (ctubbsii) [inline server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java:582]:
```suggestion
        LOG.debug("Compaction canceled {}", job.getExternalCompactionId());
```

**Review by ctubbsii — CHANGES_REQUESTED** [review]

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java [hunk 4]
```diff
@@ -280,7 +280,10 @@ public CompactionStats call() throws IOException, CompactionCanceledException {
           }
         }
       } catch (IOException | RuntimeException e) {
-        log.warn("{}", e.getMessage(), e);
+        log.warn("{}", e.getMessage());
+        if (log.isDebugEnabled()) {
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:284]: You don't need these `if (log.isDebugEnabled())` conditionals either. You only need that when you're avoiding some expensive operation while constructing the log message. The only thing you'd avoid here is `e.getMessage()`, which I don't think is necessary.

**Review by ctubbsii — CHANGES_REQUESTED** [review]

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java (hunk 4 above)
Comment (cshannon) [reply server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:284]: Good point, mostly a force of habit when doing debugging statements as sometimes it's expensive when outputting a lot of information. I'll push an update.

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java (hunk 1 above)
Comment (cshannon) [reply server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:285]: Good to know, I was wondering what the purpose of that was. I will keep that in mind for the future.

**Review by ctubbsii — COMMENTED** [review]
I think these changes are okay, but I'm not sure it's going to help folks who typically leave the debug logs enabled. In fact, it may make things worse for them, because now there's extra log statements, the basic one at warn and the more detailed stack trace at debug.

**Comment by cshannon** [comment]
> I think these changes are okay, but I'm not sure it's going to help folks who typically leave the debug logs enabled. In fact, it may make things worse for them, because now there's extra log statements, the basic one at warn and the more detailed stack trace at debug.

I suppose one thing we could do is only log one statement regardless depending on what is enabled so we don't have the second log statement. We could add back in the debug is enabled check, and if it is, then only log the full stack trace (either at debug level or even error/warn level) and if it's not enabled then just log the 1 line statement and no stack trace.

But, in my opinion, that isn't necessary and the change here should be ok as is. I'm not really worried about the extra log statements because if someone turns on debug then they should expect to get flooded with log statements and information as that is the entire point. To me this is about fixing the non-debug use case (ie not development but production) where you don't want see a bunch of extra stuff that isn't a big deal and you wouldn't leave debug turned on.

**Comment by ctubbsii** [comment]
> But, in my opinion, that isn't necessary and the change here should be ok as is. I'm not really worried about the extra log statements because if someone turns on debug then they should expect to get flooded with log statements and information as that is the entire point. To me this is about fixing the non-debug use case (ie not development but production) where you don't want see a bunch of extra stuff that isn't a big deal and you wouldn't leave debug turned on.

In revisiting the original issue that prompted this, I'm thinking about what I, as a user, would want the behavior to be. I think that when a tablet split causes an external compaction task to be cancelled, I would want to see a single warning per cancelled task, at most, if there's something I should do about it (like issue a new compaction command), or just a single debug message if there's nothing for me to do about it (in the case of an automatic retry or something). In the message, I would want to see compaction identifying information (compaction id?) and information about the tablet that split, but I don't think it would be helpful to see a stack trace at all in this situation. I'm not sure if there are any other situations where this code is called, though, so I'd be careful to check that before suppressing the stack trace for all callers.

**Comment by dlmarion** [comment]
The CompactionEnv implementation that is used in External Compactions is [ExtCEnv](https://github.com/apache/accumulo/blob/main/server/compactor/src/main/java/org/apache/accumulo/compactor/ExtCEnv.java). When [CompactionJobHolder.cancel()](https://github.com/apache/accumulo/blob/main/server/compactor/src/main/java/org/apache/accumulo/compactor/CompactionJobHolder.java#L61) is called, then ExtCEnv.isCompactionEnabled() returns false. CompactionJobHolder.cancel() is called from several places in Compactor.java. When it's called from Compactor.checkIfCanceled, then it's not an error, the compaction is being canceled because the tablet split, the table was deleted, or the user canceled the compaction. I think in this case, it warrants a debug message. When CompactionJobHolder.cancel is called via Compactor.cancel(String) from Compactor.run(), it's preceded by an error message.

I'm thinking that when env.isCompactionEnabled() returns false in FileCompactor.compactLocalityGroup() and a CompactionCanceledException is thrown, then FileCompactor.call() should log a debug message in the exception handler *and* suppress logging in the finally block.

**Comment by cshannon** [comment]
> compactLocalityGroup

Thanks for the explanation, I can catch the CompactionCanceledException in FileCompactor.call() [here](https://github.com/apache/accumulo/blob/7448970bc277bf1365bc0304b7d8f74412547617/server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java#L261) and log a debug instead of an error since it would be expected and in the finally block can update the logging to check if cancelled to supresss logging on file close. 

And just to make sure I am following you, I think I would also want to only log a debug inside compactLocalityGroup() [here](https://github.com/apache/accumulo/blob/7448970bc277bf1365bc0304b7d8f74412547617/server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java#L395) and get rid of the error also as it's trying to close because compaction was cancelled and it's checking the flag using env.isCompactionEnabled(). ?

Lastly, I assume we still want/need to rethrow the CompactionCanceledException from call() so  that Compaction.createCompactionJob() gets it so it knows it didn't finish. It would log another debug there currently with the way the PR is.

**Comment by dlmarion** [comment]
> Thanks for the explanation, I can catch the CompactionCanceledException in FileCompactor.call() [here](https://github.com/apache/accumulo/blob/7448970bc277bf1365bc0304b7d8f74412547617/server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java#L261) and log a debug instead of an error since it would be expected and in the finally block can update the logging to check if cancelled to supresss logging on file close.

Yes, this is what I'm thinking.

> And just to make sure I am following you, I think I would also want to only log a debug inside compactLocalityGroup() [here](https://github.com/apache/accumulo/blob/7448970bc277bf1365bc0304b7d8f74412547617/server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java#L395) and get rid of the error as it's trying to close because compaction was cancelled and it's checking the flag using env.isCompactionEnabled(). ?

So, I'm not sure. We may want to change this to a `warn` or `info`. I would be interested in other opinions here. It's possible that there could be other cases outside of external compaction cancellation where we would want to know this happened.

> Lastly, I assume we still want/need to rethrow the CompactionCanceledException from call() so that Compaction.createCompactionJob() gets it so it knows it didn't finish. It would log another debug there currently with the way the PR is.

Yes, I don't think we want to mess with the exceptions here, just the logging.

**Comment by cshannon** [comment]
@dlmarion  - thanks, I'll make some changes and push up a new commit today and then we can discuss, etc.

**Comment by cshannon** [comment]
It appears I have screwed up the history here with trying to merge main/reverts so I'm just going to reset from 2.1 and force push

**Comment by cshannon** [comment]
Ok I forced pushed up the latest, let me know what you think.

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java [hunk 5]
```diff
@@ -280,7 +283,13 @@ public CompactionStats call() throws IOException, CompactionCanceledException {
           }
         }
       } catch (IOException | RuntimeException e) {
-        log.warn("{}", e.getMessage(), e);
+        // If compaction was cancelled then this may happen due to an
+        // InterruptedException etc so suppress logging
+        if (!env.isCompactionEnabled()) {
```
Comment (dlmarion) [inline server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:288]: I think you have this backward.

Comment (cshannon) [reply server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:288]: Yup, indeed I do, oops.

**Comment by dlmarion** [comment]
This looks good. Suggest testing it on single node to see what happens in the monitor when compactions are canceled. I saw it when the `ci` table split when using external compactions and running continuous ingest. If you want to test single node, and need help with the configuration, let me know.

**Comment by cshannon** [comment]
> This looks good. Suggest testing it on single node to see what happens in the monitor when compactions are canceled. I saw it when the `ci` table split when using external compactions and running continuous ingest. If you want to test single node, and need help with the configuration, let me know.

Yeah I think testing would be good and I can report back how things look with log examples. I can message you on chat to get some info on setting up a good test.

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java [hunk 6]
```diff
@@ -280,7 +283,13 @@ public CompactionStats call() throws IOException, CompactionCanceledException {
...
+          log.debug("{}", e.getMessage(), e);
+        } else {
+          log.warn("{}", e.getMessage(), e);
+        }
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java:292]: I'm very confused about the negation and order of these. Getting rid of the negation, it becomes:

```suggestion
        // If compaction was cancelled then this may happen due to an
        // InterruptedException etc so suppress logging
        if (env.isCompactionEnabled()) {
          log.warn("{}", e.getMessage(), e);
        } else {
          log.debug("{}", e.getMessage(), e);
        }
```

But in addition to this, the comment is a bit confusing, because it talks about `if compaction was cancelled`, but the code says `if compaction is enabled`. It would be good to improve the comment so it connects the dots between the condition the code is checking and the phrasing of the comment. It's not clear to me from reading this the connection between compaction being enabled and a cancellation.

**Review by ctubbsii — CHANGES_REQUESTED** [review]
To simplify the code, please remove the negation on the condition, and change the order of the if/else. Also, I think the comment above it needs improved.

**Comment by cshannon** [comment]
Sure that is fine, makes more sense that way now that I think about it.

File: server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java (hunk 6 above)
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java]: Suggestion:

```
The CompactionEnv may disable the compaction for a number of reasons (e.g. user compaction cancelled, tablet split, table deletion, etc.). When this happens it's possible for an exception to be thrown when a file fails to close or some other cleanup-type issue. These error messages can be supressed.
```

Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java]: Ignore my last, I was making the comment at the same time you pushed a change. Your new comment is essentially the same.

Comment (cshannon) [reply server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java]: sounds good, your is a bit more concise but I think either is fine and as you said basically says the same thing.

**Comment by cshannon** [comment]
I ran this against Uno for a while with ingest running and a small split threshold to induce cancellations on tablet spltis and saw the following in the logs:

```
2022-11-10T06:24:05,091 [compaction.FileCompactor] DEBUG: Compaction canceled 7;683c;664
...
2022-11-10T06:26:55,021 [compaction.FileCompactor] DEBUG: Compaction canceled 7;0214<
```
No more stack trace or verbose output and I didn't see anything show up in the Monitor.

**Review by dlmarion — APPROVED** [review]

**Review by ctubbsii — APPROVED** [review]
