### PR TITLE
Fix #418 Javadoc updated with workaround for createIfNotExists

### LINKED ISSUE #418: Add createIfNotExists method to table/namespace operations
Currently, if you want to create a namespace or table in Accumulo that may already exists, you need to try to create it and ignore the exception.

```java 
  try {
      connector.namespaceOperations().create("mynamespace");
    } catch (NamespaceExistsException e) {
      // ignore
    }

    try {
      connector.tableOperations().create("mynamespace.mytable");
    } catch (TableExistsException e) {
      // ignore
    }
```

It would be nice if a `createIfNotExists` method was added to the API that ignored this exception. This would simplify the above code to the following:

```java
connector.namespaceOperations().createIfNotExists("mynamespace");
connector.tableOperations().createIfNotExists("mynamespace.mytable");
```

### PR DESCRIPTION
**Pull request by hkeebler**
Updated javadoc with the example provided by @keith-turner .  Why?  I needed something to do and I do like code examples in documentation.

### CODE REVIEW

**Comment by milleruntime** [comment]
Checkstyle got you!  Just make sure to remove trailing whitespace in javadoc:
<pre>
[INFO] --- maven-checkstyle-plugin:3.0.0:check (check-style) @ accumulo-core ---
[WARNING] src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:[71] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:[147] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
[WARNING] src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java:[89] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
</pre>
https://travis-ci.org/apache/accumulo/jobs/541226911

**Comment by hkeebler** [comment]
blast me for not reverifying after my reformat.  sorry.  trying again.

**Comment by milleruntime** [comment]
> blast me for not reverifying after my reformat. sorry. trying again.

It was actually Travis not me so blame him. :smile:

**Comment by hkeebler** [comment]
No Problem @milleruntime , I was blasting myself.

File: core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java [hunk 1]
```diff
@@ -84,7 +84,18 @@
 
   /**
    * Create an empty namespace with no initial configuration. Valid names for a namespace contain
-   * letters, numbers, and the underscore character.
+   * letters, numbers, and the underscore character. A safe way to ignore namespaces that do exist
+   * would be to do something like the following:
+   *
+   * <pre>
+   * {@code}
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java]: This won't work. You need:

```java
  /**
   * <pre>
   * {@code
   * ... code here; note the @code tag is open ...
   * }
   * </pre>
   */
```

```

Comment (hkeebler) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java]: Actually it does work and that's because I have the <pre> which I don't need if I use the {@code} correctly.  Thanks.

Comment (hkeebler) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java]: Took the @code out and left the "pre" tags.  the @code did not really do anything useful.

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java]: The main reason to use `{@code ... some code here ... }` is to not have to escape reserved HTML characters, like `<` and `>` as `&lt;` and `&gt;`, respectively. You weren't using any reserved characters, so you're fine either way. It can also be useful to some renderers to do syntax highlighting, but that's less important that displaying the contents in HTML correctly.
