### PR TITLE
Fixed TabletManagmentParameters serialization of replacements

### LINKED ISSUE #4107: TabletManagementParameters uses convoluted serialization
For #4103 , I replaced `List<Pair<Path,Path>>` with the much friendlier and more intuitive `Map<Path,Path>`.

However, when merging this into the elasticity branch, the TabletManagementIteratorIT failed. Looking at the server logs, I saw that it was failing on Gson serialization of TabletManagementParameters. In order to get it to pass, I had to preserve the `List<Pair<Path,Path>>` in the JsonData inner class, and convert it back and forth from the `Map<Path,Path>`. This is not ideal.

The TabletManagementParameters serialization should be fixed so it can use the simpler, `Map<Path,Path>` directly. I'm not sure what this involves yet, because I'm not sure why it's working with the list of pairs and not working with a map. Other maps, even of user classes, seem to deserialize just fine. And Path itself serializes fine either way. If anything, there should be fewer classes to serialize, because the removal of the Pair, so I don't understand it just yet.

See:

https://github.com/apache/accumulo/blob/48d39719148454f002ab346610ad39b911662acc/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java#L128-L129

and

https://github.com/apache/accumulo/blob/48d39719148454f002ab346610ad39b911662acc/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java#L248-L249

### PR DESCRIPTION
**Pull request by dlmarion**
TabletManagementParameters was still using a List<Pair<Path,Path>> for volume replacements serialization. This was changed to a Map<Path,Path> in other places of the code because there was an issue with Gson serialization. I added a test for serialization and deserialization and was able to successfully use a Map when setting enableComplexMapKeySerialization() on the Gson object.

Fixes #4107

### CODE REVIEW

File: server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java [hunk 1]
```diff
@@ -125,14 +126,17 @@ private TabletManagementParameters(JsonData jdata) {
       return Map.copyOf(resourceGroups);
     });
     this.canSuspendTablets = jdata.canSuspendTablets;
-    this.volumeReplacements = jdata.volumeReplacements.stream()
-        .collect(toUnmodifiableMap(Pair::getFirst, Pair::getSecond));
+    this.volumeReplacements = jdata.volumeReplacements;
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java:129]: This map seems to come from GSON, not sure if its modifiable.  If its could use Map.copyof or the following to make it unmodifiable. 

```suggestion
    this.volumeReplacements = Collections.unmodifiableMap(jdata.volumeReplacements);
```

File: server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementParametersTest.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+import org.apache.accumulo.core.metadata.TServerInstance;
+import org.apache.accumulo.core.metadata.schema.Ample;
+import org.apache.accumulo.server.manager.LiveTServerSet;
+import org.apache.hadoop.fs.Path;
+import org.junit.jupiter.api.Test;
+
+public class TabletManagementParametersTest {
+
+  @Test
+  public void testDeSer() {
```
Comment (keith-turner) [inline server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementParametersTest.java:39]: This is a good test to add.

**Review by keith-turner — APPROVED** [review]
