### PR TITLE
Corrected servlet parameter handling so that it does not break things

### LINKED ISSUE #1401: ShowTrace servlet is unusable
The fix for ACCUMULO-4660, 6f187823e4309ed79d6fa3f24b049731126f5263 , introduced a regression that makes it impossible to view traces via the Accumulo Monitor.

Specifically, `Basic.getStringParameter` was modified to strip out non-alphabetic characters from query parameters. Given that trace ids are hexadecimal strings, this causes all decimal digits to get stripped out. The `ShowTrace` servlet then behaves _very_ strangely as a result, as it ends up scanning the wrong range, which apparently returns entries that are not encoded spans, but tries to interpret them as such.

### PR DESCRIPTION
**Pull request by reggert**
This resolves #1401.

I removed the previous implementation of  string sanitization, replacing it with more specific checks at the places where the parameters are used. As it turns out, the broken method was only used in two places, `ListType` and `ShowTrace`. In the former case, sanitization was only needed when including in the HTML output, so I used `StringEscapeUtils.escapeHtml` for that. In the latter case, sanitization was needed prior to passing the string in an Accumulo range, so I used a regular expression in `getTraceID` to validate that the string contains exactly 16 hexadecimal digits, which is how trace IDs are represented in the trace table.

`BasicTest` was deleted because it was exclusively testing the broken
sanitization mechanism. No other tests exist for the servlets, which is a problem but out of scope for what this patch is fixing.

As a more long term solution, the servlets really ought to be replaced by JSP or another templating mechanism that can automatically handle escaping HTML content, rather that building HTML by concatenating Java strings.

### CODE REVIEW

File: server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/trace/ShowTrace.java [hunk 1]
```diff
@@ -45,9 +46,11 @@
   private static final long serialVersionUID = 1L;
   private static final String checkboxIdSuffix = "_checkbox";
   private static final String pageLoadFunctionName = "pageload";
+  private static final Pattern TRACE_ID_PATTERN = Pattern.compile("\\p{XDigit}{16}");
 
   String getTraceId(HttpServletRequest req) {
-    return getStringParameter(req, "id", null);
+    final String stringValue = getStringParameter(req, "id", null);
+    return TRACE_ID_PATTERN.matcher(stringValue).matches() ? stringValue : null;
```
Comment (ctubbsii) [inline server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/trace/ShowTrace.java]: This looks like it could produce an NPE from the matcher if `stringValue` is null. We probably want to add a check for that:

```suggestion
    if (stringValue == null) {
      return null;
    }
    return TRACE_ID_PATTERN.matcher(stringValue).matches() ? stringValue : null;
```

File: server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/trace/Basic.java [hunk 2]
```diff
@@ -51,13 +51,14 @@
...
       String defaultValue) {
-    String result = req.getParameter(name).replaceAll("[^A-Za-z]", "");
+    final String result = req.getParameter(name);
     if (result == null) {
       return defaultValue;
     }
     return result;
   }
 
+
```
Comment (ctubbsii) [inline server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/trace/Basic.java]: This extra whitespace will probably get deleted when the project is built, due to the formatter plugin. Please run the formatter with `mvn package -DskipTests` and update the PR with any changes.

Comment (reggert) [reply server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/trace/Basic.java]: Will do.

Comment (reggert) [reply server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/trace/Basic.java]: Done.
