### PR TITLE
stop removing backslashes in shell

### LINKED ISSUE #3367: Accumulo 2 shell scans require escape characters where Accumulo 1 did not
**Describe the bug**
If any part of the key has something like a null character separator, we used to be able to scan without escaping in Accumulo 1, but now we have to in Accumulo 2.

e.g.  for a composite edge key:
apple\x00banana
In Accumulo 1 we used to be able to run: `'scan -r apple\x00banana' `
but now in Accumulo 2 we have to add a slash: `'scan -r apple\\x00banana'`

We have a variety of scripts we'd need to update to handle this.  It is also not backwards compatible i.e. if we try to scan Accumulo 1.* with the extra slash, we get nothing.  We were wondering if it was intentional.

**To Reproduce**
Create a row with a null separator in the rowid and scan.

**Expected behavior**
We would expect to be able to scan the same way between Accumulo 1 and 2.

### PR DESCRIPTION
**Pull request by keith-turner**
fixes #3367

### CODE REVIEW

**Comment by keith-turner** [comment]
Created this as a draft because I am not sure what functionality this might break in jshell.   Also this changes shell behavior that has been different since 2.1.0.  Test this and it does work, the jline line reader no longer turns `\x00` into `x00`

File: shell/src/main/java/org/apache/accumulo/shell/Shell.java [hunk 1]
```diff
@@ -557,8 +558,16 @@ public void execute(final String[] args) throws IOException {
     }
   }
 
+  public static class NonEscapeParser extends org.jline.reader.impl.DefaultParser {
+    @Override
+    public boolean isEscapeChar(char ch) {
```
Comment (ddanielr) [inline shell/src/main/java/org/apache/accumulo/shell/Shell.java]: We should verify that only the backslash char is affected by this override. 

Otherwise disabling all escaping via the option in the builder might be cleaner as the option name is referenced in jline documentation. 

 `reader.setOption(LineReader.Option.DISABLE_EVENT_EXPANSION, true);`

**Comment by keith-turner** [comment]
Reworked this in commit 82900a9 to make Accumulo look for the jline option and set it.

Test that commit by inserting the following data in jshell.

```
jshell> client.tableOperations().create("test"); var writer=client.createBatchWriter("test"); Mutation m = new Mutation("r1"); m.at().family(new byte[]{'a',0,'b'}).qualifier("q").put("v1"); writer.addMutation(m); writer.close();
```

Then made the following change in accumulo-env.sh

```bash
JAVA_OPTS=(
  '-XX:OnOutOfMemoryError=kill -9 %p'
  '-XX:-OmitStackTraceInFastThrow'
  '-Djava.net.preferIPv4Stack=true'
  '-Dorg.jline.reader.props.disable-event-expansion=on'
  "-Daccumulo.native.lib.path=${lib}/native"
  "${accumulo_initial_opts[@]}"
)
```

After that, ran the shell and jline is no longer removing `\`

```
root@uno> scan -t test -c a\x00b
r1 a\x00b:q []	v1
```

**Review by ddanielr — APPROVED** [review]
