### PR TITLE
Throw new exception when invalid tablet hosting request made

### LINKED ISSUE #3326: OnDemand Follow-on: Shell scans hang when scanning tables with NEVER hosting goal
Attempts to scan a table from the Accumulo Shell hang if the table has a hosting goal of NEVER.

This issue occurs when running an Accumulo instance built from the Elasticity branch of Accumulo.

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #3326

### CODE REVIEW

**Review by cshannon — APPROVED** [review]
LGTM, I tested everything out and looks like the issue is fixed. I had some timeout issues running various tests in `ShellServerIT` which I think must be due to things being slower to come online now with ondemand goal being the default. 

When I increased the timeout factor to 2 the new `scansWithNeverHostedTablets` test inside `ShellServerIT` is passing and I confirmed the test fails if you remove the update in `MetadataTableUtil` that handles the exception and throws a `RuntimeException` to prevent the retry. I also verified the output in the shell logs that showed the new exception being thrown and properly passed up and handled.

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java [hunk 1]
```diff
@@ -213,10 +214,12 @@ Collection<Text> listSplits(String tableName, int maxSplits)
    * @param ranges The input ranges that should be mapped to tablet servers and tablets.
    *
    * @throws TableOfflineException if the table is offline or goes offline during the operation
+   * @throws InvalidTabletHostingRequestException if tablet hosting is requested for table with
+   *         NEVER goal
    * @since 1.8.0
    */
-  Locations locate(String tableName, Collection<Range> ranges)
-      throws AccumuloException, AccumuloSecurityException, TableNotFoundException;
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: Not sure about binary compatibility, but I think adding or removing checked exceptions breaks source compatibility.  So we usually avoid changing them.  Could make this an unchecked exception and declare it in the javadoc.

Comment (cshannon) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: I didn't think we would care about breaking compatibility since this is the 4.0 branch and for elasticity. Seems like for a major version it would be fine to be incompatible with a new API in this case but I could be wrong.

One plus is if it is a runtime exception you could re-work this and avoid having to add the exception everywhere to rethrow it. Another option to avoid having to add it to the throws line everywhere is to update the new exception to  just extend AccumuloException and still handle it separately. However, this would not follow the typical pattern as all the existing exceptions just seem to extend Exception or RuntimeException.

Comment (EdColeman) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: If the method is only changing the exceptions - it may not be possible to mark the method as deprecated and provide the "new" method - if the only difference is the exceptions in the method signature.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: I used the checked exception because it caused things to not-compile and break in the IDE. That allowed me to figure out how/where to handle the exception. If I were to throw an AccumuloException or RuntimeException from the ClientTabletCacheImpl.requestTabletHosting method, then it would likely have been swallowed and in some cases not handled correctly. Regarding the new exception, unlike a TableNotFoundException, the client could retry the operation after removing the ranges that are set to NEVER.

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java [hunk 2]
```diff
@@ -558,9 +561,12 @@ Map<String,Set<Text>> getLocalityGroups(String tableName)
    * @throws AccumuloException if a general error occurs
    * @throws AccumuloSecurityException if the user does not have permission
    * @throws TableNotFoundException if the table does not exist
+   * @throws InvalidTabletHostingRequestException if tablet hosting is requested for table with
+   *         NEVER goal
    */
   Set<Range> splitRangeByTablets(String tableName, Range range, int maxSplits)
-      throws AccumuloException, AccumuloSecurityException, TableNotFoundException;
+      throws AccumuloException, AccumuloSecurityException, TableNotFoundException,
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:568]: Looking into the implementation of this it only needed tablet extents and did not need tablet locations (it was ignoring them).  I updated it to call a new method in the tablet cache that allows getting the extents w/ or w/o a location. So it should not throw this exception anymore.  The pr w/ the update is #3330

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: > I didn't think we would care about breaking compatibility since this is the 4.0 branch and for elasticity.

We don't usually break the compatibility of method in place.  We usually deprecate them and introduce new methods.  This allows code to keep compiling while devs work through removing deprecated code.  As @EdColeman  mentioned when you only want to change the checked exceptions on a method, Java provides no good way to slowly evolve this that I know of.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: > Regarding the new exception, unlike a TableNotFoundException, the client could retry the operation after removing the ranges that are set to NEVER.

That is a good thing .  Its nice to have things that people can reliably write automation against for specific error conditions rather than parsing the exception message.

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 2 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: I suppressed this exception in 8694d09 as, in theory, it shouldn't happen.

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: My take-away from this thread is that I have nothing to do here. Correct?

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: If we make InvalidTabletHostingRequestException a RunTimeException instead of an Exception we can avoid an incompatible change.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: InvalidTabletHostingRequestException could also extend AccumuloException and void a breaking change.  This avoids the breaking change while still passing more specific information that can easily be automatically handled.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: > If we make InvalidTabletHostingRequestException a RunTimeException instead of an Exception we can avoid an incompatible change.

If we make it a RuntimeException, then existing code will compile successfully and users may not realize that they can catch the exception, modify their parameters, and retry the operation to get a successful response.

> InvalidTabletHostingRequestException could also extend AccumuloException and void a breaking change. This avoids the breaking change while still passing more specific information that can easily be automatically handled.

This has the same problem as the RuntimeException. In addition, there can be places in our code where we need to handle the InvalidTabletHostingRequestException differently than a generic AccumuloException (ref [this](https://github.com/apache/accumulo/pull/3329/files#diff-220fceec2f35665a23a2111c5d354962d923a7183130529fdacbaa0f3321ec84R155)).


I'm not concerned about breaking compatibilty, as I think the elasticity branch is going to end up being a 4.0.0 release. If adding this Exception to this method is still an issue with a major release, then I would suggest that we deprecate `TableOperations.locate` in `3.0.0` and then rename `locate` to `locateTablets` or something in the `elasticity` branch (which again, would cause the `elasticity` branch to be a 4.0.0 version).

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: I think I have a solution which will not require the API change. The solution is to create `ClientTabletCache.binHostedRanges` which calls `findTablets` with `LocationNeed.NOT_REQUIRED` and catches the Exception. it occurred to me after writing my last comment, that merely finding tablet locations should not require hosting.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:219]: This is the API method that assumes all tablets have a location.  https://github.com/apache/accumulo/blob/1fd1284afc270366d4dfadb79ee285fab5b060c9/core/src/main/java/org/apache/accumulo/core/client/admin/Locations.java#L53

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: Modified TableOperationsImpl.locate to call findTablets instead of binRanges, in 6744e61

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: I looked at the changes in 6744e61 and it changes the behavior behind the API.  The API used to return locations for every tablet in the given range.  Now it returns a subset of the tablets in the range that happen to have a location.  For anything using this API the behavior change could cause it to break in weird ways.    

We can not leave the API as is because it could cause tablets to be unexpectedly hosted.  The API just does not seem viable with the on demand changes, I don't see a way to make it do anything sensible.

I can take a stab at deprecating this in 3.x, then we can delete the API in the elasticity branch.   Let me know if you see any issues with that.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: This API made me wonder about map reduce and I ended up opening #3341

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: > I looked at the changes in [6744e61](https://github.com/apache/accumulo/commit/6744e611c514ecebe41c37f0ea398ef2ee1e8219) and it changes the behavior behind the API. The API used to return locations for every tablet in the given range. Now it returns a subset of the tablets in the range that happen to have a location. For anything using this API the behavior change could cause it to break in weird ways.
> 
> We can not leave the API as is because it could cause tablets to be unexpectedly hosted. The API just does not seem viable with the on demand changes, I don't see a way to make it do anything sensible.
> 
> I can take a stab at deprecating this in 3.x, then we can delete the API in the elasticity branch. Let me know if you see any issues with that.

Yeah, I was trying to just locate the tablets that are hosted, not cause others to be hosted just by trying to get the location. If you think that is the best course of action, I have no issue with that.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: I had one more idea, maybe we can just make this only w/ a hosting goal of always.  Going to pull your branch and add that check and see what it looks like.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 3]
```diff
@@ -1917,27 +1925,19 @@ public Locations locate(String tableName, Collection<Range> ranges)
...
-      }
-      locator.invalidateCache();
+    Map<String,Map<KeyExtent,List<Range>>> binnedRanges = new HashMap<>();
+    try {
+      @SuppressWarnings("unused")
+      List<Range> failed = locator.findTablets(context, rangeList, ((cachedTablet, range) -> {
+        if (cachedTablet.getTserverLocation().isPresent()) {
+          ClientTabletCacheImpl.addRange(binnedRanges, cachedTablet, range);
+        }
+      }), LocationNeed.NOT_REQUIRED);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1938]: I locally tired making the method only work with the ALWAYS hosted goal.  Did not test this, it does compile. This is an alternative approach to deprecating and removing.  I like this approach.  If we go with this approach over deprecation then would need to update the javadoc to mention it only works with tablets that have a certain hosting goal.

```suggestion
Retry retry = Retry.builder().infiniteRetries().retryAfter(100, MILLISECONDS)
            .incrementBy(100, MILLISECONDS).maxWait(2, SECONDS).backOffFactor(1.5)
            .logInterval(3, MINUTES).createRetry();

    ArrayList<KeyExtent> locationLess = new ArrayList<>();
    Map<String,Map<KeyExtent,List<Range>>> binnedRanges = new HashMap<>();

    BiConsumer<CachedTablet,Range> rangeConsumer = (cachedTablet, range) -> {
      if (cachedTablet.getTserverLocation().isPresent()) {
        ClientTabletCacheImpl.addRange(binnedRanges, cachedTablet, range);
      } else {
        locationLess.add(cachedTablet.getExtent());
      }
    };

    try {

      List<Range> failed =
          locator.findTablets(context, rangeList, rangeConsumer, LocationNeed.NOT_REQUIRED);

      while (!failed.isEmpty() || !locationLess.isEmpty()) {
        context.requireTableExists(tableId, tableName);
        context.requireNotOffline(tableId, tableName);

        boolean allAlwaysHosted = context.getAmple().readTablets().forTablets(locationLess)
            .fetch(PREV_ROW, HOSTING_GOAL).build().stream()
            .allMatch(tmeta -> tmeta.getHostingGoal() == TabletHostingGoal.ALWAYS);

        if (!allAlwaysHosted) {
          throw new AccumuloException(
              "TableOperations.locate() only works with tablets that have a hosting goal of "
                  + TabletHostingGoal.ALWAYS
                  + ". Tablets with other hosting goals were seen.  table:" + tableName
                  + " table id:" + tableId);
        }

        try {
          retry.waitForNextAttempt(log,
              String.format("locating tablets in table %s(%s) for %d ranges", tableName, tableId,
                  rangeList.size()));
        } catch (InterruptedException e) {
          throw new RuntimeException(e);
        }

        locationLess.clear();
        binnedRanges.clear();
        locator.invalidateCache();
        failed = locator.findTablets(context, rangeList, rangeConsumer, LocationNeed.NOT_REQUIRED);
      }

```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 4]
```diff
@@ -1248,17 +1250,21 @@ public Set<Range> splitRangeByTablets(String tableName, Range range, int maxSpli
...
-      unmergedExtents.clear();
-      tl.invalidateCache();
+        log.warn("Unable to locate bins for specified range. Retrying.");
+        // sleep randomly between 100 and 200ms
+        sleepUninterruptibly(100 + random.nextInt(100), MILLISECONDS);
+        unmergedExtents.clear();
+        tl.invalidateCache();
+      }
+    } catch (InvalidTabletHostingRequestException e) {
+      throw new RuntimeException("findTablets requested tablet hosting when it should not have", e);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1267]:
```suggestion
      throw new AccumuloException("findTablets requested tablet hosting when it should not have", e);
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 5]
```diff
@@ -1917,27 +1925,19 @@ public Locations locate(String tableName, Collection<Range> ranges)
...
+    Map<String,Map<KeyExtent,List<Range>>> binnedRanges = new HashMap<>();
+    try {
+      @SuppressWarnings("unused")
+      List<Range> failed = locator.findTablets(context, rangeList, ((cachedTablet, range) -> {
+        if (cachedTablet.getTserverLocation().isPresent()) {
+          ClientTabletCacheImpl.addRange(binnedRanges, cachedTablet, range);
+        }
+      }), LocationNeed.NOT_REQUIRED);
+    } catch (InvalidTabletHostingRequestException e) {
+      throw new RuntimeException("findTablets requested tablet hosting when it should not have", e);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1940]:
```suggestion
      throw new AccumuloException("findTablets requested tablet hosting when it should not have", e);
```

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: I made a comment with an alternative approach to deprecation.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: I applied your patch so that I could better see the differences. For the tablets that are returned, I don't think all of them have a goal of ALWAYS as the one's returned in the initial call to `locator.findTablets` could be currently hosted, but with a goal of ONDEMAND. The retry code checks that the tablets have a goal of ALWAYS. This change also clears the TabletLocator, so any other concurrent operation may incur a latency penalty when it tries to scan / write to a Tablet. Since this change introduces a call to Ample to check that the `locationless` are ALWAYS hosted, I wonder if `TableOperations.locate` should just call Ample and return the `Locations` for ALWAYS hosted Tablets for the requested table and not clear/use the TabletLocator.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 5 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: Changed in 73b1967.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 4 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: Changed in 73b1967.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 6]
```diff
@@ -1917,27 +1927,68 @@ public Locations locate(String tableName, Collection<Range> ranges)
...
+            .fetch(PREV_ROW, HOSTING_GOAL).build().stream()
+            .allMatch(tmeta -> tmeta.getHostingGoal() == TabletHostingGoal.ALWAYS);
+
+        if (!allAlwaysHosted) {
+          throw new AccumuloException(
+              "TableOperations.locate() only works with tablets that have a hosting goal of "
+                  + TabletHostingGoal.ALWAYS
+                  + ". Tablets with other hosting goals were seen.  table:" + tableName
+                  + " table id:" + tableId);
+        }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1973]: Since we are clearing the cache before the goals in the cache should be really fresh and would could probably drop the call to ample only use the data from the cache. In the rangeConsumer passed to the cache we could add to a list of extents (or set an atomic boolean to true) that do not have a goal of always.  We can check that and if its not as expected throw this exception.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 7]
```diff
@@ -1917,27 +1927,68 @@ public Locations locate(String tableName, Collection<Range> ranges)
...
+
+    try {
+
+      List<Range> failed =
+          locator.findTablets(context, rangeList, rangeConsumer, LocationNeed.NOT_REQUIRED);
+
+      while (!failed.isEmpty() || !locationLess.isEmpty()) {
+
+        log.warn("failures: {}", failed);
+        log.warn("w/out location: {}", locationLess);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1959]: These can occur under normal conditions in a cluster, could log at a lower level of debug.  Also the retry object will log something that is more consistent across the code.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCache.java [hunk 8]
```diff
@@ -328,6 +338,10 @@ public Optional<String> getTserverLocation() {
     public Optional<String> getTserverSession() {
       return Optional.ofNullable(tserverSession);
     }
+
+    public TabletHostingGoal getGoal() {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCache.java:342]: I think this goal in the cache could be really useful in the future, but its a bit different than the location so tried to capture that in the javadoc.

```suggestion
    /**
      * This information in the cache may have a higher chance of being stale than other entries in the cache.
      * The location in the cache is cleared when something tries to use the location and its wrong.  There is 
      * currently no feedback loop like that for the cached goal.  If this information is needed to be fresh may want
      * to consider clearing the cache.
      */
    public TabletHostingGoal getGoal() {
```

Since its a bit different we may want to know its age when using it from the cache.  Thinking we could add an age getter to the cachedtablet class.  Could record nano time when its the object is created and then have something like.

```java
   Duration getAge() {
      return Duration.ofNanos(System.nanoTime() - creationTime):
   }
```

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: I like adding the goal to the cache.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 7 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1959]: I used these for debugging, I will remove them.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 6 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:1973]: You are saying that we can remove the entire retry loop?

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 7 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: Removed in 8066fd0

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 6 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: Used AtomicBoolean in consumer to identify when tablet found in Range with goal != ALWAYS. Removed call to Ample in 8066fd0.
