### PR TITLE
Make ZooCache close() and clear() more idempotent

### LINKED ISSUE #291: Error logged when running cingest createtable
The following gets logged every time I run `cingest createtable` on main.

```
2025-02-11T16:26:04,272 [testing.continuous.CreateTable] INFO : Created Accumulo table ci with 20 tablets
2025-02-11T16:26:04,375 [apache.zookeeper.ClientCnxn] ERROR: Error while calling watcher.
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.core.zookeeper.ZooCache.clear(ZooCache.java:487) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.core.zookeeper.ZooCache$ZCacheWatcher.process(ZooCache.java:129) ~[accumulo-testing-shaded.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:564) [accumulo-testing-shaded.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:539) [accumulo-testing-shaded.jar:?]
```

This may be related to recent changes to `ZooCache` in accumulo.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes [accumulo-testing#291](https://github.com/apache/accumulo-testing/issues/291)

These changes make it so that if `close()` or `clear()` are called on a `ZooCache` that has already been closed, it will essentially just return. This is a change in behavior since before, an exception would be thrown in these cases.

I was seeing this exception being thrown when running `cingest createtable` in accumulo-testing (see ticket linked above for more details). And I think this is happening from asynchronous calls coming in after a call to close has already happened.

### CODE REVIEW

**Comment by DomGarguilo** [comment]
In eed5e0d I removed the logs I had in place to help while manually testing this change as well as switched backed from using an `AtomicBoolean` to the original `volatile boolean` since that seems fine here. Overall the change set is very small now especially ignoring the trivial changes to improve the `Preconditions.checkState()` messages.

**Review by keith-turner — APPROVED** [review]

File: core/src/main/java/org/apache/accumulo/core/zookeeper/ZooCache.java [hunk 1]
```diff
@@ -484,13 +484,18 @@ protected void copyStats(ZcStat userStat, ZcStat cachedStat) {
...
+    if (closed) {
+      return;
+    }
     nodeCache.clear();
     updateCount.incrementAndGet();
     log.trace("{} cleared all from cache", cacheId);
   }
 
   public void close() {
+    if (closed) {
```
Comment (cshannon) [inline core/src/main/java/org/apache/accumulo/core/zookeeper/ZooCache.java:496]: Changes here are fine, but I was wondering if it would be better to use a final AtomicBoolean for the closed flag instead of a volatile. The atomic classes are really nice for use cases like this. You could then do something like:

public void close() {
  if (closed.compareAndSet(false, true)) {
    clear();
  }
}
```

Comment (cshannon) [reply core/src/main/java/org/apache/accumulo/core/zookeeper/ZooCache.java:496]: Oops nevermind, I missed the comment where the AtomicBoolean was switched to a volatile on purpose so ignore.

**Review by cshannon — APPROVED** [review]

**Comment by DomGarguilo** [comment]
I had the same thought and tried this on a earlier iteration. The problem
is the flag would be true before clear() is called.

**Comment by cshannon** [comment]
> I had the same thought and tried this on a earlier iteration. The problem is the flag would be true before clear() is called.
Ah, yep that flag would be set immediately, so that makes sense to leave it how it is then.

File: core/src/main/java/org/apache/accumulo/core/zookeeper/ZooCache.java (hunk 1 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/zookeeper/ZooCache.java:496]: I came here to make the same comment. I know it was changed back on purpose. But the reasoning stated was "that seems fine here". While it may be "fine", I still think the use of compareAndSet is cleaner, and is better than the using volatile directly. Internally, the AtomicBoolean uses a volatile, so it has the same memory effects either way... but the AtomicBoolean is easier to reason about, because it makes it clear what the memory effects are without needing to check the flags on the variable, and compareAndSet is a nice clean API.

**Comment by ctubbsii** [comment]
> > I had the same thought and tried this on a earlier iteration. The problem is the flag would be true before clear() is called.
> 
> Ah, yep that flag would be set immediately, so that makes sense to leave it how it is then.

I don't see why that's a problem. If the close gets interrupted, then there are bigger problems happening. In the normal case, the clear is going to be called.
