### PR TITLE
Resolve relative delete markers on upgrade. Closes #1463

### LINKED ISSUE #1463: Investigate the need for commons-beanutils dependency
In d7a407a3d6367b96fbc513f5b94b3c0511a68bf0, commons-beanutils was added to satisfy a missing runtime dependency for commons-configuration 2.5, which is not necessarily a mandatory dependency (it's optional, depending on how one uses the commons-configuration API).

It's not clear that we actually need or want to use the features in commons-configuration 2 that require commons-beanutils. In 1ed12fa585a37caf36cfd674bd7ad6903c1d4e79, some of the spammy debug logging from that library was suppressed for the testing environment, but it raises the question of whether we even need it in the first place.

For example, I believe the following code requires it:

```java
var file = new File(path);
var propsBuilder =
  new FileBasedConfigurationBuilder<PropertiesConfiguration>(PropertiesConfiguration.class)
  .configure(new Parameters().properties().setFile(file));
```

However, I think the following code would probably not require it:

```java
var file = new File(path);
var propConfig = new PropertiesConfiguration();
try (var reader = new FileReader(file)) {
    propConfig.getLayout().load(propConfig, reader);
}
```

I do not know if this code can be simply swapped out or not, and whether all our tests would pass or not, and whether we'd lose any functionality (especially important functionality, such as interpolation, importing common config from another file, or injecting system environment variables).

Investigation is needed to determine:

1. Can we safely drop the commons-beanutils dependency (with or without changing how we load properties with commons-configuration2.5's API)?
2. If yes to item 1, does interpolation work? Does injecting system properties?
3. Do we use any data type conversions that are broken?
4. Does the changes to remove it fix the spammy debug log messages that were suppressed in 1ed12fa585a37caf36cfd674bd7ad6903c1d4e79 ?

More information on commons-configuration basic features can be found at https://commons.apache.org/proper/commons-configuration/userguide/howto_basicfeatures.html ; this covers information about interpolation and data type conversions that may be relevant to understand in order to properly investigate this.

If we can drop the commons-beanutils dependency, I think we should. And, if we can get rid of the use of the `FileBasedConfigurationBuilder` class without loss of essential functionality, I think we should do that, too.

### PR DESCRIPTION
**Pull request by milleruntime**
* Also some minor clean up to Upgrader9to10

### CODE REVIEW

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java [hunk 1]
```diff
@@ -625,4 +626,39 @@ private static Path resolveRelativePath(String metadataEntry, Key key) {
...
+    Path pathNoVolume = VolumeManager.FileType.TABLE.removeVolume(new Path(oldDelete));
+
+    // abs path won't be null so return
+    if (pathNoVolume != null)
+      return pathNoVolume;
+
+    // use Path to check the format is correct
+    Path pathToCheck = new Path(oldDelete);
+    Preconditions.checkState(
+        oldDelete.startsWith("/") && (pathToCheck.depth() == 2 || pathToCheck.depth() == 3),
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: Should have comment to briefly explain intent of this check, so its implementation can be more easily verified. The current comment just says "check the format is correct", but does not explain what it means to be "correct".

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java [hunk 2]
```diff
@@ -625,4 +626,39 @@ private static Path resolveRelativePath(String metadataEntry, Key key) {
...
+  /**
+   * Resolve old relative delete markers of the form /tableId/tabletDir/[file] to
+   * UpgradeVolume/tables/tableId/tabletDir/[file]
+   */
+  static Path resolveRelativeDelete(VolumeManager fs, String oldDelete, String upgradeProperty) {
+    Path pathNoVolume = VolumeManager.FileType.TABLE.removeVolume(new Path(oldDelete));
+
+    // abs path won't be null so return
+    if (pathNoVolume != null)
+      return pathNoVolume;
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: This says "absolute path won't be null", but that's not the same as "relative path must be null". Can relative path be non-null? If so, then this will return for both absolute paths and non-null relative paths.

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java [hunk 3]
```diff
@@ -430,26 +432,27 @@ public void upgradeFileDeletes(ServerContext ctx, Ample.DataLevel level) {
...
-          olddelete.startsWith("/") && relPath.depth() == 3 || relPath.depth() == 4,
-          "Unrecongnized relative delete marker {}", olddelete);
-    }
-
-    if (relPath.depth() == 3 && !relPath.getName().startsWith(Constants.BULK_PREFIX)) {
-      return GcVolumeUtil.getDeleteTabletOnAllVolumesUri(TableId.of(relPath.getParent().getName()),
-          relPath.getName());
+  static String switchToAllVolumes(Path olddelete) {
+    // for directory, change volume to all volumes
+    if (olddelete.depth() == 4 && !olddelete.getName().startsWith(Constants.BULK_PREFIX)) {
```
[the remark this answers is not in the document]
Comment (keith-turner) [reply server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: Volumes do not have to be depth of 1.  For example a user could configure a volume like `hdfs://localhost:9000/dev/accumulo`.  This would make a dir using that volume have a depth != 4.

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java [hunk 4]
```diff
@@ -625,4 +626,39 @@ private static Path resolveRelativePath(String metadataEntry, Key key) {
...
+
+    // found relative paths so verify the property used to build the absolute paths
+    if (upgradeProperty == null || upgradeProperty.isBlank()) {
+      throw new IllegalArgumentException(
+          "Missing required property " + Property.INSTANCE_VOLUMES_UPGRADE_RELATIVE.getKey());
+    }
+    Path absPath =
+        new Path(upgradeProperty, VolumeManager.FileType.TABLE.getDirectory() + oldDelete);
+    try {
+      if (!fs.exists(absPath)) {
```
Comment (keith-turner) [inline server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: Delete entries do not have to exists.  This can happen when the GC deletes some files, but the GC process dies before it deletes the delete entries.

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (milleruntime) [reply server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: Ah OK.  Then we still need to remove the volume before checking.  

@ctubbsii I added a comment above the line and at the beginning of the method.  I will add the ```removeVolume``` call back and update the comments.

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java (hunk 2 above)
Comment (milleruntime) [reply server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: The ```removeVolume``` method will return null if it doesn't have a volume aka it is a relative path.

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java (hunk 4 above)
Comment (milleruntime) [reply server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: Good to know, thanks.  I will remove this check.

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java (hunk 1 above)
Comment (milleruntime) [reply server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: Updated comments.  Let me know if it is more clear now

**Comment by milleruntime** [comment]
@ctubbsii I think this is good to go if you are happy with updated the comments

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java [hunk 5]
```diff
@@ -625,4 +630,30 @@ private static Path resolveRelativePath(String metadataEntry, Key key) {
...
   }
+
+  /**
+   * Resolve old relative delete markers of the form /tableId/tabletDir/[file] to
+   * UpgradeVolume/tables/tableId/tabletDir/[file]
+   */
+  static Path resolveRelativeDelete(String oldDelete, String upgradeProperty) {
+    Path pathNoVolume = VolumeManager.FileType.TABLE.removeVolume(new Path(oldDelete));
+
+    // removeVolume will return null if path doesn't have a volume aka is a relative path
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: I'm still a bit concerned about the wording of this comment here. Is this an `if` or an `iff (if and only if)`?

File: server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java (hunk 1 above)
Comment (ctubbsii) [reply server/master/src/main/java/org/apache/accumulo/master/upgrade/Upgrader9to10.java]: This is definitely better. Thanks.

**Comment by milleruntime** [comment]
I updated the comment again and added test for this scenario to ```FileTypeTest.```  I get a sense that you are more concerned about the FileType method itself then the upgrade code.  There is still potential for the bug you created [here](https://issues.apache.org/jira/browse/ACCUMULO-3577) which I think should be addressed separately.

**Comment by ctubbsii** [comment]
The "otherwise" wording makes it clear this is a bi-implication. :smiley_cat:

**Comment by ctubbsii** [comment]
To aid future code archaeologists. The references to #1463 in the commits here are a mistake. They should reference #1465 instead. :smiley_cat:
