### PR TITLE
Fixed bug with USER compaction hints showing on SYSTEM compactions

### LINKED ISSUE #4460: Seeing execution hints in logs for system compaction
**Describe the bug**
After running a user compaction with hints, the hints will show up in the logs for system compactions.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 7c6572caf336cd76bb794befe7a31dce3503cd4b

**To Reproduce**
A compaction like the following was run with execution hints set.

```
compact -t testtab -w --exec-hints compaction_type=test
```

The user compaction completed and more files were inserted causing a system compaction.  The logging for system compaction showed the hints from the previous user compaction.  Hints should only be associated with an active user compaction.

```
2024-04-12T20:54:46,255 [tablet.files] DEBUG: Compacting 2<< on i.default.small for SYSTEM from [F000000f.rf, F000000e.rf, F000000d.rf, A000000c.rf] size 864 bytes config [hints={compaction_type=test}]
```

**Expected behavior**
Should not see hints related to system compactions.

### PR DESCRIPTION
**Pull request by kevinrr888**
Closes #4460
- Confirmed that these changes fix the issue: no longer shows hints on SYSTEM compactions which follow a USER compaction that had hints
- This may not be the best way to fix this issue but this keeps the amount of code changes small. Figured filtering them out at the time they are logged may not be the best approach in case these incorrect hints would be seen/used deeper in the code. But also didn't filter them out at the deepest level where they are set. This would have required larger refactoring.
- This issue made me think that maybe these execution hints would carry over to new USER compactions. For example, if a user compaction is initiated with execution hints "hints1", and later another user compaction was initiated with no execution hints, we may still see "hints1". I confirmed that this is not the case.

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java [hunk 1]
```diff
@@ -1281,6 +1281,10 @@ private Optional<CompactionInfo> reserveFilesForCompaction(CompactionServiceId s
 
       cInfo.localHelper = this.chelper;
       cInfo.localCompactionCfg = this.compactionConfig;
+      // don't include execution hints, which may have been previously set, for system compactions
+      if (job.getKind() == CompactionKind.SYSTEM) {
+        cInfo.localCompactionCfg.setExecutionHints(Collections.emptyMap());
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java:1286]: `cInfo.localCompactionCfg` is a reference to `this.compactionConfig` so changing it will change `this.compactionConfig` which could cause bugs with user compactions. 

`cInfo.localCompactionCfg` really only needs to be logged for user compactions.  One way to achieve this is to only set `cInfo.localCompactionCfg` for user compactions and have it be null otherwise.  This would log null for the config then.

Comment (kevinrr888) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java]: Ah okay wasn't sure if other config was still needed in the logs for SYSTEM compactions. Addressed

Comment (kevinrr888) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java]: Also manually verified that this change works

**Review by keith-turner — APPROVED** [review]
