### PR TITLE
Caches non-existence of ZK node for ZooCache.getChildren

### LINKED ISSUE #5047: The handling of children for non-existent nodes in ZooCache may not be correct.
**Describe the bug**

ZooCache attempts to cache nonexistence.  This may not be done correctly for the case of getChildren.

The ZooCache code expects that ZooKeeper.getChildren() may return null [here](https://github.com/apache/accumulo/blob/cfae5e9abc7447aacc7136777f853fc0842c49de/core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java#L316-L318).  However it will probably never return null.  When a node in zookeeper exists and has no children an empty list is returned.  When a node does not exist a NONODE KeeperException is thrown.  The code zoocache code is handling this, however it does not cache this.   The code behaves correctly, this is only a possible performance bug.

**Expected behavior**

 * Remove handling for null in code as its not expected to ever happen.
 * Determine if its safe to cache non-existence for getChildren, which depends on ZK watcher behavior.  If it is safe then look into changing the code to cache this.  If not then only the null handling needs to be removed for this issue.

### PR DESCRIPTION
**Pull request by keith-turner**
For a nodes data in zookeeper ZooCache was caching when a node did not exist.  However for getChildren when a node did not exist it would not cache this and would always go to zookeeper. Also ZooCache was handling a null return from Zookeeper.getChildren that would never happen.  Fixed these issues.

fixes #5047

### CODE REVIEW

**Review by dlmarion — APPROVED** [review]
LGTM

File: test/src/main/java/org/apache/accumulo/test/zookeeper/ZooCacheIT.java [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+  }
+
+  @Test
+  public void testGetChildren() throws Exception {
+    ZooCache zooCache = new ZooCache(zk, null);
+
+    zk.mkdirs("/test2");
+    zk.mkdirs("/test3");
+    zk.mkdirs("/test3/c1");
+    zk.mkdirs("/test3/c2");
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/zookeeper/ZooCacheIT.java:66]: mkdirs on the parent before the child is redundant. The purpose of the method is to create each node in the hierarchy. The purpose of the method is analogous to `mkdir -p`

```suggestion
    zk.mkdirs("/test2");
    zk.mkdirs("/test3/c1");
    zk.mkdirs("/test3/c2");
```

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java [hunk 2]
```diff
@@ -316,43 +277,46 @@ public List<String> getChildren(final String zPath) {
...
-            } catch (InterruptedException e) {
-              throw new ZcInterruptedException(e);
+          try {
+            final ZooKeeper zooKeeper = getZooKeeper();
+            // Register a watcher on the node to monitor creation/deletion events for the node. It
+            // is possible that an event from this watch could trigger prior to calling getChildren.
+            // That is ok because the compute() call on the map has a lock and processing the event
+            // will block until compute() returns. After compute() returns the event processing
+            // would clear the map entry.
+            Stat stat = zooKeeper.exists(zPath, watcher);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:299]: I'm wondering if this is going to cause an increase in the number of watches that we cannot clean up (or have a hard time doing so). If the node doesn't exist, and never comes into existence, the watch will be registered forever. This was one of the problems that motivated moving the system/table/namespace configs to a single node, because we were watching for exists on property keys for properties that were never stored in ZK, or for tables that had already been deleted, and so the properties would never come into being.

So, caching non-existence seems risky... prone to the same sort of memory leak, where the ZK client memory keeps growing and growing due to an unbounded number of watches on nodes that don't exist and may never exist.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:299]: That is a good point.  Makes me wonder about the existing functionality of  caching non-existence when get node data.

The use case I was trying to solve was looking up tablet server locks.  For this use case if we have AC="num accumuo clients reading from tservers", TRG="number of tablet severs resource groups", ATPC="average number of tservers accessed per accumulo client" then the number of watches for non-existence created would be AC*ATPC*(TRG-1).  If any two of those three numbers are large then it could result in a lot of watches.

I made #5134 a blocker for 4.0.0.  Thinking prior to releasing 4.0 it would be good to get a handle on what the watches look like.

Looking into what zookeper might offer I discovered [WatchManager](https://zookeeper.apache.org/doc/current/apidocs/zookeeper-server/org/apache/zookeeper/server/watch/WatchManager.html) which is new to me.  Going to look into this a bit and see if there anything that can be done with it in zoocache to avoid excessive watches.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:318]: In ee80c70 updated to remove entries in zoocache that have not been accessed in 3 minutes.  This also removes their watches. I think this covers a lot of the issues of creating watches that hang around forever.  Looking into this I think the following follow on work could be done to improve the watch situation.

 * When something is removed from zoocache also remove the watch.  Currently when something is removed from zoocache explicitly its watch is just left there. 
 * Only set a watch on things that are accesses more than once. I suspect there are things in zoocache that are only accessed once and a watch is set.   These expire changes will help with this.  We could reduce watches further in a follow on by only setting them on the 2nd access.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:318]: Also found WatchManager is not public API for ZK.  Fortunately a subset of its functionality is available in the public API.

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java [hunk 3]
```diff
@@ -207,8 +172,23 @@ public void process(WatchedEvent event) {
...
+      } catch (InterruptedException | KeeperException | RuntimeException e) {
+        log.warn("Failed to remove watches on path {} in zookeeper", path, e);
+      }
+    };
+    // Must register the removal listener using evictionListener inorder for removal to be mutually
+    // exclusive with any other operations on the same path. This is important for watcher
+    // consistency, concurrently adding and
+    // removing watches for the same path would leave zoocache in a really bad state. The cache
+    // builder has another way to register a removal listener that is not mutually exclusive.
+    Cache<String,ZcNode> cache = Caffeine.newBuilder().expireAfterAccess(3, TimeUnit.MINUTES)
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:189]: There is a `Caches` class that we are using to provide a common way to create Caffeine caches.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java]: Updated to use that in 5c65c4f

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java (hunk 2 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:326]: I'm not sure when the removeWatches functionality was added, but I believe it was relatively recent. It might be newer than the oldest ZK we support, and we might need to document that we require a newer version... I'm not sure.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:326]: Zookeeper.removeWatches has a since 3.5.0 tag in its javadoc.

Comment (ddanielr) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java:326]: I was able to build this branch using zookeeper 3.7.1 and `Zookeeper.removeWatches` was present. 

The [release notes for 2.1.0](https://accumulo.apache.org/release/accumulo-2.1.0/)  mention 3.8.0 so this change should be fine. 
```
During much of this release’s development, ZooKeeper 3.5 was used as a minimum. However, that version reach its end-of-life during development, and we do not recommend using end-of-life versions of ZooKeeper. The latest bugfix version of 3.6, 3.7, or 3.8 should also work fine. By default, our POM depends on 3.8.0.
```

**Review by ddanielr — APPROVED** [review]
