### PR TITLE
Fix flaky AuthenticationTokenSecretManagerTest

### LINKED ISSUE #3075: Broken or Flaky test: AuthenticationTokenSecretManagerTest
**Test name(s)**
 - AuthenticationTokenSecretManagerTest.testVerifyPassword

**Describe the failure observed**

There seems to be some small probability that the AuthenticationTokenSecretManager will generate the same random password. I've seen the following error a few times, but it's hard to reproduce. Since it's calling into Hadoop code to generate things, this could depend on specific Hadoop versions.

```
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.485 s <<< FAILURE! - in org.apache.accumulo.server.security.delegation.AuthenticationTokenSecretManagerTest
[ERROR] org.apache.accumulo.server.security.delegation.AuthenticationTokenSecretManagerTest.testVerifyPassword  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Different tokens for the same user shouldn't have the same password ==> expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:236)
	at org.apache.accumulo.server.security.delegation.AuthenticationTokenSecretManagerTest.testVerifyPassword(AuthenticationTokenSecretManagerTest.java:222)

```

**Additional context**

If I remember correctly, this code is part of the delegation token management stuff that is used with Kerberos-enabled clusters so that MapReduce and other similar tasks don't need a keytab for each individual job task. Most recently, I saw this on 3.0.0-SNAPSHOT in the main branch, but I've previously seen it in development on earlier branches as well.

### PR DESCRIPTION
**Pull request by cshannon**
Part of the ID of the generated token is the issue date which is the current time in millis so this adds a 1 millisecond sleep in between token generation to guarantee the tokens will be unique.

This fixes #3075

### CODE REVIEW

**Comment by cshannon** [comment]
@ctubbsii - not sure what's up but the recent checks are failing due to "shellcheck" having an issue. It looks like the last 3 commits have had the same problem starting with the Apache parent pom version 28 update so not sure if it's related to the root pom change or a coincidence.

**Review by EdColeman — APPROVED** [review]
LGTM - it would be nice if the mentioned spell check and other checks pass before merging, but seems unlikely caused directly but this minor change.

File: server/base/src/test/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManagerTest.java [hunk 1]
```diff
@@ -208,6 +208,8 @@ public void testVerifyPassword() throws Exception {
     assertArrayEquals(password, secretManager.retrievePassword(id));
 
     // Make a second token for the same user
+    // Sleep for 1 millisecond to guarantee token is unique
+    Thread.sleep(100);
```
Comment (ctubbsii) [inline server/base/src/test/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManagerTest.java:212]: The comment doesn't match. This is sleeping for 100 milliseconds, right? Other than that mismatch, this seems fine.

```suggestion
    // Briefly sleep to guarantee token is unique, since the token is based on the time
    Thread.sleep(100);
```

**Comment by ctubbsii** [comment]
> @ctubbsii - not sure what's up but the recent checks are failing due to "shellcheck" having an issue. It looks like the last 3 commits have had the same problem starting with the Apache parent pom version 28 update so not sure if it's related to the root pom change or a coincidence.

@cshannon The changes where this was first observed did not change anything even remotely related to the scripts that would have triggered shellcheck. It looks like the version of shellcheck installed on the builder is newer than the version that we've previously seen, and the newer version is detecting a new issue, https://www.shellcheck.net/wiki/SC2294

This is easily fixed. Please disregard for now, since you're not changing any scripts.

File: server/base/src/test/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManagerTest.java (hunk 1 above)
Comment (cshannon) [reply server/base/src/test/java/org/apache/accumulo/server/security/delegation/AuthenticationTokenSecretManagerTest.java:212]: Yeah I updated the time from 1 to 100 in my second commit but didn't update the comment so good catch.
