### PR TITLE
Better handling for ignored interrupted exceptions

### LINKED ISSUE #5203: Log interrupted exceptions in TabletSeverLogger
The following code catches and ignores interrupted exceptions assuming shutdown is happening.  This assumption may not be correct.   Should at least log the exception.

https://github.com/apache/accumulo/blob/7b746cd08fc18ea3e75ea5f5180c1a6661367db5/server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java#L350

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #5203

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java [hunk 1]
```diff
@@ -137,7 +137,8 @@ public void lock() {
             return;
           }
         } catch (InterruptedException ex) {
-          // ignored
+          Thread.currentThread().interrupt();
+          log.warn("Interrupted while waiting to acquire " + getClass().getSimpleName());
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java:141]: If this were seen in the logs, I think it'd be very hard to troubleshoot, unless the user know they were the ones who interrupted it (with Ctrl-C or something). It's probably best to preserve the stack trace:

```suggestion
          log.warn("Interrupted while waiting to acquire lock", ex);
```

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java [hunk 2]
```diff
@@ -494,22 +494,29 @@ private static void flushAll(final ClientContext context) {
     try {
       flusher.join(3000);
     } catch (InterruptedException e) {
-      // ignore
+      log.warn("Interrupted while waiting to join Flush thread");
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:497]: I don't see much reason to suppress the interrupt flag here, so we should restore it in case there's something monitoring it. This is the recommended best practice if we're not re-throwing it.

```suggestion
      Thread.currentThread().interrupt();
      log.warn("Interrupted while waiting to join Flush thread", e);
```

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java [hunk 3]
```diff
@@ -494,22 +494,29 @@ private static void flushAll(final ClientContext context) {
...
     }
 
     while (flusher.isAlive() && System.currentTimeMillis() - start < 15000) {
       int flushCount = flushesStarted.get();
       try {
         flusher.join(1000);
       } catch (InterruptedException e) {
-        // ignore
+        log.warn("Interrupted while waiting to join Flush thread");
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:505]:
```suggestion
        Thread.currentThread.interrupt();
        log.warn("Interrupted while waiting to join Flush thread", e);
```

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java [hunk 4]
```diff
@@ -494,22 +494,29 @@ private static void flushAll(final ClientContext context) {
     try {
       flusher.join(3000);
     } catch (InterruptedException e) {
-      // ignore
+      log.warn("Interrupted while waiting to join Flush thread");
     }
 
     while (flusher.isAlive() && System.currentTimeMillis() - start < 15000) {
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:500]: Not part of this issue and not critical, but I hope we've fixed this in newer versions to use nanos.

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java [hunk 5]
```diff
@@ -494,22 +494,29 @@ private static void flushAll(final ClientContext context) {
...
         // no progress was made while waiting for join... maybe its stuck, stop waiting on it
         break;
       }
     }
+
+    flusher.interrupt();
+    try {
+      flusher.join();
+    } catch (InterruptedException e) {
+      log.warn("Interrupted while waiting to join Flush thread");
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:518]: I think it's a good idea to interrupt the flusher thread, if we're not going to wait on it anymore, but I still think the current thread needs to reset the interrupt flag on itself, when it is interrupted waiting for the join.

```suggestion
    flusher.interrupt();
    try {
      flusher.join();
    } catch (InterruptedException e) {
      Thread.currentThread.interrupt();
      log.warn("Interrupted while waiting to join Flush thread", e);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java [hunk 6]
```diff
@@ -285,6 +285,8 @@ public void run() {
               try {
                 alog.close();
               } catch (Exception e) {
+                // Throw an Error, not an Exception, so the AccumuloUncaughtExceptionHandler
+                // will log this then halt the VM.
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:289]: It looks like this comment was pasted into the wrong place. This is where the error is logged. The throw is further down, and is missing this comment.

But, I am wondering if InterruptedException is one of the checked exceptions possible from this overly broad catch clause. We really shouldn't have overly broad catch clauses this way. It's much better to do multi-catch to enumerate the exceptions we want to handle here. RTEs can be included, if the catch is intended to handle them as well.

For example:

```java
  } catch (IOException | InterruptedException | RuntimeException e) {
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java [hunk 7]
```diff
@@ -348,7 +352,9 @@ public void run() {
               log.info("Our WAL was not used for 12 hours: {}", fileName);
             }
           } catch (InterruptedException e) {
-            // ignore - server is shutting down
+            // Throw an Error, not an Exception, so the AccumuloUncaughtExceptionHandler
+            // will log this then halt the VM.
+            throw new Error("Next log maker thread interrupted", e);
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:357]: I'm not sure about this. It seems like it might be a bad idea to use Error for program flow this way. Maybe we should be propagating up the InterruptedException in these cases, and handling it at a higher level to halt? It seems risky to rely on the UEH to deal with this on the assumption that it's going to handle it properly. If there's no other immediate options, I think this is okay... but might be worth keeping a ticket open to pursue a better approach.

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java (hunk 2 above)
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:497]: Yeah, I didn't include it because it's likely called from the CLI. I can add it though.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 6 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:289]: Yes, copy/paste error. I will fix. I'll look at the close method and see if IntExc is possible.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 7 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:357]: This is in a background thread. I don't think there is a way to propagate this up.

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java (hunk 2 above)
Comment (ctubbsii) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java]: It could be called by a script, too. Even if it's called by a user from the CLI, I don't think it's that bad to show them the mess they caused when they hit Ctrl-C :smiley_cat:

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 7 above)
Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:357]: > This is in a background thread. I don't think there is a way to propagate this up.

That's fine if this is the best option today. I haven't spent much time thinking about alternatives, just thinking it'd be useful to have a follow on ticket to try to avoid "new Error" in the code. For this one, I was thinking about what the thread pool executor service would see if the thread was interrupted... that maybe it could be watched like the flusher thread.

I found [this answer](https://stackoverflow.com/a/10038019/196405) about how it should be handled inside a thread pool. The answer seems to assume the thread could only be interrupted by the thread pool, so it's fine to just reset the interrupt flag with Thread.currentThread.interrupt(). I'm not sure if that's always a valid assumption, , but it does seem like it would be difficult for something outside the thread to interrupt it without going through the thread pool.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java [hunk 8]
```diff
@@ -284,7 +284,7 @@ public void run() {
             if (alog != null) {
               try {
                 alog.close();
-              } catch (Exception e) {
+              } catch (IOException e) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:287]: This is a change in behavior, but I'm not sure if it's an important one. Avoiding changing the behavior would look like:

```suggestion
              } catch (IOException | RuntimeException e) {
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java [hunk 9]
```diff
@@ -293,15 +293,17 @@ public void run() {
                 if (fs.exists(path)) {
                   fs.delete(path);
                 }
-              } catch (Exception e) {
+              } catch (IOException e) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:296]: same comment about change in behavior

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java [hunk 10]
```diff
@@ -319,7 +321,7 @@ public void run() {
               // Intentionally not deleting walog because it may have been advertised in ZK. See
               // #949
               alog.close();
-            } catch (Exception e) {
+            } catch (IOException e) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java:324]: same comment about change in behavior

**Review by ctubbsii — APPROVED** [review]
If the change in behavior to ignore RTEs in those places where IOException is being caught is acceptable, then this looks fine to me.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 8 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java]: reverted this change

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 9 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java]: reverted this change

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 10 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java]: reverted this change

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java (hunk 8 above)
Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java]: I think it's still helpful to narrow the exception, but it can be done without changing behavior using multi-catch with `| RuntimeException`
