### PR TITLE
Fix #1314 fixes gc thread issue by creating one timed task instance

### LINKED ISSUE #1314: Garbage Collector problematic use of SimpleTimer
SimpleGarbageCollector creates a new instance of GarbageCollectWriteAheadLogs on each loop. Each construction of GCWAL creates a new LiveTServerSet, which registers a SimpleTimer task to scan for changes in the set of live TServers. This task executes indefinitely, and is never de-registered. Multiple copies of LiveTServerSet are created over time, each registering a new SimpleTimer task that executes indefinitely.

There are several problems here:

1. The tasks are redundant, and never de-registered. So, in GC's main loop, a new SimpleTimer task is created each time... growing indefinitely. We should only need one at any given time.
2. Because of the changes in 1be829848ffc195dbc8c3fa42a4f354d2678645e (#781), the GCWAL's overridden `update` method is called frequently, even when there are no changes in the live TServer set. This results in excessive spam of: "New tablet servers noticed: []" and "Tablet servers removed: []" log messages.

The first problem has been around longer (and might affect other uses of SimpleTimer... we should check), but the second problem was introduced in 1.9.3. Together, this results in an increasing number of timer tasks, each constantly logging to report no changes, easily filling up logs with useless information over time.

Workaround: restart the GC.

### PR DESCRIPTION
**Pull request by EdColeman**
This fix moved the creation of the live tserver set to the simple garbage collector, outside of the run loop and passes it to the wal collector.

modified log message by putting guard to only print on changes and to include number of tservers.

### CODE REVIEW

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 1]
```diff
@@ -163,6 +155,7 @@ public void collect(GCStatus status) {
       span.stop();
 
       // now it's safe to get the liveServers
+      liveServers.scanServers();
```
Comment (ctubbsii) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: Don't need this anymore.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java [hunk 2]
```diff
@@ -90,20 +89,13 @@
...
-    this.liveServers = new LiveTServerSet(context, new Listener() {
-      @Override
-      public void update(LiveTServerSet current, Set<TServerInstance> deleted,
-          Set<TServerInstance> added) {
-        log.debug("New tablet servers noticed: " + added);
-        log.debug("Tablet servers removed: " + deleted);
-      }
-    });
-    liveServers.startListeningForTabletServerChanges();
+    this.liveServers = liveServers;
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: Could call `liveServers.scanServers()` here making it more functionally equivalent to the old code.  The old code used to call `liveServers.startListeningForTabletServerChanges()` which internally called `scanServers()` and registered a timer to call `scanServers()`.  I don't think registering the timer is needed.

File: server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java [hunk 3]
```diff
@@ -564,6 +566,19 @@ private void run() {
...
+      @Override
+      public void update(LiveTServerSet current, Set<TServerInstance> deleted,
+          Set<TServerInstance> added) {
+        if (!deleted.isEmpty() || !added.isEmpty()) {
+          log.debug("Number of current servers {}, tservers added {}, removed {}",
+              current == null ? -1 : current.size(), added, deleted);
+        }
+      }
+    });
+
```
Comment (keith-turner) [inline server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java]: Why not call here `liveServers.startListeningForTabletServerChanges()` here?  I don't think its needed if my other suggestion to call `scanServers` is made.  However I am curious if there was  reason for not calling it.

Comment (ctubbsii) [reply server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java]: I discussed this solution with @EdColeman yesterday. I think the intent was to call `liveServers.startListeningForTabletServerChanges()` here. I had thought it was present when I approved the PR, but now I can't find it in the commits.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 2 above)
Comment (ctubbsii) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: One benefit for the timer is that it keeps the tserver set up-to-date so we don't have to wait to scan them in the GC loop. I'm not sure that's a big deal, though. Another is that it lets us know about the changes in the logs.

However, using `scanServers()` directly here would still let us know about changes in the logs... so long as the LiveTServersSet object is kept as a singleton in the SimpleGarbageCollector. The problem with the first "option 2" mentioned in #1314 that used `scanServers()` directly is that a new LiveTServersSet was being created over and over again, so the logs would have always shown an "updated" list of tservers being the entire set of current tservers, before being reset... not very useful. But the `scanServers()` option should work fine now that the LiveTServersSet object is being passed in and reused.

File: server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java (hunk 3 above)
Comment (keith-turner) [reply server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java]: ok, I think I like calling `scanServers()` explicitly anyway because it seems easier to reason about when things happen during the GC cycle.  Otherwise there is some timer that runs concurrently at random points during the cycle.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 2 above)
Comment (keith-turner) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: I think its best to separate the issue of logging tserver information and reasoning about GC correctness.  The timer seems to add unnecessary concurrency, that while it seems correct does make reasoning about the GC algorithm more complex.

Comment (keith-turner) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: The existing code was always calling `scanServers()` because `startListeningForTabletServerChanges()` always called it.

File: server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java (hunk 3 above)
Comment (ctubbsii) [reply server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java]: I agree.

File: server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java (hunk 2 above)
Comment (ctubbsii) [reply server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java]: The choice is to decide whether `startListeningForTabletServerChanges()` in a single background task every 5 seconds is better, or calling `scanServers()` immediately before using the set is better. I don't know that one is significantly easier to reason about than the other. In both scenarios we are getting a relatively recent view of the current live tservers. But, I do like avoiding the background task if we don't actually need it. SimpleTimer is dubious.

File: server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java (hunk 3 above)
Comment (EdColeman) [reply server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java]: I'll put the call to scanServers - that's seems better than a random timer task update.  I'll keep the external tserver list that get passed to the wal collector so that it does update between gc runs as desired.

I'm also seeing what I can do about adding or modify the tests - the current tests pass in a mock instance and it they don't seem to exercise a path when the set changes.

File: server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java [hunk 4]
```diff
@@ -564,6 +566,19 @@ private void run() {
     ProbabilitySampler sampler =
         new ProbabilitySampler(getConfiguration().getFraction(Property.GC_TRACE_PERCENT));
 
+    // This is created outside of the run loop and passed to the walogCollector so that
+    // only a single timed task is created (internal to LiveTServerSet using SimpleTimer.
+    final LiveTServerSet liveTServerSet = new LiveTServerSet(this, new LiveTServerSet.Listener() {
+      @Override
+      public void update(LiveTServerSet current, Set<TServerInstance> deleted,
+          Set<TServerInstance> added) {
+        if (!deleted.isEmpty() || !added.isEmpty()) {
```
Comment (ctubbsii) [inline server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java]: Since it's not scanning every 5 seconds any more, could remove this check and have it show current status every accumulo-gc cycle instead, if that met your logging expectations better.

File: server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java [hunk 5]
```diff
@@ -250,7 +265,10 @@ public void replicationDelaysFileCollection() throws Exception {
 
     GCStatus status = new GCStatus(null, null, null, new GcCycleStats());
 
+    tserverSet.scanServers();
+    EasyMock.expectLastCall();
```
Comment (ctubbsii) [inline server/gc/src/test/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogsTest.java]: That's a really nice (and simple) improvement to the test to make sure we call scanServers to ensure it is updated before we expect the call to getCurrentServers.
