### PR TITLE
Fix #2070 address ShellServerIT test failures

### LINKED ISSUE #2070: Broken or Flaky test: ShellServerIT
**ShellServerIT**

**Describe the failure observed**
ShellServerIT is failing with two errors consistently.

ShellServerIT.testPertableClasspath times out.
<details>
  <summary>Click to expand!</summary>
  `ERROR] org.apache.accumulo.test.ShellServerIT.testPertableClasspath  Time elapsed: 60.007 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at java.base@11.0.11/java.lang.Object.wait(Native Method)
	at java.base@11.0.11/java.lang.Object.wait(Object.java:328)
	at app//org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.waitRTE(TabletServerBatchWriter.java:470)
	at app//org.apache.accumulo.core.clientImpl.TabletServerBatchWriter.close(TabletServerBatchWriter.java:340)
	at app//org.apache.accumulo.core.clientImpl.BatchWriterImpl.close(BatchWriterImpl.java:57)
	at app//org.apache.accumulo.shell.commands.InsertCommand.execute(InsertCommand.java:112)
	at app//org.apache.accumulo.shell.Shell.execCommand(Shell.java:779)
	at app//org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:219)
	at app//org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:229)
	at app//org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:224)
	at app//org.apache.accumulo.test.ShellServerIT.testPertableClasspath(ShellServerIT.java:1752)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.11/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
`
</details>

ShellServerIT.durability - java.lang.AssertionError: expected:<0> but was:<1>
<details>
  <summary>Click to expand!</summary>
  `[ERROR] org.apache.accumulo.test.ShellServerIT.durability  Time elapsed: 1.639 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.apache.accumulo.test.ShellServerIT$TestShell.assertGoodExit(ShellServerIT.java:269)
	at org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:255)
	at org.apache.accumulo.test.ShellServerIT$TestShell.exec(ShellServerIT.java:248)
	at org.apache.accumulo.test.ShellServerIT.durability(ShellServerIT.java:585)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
`
**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit):
 - OS: ubuntu
 - Java: openjdk version "11.0.11" 
 - Maven: Apache Maven 3.6.3
 - Other environment details:

**What have you tried already?**
A clear and concise description of any steps you've already taken in an attempt to troubleshoot.

**Additional context**
Add any other context about the problem or your testing environment here.

### PR DESCRIPTION
**Pull request by EdColeman**
- replaces https://github.com/apache/accumulo/pull/2073

- address simple check-style errors
- use unique table and namespace names
- Add test for constraints jar built with 2_1
- Address pr comments
  - removed auto-format changes
  - moved assignment to eliminate possible null warnings

### CODE REVIEW

**Review by milleruntime — APPROVED** [review]
Looks good. After @Manno15 takes a look at the `history` test, you can remove the TODOs and this can be merged.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 1]
```diff
@@ -1421,21 +1431,24 @@ public void help() throws Exception {
...
 
+  // TODO - evaluate this test is testing what is expected or history is working.
   @Test
   public void history() throws Exception {
     final String table = name.getMethodName();
 
     ts.exec("history -c", true);
     ts.exec("createtable " + table);
     ts.exec("deletetable -f " + table);
+    // TODO - this may be passing only because method name is history.
```
Comment (Manno15) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1442]: There does appear to be an issue with the history test. Changing the name of the table does result in a test failure. I am not quite sure if it has to do with the history command itself or with the way we search for the expectedString.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 2]
```diff
@@ -1421,21 +1431,24 @@ public void help() throws Exception {
...
     ts.exec("history", true, table, true);
+    // TODO - what is this testing?
```
Comment (Manno15) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1444]: This is ideally testing to see if the history command ran previously shows up in this history check. Which it does in the shell. Unsure if this is working correctly due to the issue mentioned above.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 1 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1442]: This issue seems to occur in 1.10 as well. Interestingly, the @test annotation for this test was commented out in the 2.0.0 and 2.0.1 release and was uncommented in #1483.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 2 above)
Comment (EdColeman) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1444]: What I was marking - testing for a table named "history" and a string "history" seems either redundant - or was trying to test something else.  It could be that the string test was to see that history was returned as part of the command and when something else besides history is the table name then it makes more sense.

Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1444]: I believe it was just to test that 'history' showed up in the history. I do agree that it didn't make sense since the table was also called 'history'.
