### PR TITLE
Disallows table props in site config

### LINKED ISSUE #5854: Fail to start server process if table properties in accumulo.properties
In #5781 we made it such that table properties can
only be set in the namespace and table configuration.
Look at modifying AbstractServer such that the server
processes fail to start if there are table properties
in the accumulo.properties file.

### PR DESCRIPTION
**Pull request by keith-turner**
fixes #5854

### CODE REVIEW

**Comment by dlmarion** [comment]
Do you think `UpgradeUtil.start` will fail if there are table properties in the site configuration at that time? If not, do you think we should check that there?

Edit: With these changes, the server processes will likely fail to start, so the upgrade process won't even begin in the Manager. Wondering if we should warn users in the `start` step that they need to remove the table properties.

**Comment by keith-turner** [comment]
> Wondering if we should warn users in the start step that they need to remove the table properties.

The upgrade start code should fail [here](https://github.com/apache/accumulo/blob/496b8a26130da425010eff7ebac67e478e3b7626/server/base/src/main/java/org/apache/accumulo/server/util/UpgradeUtil.java#L316) with an exception w/ these changes.  I can test that.   Yesterday I manually tested starting all of the accumulo server processes w/ a tablet prop in the site confg and all failed to start.  Also we have #5855 open, we may be able to close that if an exception is ok.

**Comment by ctubbsii** [comment]
> Also we have #5855 open, we may be able to close that if an exception is ok.

I think that one needs to be open for 2.1 pre-upgrade to 4.0.

**Comment by keith-turner** [comment]
Tried running upgrade start w/ these changes and saw the following.

```
$ accumulo upgrade --start
Thread 'upgrade' died.
java.lang.IllegalArgumentException: Site configuration can not contain table properties, saw : table.durability
	at org.apache.accumulo.core.conf.SiteConfiguration.lambda$new$0(SiteConfiguration.java:209)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1554)
	at org.apache.accumulo.core.conf.SiteConfiguration.<init>(SiteConfiguration.java:207)
	at org.apache.accumulo.core.conf.SiteConfiguration$Builder.build(SiteConfiguration.java:171)
	at org.apache.accumulo.core.conf.SiteConfiguration.auto(SiteConfiguration.java:200)
	at org.apache.accumulo.server.util.UpgradeUtil.execute(UpgradeUtil.java:316)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:81)
	at java.base/java.lang.Thread.run(Thread.java:840)
$ echo $?
1
```

**Comment by dlmarion** [comment]
> > Also we have #5855 open, we may be able to close that if an exception is ok.
> 
> I think that one needs to be open for 2.1 pre-upgrade to 4.0.

I commented on #5855, but I think the check should happen in the `start` command, not the `prepare` command. The `prepare` command is used on an older version and the user has the option to abort the upgrade even after running `prepare`. It doesn't necessarily make sense for the user to have to modify their property files for the older version at this phase.

**Comment by ctubbsii** [comment]
> > > Also we have #5855 open, we may be able to close that if an exception is ok.
> > 
> > 
> > I think that one needs to be open for 2.1 pre-upgrade to 4.0.
> 
> I commented on #5855, but I think the check should happen in the `start` command, not the `prepare` command. The `prepare` command is used on an older version and the user has the option to abort the upgrade even after running `prepare`. It doesn't necessarily make sense for the user to have to modify their property files for the older version at this phase.

At the very least, a strong warning would make sense for the prepare stage, because it might be hard to run a tool in the newer version to move the configs to the namespace, if the ZK layout has changed in 4.0, and you haven't run the upgrade yet, but still want the properties to be in effect on startup of 4.0. In such a case, the 4.0 tooling to edit the config to put the props in a namespace (like ZooPropEditor) may not understand the 2.1 paths, and waiting until after the system is started and upgraded is too late for some table properties that you want to have set before you make it hosted (encryption, volume chooser, balancer, etc.). Such a tool could be run after the upgrade start stage, before Accumulo is running, if the start stage finished all the ZK upgrade steps.

**Comment by keith-turner** [comment]
> and waiting until after the system is started and upgraded is too late for some table properties that you want to have set before you make it hosted

Making sure the migration from file to ZK can be done prior to hosting does seem super important. In the following comment was trying to work through how all of this could be resolved in 2.1 prior to upgrade. 

https://github.com/apache/accumulo/pull/5888#discussion_r2356280281

**Comment by keith-turner** [comment]
> Such a tool could be run after the upgrade start stage, before Accumulo is running, if the start stage finished all the ZK upgrade steps.

This could be tricky.  After upgrade start, not all of ZK data may be upgraded.  Running a tool that direclty edits ZK at this point in time could cause problems.  Those tools are written w/ the assumption that data in ZK follows the current schema that would exists after init or manager upgrade completes.

**Comment by dlmarion** [comment]
I think @ctubbsii suggested a while back that some of the ZooKeeper upgrade validation / modifications could be performed in `upgrade --start`. There are already two items being performed (see [here](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/util/UpgradeUtil.java#L270-L283)).

With the current changes `upgrade --start` will fail if there are table properties in the site config. The failure happens early in the process. I wonder if the validation of the site configuration should be bypassed initially, allowing `start` to set the table properties in the system configuration in ZooKeeper. After that, could fail and tell the user to remove them from the file and try again. The 4.0 upgrader already moves the system properties to the namespace level [here](https://github.com/apache/accumulo/blob/main/server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java#L920). 

Edit: I just saw your comment at https://github.com/apache/accumulo/issues/5855#issuecomment-3303926695 after writing this. My suggestion here doesn't consider different files across the cluster.

**Comment by ctubbsii** [comment]
> The 4.0 upgrader already moves the system properties to the namespace level [here](https://github.com/apache/accumulo/blob/main/server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader11to12.java#L920).

Maybe it's okay to just produce an error. If a user wants them to be added to the namespaces automatically during the upgrade, they should set them in the system properties, rather than in the site config file. That also prevents any weirdness associated with different site files.

**Comment by ctubbsii** [comment]
We could also just add a regular startup warning about these properties for 2.1.5 (and 3.1.0 later) for SiteConfiguration, and `upgrade --prepare` and `upgrade --start` could both just produce an error. So, users still get a warning... but when they are ready to do any upgrading, it's a hard error.

**Comment by dlmarion** [comment]
> If a user wants them to be added to the namespaces automatically during the upgrade, they should set them in the system properties

The error would tell the user to set the system properties using ZooPropEditor of the old version of software, or the 4.0 version?

**Comment by ctubbsii** [comment]
> > If a user wants them to be added to the namespaces automatically during the upgrade, they should set them in the system properties
> 
> The error would tell the user to set the system properties using ZooPropEditor of the old version of software, or the 4.0 version?

So, I think there's 3 scenarios we need to warn or error:

1. 2.1.5 process startup (non-upgrade) -> should emit a WARNING instructing users that those properties will be disallowed in SiteConfiguration in the future, and recommend they add the desired config to the namespace or tables they want it to apply to (user has multiple choices about how to do that, so we don't need to provide very detailed instructions on which tool to use... because it's up to the user to decide namespaces vs. tables, ZooPropEditor vs. accumulo-shell vs. tableOperations() API, etc.
2. 2.1.5 `upgrade --prepare` -> should fail hard; the users have limited options at this point if they don't want to restart 2.1.5 to use the shell or the public API... so the best option is to put the config in the system config in ZK, and let the upgrade code in 4.0 migrate it to each namespace. they can use the 2.1.5 ZooPropEditor to add the configs to the system config, or they can use it to add it directly to the specific namespaces or tables they want to apply it to.
3. 4.0.0 `upgrade --start` -> should fail hard; at this point, the user doesn't have many options... they can't use ZooPropEditor at this point, because ZK hasn't been upgraded yet; they will have to remove the properties from the config file, complete the upgrade, and then add them to the namespaces or tables they want them to be applied to; *if* we are able to get all the upgrade code in a state so that the ZK layout can be completely upgraded after `upgrade --start` finishes, but *before* they start the cluster, they *could* use the 4.0.0 ZooPropEditor at that time, to add things to namespaces/tables before they are hosted... but that depends on what state the upgrade code is in when we release.

The best option is for users to pay attention to the warning in scenario 1 above, the next best option is to use ZooPropEditor when they see an error in scenario 2 above. the worst option is waiting until after 4.0.0 is installed. But they shouldn't ever get to scenario 3, because they should have fixed it after the 2.1.5 `upgrade --prepare` caused an error.

**Comment by keith-turner** [comment]
> So, I think there's 3 scenarios we need to warn or error:

Those three SGTM.  i updated #5888 for 1 and 2.

**Comment by keith-turner** [comment]
> 4.0.0 upgrade --start -> should fail hard; at this point, the user doesn't have many options... they can't use ZooPropEditor at this point

At that point, the zoo prop editor from the 2.1 code may still work.  But that is dicey.

**Comment by keith-turner** [comment]
@ctubbsii  your comments on this issue are about the end to end upgrade processes from 2.1 to 4.0.  I don't think you have any outstanding comments for this PR.  Let me know if I missed anything.  I think this is ready to merge.

File: core/src/test/resources/accumulo3.properties
Comment (ctubbsii) [inline core/src/test/resources/accumulo3.properties:1]: I would give this file a more descriptive name, like `accumulo-props-with-table.properties`; could also add some comments to the file to explain what it should contain

File: core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java [hunk 1]
```diff
@@ -204,6 +204,12 @@ public static SiteConfiguration auto() {
 
   private SiteConfiguration(Map<String,String> config) {
     ConfigCheckUtil.validate(config.entrySet(), "site config");
+    config.forEach((prop, value) -> {
+      if (prop.startsWith(Property.TABLE_PREFIX.getKey())) {
+        throw new IllegalArgumentException(
+            "Site configuration can not contain table properties, saw : " + prop);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java]:
```suggestion
            "Site configuration must not contain table properties, saw : " + prop);
```

File: core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java [hunk 2]
```diff
@@ -791,7 +791,7 @@ public void testMaxTabletFilesNoCompaction() {
     var overrides2 = new HashMap<>(overrides);
     overrides2.put(Property.COMPACTION_SERVICE_PREFIX.getKey() + "cs1.planner.opts.lowestRatio",
         "1.04");
-    var conf2 = new ConfigurationImpl(SiteConfiguration.empty().withOverrides(overrides2).build());
+    var conf2 = new ConfigurationImpl(new ConfigurationCopy(overrides2));
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java]: I think this part should be reverted. Whereas ConfigurationCopy is being repurposed from being a cache of config properties to being a test copy of a real AccumuloConfiguration instance, SiteConfiguration is explicitly a real AccumuloConfiguration, with DefaultConfiguration as its parent. So, they have different behavior.

I think we should generally avoid ConfigurationCopy unless we're really using it as a temporary copy, like a cached snapshot, or if we really need fine-grained control over its contents for testing the configuration code itself. If we just want to emulate a realistic AccumuloConfiguration with some specific values set by the user, to test some component of Accumulo, using SiteConfiguration is better I think, because it's more realistic to to the behavior of a real configuration object.

File: src/build/ci/check-module-package-conventions.sh [hunk 3]
```diff
@@ -59,6 +59,7 @@ ALLOWED=(
   core/src/test/resources/empty.jceks
   core/src/test/resources/site-cfg.jceks
   core/src/test/resources/accumulo2.properties
+  core/src/test/resources/accumulo3.properties
```
Comment (ctubbsii) [inline src/build/ci/check-module-package-conventions.sh]: This shouldn't be added to this directory, and shouldn't require a new exception added to the existing TODO section of the file. Instead, it should be in:
```
core/src/test/resources/org/apache/accumulo/core/
```

somewhere, preferably named after the test case, so maybe:

```
core/src/test/resources/org/apache/accumulo/core/conf/SiteConfigurationTest-testTableProps.properties
```

File: core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java [hunk 4]
```diff
@@ -93,4 +94,16 @@ public void testConfigOverrides() {
...
   }
+
+  @Test
+  public void testTableProps() {
+    // try setting a table prop as an override
+    assertThrows(IllegalArgumentException.class, () -> SiteConfiguration.empty()
+        .withOverrides(Map.of(Property.TABLE_MAJC_RATIO.getKey(), "5")).build());
+
+    // try loading a properties file that has a a table prop
+    URL propsUrl = getClass().getClassLoader().getResource("accumulo3.properties");
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/conf/SiteConfigurationTest.java]: With the file move/rename I suggested in the other comment, this becomes:

```suggestion
    URL propsUrl = getClass().getResource("SiteConfigurationTest-testTableProps.properties");
```

This could be further made dynamic using `getClass().getSimpleName()` or the JUnit's features to get the test name (several tests extend `WithTestNames`, which is a convenience class to make it easier to get the test name with less boilerplate.

At the very least, putting it in the same path as the class, regardless of the filename part, makes the getResource() much simpler, and you don't need to add another exception to the check script's TODO section.

File: core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java [hunk 5]
```diff
@@ -204,6 +204,12 @@ public static SiteConfiguration auto() {
 
   private SiteConfiguration(Map<String,String> config) {
     ConfigCheckUtil.validate(config.entrySet(), "site config");
+    config.forEach((prop, value) -> {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java]: You could also use a stream collector to collect all of the violations to include in a single exception, so users don't need to fix one, see another error, fix another, etc.

File: core/src/test/resources/accumulo2.properties [hunk 6]
```diff
@@ -21,7 +21,6 @@ general.rpc.timeout=123s
 instance.secret=mysecret
 instance.volumes=hdfs://localhost:8020/accumulo123
 instance.zookeeper.host=myhost123:2181
-table.durability=flush
```
Comment (ctubbsii) [inline core/src/test/resources/accumulo2.properties:24]: This looks safe. I don't think any test code was relying on this being `flush` instead of the default, `sync`.

**Review by ctubbsii — CHANGES_REQUESTED** [review]

File: core/src/test/resources/accumulo2.properties (hunk 6 above)
Comment (keith-turner) [reply core/src/test/resources/accumulo2.properties:24]: I moved this out because some test code would attempt create a SiteConfig obj and that now fails.  I examined all the test code using this and none explicitly depended on this prop AFACIT.

File: core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java (hunk 2 above)
Comment (keith-turner) [reply core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java]: I made this change because the test has a table prop in `overrides2` and that now fails when using site config.

File: src/build/ci/check-module-package-conventions.sh (hunk 3 above)
Comment (keith-turner) [reply src/build/ci/check-module-package-conventions.sh]: updated in 81994fb

File: core/src/test/resources/accumulo3.properties
Comment (keith-turner) [reply core/src/test/resources/accumulo3.properties:1]: updated in 81994fb

File: core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java (hunk 5 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java]: updated in f32f471 and used some wording disucussed in #5888 for the excpetion message.  This code logs a warning in #5888 and throws an exception here.

File: core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java (hunk 2 above)
Comment (ctubbsii) [reply core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java]: It was surprising to me that there was a table property in there. So I dug into the code a bit more. It looks like the tests are mocking two different ServiceEnvironments. The first one is for `.init(InitParameters)`, and the other is for `planner.makePlan(PlanningParameters)`. Only the system/site configuration is used for `init`, but the TableConfiguration is used for the `makePlan`, so the `ServiceEnvironment.getConfiguration(TableId)` is only mocked in the second ServiceEnvironment, and the one used for `init` only mocks `ServiceEnvironment.getConfiguration()` (without a TableId).

This is very confusing because I generally expect the same `ServiceEnvironment` to be used for both, and I was further confused because I didn't understand that the table property was going into the mock object for the system configuration, where it shouldn't be used from. However, I now realize that this is the case because the same config is being used to back both mocked `ServiceEnvironment` instances.

This code should be improved (in a different PR) to do separate the config that is used for mocking the system properties from the config that is used for mocking the table properties... something like:

```java
var mockServiceEnvironment = createMockServEnv(systemConfigOverrides, tableConfigOverrides);
var mockInitParams = createMockInitParams(mockServiceEnvironment);
var mockPlanningParams = createMockPlanningParams(mockServiceEnvironment);
```

That would make it clear that that the table prop overrides aren't being used in the system config, and would allow the resulting `ServiceEnvironment` to be reused, but the tableConfigOverrides would only be used for mocking `ServiceEnvironment.getConfiguration(TableId)`, and not the method without a TableId.

Having traversed that rabbit hole, I also discovered that elsewhere in the test, we construct the ServiceEnvironment configuration differently, and that can be done here the same way:

```suggestion
    var conf2 = ServiceEnvironment.Configuration.from(overrides2, true);
```

This should give equivalent behavior, with the DefaultConfiguration elements included, though the test still passes if `false` is used to exclude the defaults. I guess none of the code being tested reads any of the properties other than those set in the overrides, so the defaults don't matter in this case.

I think my suggested line here should be used instead of either of the previous two versions... since it correctly models the site/system configuration, backed by defaults, for the InitParameters, but does so more directly, rather than messing with the ConfigurationImpl constructor and ConfigurationCopy.

Note: to illustrate what I was talking about, regarding the same config carrying properties for both the InitParameters (which reads the system config) and the PlanningParameters (which reads the table config), consider the line two lines after this one, where `createPlanningParams` is called. It is using `conf` instead of the modified `conf2` properties, and the reason why this still works is because we modified the `lowestRatio` property, which apparently affects the `InitParameters`, but is ignored by the `PlanningParameters`. But, it's confusing that we modified props and then kept using the old `conf` that wasn't modified and it still worked. That's because both the system props and the table props are being carried in the same bucket. It would be much more clear if we just passed the same mocked ServiceEnvironment as I explained above.

Comment (ctubbsii) [reply core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java]: @keith-turner I created #5896 to implement the improvements I was talking about in my last comment. It should make it so you don't have to modify that test in this PR.

Comment (keith-turner) [reply core/src/test/java/org/apache/accumulo/core/spi/compaction/RatioBasedCompactionPlannerTest.java]: I merged in the changes from #5896 and removed the changes to the unit test when doing that.

**Comment by dlmarion** [comment]
It looks like a bunch of ITs may have started failing due to this change. ITs that set table properties in the Mini configuration will need to be modified to set them on the table.

**Comment by keith-turner** [comment]
> It looks like a bunch of ITs may have started failing due to this change. ITs that set table properties in the Mini configuration will need to be modified to set them on the table.

I am looking into fixing broken test.  Started working on one change to fix them all and then ran into some problems w/ VolumeChooserIT and decided to do a PR per test, when trying to fix VolumeChooserIT I discovered the existing test may be silently broken.
