### PR TITLE
Fixed concurrency issue in ServiceLock.determineLockOwnership

### LINKED ISSUE #6197: Error in ServiceLock.determineLockOwnership
When restarting processes after an un-clean stop, an exception can be thrown in a ZooKeeper Watcher thread. This situation could occur when a process is killed and then restarted before the ZooKeeper server realizes the process is dead and removes its lock.

The current process will call `ServiceLock.tryLock`, which calls `ServiceLock.lock` and does the following:

  1. Creates an ephemeral node at some path `p`
  2. Sets a watcher on the node created in step 1
  3. In determineLockOwnership() sorts the children of `p` to determine if the node created in step 1 is the first child.
  4. The node is step 1 is *not* the first child because the ZK server has not removed the prior ephemeral node from the server process that was killed
  5. Establishes a Watcher on the node prior to the node in step 1
  6. The ZK Server deletes the prior ephemeral node concurrent to step 5
  7. Because the prior node no longer exists in ZooKeeper, determineLockOwnership is called again where we obtain the lock and set `createdNodeName` to null
  8. The watcher for the prior node fires because the ZK server removed it and calls determineLockOwnership at line 363 which throws an IllegalStateException because `createdNodeName` is null.

### PR DESCRIPTION
**Pull request by dlmarion**
Added some detailed comments to ServiceLock to make it easier to maintain. Renamed variables where it would make it clearer and added volatile modifiers to variables that were set or checked in a Watcher. Made sure that createdNodeName was not null before calling determineLockOwnership.

Closes #6197

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java [hunk 1]
```diff
@@ -360,7 +407,9 @@ public void process(WatchedEvent event) {
                 // created a Watcher on a node that does not exist. Delete the watcher we just
                 // created.
                 zooKeeper.removeWatches(nodeToWatch, this, WatcherType.Any, true);
-                determineLockOwnership(createdEphemeralNode, lw);
+                if (createdNodeName != null) {
+                  determineLockOwnership(lw);
+                }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: After checking createdNodeName and before calling determineLockOwnership() it could change to null.  Would be better to sync this entire block.  Also the check on createdNodeName could be moved before the exist check,  if createNodeName is null there is no need to do that exist check.

Could change the code in the try block to the following.

```java
              synchronized (ServiceLock.this){
                if(createdNodeName != null) {
                  Stat restat = zooKeeper.exists(nodeToWatch, this);
                  if (restat == null) {
                    // if stat is null from the zookeeper.exists(path, Watcher) call, then we just
                    // created a Watcher on a node that does not exist. Delete the watcher we just
                    // created.
                    zooKeeper.removeWatches(nodeToWatch, this, WatcherType.Any, true);
                    determineLockOwnership(lw);
                  } else {
                    LOG.debug("[{}] Renewed watch on prior node  {}", vmLockPrefix, nodeToWatch);
                  }
                }
              }
```

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java [hunk 2]
```diff
@@ -100,38 +119,70 @@ public interface AccumuloLockWatcher extends LockWatcher {
...
+  // the ZooKeeper server created for us with the unique one-up
+  // counter. This variable is set to null when this instance
+  // acquires the lock.
+  private volatile String createdNodeName;
+
+  // Represents the name of the ephemeral sequential node that
+  // has the next lowest counter value. An instance of this class
+  // will watch this node and will attempt to acquire the lock
+  // when this node is deleted.
   private String watchingNodeName;
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: This existing variable name seems wrong, the value is not just the node name.  Seems to be the full path.

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java [hunk 3]
```diff
@@ -378,7 +427,9 @@ public void process(WatchedEvent event) {
         // if stat is null from the zookeeper.exists(path, Watcher) call, then we just
         // created a Watcher on a node that does not exist. Delete the watcher we just created.
         zooKeeper.removeWatches(nodeToWatch, priorNodeWatcher, WatcherType.Any, true);
-        determineLockOwnership(createdEphemeralNode, lw);
+        if (createdNodeName != null) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Should not need a null check here because we are in a syncronized method and it was checked for null at the top of the method.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Removed check in 2a591cc

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java (hunk 2 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Fixed variable name in 2a591cc

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Implemented in 2a591cc
