### PR TITLE
Modified IteratorEnvironment to no longer throw UOE

### LINKED ISSUE #4810: RFileScanner's IteratorEnvironment throws UnsupportedOperationException for getConfig() and getServiceEnv()
**Describe the bug**
When attaching an iterator to an RFileScanner which uses either the iterator environments config or ServiceEnvironment, the iterators will throw UnsupportedOperationExceptions 

**Versions (OS, Maven, Java, and others, as appropriate):**
Accumulo 2.x

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Create an RFileScanner
2. Attach an Iterator which in the init method calls env.getConfig() or env.getServiceEnv()

**Expected behavior**
The config for the RFileScanner should be built from any table properties passed into the builder's withTableProperties() method. These properties can also be returned for any env.getServiceEnv().getConfiguration() or env.getServiceEnv().getConfiguration(TableId) methods.

### PR DESCRIPTION
**Pull request by dlmarion**
Modified the IteratorEnvironment interface such that the methods no longer have default implementation that throw UnsupportedOperationException. Created the class ClientIteratorEnvironment to serve as the default implementation for the client objects that defined their own implementation and for use in the tests. Removed all test implementations of IteratorEnvironment.

Closes #4810

### CODE REVIEW

**Comment by dlmarion** [comment]
The replacement of the `IteratorEnvironment` implementations in `ClientSideIteratorScanner`, `RFileScanner`, `OfflineIterator` with `ClientIteratorEnvironment` need to be scrutinized. I know that in one case one of the implementations handled the `registerSideChannel` method, but I could not find it being used anywhere so I just deleted it.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java [hunk 1]
```diff
@@ -345,9 +245,13 @@ private SortedKeyValueIterator<Key,Value> createIterator(KeyExtent extent,
...
-    OfflineIteratorEnvironment iterEnv =
-        new OfflineIteratorEnvironment(context, tableId, authorizations, tableCC, false,
-            samplerConfImpl == null ? null : samplerConfImpl.toSamplerConfiguration());
+    ClientIteratorEnvironment.Builder iterEnvBuilder =
+        new ClientIteratorEnvironment.Builder().withAuthorizations(authorizations)
+            .withScope(IteratorScope.scan).withTableId(tableId).withClient(context);
+    if (scannerSamplerConfig != null) {
+      iterEnvBuilder.withSamplerConfiguration(scannerSamplerConfig);
+    }
+    IteratorEnvironment iterEnv = iterEnvBuilder.build();
```
Comment (kevinrr888) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java:254]: It seems usage of `tableCC` and `samplerConfImpl` were dropped. Was this intentional?

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java:254]: It also seems like `isSamplingEnabled()` is always false in original impl, but not in this impl

**Review by kevinrr888 — COMMENTED** [review]
Have not finished reviewing everything; want to first ensure this is a PR we want to move forward with. Overall, I think these changes are a good idea, however, this refactoring can very easily have bugs that are hard to spot. I'm not sure if this is the best for a 2.1 change, risking potentially introducing more bugs than the original PR set out to fix.

Some additional comments:
- IteratorEnvIT may need to be changed (would be nice to include the changes to that IT from #4816 here as well)
- There may still be some other things from #4816 that we still want

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+
+    public Builder withSamplerConfiguration(SamplerConfiguration sc) {
+      this.samplerConfig = Optional.of(sc);
+      return this;
+    }
+
+    public Builder withClient(AccumuloClient client) {
+      this.env = Optional.of(new ClientServiceEnvironmentImpl((ClientContext) client));
+      return this;
+    }
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:85]: I had that earlier, and it fails the build. `o.a.a.core.iterators` is in the public API, so this method needs to use AccumuloClient vs ClientContext as the API parameter.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java:254]: The old code set useSampling to `false`, but went to the trouble of creating the `sampleConfiguration`. I'm wondering if setting `useSampling` to `false` was a bug in the old version.

https://github.com/apache/accumulo/blob/3912b36d0b0ca103b7068d7c7575c99d32a11a97/core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java#L324-L331

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java:254]: Regarding the missing `tableCC`, by setting `withClient(ClientContext)`, it will create a `ClientServiceEnvironmentImpl` for the calls to ` getServiceEnv` and `getPluginEnv` and the table configuration can be retrieved from that object.

File: core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java [hunk 3]
```diff
@@ -295,9 +230,10 @@ public Iterator<Entry<Key,Value>> iterator() {
 
     SortedKeyValueIterator<Key,Value> skvi;
     try {
-      IteratorEnvironment iterEnv = new ClientSideIteratorEnvironment(
-          getSamplerConfiguration() != null, getIteratorSamplerConfigurationInternal());
-
+      IteratorEnvironment iterEnv = new ClientIteratorEnvironment.Builder()
+          .withClient(context.get()).withAuthorizations(getAuthorizations())
+          .withScope(IteratorScope.scan).withTableId(tableId.get())
+          .withSamplerConfiguration(getIteratorSamplerConfigurationInternal()).build();
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java]: I think I fixed this in c14c35f

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 4]
```diff
@@ -292,15 +280,54 @@ public Iterator<Entry<Key,Value>> iterator() {
             EMPTY_BYTES, tableConf);
       }
 
+      ClientServiceEnvironmentImpl senv = new ClientServiceEnvironmentImpl(null) {
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java]: Moved this to a static inner class in c14c35f

File: core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java]: Fixed the `samplerConfImpl` issue in c14c35f

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 5]
```diff
@@ -0,0 +1,207 @@
...
+    this.env = builder.env;
+  }
+
+  private ClientIteratorEnvironment(ClientIteratorEnvironment copy) {
+    this.scope = copy.scope.isPresent() ? Optional.of(copy.scope.orElseThrow()) : Optional.empty();
+    this.isFullMajorCompaction = copy.isFullMajorCompaction;
+    this.auths = copy.auths.isPresent() ? Optional.of(copy.auths.orElseThrow()) : Optional.empty();
+    this.isUserCompaction = copy.isUserCompaction;
+    this.tableId =
+        copy.tableId.isPresent() ? Optional.of(copy.tableId.orElseThrow()) : Optional.empty();
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:122]: Optional objects are immutable so do not need to copy.

```suggestion
    this.tableId = copy.tableId;
```

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 6]
```diff
@@ -0,0 +1,207 @@
...
+  @Override
+  @Deprecated(since = "2.0.0")
+  public void registerSideChannel(SortedKeyValueIterator<Key,Value> iter) {
+    throw UOE;
+  }
+
+  @Override
+  public Authorizations getAuthorizations() {
+    if (getIteratorScope() != IteratorScope.scan) {
+      throw new IllegalStateException("Iterator scope is not majc");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:159]:
```suggestion
      throw new IllegalStateException("Iterator scope is not scan");
```

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 7]
```diff
@@ -0,0 +1,207 @@
...
+
+  @Override
+  public boolean isSamplingEnabled() {
+    return this.samplerConfig.isPresent();
+  }
+
+  @Override
+  public SamplerConfiguration getSamplerConfiguration() {
+    return samplerConfig.orElse(null);
+  }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:180]: Sampling being enabled and the config being present are separate.  An iterator w/o sampling can create deep copy over sample data.   For this to work, can have an iter env that has sample config but does not have sampling enabled.  To create the deep copy cloneWithSamplingEnabled() is called which returns a new iter env w/ the sampling config and sampling enabled.

So would need a `boolean isSamplingEnabled` instance variable on this class.  

```suggestion
  public IteratorEnvironment cloneWithSamplingEnabled() {
    if (!samplerConfig.isPresent()) {
      throw new SampleNotPresentException();
    }
    // return a new iter env that is identical in every way except it has sampling enabled.
    return new ClientIteratorEnvironment(this, true);
  }

  @Override
  public boolean isSamplingEnabled() {
    return isSamplingEnabled;
  }

  @Override
  public SamplerConfiguration getSamplerConfiguration() {
    if(!isSamplingEnabled){
       // javadoc mentions null should be returned when sampling is not enabled
       return null;
    }
    return samplerConfig.orElse(null);
  }
```

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: Fixed in 3cec5f7

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java (hunk 6 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: Fixed in 3cec5f7

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java (hunk 5 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: Fixed in 3cec5f7

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 8]
```diff
@@ -0,0 +1,207 @@
...
+    if (getIteratorScope() != IteratorScope.majc) {
+      throw new IllegalStateException("Iterator scope is not majc");
+    }
+    return isFullMajorCompaction;
+  }
+
+  @Override
+  @Deprecated(since = "2.0.0")
+  public void registerSideChannel(SortedKeyValueIterator<Key,Value> iter) {
+    throw UOE;
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: Fixed in 3cec5f7

File: core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/OfflineIterator.java]: Fixed in 3cec5f7

File: core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java]: Fixed in 3cec5f7

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 9]
```diff
@@ -292,15 +280,54 @@ public Iterator<Entry<Key,Value>> iterator() {
...
+
+      };
+
+      ClientIteratorEnvironment.Builder iterEnvBuilder =
+          new RFileScannerIteratorEnvironmentBuilder().withEnvironment(senv)
+              .withAuthorizations(opts.auths).withScope(IteratorScope.scan);
+      if (getSamplerConfiguration() != null) {
+        iterEnvBuilder.withSamplerConfiguration(getSamplerConfiguration());
+      }
+      IteratorEnvironment iterEnv = iterEnvBuilder.build();
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java]: Fixed in bf294a4

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 10]
```diff
@@ -292,15 +280,54 @@ public Iterator<Entry<Key,Value>> iterator() {
             EMPTY_BYTES, tableConf);
       }
 
+      ClientServiceEnvironmentImpl senv = new ClientServiceEnvironmentImpl(null) {
+
+        @Override
+        public String getTableName(TableId tableId) throws TableNotFoundException {
+          throw new IllegalStateException("TableId not known in RFileScanner");
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java]: Fixed in bf294a4

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 11]
```diff
@@ -0,0 +1,220 @@
...
+    return auths.orElseThrow();
+  }
+
+  @Override
+  public IteratorEnvironment cloneWithSamplingEnabled() {
+    String samplerClass =
+        getPluginEnv().getConfiguration(getTableId()).get(Property.TABLE_SAMPLER.getKey());
+    if (samplerClass == null || samplerClass.isBlank()) {
+      throw new SampleNotPresentException();
+    }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:178]: The following seems good for ClientSideIteratorScanner and is tested in `SampleIT.testIterator()`.

```suggestion
    if (samplerConfig.isEmpty()) {
      throw new SampleNotPresentException();
    }
```

Inspecting table props seems like the right way to go, however the bit of code here is not complete for that.  Looking into RFileScanner it may benefit from a secondary check of tables props.  AFIACT there are no tests for calling `cloneWithSamplingEnabled()` when using RFileScanner. In a follow on PR I could add unit test that cover calling this code when using RFileScanner and maybe add some code that inspects the table config as a secondary step when samplerConfig.isEmpty().

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 12]
```diff
@@ -0,0 +1,220 @@
...
+import org.apache.accumulo.core.data.TableId;
+import org.apache.accumulo.core.data.Value;
+import org.apache.accumulo.core.iterators.IteratorUtil.IteratorScope;
+import org.apache.accumulo.core.iteratorsImpl.system.MapFileIterator;
+import org.apache.accumulo.core.security.Authorizations;
+import org.apache.accumulo.core.spi.common.ServiceEnvironment;
+import org.apache.hadoop.conf.Configuration;
+import org.apache.hadoop.fs.FileSystem;
+
+public class ClientIteratorEnvironment implements IteratorEnvironment {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:41]: Is this class intended to be in the public API?  This package is in the public API.  Would need javadoc and since tags if that is the intent.  Seems like all of its public methods only use public API types, so it could be in the public API.

If this were in the public API, then it seems like it would be useful for users writing unit test.  Would be good to kick the tires on that concept before releasing and try using on an external project in unit test to see if there any hiccups.  Seems like it may work nicely w/ the following for external unit test.

https://github.com/apache/accumulo/blob/9eda6d28f469fef0844eeb6ff4c765a2896cb41c/core/src/main/java/org/apache/accumulo/core/client/PluginEnvironment.java#L145

However those changes are in main.

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java [hunk 13]
```diff
@@ -0,0 +1,220 @@
...
+    this.samplerConfig = copy.samplerConfig;
+    this.env = copy.env;
+    this.samplingEnabled = true;
+  }
+
+  @Override
+  @Deprecated(since = "2.0.0")
+  public SortedKeyValueIterator<Key,Value> reserveMapFileReader(String mapFileName)
+      throws IOException {
+    Configuration hadoopConf = new Configuration();
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:140]: Was this implementation based on something else?  On the server side this method can open an rfile or a mapfile (Looking at TabletIteratorEnvironment).  According to my IDE nothing calls this method, so no test.  Since this method has zero test, we may be better off throwing UnsupportedOperationException for now.  Should probably test it if we add an impl.

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 14]
```diff
@@ -74,8 +79,65 @@
...
+        throws ReflectiveOperationException, IOException {
+      return RFileScanner.class.getClassLoader().loadClass(className).asSubclass(base)
+          .getDeclaredConstructor().newInstance();
+    }
+
+    @Override
+    public <T> T instantiate(TableId tableId, String className, Class<T> base)
+        throws ReflectiveOperationException, IOException {
+      return instantiate(className, base);
+    }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java:119]: These seem similar enough to the methods in the super class that they could be dropped here.

```suggestion
```

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 15]
```diff
@@ -74,8 +79,65 @@
...
+
+    @Override
+    public Configuration getConfiguration(TableId tableId) {
+      Preconditions.checkArgument(tableId == TABLE_ID, "Expected " + TABLE_ID + " obtained"
+          + " from IteratorEnvironment.getTableId(), but got: " + tableId);
+      ConfigurationCopy tableCC = new ConfigurationCopy(DefaultConfiguration.getInstance());
+      opts.tableConfig.forEach(tableCC::set);
+      return new ConfigurationImpl(tableCC);
+    }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java:133]: Could memorize these or create them once in the constructor.  Sometimes calling code will repeatedly call these methods for each property.

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java (hunk 13 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java:140]: It came from core/test/.../DefaultIteratorEnvironment. I also found no references to this method, but wasn't sure if we should try and implement something, or throw an exception. I'm good with changing this to throwing an exception.

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 16]
```diff
@@ -74,8 +79,65 @@
 
 class RFileScanner extends ScannerOptions implements Scanner {
 
+  private static class RFileScannerIteratorEnvironmentBuilder
+      extends ClientIteratorEnvironment.Builder {
+
+    public ClientIteratorEnvironment.Builder withEnvironment(ClientServiceEnvironmentImpl env) {
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java]: In 2d39e46 I moved ClientIteratorEnvironment out of the public api package, and moved this method into it.

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java (hunk 12 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: I moved ClientIteratorEnvironment out of the public API in 2d39e46.

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java (hunk 13 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: Modified this in 2d39e46 to throw an UnsupportedOperationException

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java (hunk 14 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java]: Removed these in 2d39e46.

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java (hunk 15 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java]: Moved the configuration calculations to the constructor in 2d39e46. Had to guard against opts.tableConfig being null, which it is in RFileClientTest.

**Comment by kevinrr888** [comment]
> While reviewing this today I found a place I would like to add a unit test for RFileScanner. More generally we may want to eventually have something like https://github.com/apache/accumulo/pull/5474 that covers the iteratorEnv in all the different scanner types (like RFileScanner,OfflineScanner,ScannerImpl,BatchScanner,ClientSideIteratorScanner). We could try to as much as possible to run the same tests across all the different scanner types. For this PR I will try to run all the unit test w/ code coverage and see what the coverage looks like for the new code.

In #4816, I changed the `IteratorEnvIT` to test across different scanner types. Could use that code and expand on that as needed for full test coverage. Could potentially move those changes into this PR, or change that PR to only have the changes not accomplished by this PR and merge them both in.

**Comment by keith-turner** [comment]
> @keith-turner - In https://github.com/apache/accumulo/pull/4816, I changed the IteratorEnvIT to test across different scanner types. Could use that code and expand on that as needed for full test coverage. Could potentially move those changes into this PR, or change that PR to only have the changes not accomplished by this PR and merge them both in.

After this PR is merged, seems like it would good to circle back to #4816 and pull the useful bits into another PR.

File: core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java (hunk 11 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/iterators/ClientIteratorEnvironment.java]: Opened #5500 to remind myself of the follow on work I want to do here.

**Comment by dlmarion** [comment]
I'm not sure about the change I made in 1c75b6c. With the builder pattern should we allow the user to call whatever methods they want in which-ever order they want?

File: server/base/src/main/java/org/apache/accumulo/server/iterators/TabletIteratorEnvironment.java [hunk 17]
```diff
@@ -79,6 +80,30 @@ public TabletIteratorEnvironment(ServerContext context, IteratorScope scope,
     this.topLevelIterators = new ArrayList<>();
   }
 
+  public TabletIteratorEnvironment(ServerContext context, IteratorScope scope,
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/iterators/TabletIteratorEnvironment.java:83]: What is going on w/ this new constructor?  Its only used in a test, what is preventing the test from using the new builder?

**Comment by keith-turner** [comment]
> I'm not sure about the change I made in https://github.com/apache/accumulo/commit/1c75b6c646bbd4bf5d7cdfff7d387445ff636445. With the builder pattern should we allow the user to call whatever methods they want in which-ever order they want?

That change is nice for runtime validation.    Could add more runtime checks making sure things are empty when set in the builder w/ the assumption that if the same builder method is called twice it probably is not what was intended.  I like the way it currently is, the optionals provide a lot of runtime validation (like for the case attempting to use something not set in the builder).

File: server/base/src/main/java/org/apache/accumulo/server/iterators/TabletIteratorEnvironment.java (hunk 17 above)
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/iterators/TabletIteratorEnvironment.java:83]: which test?

Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/iterators/TabletIteratorEnvironment.java:83]: ah, I think it's because I was trying to get all of the server side code to use server-side iterator environment objects vs having all the server side tests using the new ClientIteratorEnvironment.

**Comment by dlmarion** [comment]
> That change is nice for runtime validation. Could add more runtime checks making sure things are empty when set in the builder w/ the assumption that if the same builder method is called twice it probably is not what was intended. I like the way it currently is, the optionals provide a lot of runtime validation (like for the case attempting to use something not set in the builder).

Ok, I can add more validation on the Builder

File: core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java [hunk 18]
```diff
@@ -295,9 +230,14 @@ public Iterator<Entry<Key,Value>> iterator() {
...
-          getSamplerConfiguration() != null, getIteratorSamplerConfigurationInternal());
-
+      ClientIteratorEnvironment.Builder builder = new ClientIteratorEnvironment.Builder()
+          .withClient(context.get()).withAuthorizations(getAuthorizations())
+          .withScope(IteratorScope.scan).withTableId(tableId.get())
+          .withSamplerConfiguration(getIteratorSamplerConfigurationInternal());
+      if (getSamplerConfiguration() != null) {
+        builder.withSamplingEnabled();
+      }
+      IteratorEnvironment iterEnv = builder.build();
```
[the remark this answers is not in the document]
Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java:240]: Nevermind, I think `withClient` covers this

**Review by kevinrr888 — COMMENTED** [review]
Posting what I have now. Will finish review tomorrow

File: core/src/main/java/org/apache/accumulo/core/iteratorsImpl/ClientIteratorEnvironment.java [hunk 19]
```diff
@@ -0,0 +1,219 @@
...
+    }
+    return auths.orElseThrow();
+  }
+
+  @Override
+  public IteratorEnvironment cloneWithSamplingEnabled() {
+    if (samplerConfig.isEmpty()) {
+      throw new SampleNotPresentException();
+    }
+    return new ClientIteratorEnvironment(this);
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/iteratorsImpl/ClientIteratorEnvironment.java:186]: The copy constructor sets samplingEnabled to true.

**Review by ctubbsii — COMMENTED** [review]
I'm in favor of this change, overall. There is some small risk of doing this in a bugfix release, but I don't see any public API changes, or even SPI changes, that would really impact users. As long as all the ITs pass, I'm in favor of this overall. Aside from that, I don't have anything to add that others haven't already said or have already been fixed in the implementation.

**Comment by dlmarion** [comment]
Full IT build passed

File: core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java [hunk 20]
```diff
@@ -74,8 +78,46 @@
...
+          + " from IteratorEnvironment.getTableId(), but got: " + tableId);
+      return tableConf;
+    }
+
+  }
+
   private static final byte[] EMPTY_BYTES = new byte[0];
   private static final Range EMPTY_RANGE = new Range();
+  private static final String TABLE_NAME = "rfileScanner";
+  private static final TableId TABLE_ID = TableId.of(TABLE_NAME);
```
[the remark this answers is not in the document]
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java:120]: Could spin this off in a separate issue since it was a preexisting pattern in the code.

**Review by keith-turner — APPROVED** [review]

**Review by kevinrr888 — APPROVED** [review]
These changes look good and are a lot nicer than the previous impl. Some follow ons for this may be:
* https://github.com/apache/accumulo/pull/5490#discussion_r2056825666 - I did not understand this constructor and why the builder couldn't be used, but since it's just used in tests and those pass, not too important.
* #4816 - Should extract the useful bits from this PR and merge in separately (I can do this). Most importantly, want the `IteratorEnvIT` changes which will test the changes done here.
* Look at potentially replacing the `RFileScanner` table id with null or something better if possible.

File: core/src/test/java/org/apache/accumulo/core/iterators/DefaultIteratorEnvironment.java [hunk 21]
```diff
@@ -1,56 +0,0 @@
...
-    this.conf = DefaultConfiguration.getInstance();
-  }
-
-  @Deprecated(since = "2.0.0")
-  @Override
-  public SortedKeyValueIterator<Key,Value> reserveMapFileReader(String mapFileName)
-      throws IOException {
-    FileSystem fs = FileSystem.get(hadoopConf);
-    return new MapFileIterator(fs, mapFileName, hadoopConf);
-  }
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/test/java/org/apache/accumulo/core/iterators/DefaultIteratorEnvironment.java:50]: The ITs passed with this change, so I think we are safe. IIRC, Keith said above that he could not find any uses of it.
