### PR TITLE
Started upgrade test, fixed issue in upgradeZookeeper

### LINKED ISSUE #5343: 4.0.0 upgrade fails when old scan server path found in ZooKeeper
**Describe the bug**
```
java.lang.IllegalStateException: Found server address at /sservers/localhost:9996. Was expecting either a resource group name or nothing. Stop any referenced servers.
        at org.apache.accumulo.manager.upgrade.Upgrader12to13.validateEmptyZKWorkerServerPaths(Upgrader12to13.java:366) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.upgrade.Upgrader12to13.upgradeZookeeper(Upgrader12to13.java:76) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.upgrade.UpgradeCoordinator.upgradeZookeeper(UpgradeCoordinator.java:183) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.Manager.setManagerState(Manager.java:338) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.Manager.getManagerLock(Manager.java:1554) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.Manager.run(Manager.java:1156) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

### PR DESCRIPTION
**Pull request by dlmarion**
The Upgrader12to13.validateEmptyZKWorkerServerPaths method was checking for no children in the zookeeper paths for compactors, scan servers, tablet server, and dead tablet servers as an indication that no servers were current running. Prior to recent changes in 4.0, zookeeper paths were not cleaned up for server processes when those processes are stopped. Modified the logic in the method to remove any children under those paths that are empty. Started the Upgrader12to13 unit test.

Closes #5343

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java [hunk 1]
```diff
@@ -363,8 +364,18 @@ private void validateEmptyZKWorkerServerPaths(ServerContext context) {
...
         for (String child : children) {
           if (child.contains(":")) {
-            throw new IllegalStateException("Found server address at " + serverPath + "/" + child
-                + ". Was expecting either a resource group name or nothing. Stop any referenced servers.");
+            String childPath = zkRoot + serverPath + "/" + child;
+            if (zr.getChildren(childPath).isEmpty()) {
+              // child is likely host:port and is an empty directory. Since there
+              // is no lock here, then the server is likely down (or should be).
+              // Remove the entry and move on.
+              context.getZooSession().asReaderWriter().recursiveDelete(childPath,
```
Comment (ctubbsii) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java:372]: I wonder if it would be safer if this upgrade code reserved its own lock on these empty nodes, to prevent other services from getting the lock while in this upgrade code.

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java [hunk 2]
```diff
@@ -363,8 +364,18 @@ private void validateEmptyZKWorkerServerPaths(ServerContext context) {
...
+                  NodeMissingPolicy.FAIL);
```
Comment (ctubbsii) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java:373]: It might be okay to use NodeMissingPolicy.SKIP instead... if something else deleted the lock node in the interim, that might be okay?

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java (hunk 1 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java:372]: I guess deleting the lock is probably sufficient... no need to reserve it. I was just thinking of the case where a new one tried to come online.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java:372]: I don't know that a lock would help here. We know that it's an old path in ZooKeeper and that it's empty, so we are going to delete it. If another process for some reason is going to try and use it, we don't want that process up anyway, so deleting the server directory would delete any lock that is acquired after we determined the directory was empty, and deleting the lock would terminate the process.

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java (hunk 2 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader12to13.java]: Changed in 9f70857
