### PR TITLE
Fixes some minor table op inconsistencies for system tables

### LINKED ISSUE #5680: Inconsistencies in TableOperations Exceptions for System Tables
**Describe the bug**
With the new comprehensive table operations IT, noticed several operations on system tables resulted in different exceptions based on the system table provided. Some of these have since been resolved but there are two instances still unresolved:
https://github.com/apache/accumulo/pull/5474#discussion_r2042464584
https://github.com/apache/accumulo/pull/5474#discussion_r2042459382

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 4.0 (potentially earlier, but don't want to change in 2.1.x)

**To Reproduce**
View the tests linked above

**Expected behavior**
See https://github.com/apache/accumulo/pull/5474#discussion_r2060572359. A similar argument can be made for `clone()`

### PR DESCRIPTION
**Pull request by kevinrr888**
closes #5680

This didn't change anything for clone as mentioned in the ticket because this had since been addressed by #5711

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT_SimpleSuite.java [hunk 1]
```diff
@@ -367,8 +367,9 @@ public void testCloneSystemTables() {
       for (int i = 0; i < sysTables.length; i++) {
         var sysTable = sysTables[i];
         var cloneTableName = tableNames[i];
-        assertThrows(Exception.class, () -> client.tableOperations().clone(sysTable.tableName(),
-            cloneTableName, CloneConfiguration.empty()), () -> "Table:" + sysTable.tableName());
+        assertThrows(AccumuloException.class, () -> client.tableOperations()
+            .clone(sysTable.tableName(), cloneTableName, CloneConfiguration.empty()),
+            () -> "Table:" + sysTable.tableName());
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/functional/CloneTestIT_SimpleSuite.java:372]: Was previously `Exception` because different exceptions could be thrown for diff system tables. #5711 fixed this, so updated the test here
