### PR TITLE
Reuse already read lastLocation information during location updates

### LINKED ISSUE #3301: Setting the last location may do unnecessary metadata read.
**Describe the bug**

While working on #3284 I noticed that [ManagerMetadataUtil.updateLastForAssignmentMode()](https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java#L261-L270) is doing a metadata read during tablet location updates.  Not sure, but may be able to avoid this read by passing information from earlier metadata reads.

One place updateLastForAssignmentMode() is called is in [MetaDataStateStore](https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java#L110) where the available TabletLocationState may have the last location obtained in [MetaDataTableScanner](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java#L198) when scanning the metadata table.  So if that information about the last location could be passed from the scan, then the information could be obtained  more efficiently.  Getting the information from a scan of the metadata table avoids the RPC per tablet to get the information.

Another place updateLastForAssignmentMode() is called is when TabletStateStore.setLocation() is called in [AssignmentHandler](https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java#L185).  Earlier in the AssignmentHandler code it reads the tablets metadata and could pass that to TabletStateStore.setLocation() which could pass it to updateLastForAssignmentMode().

**Expected behavior**

Last location is obtained via leveraging existing metadata reads, if possible, rather than doing a new one.

### PR DESCRIPTION
**Pull request by cshannon**
This change will reuse previously read lastLocation information when ManagerMetadataUtil updates last location to prevent unnecessary metadata reads. If the value is not known then a metadata read will be performed like before.

This closes #3301

### CODE REVIEW

**Comment by cshannon** [comment]
@keith-turner - It seemed like the best thing to do here was to add a new field to the `Assignment` class to pass the previously read last location data if known. This was nice as I didn't have to change method signatures and also works for the case where a list of assignments are passed. I added a bunch of mock tests to verify that the new behavior is correct in terms of when the update will do a metadata read or skip it. I ran through the sunny tests and they all passed but I will also kick off a full IT build.

File: server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java [hunk 1]
```diff
@@ -257,14 +257,23 @@ public static Optional<StoredTabletFile> updateTabletDataFile(ServerContext cont
...
-      Ample.TabletMutator tabletMutator, KeyExtent extent, TServerInstance location) {
+      Ample.TabletMutator tabletMutator, KeyExtent extent, TServerInstance location,
+      Location prevLastLocation) {
     // if the location mode is assignment, then preserve the current location in the last
     // location value
     if ("assignment".equals(context.getConfiguration().get(Property.TSERV_LAST_LOCATION_MODE))) {
-      TabletMetadata lastMetadata = ample.readTablet(extent, TabletMetadata.ColumnType.LAST);
-      Location lastLocation = (lastMetadata == null ? null : lastMetadata.getLast());
+      // If prevLastLocation is not provided then look it up from metadata
+      final Location lastLocation = Optional.ofNullable(prevLastLocation).orElseGet(() -> {
```
Comment (dlmarion) [inline server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java:269]: Could use a conditional statement here and avoid the object creation.

```
  Location lastLocation = prevLastLocation;
  if (lastLocation == null) {
        log.trace(
            "Previous last location for {} not provided to updateLastForAssignmentMode, loading from metadata.", extent);
        final TabletMetadata lastMetadata =
            ample.readTablet(extent, TabletMetadata.ColumnType.LAST);
        lastLocation = lastMetadata == null ? null : lastMetadata.getLast();
  }
```

File: server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java [hunk 2]
```diff
@@ -257,14 +257,23 @@ public static Optional<StoredTabletFile> updateTabletDataFile(ServerContext cont
...
+        log.trace(
+            "Previous last location for {} not provided to updateLastForAssignmentMode, loading from metadata.",
+            extent);
+        final TabletMetadata lastMetadata =
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java:273]: If the last was not present when we read earlier, then we probably do not need to read it again.  Its tricky though because null can have two meanings, it can mean it was never read previously or it was read previously and was not present.  One simplification is that if we assume that all code calling this method has already tried to read the last location, then we never need to read it here when null.

**Comment by ctubbsii** [comment]
The original ticket was targeting 2.1.1, but this PR was made against the main branch instead of the 2.1 branch. I'm not sure what the desired intent is, but these should probably match, or we'll need another PR to backport it if they remain different. If you want to avoid creating a new PR, this PR can be updated by editing the base branch to 2.1, and then rebasing (cherry-picking) the commits from the HEAD of the main branch onto the head of the 2.1 branch and force pushing the branch that backs this PR.

**Comment by cshannon** [comment]
> The original ticket was targeting 2.1.1, but this PR was made against the main branch instead of the 2.1 branch. I'm not sure what the desired intent is, but these should probably match, or we'll need another PR to backport it if they remain different. If you want to avoid creating a new PR, this PR can be updated by editing the base branch to 2.1, and then rebasing (cherry-picking) the commits from the HEAD of the main branch onto the head of the 2.1 branch and force pushing the branch that backs this PR.

I actually didn't need to do anything here but switch the target merge branch in my PR to 2.1. I actually already did base this PR off the 2.1 branch (I thought I did) but when I created the PR I just mistakenly picked the wrong target as it defaulted to main and I didn't notice.

**Comment by cshannon** [comment]
@keith-turner - This is ready for another review, I simplified things and removed the attempt to read the metadata if the passed in lastLocation value is null and updated the Assignment class to only have one constructor that requires lastLocation now so we don't miss passing in the value. All the sunny tests passed and I kicked off another full IT build as well.

File: server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java [hunk 3]
```diff
@@ -924,7 +925,8 @@ private void getAssignmentsFromBalancer(TabletLists tLists,
                   lastLocation.getHostPort());
             }
 
-            tLists.assignments.add(new Assignment(assignment.getKey(), assignment.getValue()));
+            tLists.assignments.add(new Assignment(assignment.getKey(), assignment.getValue(),
+                lastLocation != null ? Location.last(lastLocation) : null));
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java:929]: Looking around in the code I am not entirely sure `lastLocation` is actually a location from the last column. Not sure what the value in the map is for ATM.  Entries are added to the unassigned map in the following method and that does not look like its adding things from the last column to the map.

https://github.com/apache/accumulo/blob/9c459ce8f06d9d9e04280d020ea091fedf13749b/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L383-L399

File: server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java [hunk 4]
```diff
@@ -253,18 +253,16 @@ public static Optional<StoredTabletFile> updateTabletDataFile(ServerContext cont
...
    * @param location The new location
+   * @param lastLocation The previous last location, which may be null
    */
-  public static void updateLastForAssignmentMode(ClientContext context, Ample ample,
-      Ample.TabletMutator tabletMutator, KeyExtent extent, TServerInstance location) {
+  public static void updateLastForAssignmentMode(ClientContext context,
+      Ample.TabletMutator tabletMutator, TServerInstance location, Location lastLocation) {
     // if the location mode is assignment, then preserve the current location in the last
     // location value
+    log.info("Loaded Last location: {}", lastLocation);
```
[the remark this answers is not in the document]
Comment (cshannon) [reply server/base/src/main/java/org/apache/accumulo/server/util/ManagerMetadataUtil.java:264]: Yep, I forgot to take this out, I will remove it.

File: server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java (hunk 3 above)
Comment (cshannon) [reply server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java]: I updated the PR to use the lastLocation value that is part of TabletLocationState when doing the metadata updates. Before the change the value was always coming from getServer() which is returning getLocation() and that could be current, future or last so this makes sure to always use the last value from metadata. The old value (getServer()) is still being tracked now as I created an UnassignedTablet class to track both that value and lastLocation as they are used for different things.

**Comment by cshannon** [comment]
I ran a full IT build against this PR and it passed.

File: server/base/src/main/java/org/apache/accumulo/server/manager/state/UnassignedTablet.java [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+import com.google.common.base.Preconditions;
+
+public class UnassignedTablet {
+  private final Location location;
+  private final Location lastLocation;
+
+  public UnassignedTablet(Location location, Location lastLocation) {
+    Preconditions.checkArgument(
+        lastLocation == null || lastLocation.getType() == TabletMetadata.LocationType.LAST);
+    this.location = location;
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/manager/state/UnassignedTablet.java:34]: If the following is also en expecation, could check it.

```suggestion
     Preconditions.checkArgument(location == null || location.getType() == TabletMetadata.LocationType.CURRENT || location.getType() == TabletMetadata.LocationType.FUTURE)
    this.location = location;
```

File: server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java [hunk 6]
```diff
@@ -240,7 +242,7 @@ public void run() {
             return mStats != null ? mStats : new MergeStats(new MergeInfo());
           });
           TabletGoalState goal = manager.getGoalState(tls, mergeStats.getMergeInfo());
-          TServerInstance location = tls.getServer();
+          Location location = tls.getLocation();
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java:245]: Later in the code the location is logged and the Location class does not seem to have a toString method, so with this change will need to add a toString method to the Location class or change the log stmt.

File: server/base/src/main/java/org/apache/accumulo/server/manager/state/UnassignedTablet.java [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+ */
+package org.apache.accumulo.server.manager.state;
+
+import org.apache.accumulo.core.metadata.TServerInstance;
+import org.apache.accumulo.core.metadata.schema.TabletMetadata;
+import org.apache.accumulo.core.metadata.schema.TabletMetadata.Location;
+
+import com.google.common.base.Preconditions;
+
+public class UnassignedTablet {
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/manager/state/UnassignedTablet.java:27]: I like this new class it makes the existing code more clear.  I didn't see anything logging this class, but not sure its not logged. If its logged anywhere it would need a toString.

**Review by keith-turner — APPROVED** [review]

File: server/base/src/main/java/org/apache/accumulo/server/manager/state/UnassignedTablet.java (hunk 7 above)
Comment (cshannon) [reply server/base/src/main/java/org/apache/accumulo/server/manager/state/UnassignedTablet.java:27]: I'll add toString() and also equals/hashcode so it's there for the future if we need it.
