### PR TITLE
ensures no writes happen after batch writer closes

### LINKED ISSUE #3721: Writes made by batch writer may happen after its closed or flushed.
**Describe the bug**
The batch writer uses [this code](https://github.com/apache/accumulo/blob/cd7642988bac831292e988326aaa96e07938c641/core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java#L948-L990) to actually write data via RPC.  The code handles single mutation writes differently than multiple mutations.  For single mutations it does a single RPC.  For multiple mutations it does 3 or more RPCs like the following.

 1. contact the tserver to create a session
 2. make one more calls to the tserver to write mutations using the session id
 3. contact the tserver get that status of the writes to the session and close the session

In either case if there is a network timeout, the batch writer will retry making the RPCs.  However its not know what the status of the previous RPCs is, they could still be processing on the tserver and go through after the batch writer is closed or flushed.

**Expected behavior**
Writes do not go through after a batch writer is closed or flushed.  To accomplish this the single RPC write would probably have to be abandoned.  The multistep RPC could be modified to do something like the following in order to prevent write from happening after the batch writer is closed.

 1. contact the tserver to create a session
 2. make one more calls to the tserver to write mutations using the session id
 3. contact the tserver get that status of the writes to the session and close the session.  In the case of network failure, retry closing the session until the tserver no longer holds it lock in zookeeper.

### PR DESCRIPTION
**Pull request by keith-turner**
Fixes a problem with the batch writer where when retries happened that writes could possibly happen after the batch writer was closed.  Adds a test that causes writes after close without the fixes in this PR.

Fixes #3721

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 1]
```diff
@@ -1028,14 +1022,133 @@ private MutationSet sendMutationsToTabletServer(String location,
...
+       */
+      private boolean isALockHeld(String tserver) {
+        var root = context.getZooKeeperRoot() + Constants.ZTSERVERS;
+        var zLockPath = ServiceLock.path(root + "/" + tserver);
+        return ServiceLock.getSessionId(context.getZooCache(), zLockPath) != 0;
+      }
+
+      private void closeSession() throws InterruptedException, ThriftSecurityException {
+
+        Retry retry = Retry.builder().infiniteRetries().retryAfter(100, MILLISECONDS)
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1089]: Not sure if it will help, but I created RetryableThriftCall as part of the external compaction code. Example [here](https://github.com/apache/accumulo/blob/main/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L359)

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 2]
```diff
@@ -160,8 +165,9 @@ public class TabletServerBatchWriter implements AutoCloseable {
   private final HashSet<String> serverSideErrors = new HashSet<>();
   private final FailedMutations failedMutations;
   private int unknownErrors = 0;
-  private boolean somethingFailed = false;
+  private volatile boolean somethingFailed = false;
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:168]: This doesn't need to be changed in this PR, but I think there's a good case to be made to prefer the Java 5 atomic classes over manually making variables volatile.

* Atomic classes force correct usage
* Usually the extra object creation overhead doesn't matter (but obviously, don't use them when it does matter)
* final Atomic references allow the object's contained value to be updated inside a lambda or anonymous class
* One can immediately infer the memory characteristics by merely looking at the type of the variable in the IDE, and not needing to reference any initializing keywords, which makes for less IDE juggling back and forth, and doesn't require the developer to juggle that information in their head about which fields are declared volatile and which aren't.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 3]
```diff
@@ -901,8 +907,8 @@ public void send(TabletServerMutations<Mutation> tsm)
             span.end();
           }
         } catch (IOException e) {
-          if (log.isTraceEnabled()) {
-            log.trace("failed to send mutations to {} : {}", location, e.getMessage());
+          if (log.isDebugEnabled()) {
+            log.debug("failed to send mutations to {} : {}", location, e.getMessage());
           }
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:912]: The guarding based on the log level is unnecessary.

```suggestion
          log.debug("failed to send mutations to {} : {}", location, e.getMessage());
```

File: test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java [hunk 4]
```diff
@@ -52,15 +51,14 @@ public void test() throws Exception {
...
 
       Mutation m = new Mutation(extent.toMetaRow());
       // unknown columns should cause constraint violation
       m.put("badcolfam", "badcolqual", "3");
-      var e = assertThrows(RuntimeException.class,
-          () -> MetadataTableUtil.update(context, w, null, m, extent));
-      assertEquals(ConstraintViolationException.class, e.getCause().getClass());
+      var e = assertThrows(IllegalArgumentException.class,
+          () -> MetadataTableUtil.update(context, null, m, extent));
+      assertEquals(MutationsRejectedException.class, e.getCause().getClass());
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java:61]: I think the idea here was to verify that the rejection happened because the constraint was violated. I think you need to inspect the MutationsRejectedException a bit deeper in order to get the same verification.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/Writer.java [hunk 5]
```diff
@@ -59,62 +42,18 @@ public Writer(ClientContext context, TableId tableId) {
...
-      } catch (TException e) {
-        log.error("error sending update to {}", parsedLocation, e);
-        TabletLocator.getLocator(context, tableId).invalidateCache(tabLoc.tablet_extent);
-      }
+    String table = Ample.DataLevel.of(tableId).metaTable();
 
-      sleepUninterruptibly(500, MILLISECONDS);
+    try (var writer = context.createBatchWriter(table)) {
+      writer.addMutation(m);
+      writer.flush();
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/Writer.java:56]:
```suggestion
```

Should flush on close anyway. Not much point in calling it manually. The other places this was changed didn't. So, for consistency, I suggest not putting it here either.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 6]
```diff
@@ -931,6 +937,8 @@ private MutationSet sendMutationsToTabletServer(String location,
 
       timeoutTracker.startingWrite();
 
+      Long usid = null;
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:940]: OptionalLong is a better style here, as it's more explicit than null checking and implicit reliance on auto-boxing.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 7]
```diff
@@ -1028,14 +1020,139 @@ private MutationSet sendMutationsToTabletServer(String location,
...
+            throw e;
+          } catch (TException e) {
+            retry.waitForNextAttempt(log, "Attempting to close failed write session " + location
+                + " " + usid + " " + e.getMessage());
+          } finally {
+            ThriftUtil.returnClient(client, context);
+          }
+
+          // if a timeout is set on the batch writer, then do not retry longer than the timeout
+          if ((System.currentTimeMillis() - startTime) > timeout) {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1151]: This should be using System.nanoTime() to check the timeout, which tracks the process execution duration, and should not be using the system clock, which can be changed arbitrarily by NTP, a user, another process.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 8]
```diff
@@ -1028,14 +1020,139 @@ private MutationSet sendMutationsToTabletServer(String location,
...
+
+      private void closeSession() throws InterruptedException, ThriftSecurityException {
+
+        Retry retry = Retry.builder().infiniteRetries().retryAfter(100, MILLISECONDS)
+            .incrementBy(100, MILLISECONDS).maxWait(60, SECONDS).backOffFactor(1.5)
+            .logInterval(3, MINUTES).createRetry();
+
+        final HostAndPort parsedServer = HostAndPort.fromString(location);
+
+        long startTime = System.currentTimeMillis();
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1101]: Should use nanoTime.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 9]
```diff
@@ -1028,14 +1020,139 @@ private MutationSet sendMutationsToTabletServer(String location,
...
+          // the mutations for this task are still incremented in totalMemUsed. It is important that
+          // these overlap in time so that there is no gap where the client would not wait for the
+          // session to close. Overlap in times means the session is added to failedSessions before
+          // the mutations are decremented from totalMemUsed.
+          sendThreadPool.execute(new CloseSessionTask(location, usid));
+        }
+      }
+    }
+
+    class CloseSessionTask implements Runnable {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1052]: There's a lot going on in this. This type should be in its own file. If you want it to have access to TabletServerBatchWriter internals, you can pass `this` as a parameter.

**Review by ctubbsii — CHANGES_REQUESTED** [review]

**Comment by ctubbsii** [comment]
I think removing the use of Writer, and cleanup of closing the batch writer are distinct things. Removing the use of the single-mutation Writer can be done as a separate, first step. It would make it much easier to evaluate the changes that are specifically related to the Batch Writer cleanup.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 9 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1052]: The class is very tightly coupled with the internal implementation and accesses private functions and instance variable of the containing class.  So to push it out would also require changing things to be non private.   I do not think that internal classes that are very tightly coupled with internal  implementation of the containing class need to be moved out.   Its only a class because its internal code that needs to be run in a another thread.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/Writer.java (hunk 5 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/Writer.java]: fixed in a513d75. I think that was vestigial code  (I had a loop or somethnig inside the try block that needed that in past iterations)

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 6 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java]: changed in a513d75.  Didn't see much harm or benefit in this change after making it.

**Comment by keith-turner** [comment]
> I think removing the use of Writer, and cleanup of closing the batch writer are distinct things. Removing the use of the single-mutation Writer can be done as a separate, first step. It would make it much easier to evaluate the changes that are specifically related to the Batch Writer cleanup.

I fixed that because I realized it had the same underlying problem and could cause metadata writes to happen after one would expect.  I can the change commit messages to be more generic in that it fixes all write issues of the same kind.

File: test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java (hunk 4 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/MetaConstraintRetryIT.java]: changed in a513d75

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 3 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java]: changed in a513d75

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1096]: Yeah, I think the RetryableThriftCall I created is meant to continue retrying even in the midst of errors. For example, if the CompactionCoordinator is restarting and the Compactor needs to report status.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 7 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1152]: I would prioritize correctness over consistency. If we avoid incorrect implementations, it avoids creating more work for somebody else to fix later. This one is independent of any others in this very large class, so it's easy to get it correct now, and will create more work for somebody later if deferred.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 9 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1053]: I think that the tight coupling might be the problem. It strains the principle of encapsulation by making everything accessible to everything else within a very large class. I think a more modular approach would make this very large class a bit more comprehensible by forcing clear APIs. We've been in this situation before, and it has benefited us to separate things out. I don't think this is that different. I'm not suggesting it all be done here... I'm just suggesting the new class doesn't need to add to the size and complexity of the already large containing class.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 2 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java]: I try to always declare Atomics as final, so there's no additional concern about pointer chasing. But yeah, I get what you mean if that's not certain. Not really relevant here, but I remembered another good use of Atomics that you don't get directly with volatile: compareAndSet.

**Comment by ctubbsii** [comment]
> > I think removing the use of Writer, and cleanup of closing the batch writer are distinct things. Removing the use of the single-mutation Writer can be done as a separate, first step. It would make it much easier to evaluate the changes that are specifically related to the Batch Writer cleanup.
> 
> I fixed that because I realized it had the same underlying problem and could cause metadata writes to happen after one would expect. I can the change commit messages to be more generic in that it fixes all write issues of the same kind.

No argument from me for fixing it... it definitely needed to be fixed. I was just thinking it would be nice to clearly see the swapping out of Writer for BatchWriter in one commit, and a separate commit that actually fixes the bug in the BatchWriter, so it's clear which part of this changeset addresses the bug. In case we need to revisit the bugfix later (because it's complicated and I don't fully understand it... I'm just kind of taking your word for it after not seeing anything obviously wrong with it), I thought it would be useful to not have to tease them apart later if there was a problem that required a follow-up bugfix. And also the first commit that would remove the use of Writer would enable the follow on work for #3734 and #3735 to proceed right away, fully decoupled from the bugfix here, since they only depend on the discontinuation of the Writer class, and not on the bugfix.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 7 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java]: > I would prioritize correctness over consistency.

That's a good reason to update.  It was irksome to make it inconsistent, but I made the change in 66c6849 to make it correct.  Don't want to fix all the other places in this PR though.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 9 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1054]: I think the tight coupling is nice when analyzing the code. I like when I can examine references to a batch writer variable in an IDE and see all the functions that directly use it. Makes it easy to analyze the code for correctness w/ multithreading.  In  other parts of the Accumulo code we have layers of evolved indirection in the code that make it much more difficult to analyze, understand, and maintain.  I think this code could benefit from being made more modular, but making it more modular should be done with an overall strategy in mind.  I think a strategy of simply extracting inner classes does not evolve to any particular goal and can make the code harder to understand and maintain when iterating that strategy. Maybe a plan like separating  the RPC code from the in in memory state of the batch writer would be a better way to achieve a modular batch writer, not sure.

**Comment by keith-turner** [comment]
> I thought it would be useful to not have to tease them apart later if there was a problem that required a follow-up bugfix. 

I am not going to break this into multiple commits in order to optimize possible eventualities that may or may not happen.  If I wanted to spend time on it, I could probably come up with a scenario for breaking this in 3 commits and another for breaking it into 4 commits.  I would rather spend my time ensuring the changes to fix the observed bug are correct.  If anyone needs assistance reviewing because its a big change, I will be glad to chat and discuss the changes.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 10]
```diff
@@ -1028,14 +1022,139 @@ private MutationSet sendMutationsToTabletServer(String location,
...
+          // happen after the batch writer closes. See #3721. Queuing a task instead of executing
+          // the code here because throwing exceptions in a finally block makes the code hard to
+          // reason about. Queue is less likely to throw an exception.
+          //
+          // When the task is created below it adds to the failedSessions map, this is done while
+          // the mutations for this task are still incremented in totalMemUsed. It is important that
+          // these overlap in time so that there is no gap where the client would not wait for the
+          // session to close. Overlap in times means the session is added to failedSessions before
+          // the mutations are decremented from totalMemUsed.
+          sendThreadPool.execute(new CloseSessionTask(location, usid.getAsLong()));
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1049]: The CloseSessionTask constructor can throw an IllegalStateException when there is a duplicate failed session id. Would this hide or suppress another exception that is being thrown above?

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java [hunk 11]
```diff
@@ -1028,14 +1022,139 @@ private MutationSet sendMutationsToTabletServer(String location,
...
+        try {
+          closeSession();
+        } catch (InterruptedException | RuntimeException | ThriftSecurityException e) {
+          updateUnknownErrors("Failed to close session " + location + " " + usid, e);
+        } finally {
+          synchronized (TabletServerBatchWriter.this) {
+            if (!failedSessions.remove(new Pair<>(usid, location))) {
+              throw new IllegalStateException("Session missing " + location + " " + usid);
+            }
+            TabletServerBatchWriter.this.notifyAll();
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1081]: Do we need to call `notifyAll` in all cases? If so, I think throwing the exception might defeat that.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java:1081]: In this case its ok not to call it because the set was not changed, however I could reorder because it does not hurt to call it and can be called anywhere in the sync block.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java (hunk 10 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java]: I updated the code to use closeable and moved the code out of the finally block in https://github.com/apache/accumulo/commit/cf624372ca15e5992b36003be96123c0595e703d which simplified these changes a bit

**Comment by ctubbsii** [comment]
> I am not going to break this into multiple commits

That's fine. But, do you mind if I do it, instead of merging this as-is?

**Comment by keith-turner** [comment]
> That's fine. But, do you mind if I do it, instead of merging this as-is?

No I don't mind at all.

**Comment by ctubbsii** [comment]
I applied the Writer removal changes (those more closely related to #3735) in commit f76f12baa6e6e5499fe94cc833f02f9e2865f159, and merged that into 2.1 and forward into main first. The only difference to what was originally in this PR was that I also removed an unused private Logger in Writer in that commit.

I've resolved merge conflicts by merging 2.1 into this PR.

Now, this PR just represents the fixes for #3721, and I will squash and merge that separately.
