### PR TITLE
Resolves TabletServer deadlock

### LINKED ISSUE #5597: Deadlock in tablet server when refresing tablet and closing tablet
**Describe the bug**

Sometimes when running ChaoticBalancerIT the following deadlock will happen in a tablet server.

```
Found one Java-level deadlock:
=============================
"accumulo.pool.general.server-Worker-2":
  waiting to lock monitor 0x00007f672003c100 (object 0x00000000f4c0c2c8, a org.apache.accumulo.tserver.tablet.Tablet),
  which is held by "Minor compacting +r<<"
"Minor compacting +r<<":
  waiting for ownable synchronizer 0x00000000f4c5cda8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "accumulo.pool.tabletserver.client-Worker-1"
"accumulo.pool.tabletserver.client-Worker-1":
  waiting to lock monitor 0x00007f672003c100 (object 0x00000000f4c0c2c8, a org.apache.accumulo.tserver.tablet.Tablet),
  which is held by "Minor compacting +r<<"

Java stack information for the threads listed above:
===================================================
"accumulo.pool.general.server-Worker-2":
	at org.apache.accumulo.tserver.tablet.Tablet.updateRates(Tablet.java:1146)
	- waiting to lock <0x00000000f4c0c2c8> (a org.apache.accumulo.tserver.tablet.Tablet)
	at org.apache.accumulo.tserver.TabletServer.lambda$new$0(TabletServer.java:288)
	at org.apache.accumulo.tserver.TabletServer$$Lambda$342/0x0000000840349c40.run(Unknown Source)
	at org.apache.accumulo.core.util.threads.NamedRunnable.run(NamedRunnable.java:41)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.25/Executors.java:515)
	at java.util.concurrent.FutureTask.runAndReset(java.base@11.0.25/FutureTask.java:305)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.25/ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.25/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.25/ThreadPoolExecutor.java:628)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.lang.Thread.run(java.base@11.0.25/Thread.java:829)
"Minor compacting +r<<":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.25/Native Method)
	- parking to wait for  <0x00000000f4c5cda8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.25/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.25/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.25/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.25/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.25/ReentrantLock.java:267)
	at org.apache.accumulo.tserver.tablet.Tablet.bringMinorCompactionOnline(Tablet.java:1562)
	at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:409)
	at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:114)
	at org.apache.accumulo.tserver.tablet.Tablet.completeClose(Tablet.java:966)
	- locked <0x00000000f4c0c2c8> (a org.apache.accumulo.tserver.tablet.Tablet)
	at org.apache.accumulo.tserver.tablet.Tablet.close(Tablet.java:787)
	at org.apache.accumulo.tserver.UnloadTabletHandler.run(UnloadTabletHandler.java:90)
	at org.apache.accumulo.tserver.TabletServerResourceManager.addMigration(TabletServerResourceManager.java:858)
	at org.apache.accumulo.tserver.TabletClientHandler.unloadTablet(TabletClientHandler.java:1078)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.25/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.25/Method.java:566)
	at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:203)
	at org.apache.accumulo.core.trace.TraceUtil$$Lambda$372/0x000000084035d040.invoke(Unknown Source)
	at com.sun.proxy.$Proxy27.unloadTablet(Unknown Source)
	at org.apache.accumulo.core.tablet.thrift.TabletManagementClientService$Processor$unloadTablet.getResult(TabletManagementClientService.java:347)
	at org.apache.accumulo.core.tablet.thrift.TabletManagementClientService$Processor$unloadTablet.getResult(TabletManagementClientService.java:325)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40)
	at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147)
	at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:50)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492)
	at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129)
	at org.apache.thrift.server.Invocation.run(Invocation.java:18)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.25/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.25/ThreadPoolExecutor.java:628)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.lang.Thread.run(java.base@11.0.25/Thread.java:829)
"accumulo.pool.tabletserver.client-Worker-1":
	at org.apache.accumulo.tserver.tablet.Tablet.refreshMetadata(Tablet.java:1684)
	- waiting to lock <0x00000000f4c0c2c8> (a org.apache.accumulo.tserver.tablet.Tablet)
	at org.apache.accumulo.tserver.tablet.Tablet$RefreshSession.refreshMetadata(Tablet.java:1634)
	at org.apache.accumulo.tserver.TabletClientHandler.refreshTablets(TabletClientHandler.java:1226)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.25/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.25/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.25/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.25/Method.java:566)
	at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:203)
	at org.apache.accumulo.core.trace.TraceUtil$$Lambda$372/0x000000084035d040.invoke(Unknown Source)
	at com.sun.proxy.$Proxy27.refreshTablets(Unknown Source)
	at org.apache.accumulo.core.tabletserver.thrift.TabletServerClientService$Processor$refreshTablets.getResult(TabletServerClientService.java:1596)
	at org.apache.accumulo.core.tabletserver.thrift.TabletServerClientService$Processor$refreshTablets.getResult(TabletServerClientService.java:1573)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40)
	at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147)
	at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:50)
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492)
	at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129)
	at org.apache.thrift.server.Invocation.run(Invocation.java:18)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.25/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.25/ThreadPoolExecutor.java:628)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.lang.Thread.run(java.base@11.0.25/Thread.java:829)

Found 1 deadlock.
```

**To Reproduce**

Repeatedly run ChaoticBalancerIT with the fixes in #5596 against 82e9891610b985edce604cebcc65dbf9029be3c1 until the test hangs then jstack the two tablet servers.

**Expected behavior**

No deadlock.

### PR DESCRIPTION
**Pull request by kevinrr888**
Resolves a deadlock in Tablet related code. Expected lock order is refreshLock -> logLock -> tablet, but `Tablet.completeClose()` would lock tablet -> refreshLock -> logLock, which could (and did) result in deadlocks. ChaoticBalancerIT would previously timeout almost every run. I ran it 10+ times with these changes with no deadlocks. I did not find any other situations where we do not acquire the locks in the order refreshLock -> logLock -> tablet, so Tablet code should now be deadlock free.

closes #5597

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 1]
```diff
@@ -937,70 +928,92 @@ synchronized void completeClose(boolean saveState) throws IOException {
...
-      }
     }
 
-    try {
-      getTabletMemory().getMemTable().delete(0);
-    } catch (Exception t) {
-      log.error("Failed to delete mem table : " + t.getMessage() + " for tablet " + extent, t);
+    if (shouldPrepMinC) {
+      // must not run while tablet is locked, as this may result in deadlocks
+      mct.run();
```
Comment (kevinrr888) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:981]: `MinorCompactionTask.run()` is done elsewhere as well, but other places do not have tablet locked when calling `run()`

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 2]
```diff
@@ -937,70 +928,92 @@ synchronized void completeClose(boolean saveState) throws IOException {
...
-          closeConsistencyCheck();
-          err = null;
-        } catch (RuntimeException t) {
-          err = t;
-          log.error("Consistency check fails, retrying", t);
-          sleepUninterruptibly(500, TimeUnit.MILLISECONDS);
+          mct = prepareForMinC(getFlushID(), MinorCompactionReason.CLOSE);
+        } catch (NoNodeException e) {
+          throw new RuntimeException("Exception on " + extent + " during prep for MinC", e);
         }
```
Comment (kevinrr888) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:975]: done while tablet is locked since all other uses of `getMemTable()` are done when tablet is locked. Also `prepareForMinC()` will lock tablet, so best to keep that call in the `sync (this)` block.

Comment (kevinrr888) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:975]: The only part moved out of the sync block in this PR is `mct.run()`

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 3]
```diff
@@ -1288,8 +1299,6 @@ public boolean beginUpdatingLogsUsed(InMemoryMap memTable, DfsLogger more, boole
 
     boolean releaseLock = true;
 
-    // Should not hold the tablet lock while trying to acquire the log lock because this could lead
-    // to deadlock. However there is a path in the code that does this. See #3759
```
Comment (kevinrr888) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:1292]: I don't think this is the case anymore. I think this can be deleted and #3759 can be closed

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 4]
```diff
@@ -937,70 +928,92 @@ synchronized void completeClose(boolean saveState) throws IOException {
...
-      getTabletMemory().getMemTable().delete(0);
-    } catch (Exception t) {
-      log.error("Failed to delete mem table : " + t.getMessage() + " for tablet " + extent, t);
+    if (shouldPrepMinC) {
+      // must not run while tablet is locked, as this may result in deadlocks
+      mct.run();
     }
 
-    getTabletMemory().close();
+    synchronized (this) {
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:984]:
```suggestion
    synchronized (this) {
      // gave up the lock to allow a minor compaction to run, now that the lock is reacquired validate that nothing unexpectedly changed
      Preconditions.checkState(closeState = CloseState.CLOSED, "closeState:%s extent:%s", closeState, extent)
      Preconditions.checkState(writesInProgress == 0, "writesInProgress:%s extent:%s", writesInProgress, extent);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java (hunk 1 above)
Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:981]: Normally minor compactions run concurrently w/ reads and writes. At this point in the code no more reads and writes should be happening so I think this code did the minor compaction in the synch block because it did not matter if reads and writes were blocked.  

It should be ok to run this outside of the sync block because the close state change at the top of this method should prevent any new reads or writes from starting and the code waited for ones in progress to complete.  Added a suggestion to check some things after the lock  is reacquired.
