### PR TITLE
Bug fix no scan id for batch scans

### LINKED ISSUE #4868: Batch scans do not set scan session id in listscans
**Describe the bug**
Batch scans always show a scan session id of zero in the listscans output.  This [code](https://github.com/apache/accumulo/blob/38952c922648014e74e4e7a5704bfa256f390faa/server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java#L497) sets the scan id for a normal scan.  However in the same class a bit later when it creates an ActiveScan object for a batch scan it does not set the session id.

**Expected behavior**

The session id is also set on batch scans. In addition to this it would be good to test this.  Maybe ScanIdIT should be improved to also test creating a batch scanner in the background in addition to the background scanners it creates.  If that test also ran batch scans it may have detected this problem.

### PR DESCRIPTION
**Pull request by kevinrr888**
closes #4868
- Batch scans scan ids are now set
- At the same time, got rid of code duplication and improved readability of `SessionManager.getActiveScans()`
- Added functionality to test this case in `ScanIdIT`

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java [hunk 1]
```diff
@@ -453,83 +453,73 @@ public List<ActiveScan> getActiveScans() {
...
-        MultiScanSession mss = (MultiScanSession) session;
+        final MultiScanSession mss = (MultiScanSession) session;
+        final KeyExtent extent = mss.threadPoolExtent;
+        final ScanType scanType = ScanType.BATCH;
+        final ScanParameters params = mss.scanParams;
+        final ScanState state = computeScanState(mss.getScanTask());
+        final long scanId = entry.getKey();
+
+        addActiveScan(activeScans, mss, extent, ct, scanType, state, params, scanId);
+      }
```
Comment (dlmarion) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java:483]: I''m wondering if this could be further simplified to:
```
  boolean isSingle =  session instanceof SingleScanSession;
  addActiveScan(activeScans,
    session,
    isSingle ? session.extent : ((MultiScanSession) session).threadPoolExtent,
    ct,
    isSingle ? ScanType.SINGLE : ScanType:BATCH,
    computeScanState(session.getScanTask()),
    session.params,
    entry.getKey());
```

Comment (kevinrr888) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java:483]: In the curr code, it only adds the active scan if it is MultiScanSession or SingleScanSession. In that case, it would cast as MultiScanSession if it is not a SingleScanSession.

A simplification that could be added to the curr code would be to just inline the params, if that is desired

Comment (kevinrr888) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java:483]: There are other subtypes

Comment (kevinrr888) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java:483]: Ah yeah, didn't see that both were subs of that. Will make the suggested change

File: server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java [hunk 2]
```diff
@@ -453,83 +453,64 @@ public List<ActiveScan> getActiveScans() {
...
+    }));
 
-      } else if (session instanceof MultiScanSession) {
-        MultiScanSession mss = (MultiScanSession) session;
+    return activeScans;
+  }
 
-        ScanState state = ScanState.RUNNING;
+  private ScanState computeScanState(ScanTask<?> scanTask) {
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java:480]: Nice to see this redundant code collapsed.

**Review by keith-turner — APPROVED** [review]
