### PR TITLE
Resize FaTE thread pool correctly, attempt at making sure it's constantly running

### LINKED ISSUE #2272: Fate thread pool property listed as ZK mutable but does not dynamically resize.
**Describe the bug**

The property `manager.fate.threadpool.size`is listed as ZK mutable in the documentation implying that changes to it should cause changes in a running system.  However looking at the following code that creates the thread pool, I can not find a place in the code that changes the thread pool size after its created.

https://github.com/apache/accumulo/blob/ba83d8fa26a8adc92ca0249780b1ddf9d7135d7a/core/src/main/java/org/apache/accumulo/fate/Fate.java#L228-L234

**Expected behavior**

The thread pool should dynamically resize or the documentation should be updated to indicate its not ZK mutable.

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #2272

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java [hunk 1]
```diff
@@ -29,33 +29,30 @@
...
-            count = newCount;
-          }
-        } catch (InterruptedException e) {
-          // throw a RuntimeException and let the AccumuloUncaughtExceptionHandler deal with it.
-          throw new RuntimeException("Thread " + threadName + " was interrupted.");
-        }
-      }
-    }).start();
-
+  public static void makeResizeable(final ThreadPoolExecutor pool, final AccumuloConfiguration conf,
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java:42]: This method name seems off w/ the changes.
```suggestion
  public static void resizePool(final ThreadPoolExecutor pool, final AccumuloConfiguration conf,
```

File: core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java [hunk 2]
```diff
@@ -29,33 +29,30 @@
...
+      final Property p) {
+    int count = pool.getMaximumPoolSize();
+    int newCount = conf.getCount(p);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java:45]: Thinking the following may avoid logging when there is nothing to do.

```suggestion
    int newCount = conf.getCount(p);
    if(count == newCount) 
       return;
```

File: core/src/main/java/org/apache/accumulo/fate/Fate.java [hunk 3]
```diff
@@ -226,11 +223,17 @@ public Fate(T environment, TStore<T> store, Function<Repo<T>,String> toLogStrFun
...
-      executor.execute(new TransactionRunner());
-    }
+    final ThreadPoolExecutor pool = (ThreadPoolExecutor) ThreadPools.createExecutorService(conf,
+        Property.MANAGER_FATE_THREADPOOL_SIZE);
+    fatePoolWatcher = ThreadPools.createGeneralScheduledExecutorService(conf);
+    fatePoolWatcher.schedule(() -> {
+      ThreadPools.makeResizeable(pool, conf, Property.MANAGER_FATE_THREADPOOL_SIZE);
+      int remaining = 1000 - pool.getQueue().size();
+      for (int i = 0; i < remaining; i++) {
+        pool.execute(new TransactionRunner());
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/fate/Fate.java:233]: This may throw a bunch of exceptions if the pool is shutdown.  Would be nice to avoid that.  Could wait for `fatePoolWatcher` to shutdown before calling `executor.shutdown()` in the shutdown() method below in this class.  That might avoid the exceptions here.

Alternatively could catch rejectedexecutionexception here and ignore it if the pool is shutdown.

File: core/src/main/java/org/apache/accumulo/fate/Fate.java [hunk 4]
```diff
@@ -226,11 +223,17 @@ public Fate(T environment, TStore<T> store, Function<Repo<T>,String> toLogStrFun
...
    */
   public void startTransactionRunners(AccumuloConfiguration conf) {
-    int numThreads = conf.getCount(Property.MANAGER_FATE_THREADPOOL_SIZE);
-    executor = ThreadPools.createExecutorService(conf, Property.MANAGER_FATE_THREADPOOL_SIZE);
-    for (int i = 0; i < numThreads; i++) {
-      executor.execute(new TransactionRunner());
-    }
+    final ThreadPoolExecutor pool = (ThreadPoolExecutor) ThreadPools.createExecutorService(conf,
+        Property.MANAGER_FATE_THREADPOOL_SIZE);
+    fatePoolWatcher = ThreadPools.createGeneralScheduledExecutorService(conf);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/fate/Fate.java:228]: The Accumulo servers used to have a shared timer pool.  Not sure if that is still a thing, if it is could be used to avoid creating these watcher threads.

File: core/src/main/java/org/apache/accumulo/fate/Fate.java [hunk 5]
```diff
@@ -226,11 +223,17 @@ public Fate(T environment, TStore<T> store, Function<Repo<T>,String> toLogStrFun
...
+    fatePoolWatcher.schedule(() -> {
+      ThreadPools.makeResizeable(pool, conf, Property.MANAGER_FATE_THREADPOOL_SIZE);
+      int remaining = 1000 - pool.getQueue().size();
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/fate/Fate.java:231]: Could replace 1000 w/ a function of the numThreads and time like below.

```suggestion
      // Assume a thread could execute up to 100 operations a second.  We are sleeping for three seconds. So to calculate max to queue do 3* 100 * numThreads. 
      int maxToQueue = 300 * conf.getCount(  Property.MANAGER_FATE_THREADPOOL_SIZE);
      int remaining = 1000 - pool.getQueue().size();
```

File: core/src/main/java/org/apache/accumulo/fate/Fate.java (hunk 4 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:228]: I looked back in 1.10 for shared SimpleTimer's. Please let me know if you happen to have a location on this as I would be interested to see if I missed something when I did the Threads/ThreadPools work. In this specific case, only 1 scheduled runnable is going to be created as `startTransactionRunners` is only called once in Manager.run().

File: core/src/main/java/org/apache/accumulo/fate/Fate.java (hunk 5 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:231]: Thanks for this, I wasn't sure what a reasonable value would be.

File: core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java]: I included this in 8bed9e5.

File: core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java (hunk 2 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/util/threads/ThreadPools.java]: I included this in 8bed9e5.

File: core/src/main/java/org/apache/accumulo/fate/Fate.java (hunk 3 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java]: I addressed this in 8bed9e5.

File: core/src/main/java/org/apache/accumulo/fate/Fate.java (hunk 5 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java]: I included this in 8bed9e5.

File: core/src/main/java/org/apache/accumulo/fate/Fate.java [hunk 6]
```diff
@@ -226,11 +224,26 @@ public Fate(T environment, TStore<T> store, Function<Repo<T>,String> toLogStrFun
...
+      // Assume a thread could execute up to 100 operations a second.
+      // We are sleeping for three seconds. So to calculate max to queue do 3* 100 * numThreads.
+      int maxToQueue = 300 * conf.getCount(Property.MANAGER_FATE_THREADPOOL_SIZE);
+      int remaining = maxToQueue - pool.getQueue().size();
+      for (int i = 0; i < remaining; i++) {
+        try {
+          pool.execute(new TransactionRunner());
+        } catch (RejectedExecutionException e) {
+          // RejectedExecutionException could be shutting down
+          log.warn("Error adding transaction runner to FaTE executor pool.");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/fate/Fate.java:241]: I think if its shutdown we can avoid spamming the logs.  If its not shutdown, then its really bad and we should include the exception.  For the case where its not shutdown, should we log an error or rethrow the exception?

```suggestion
      if(pool.isShutdown()){
          // The exception is expected in this case, no need to spam the logs.
          log.trace("Error adding transaction runner to FaTE executor pool.",e);
       } else {
        // This is bad, FaTE may no longer work!
         log.error("Error adding transaction runner to FaTE executor pool.",e);
       }
```

File: server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java [hunk 7]
```diff
@@ -323,16 +323,11 @@ public static ThreadPoolExecutor createSelfResizingThreadPool(final String serve
...
-        pool.setCorePoolSize(larger);
+        ThreadPools.resizePool(pool, () -> larger, serverName + "-ClientPool");
       } else {
         if (pool.getCorePoolSize() > pool.getActiveCount() + 3) {
           int smaller = Math.max(executorThreads, pool.getCorePoolSize() - 1);
-          if (smaller != pool.getCorePoolSize()) {
-            log.info("Decreasing server thread pool size on {} to {}", serverName, smaller);
-            pool.setCorePoolSize(smaller);
-          }
+          ThreadPools.resizePool(pool, () -> smaller, serverName + "-ClientPool");
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java:330]: So, it would [appear](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/util/concurrent/ThreadPoolExecutor.java#L1533) that lowering the corePoolSize below the MaxPoolSize throws an error. Maybe this is what you were referring to?

[the remark this answers is not in the document]
Comment (keith-turner) [reply server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java:330]: I just noticed that this code was no longer making the same method calls on the thread pool that it used to make, however I was not sure if that change mattered.

[the remark this answers is not in the document]
Comment (keith-turner) [reply server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java:330]: Do you think the existing code before your change had a bug?

[the remark this answers is not in the document]
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java:330]: Right, it's now using the common way of doing the resizing.

[the remark this answers is not in the document]
Comment (keith-turner) [reply server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java:330]: hmm so maybe this code never achieved its intent.. I wonder if it only increased but never decreased

[the remark this answers is not in the document]
Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java:330]: I can't say about before my change, but in ThreadPools.java as it is now, if the thread pool was created with a pool size of 5 and no max pool specified, then the max pool size would also be set to 5. If the core pool size was then decreased, it would error.

File: core/src/main/java/org/apache/accumulo/fate/Fate.java (hunk 4 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:229]: Looking back at 1.10 I See the following which created a singleton timer that was shared in the process with a configurable number of threads.

https://github.com/apache/accumulo/blob/bbe2de8a8c00eb0b7cc01766ac6e6db672bf8444/server/base/src/main/java/org/apache/accumulo/server/util/time/SimpleTimer.java#L60-L71

AFAICT now in 2.1.0 there is no longer a process wide singleton timer related to the config `general.server.simpletimer.threadpool.size`?

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:229]: That was my concern, that maybe I missed that. However, now that the creation of that ThreadPool is singularly located in `ThreadPools.createGeneralScheduledExecutorService`, it should be easy to make it a singleton that is only created if it does not already exist. It's called from 33 locations across the code base.

**Review by keith-turner — APPROVED** [review]

File: core/src/main/java/org/apache/accumulo/fate/Fate.java (hunk 4 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:229]: It is used by the TabletServerBatchWriter. I think putting it on the ServerContext would render that unreachable.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:229]: I might be able to put it on AccumuloConfiguration.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/fate/Fate.java:229]: > It is used by the TabletServerBatchWriter. I think putting it on the ServerContext would render that unreachable.

May make sense to have it in the client context for client side code.  Server context extends client context, so maybe that would work out nicely.

**Comment by milleruntime** [comment]
I think this change still might be a problem. It is causing some of our previously stable ITs to timeout. I am not sure why but they were fine before the initial commit of https://github.com/apache/accumulo/pull/2274. The two ITs timing out are MergeIT and ShellServerIT
