### PR TITLE
Fix ConcurrentModificationException in QueueMetrics

### LINKED ISSUE #4144: Concurrent modification exception in manager
Seeing the following exception in the manager logs when running a version of Accumulo built from the elasticity branch.

```
024-01-09T17:28:25,129 [threads.ThreadPools] ERROR: Non-critical scheduled background task failed
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.apache.accumulo.core.util.threads.ThreadPools.checkTaskFailed(ThreadPools.java:125) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.util.threads.ThreadPools.lambda$static$0(ThreadPools.java:95) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.apache.accumulo.core.util.threads.ThreadPools.lambda$static$1(ThreadPools.java:92) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511) ~[?:?]
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1534) ~[?:?]
        at com.google.common.collect.Sets$3$1.computeNext(Sets.java:907) ~[guava-33.0.0-jre.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[guava-33.0.0-jre.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[guava-33.0.0-jre.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
        at org.apache.accumulo.manager.compaction.coordinator.QueueMetrics.update(QueueMetrics.java:142) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        ... 4 more

```

### PR DESCRIPTION
**Pull request by dlmarion**
The metricsWithoutQueues variable is a SetView
which is sensitive to changes in the underlying
sets. The loop was modifying one of the underlying objects. To prevent the CME from being raised I
copied the objects into a new set.

Closes #4144

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java [hunk 1]
```diff
@@ -139,7 +140,16 @@ public void update() {
 
     SetView<CompactorGroupId> metricsWithoutQueues =
         Sets.difference(queuesWithMetrics, definedQueues);
-    metricsWithoutQueues.forEach(q -> {
+    Set<CompactorGroupId> toRemove = new HashSet<>(metricsWithoutQueues.size());
+    for (CompactorGroupId orig : metricsWithoutQueues) {
+      try {
+        toRemove.add(orig.clone());
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java:146]: Why does the id need to be cloned?

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java [hunk 2]
```diff
@@ -139,7 +140,16 @@ public void update() {
 
     SetView<CompactorGroupId> metricsWithoutQueues =
         Sets.difference(queuesWithMetrics, definedQueues);
-    metricsWithoutQueues.forEach(q -> {
+    Set<CompactorGroupId> toRemove = new HashSet<>(metricsWithoutQueues.size());
```
Comment (ddanielr) [inline server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java:143]: If you used [copyInto](https://guava.dev/releases/23.0/api/docs/com/google/common/collect/Sets.SetView.html#copyInto-S-) would that still require the cloning functionality for `CompactorGroupId`?

Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/QueueMetrics.java:143]: There is another loop above this that is modifying perQeueMetrics while iterating over a set view that is based on it.  Maybe doing that following at the beginning of the method would avoid the problem for both loops.

```java
Set<CompactorGroupId> queuesWithMetrics = Set.copyOf(perQueueMetrics.keySet());
```

**Review by keith-turner — APPROVED** [review]
