### PR TITLE
Change Wait.waitFor to throw IllegalStateException

### LINKED ISSUE #3564: Wait.waitFor(Condition) return value not checked
**Describe the bug**
A lot of test code calls `Wait.waitFor(Condition)` and does not check its return value.  I had assumed this method would wait forever, but it does not it only waits for 30 seconds and then returns false.

**Expected behavior**

Either test code checks the return value OR remove the return value and make the method wait forever.  I am in favor of waiting forever and letting junit timeout the test as it makes test code easier to write.

### PR DESCRIPTION
**Pull request by EdColeman**
- Instead of returning a boolean with the condition status, throw an IllegalStateException if the condition
is not satisfied after the wait period expires.

- Fixes #3564

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java [hunk 1]
```diff
@@ -520,10 +520,12 @@ public void setIterOptionPrompt() throws Exception {
 
   protected void checkTableForProperty(final AccumuloClient client, final String tableName,
       final String expectedKey, final String expectedValue) throws Exception {
-    assertTrue(
-        Wait.waitFor(() -> client.tableOperations().getConfiguration(tableName).get(expectedKey)
-            .equals(expectedValue), 5000, 500),
-        "Failed to find expected value for key: " + expectedKey);
+    try {
```
Comment (cshannon) [inline test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java:523]: This seems like a step backwards in terms of usage. The original issue commented on making it easier to use the Wait api but having to now use a try/catch makes this pretty ugly. Maybe instead of replacing the behavior that returns false we could have an additional method (or flag) that supports throwing the exception so we support both ways depending on what the unit test writer wants to do.

**Review by cshannon — CHANGES_REQUESTED** [review]

File: test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java (hunk 1 above)
Comment (EdColeman) [reply test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java:523]: This one place had an exception message that I thought would be nice to keep - all other occurrences where just failing when they used assertTrue and there were some that did not test the return condition.

Keeping the exception message in this single case if its not adding much.

Comment (cshannon) [reply test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java:523]: Maybe we could provide an option to provide an error message for the IllegalStateException then? I feel like this is going to come up again where we want to have a custom error message that is thrown. So we should just allow providing the message for the IllegalStateException as an option with an overloaded method.

Comment (cshannon) [reply test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java:523]: Could just add a method that is something like the following and the existing method can just have a default.

```Java
public static void waitFor(final Condition condition, final long duration, final long sleepMillis, String errorMsg)
      throws Exception {
//pass error message to new IllegalStateException()
}
```

File: test/src/main/java/org/apache/accumulo/test/util/Wait.java [hunk 2]
```diff
@@ -29,23 +29,37 @@ public interface Condition {
...
   }
 
-  public static boolean waitFor(final Condition condition, final long duration,
-      final long sleepMillis) throws Exception {
+  /**
+   * Wait for the provided condition - will throw an IllegalStateException is the wait exceeds the
+   * wait period.
+   */
+  public static void waitFor(final Condition condition, final long duration, final long sleepMillis)
+      throws Exception {
```
Comment (cshannon) [inline test/src/main/java/org/apache/accumulo/test/util/Wait.java:53]: Also I think you should be able to get rid of the throws Exception here if just throwing a runtime exception only

Comment (EdColeman) [reply test/src/main/java/org/apache/accumulo/test/util/Wait.java:53]: The exception from `condition.isSatisfied()` needs to be declared, or turned into a Runtime exception - otherwise it is bubbling up through the waitFor calls - and the InterruptedException is not being specifically handled.

Comment (EdColeman) [reply test/src/main/java/org/apache/accumulo/test/util/Wait.java]: Addressed in 0031099059

File: test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java (hunk 1 above)
Comment (EdColeman) [reply test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java]: Added in 0031099059

**Review by keith-turner — APPROVED** [review]

**Review by cshannon — APPROVED** [review]
LGTM
