### PR TITLE
Always balance root and metadata tables

### LINKED ISSUE #4515: Unhosted user tablets prevent balancing of metadata table
**Describe the bug**

When starting accumulo and assigning lots of tablets if the metadata table is not initially balanced then it will be prevented from balancing.  This can leave the metadata tablets on much less tablet servers than possible at a time when the system is busy assigning and loading user tablets which generates a lot of load on the metadata table.

Overall this seems to be caused by the fact that the code related to balancing does not consider the different levels of Accumulo.

#4475 is related to this larger problem.  The specific code that prevents balancing is [here](https://github.com/apache/accumulo/blob/acaa6dc46c4fae548889ca20f32cc7cb36b9f406/server/manager/src/main/java/org/apache/accumulo/manager/Manager.java#L871), but fixing this issue would be a larger change that just that code. 

This problem is present in 2.1 and later.

**Expected behavior**

The manager can balance the metadata table independently of what is going on with user tables.

### PR DESCRIPTION
**Pull request by dlmarion**
Fixes #4515

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 1]
```diff
@@ -958,23 +956,47 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+      Map<DataLevel,Set<KeyExtent>> partitionedMigrations =
+          new HashMap<>(DataLevel.values().length);
+      migrationsSnapshot().forEach(ke -> {
+        partitionedMigrations.computeIfAbsent(DataLevel.of(ke.tableId()), f -> new HashSet<>())
+            .add(ke);
+      });
+
+      BalanceParamsImpl params = null;
+      long wait = 0;
+      for (DataLevel dl : new DataLevel[] {DataLevel.ROOT, DataLevel.METADATA, DataLevel.USER}) {
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:970]:
```suggestion
      for (DataLevel dl : DataLevel.values()) {
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 2]
```diff
@@ -958,23 +956,47 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+            }
+            TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
+            migrations.put(ke, tserverInstance);
+            log.debug("migration {}", m);
+          }
+        } while (!params.migrationsOut().isEmpty()
+            && (dl == DataLevel.ROOT || dl == DataLevel.METADATA));
       }
-      if (params.migrationsOut().isEmpty()) {
+      if (params == null || params.migrationsOut().isEmpty()) {
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:999]: Could sum up the migrationOut sizes in the loop and look at that sum here.  This will look at the migrations for the last level balanced.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 3]
```diff
@@ -958,23 +956,47 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+            KeyExtent ke = KeyExtent.fromTabletId(m.getTablet());
+            if (migrations.containsKey(ke)) {
+              log.warn("balancer requested migration more than once, skipping {}", m);
+              continue;
+            }
+            TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
+            migrations.put(ke, tserverInstance);
+            log.debug("migration {}", m);
+          }
+        } while (!params.migrationsOut().isEmpty()
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:996]: Wondering if this while loop could get stuck forever on a level w/ a balancer that is constantly flapping.  This method is called periodically, if there are more migrations they will be worked on the next method call.  The next method call will hit all of the levels if this while loop is not here.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 4]
```diff
@@ -958,23 +956,47 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+      BalanceParamsImpl params = null;
+      long wait = 0;
+      for (DataLevel dl : new DataLevel[] {DataLevel.ROOT, DataLevel.METADATA, DataLevel.USER}) {
+        Set<KeyExtent> migrationsForLevel = partitionedMigrations.get(dl);
+        if (migrationsForLevel == null) {
+          continue;
+        }
+        if (dl == DataLevel.USER && !balanceUserTables) {
+          log.debug("not balancing user tablets because there are {} unhosted tablets",
+              notHosted());
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:977]: Could drop the boolean passed to the method and call notHosted here.  Then the log stmt can print the value that was used to make the decision.

```suggestion
        int  notHostedCount = notHosted();
        if (dl == DataLevel.USER && notHostedCount > 0) {
          log.debug("not balancing user tablets because there are {} unhosted tablets",
              notHostedCount);
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 5]
```diff
@@ -958,23 +956,47 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
           continue;
         }
-        TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
-        migrations.put(ke, tserverInstance);
-        log.debug("migration {}", m);
+        params = BalanceParamsImpl.fromThrift(tserverStatusForBalancer, tserverStatus,
+            migrationsSnapshot());
+        do {
+          log.debug("Balancing for tables at level: {}", dl);
+          wait = tabletBalancer.balance(params);
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:984]:
```suggestion
          wait = Math.max(tabletBalancer.balance(params), wait);
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:970]: I didn't use `values()` because I wanted a specific order. In theory, the order could change in future releases for some reason.

Comment (keith-turner) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:970]: Doing them in a specific order is nice, could add a comment about that.

Comment (keith-turner) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:970]: Another way to tackle this is to add a unit test that ensures the order of DataLevel.values() is `DataLevel.ROOT, DataLevel.METADATA, DataLevel.USER`.  Seems generally useful to work things in that order.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:970]: Good point. My implementation doesn't account for any future values added to DataLevel.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 3 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:996]: I think it will only get stuck if it's the root or metadata table flapping. In which case, we may want this.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 5 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Implemented in 26a4939

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 4 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Implemented in 26a4939

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Implemented in 26a4939

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 2 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Implemented in 26a4939

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 6]
```diff
@@ -959,27 +957,54 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+            KeyExtent ke = KeyExtent.fromTabletId(m.getTablet());
+            if (migrations.containsKey(ke)) {
+              log.warn("balancer requested migration more than once, skipping {}", m);
+              continue;
+            }
+            TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
+            migrations.put(ke, tserverInstance);
+            log.debug("migration {}", m);
+          }
+        } while (totalMigrationsOut > 0 && (dl == DataLevel.ROOT || dl == DataLevel.METADATA));
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:999]: Not seeing `totalMigrationsOut` being modified inside the loop, so if its greater than zero when entering loop seems like it will stay that way.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 7]
```diff
@@ -959,27 +957,54 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+        if (dl == DataLevel.USER && tabletsNotHosted > 0) {
+          log.debug("not balancing user tablets because there are {} unhosted tablets",
+              tabletsNotHosted);
           continue;
         }
-        TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
-        migrations.put(ke, tserverInstance);
-        log.debug("migration {}", m);
+        params = BalanceParamsImpl.fromThrift(tserverStatusForBalancer, tserverStatus,
+            migrationsSnapshot());
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:983]: Seems like this should be the migrations for the level.

```suggestion
            migrationsForLevel);
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 8]
```diff
@@ -959,27 +957,54 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+        totalMigrationsOut += params.migrationsOut().size();
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:984]: Seems like migrations out would always be empty here because the balancer was not called yet.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 9]
```diff
@@ -959,27 +957,54 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+        do {
+          log.debug("Balancing for tables at level: {}", dl);
+          wait = Math.max(tabletBalancer.balance(params), wait);
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:987]: If the loop is being called a 2nd time, may need to reset params in order to reset migrations out.

**Comment by dlmarion** [comment]
@keith-turner  - good catch on these latest comments. I had some things outside of the loop that should have been inside of it.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 6 above)
Comment (keith-turner) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:998]: There still seems to be a problem here although a bit different with the changes in 1010954.  If the following happens it seems we will be stuck in an infinite loop.

 * data level is root
 * on iteration of loop `totalMigrationsOut` is set to 5
 * on all subsequent iterations of the loop  `totalMigrationsOut`  continue to be 5, its no longer increasing.

This happens because the loop only adds to `totalMigrationsOut`

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 10]
```diff
@@ -959,27 +957,53 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
+        if (dl == DataLevel.USER && tabletsNotHosted > 0) {
+          log.debug("not balancing user tablets because there are {} unhosted tablets",
+              tabletsNotHosted);
           continue;
         }
-        TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
-        migrations.put(ke, tserverInstance);
-        log.debug("migration {}", m);
+        log.debug("Balancing for tables at level: {}", dl);
+        do {
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:983]: Wondering if the order of the following should be flipped.  Thinking that could make it more apparent if the code is hanging out in this loop. 

```suggestion
        do {
             log.debug("Balancing for tables at level: {}", dl);
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 3 above)
Comment (keith-turner) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: > I think it will only get stuck if it's the root or metadata table flapping. In which case, we may want this.

It would be nice to have that for the metadata table, it could possibly cause new problems in a bug fix release though.  Thinking if we have sufficient logging to know if a thread ever does end up hanging out in this loop that would help debug any potential problems.  Made a comment elsewhere about tweaking some logging.  

So ss long as we can debug when code is stuck in this loop, I think its a nice change to make.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 10 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Changed location of log level in ce31896

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 6 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: In ce31896 I added another migration out variable for the inner loop, then added that to the total variable.

**Review by keith-turner — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 11]
```diff
@@ -959,27 +957,57 @@ private void checkForHeldServer(SortedMap<TServerInstance,TabletServerStatus> ts
...
           continue;
         }
-        TServerInstance tserverInstance = TabletServerIdImpl.toThrift(m.getNewTabletServer());
-        migrations.put(ke, tserverInstance);
-        log.debug("migration {}", m);
+        long migrationsOutForLevel = 0;
+        int i = 0;
+        do {
+          i++;
+          log.debug("Balancing for tables at level {}, times-in-loop: {}", dl, i);
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:986]: The times in loop info is nice, w/o it would have to dig through logs and look for changes in level.
