### PR TITLE
Modified TabletsMetadata to run filters on root tablet

### LINKED ISSUE #5643: Error checking if migration should be cleaned up
**Describe the bug**
Saw the following in the Manager log
```
2025-06-13T16:55:05,140 [manager.Manager] ERROR: Error cleaning up migrations
java.lang.IllegalStateException: This method should only be called if there is a migration
        at com.google.common.base.Preconditions.checkState(Preconditions.java:513) ~[guava-33.4.6-jre.jar:?]
        at org.apache.accumulo.manager.Manager.shouldCleanupMigration(Manager.java:586) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.Manager$MigrationCleanupThread.run(Manager.java:568) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.util.threads.Threads.lambda$createCriticalThread$0(Threads.java:76) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

There is either an error in the HasMigrationFilter that is run as part of the Ample query, or the migration was removed after the filter ran, but before the TabletMetadata was returned, by some other process.

### PR DESCRIPTION
**Pull request by dlmarion**
Filters on TabletMetadata were not being applied to the root tablet metadata causing an exception in in Manager.shouldCleanupMigration. The code was applying a filter to only return tablet metadata that contained a migration, then checking that the migration was not null. Because the filter was not being applied to the root tablet, it was being returned as matching the filter but with no migration.

Applying the fix in TabletsMetadata to run the filter on the root tablet metadata caused a subsequent issue in the GcWalsFilter where acceptTablet() would return null. Modified TabletMetadataFilter to protect against this condition.

Closes #5643

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java [hunk 1]
```diff
@@ -126,8 +131,19 @@ public TabletsMetadata build() {
...
+        if (!tabletMetadataFilters.isEmpty()) {
+          for (var filter : tabletMetadataFilters) {
+            if (!filter.acceptRow(iter)) {
+              LOG.trace("Not returning root metadata as it does not pass filter: {}",
+                  filter.getClass().getSimpleName());
+              return new TabletsMetadata((AutoCloseable) null, Set.of());
+            }
+          }
+        }
+        return new TabletsMetadata(rtm.toTabletMetadata());
```
Comment (kevinrr888) [inline core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: I'm not sure if this is working as expected
This only returns either the entire root tablet metadata or nothing. Shouldn't there be a case with some of the data filtered out?

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: This could also use some testing if we have a TabletsMetadata test

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: I can look at adding tests. Regarding correctness, I think it's correct to not return tablet metadata when the filter returns `false`. I don't believe that the filtering mechanism filters out keys within tablet metadata.

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: Oh, I guess my confusion was because in the other cases we have multiple `TabletMetadata` within the `TabletsMetadata`, so we filter out by each `TabletMetadata` but in the ROOT metadata case, there's just one `TabletMetadata` (`RootTabletMetadata`), so we either return nothing or the RTM.

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: Thinking this looks good then, but yeah tests would be good.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: > so we either return nothing or the RTM

Yes, I think that's correct. If the code is using a filter, then it's looking for where a condition exists. So it's failing when the tablet metadata is returned and that condition does not exist.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: > Thinking this looks good then, but yeah tests would be good.

The only test I can find for TabletsMetadata are one test in AmpleIT. I'll see if I can add to it.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: I added at IT in d421c0b, but two of the methods are not working as expected, and I'm not sure why. Specifically, the `testTabletsMetadataMetadataFilter` and `testTabletsMetadataUserFilter` are failing in that the first TabletsMetadata call in both methods is not returning data.

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: I'll look into this as well

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: I figured it out. Pushing an update here in a few minutes

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: great!

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: changes pushed

File: core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java [hunk 2]
```diff
@@ -126,13 +133,39 @@ public TabletsMetadata build() {
...
 
+    // visible for testing
+    protected RootTabletMetadata getRootMetadata(AccumuloClient client) {
+      return RootTabletMetadata.read((ClientContext) client);
+    }
+
+    private TabletsMetadata buildRoot(AccumuloClient client) throws IOException {
+      final RootTabletMetadata rtm = getRootMetadata(client);
+      if (!tabletMetadataFilters.isEmpty()) {
+        final SortedMapIterator iter = new SortedMapIterator(rtm.toKeyValues());
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: probably need to use ColumnFamilySkippingIterator to skip column fams

File: core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java [hunk 3]
```diff
@@ -150,7 +183,8 @@ private TabletsMetadata buildExtents(AccumuloClient client) {
 
       for (DataLevel level : groupedExtents.keySet()) {
         if (level == DataLevel.ROOT) {
-          iterables.add(() -> Iterators.singletonIterator(getRootMetadata((ClientContext) client)));
+          iterables.add(() -> Iterators
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java]: should this use the new buildroot function?
