### PR TITLE
Rewrote testFatePrintAndSummaryCommandsWithInProgressTxns for elasticity

### LINKED ISSUE #4614: Integeration test testFatePrintAndSummaryCommandsWithInProgressTxns was dropped in merge
**Describe the bug**

When merging main into elasticity in 9144377ba57350b176778b2c2e43a396d86bfa20, dropped the integration test FateSummaryIT.testFatePrintAndSummaryCommandsWithInProgressTxns from #4556.  Would still be good to have this test, but it was not working so need to look into recreating it for elasticity.  Tried the following while trying to merge before dropping the test.

 * In #4350 FateSummaryIT was moved into FateOpsCommandsIT.  So tried manually copying the test there.
 * The test would stop all compactors, but in elasticity compactors are required to run compaction.  So removed the code that was stopping compactors.

After doing the above the test would not run successfully.  Looking into it a bit I suspect that 500 compactions against the same tablet do not run as quickly as they did in 3.1 and 2.1 for multiple reasons.  So maybe this reduces the likelyhood of catching a race condition when running the command, but not sure about this.  May need to start concurrent compactions against different tablets in elasticity so they can run concurrently.

A more general problem with the test is that it does not work with the multiple fate stores.   

Since the test was not passing in its current form and seemed like it needed a good bit of work, decided to move forward with a merge w/o it and open this issue.

**Expected behavior**

The behavior of the fate command ignoring race conditions is tested.

### PR DESCRIPTION
**Pull request by kevinrr888**
closes #4614

Rewrote the test `testFatePrintAndSummaryCommandsWithInProgressTxns` for elasticity which was merged in from https://github.com/apache/accumulo/pull/4631 to 2.1 and main. This is essentially the same for the test of META transactions as it is in 2.1/main. However, for USER transactions (which are stored in a table not in ZK like in 2.1/main), I simulate a transaction returning an UNKNOWN status in `AdminUtil.getTransactionStatus()` (which is what would occur if the transaction has completed since aquiring the list of transactions) and ensure this transaction is included in the returned value and does not cause any errors.

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsIT.java [hunk 1]
```diff
@@ -592,6 +610,124 @@ protected void testFateDeleteCommand(FateStore<TestEnv> store, ServerContext sct
...
+    FateId tx2 = mockedStore.create();
+    FateId tx3 = mockedStore.create();
+    // Mock list() to ensure same order every run
+    List<ReadOnlyFateStore.FateIdStatus> fateIdStatusList =
+        List.of(createFateIdStatus(tx1), createFateIdStatus(tx2), createFateIdStatus(tx3));
+    expect(mockedStore.list()).andReturn(fateIdStatusList.stream()).once();
+
+    ReadOnlyFateStore.ReadOnlyFateTxStore<TestEnv> mockedFateTxStore1, mockedFateTxStore2,
+        mockedFateTxStore3;
+    if (isUserStore) {
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsIT.java:661]: Opened #4688 after looking at this test because it highlighted that the behavior of the two fate stores is different.  If get #4688 is merged then this test could possibly be simplified alot because it can assume a single behavior instead of accommodating two.

Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/fate/FateOpsCommandsIT.java:661]: yes, that is a nice change

**Comment by kevinrr888** [comment]
From https://github.com/apache/accumulo/pull/4688, `MetaFateStore.FateTxStoreImpl.top()` was changed to no longer throw a NNE and instead return null. I checked to see if any of the other methods called in the try-catch block of `getTransactionStatus()` could throw a NNE and they do not. `top()` was the only method that did not handle and threw the NNE if encountered. So, the original issue of a NNE exception occurring in `getTransactionStatus()` causing the print/summary commands to fail is no longer a problem in elasticity (from what I can tell). So, now the check for a NNE exception in `getTransactionStatus()` is unneccessary but doesn't hurt to keep in case of future changes to `MetaFateStore.FateTxStoreImpl` resulting in these methods throwing a NNE. For `testFatePrintAndSummaryCommandsWithInProgressTxns()`, I mock that the NNE can occur in the try-catch block (even though this won't happen in the current implementation) and ensure that it is properly handled.

**Comment by keith-turner** [comment]
From a tech debt perspective it may be best to remove the handling of NoNodeException from AdminUtil since its not expected to happen now.  Having the handling for NoNodeException may cause someone to spend time carrying it forward when refactoring AdminUtil, which would be uneeded work.  If we remove the handling for NNE, not sure there is anything to test.  We have the test for the fate stores to verify they handle the non-existent case in a uniform way.  It would probably be good to put those expectations in the javadoc on the fate store interfaces, but that is not something for this PR.  Wondering if this PR should be abandoned or changed to remove the NNE handling.

**Comment by keith-turner** [comment]
Maybe there is something to test for this changes still if NNE handling is removed.  We want to test that admin util handles the case of something showing up in list and then no longer existing when its accessed.  Just want to ensure that admin util code does not fail in that case or report junk.

**Comment by kevinrr888** [comment]
Yeah, I wasn't sure how I would test it after removal of the NNE handling in AdminUtil and wasn't sure if this handling would be better left in or removed. I have just removed the NNE handling in AdminUtil and reworked the test. Now, the test ensures AdminUtil.getTransactionStatus() functions as expected if there is a FateId returned from the list() command that doesn't exist. This simplified the test a lot too.

**Review by keith-turner — APPROVED** [review]
