### PR TITLE
Moved CloneIT out of simple suite

### LINKED ISSUE #5783: Broken test: CloneIT_SimpleSuite.testClonedMarker
Test succeeds when run by itself, but not when run as part of SimpleSharedMacTestSuiteIT. Test is failing with the following trace:

```
java.lang.IllegalStateException: No prev endrow seen.  tableId: 0 endrow: m
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.getPrevEndRow(TabletMetadata.java:489)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.lambda$new$1(TabletMetadata.java:191)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:198)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.getExtent(TabletMetadata.java:479)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.validate(TabletMetadata.java:861)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata$Builder.build(TabletMetadata.java:1036)
	at org.apache.accumulo.core.metadata.schema.TabletMetadata.convertRow(TabletMetadata.java:812)
	at org.apache.accumulo.core.metadata.schema.TabletsMetadata$Builder.lambda$buildNonRoot$11(TabletsMetadata.java:304)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:828)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:51)
	at org.apache.accumulo.core.metadata.schema.LinkingIterator.next(LinkingIterator.java:147)
	at org.apache.accumulo.core.metadata.schema.LinkingIterator.next(LinkingIterator.java:50)
	at org.apache.accumulo.server.util.MetadataTableUtil.checkClone(MetadataTableUtil.java:297)
	at org.apache.accumulo.test.CloneIT_SimpleSuite.testClonedMarker(CloneIT_SimpleSuite.java:383)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### PR DESCRIPTION
**Pull request by ArbaazKhan1**
closes [issue #5783 ](https://github.com/apache/accumulo/issues/5783)

It seems CloneIT fail 50% of the time while in simple Suite and passes when outside of it. There may be some issues with table name management while being run in a shared cluster environment.

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/CloneIT.java [hunk 1]
```diff
@@ -57,7 +57,7 @@
 import org.junit.jupiter.params.provider.ArgumentsProvider;
 import org.junit.jupiter.params.provider.ArgumentsSource;
 
-public class CloneIT_SimpleSuite extends SharedMiniClusterBase {
+public class CloneIT extends SharedMiniClusterBase {
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/CloneIT.java:60]: Are the other changes necessary for this test to consistently pass? On first glance it seems like this line is the only necessary change, if it was failing due to being in simple suite when it shouldn't have been

Comment (ArbaazKhan1) [reply test/src/main/java/org/apache/accumulo/test/CloneIT.java:60]: I just checked and the changes are not necessary. The test passes without them

**Review by kevinrr888 — APPROVED** [review]
Looking at the test, I couldn't find anything that would cause this to fail as part of the simple suite but I could just be missing something.

If the simple suite occasionally failed previously, but now always passes I have no issues with this change.
