### PR TITLE
Better handling for runtime exception in Tablet.commit 

### LINKED ISSUE #5208: RuntimeException in Tablet.commit does not decrement writes in progress
**Describe the bug**
User reported the following stack trace and issue:
```
java.lang.NegativeArraySizeException: -27
at org.apache.core.data.Mutation.readBytes(Mutation.java:1243)
at org.apache.core.data.Mutation.deserializeColumnUpdate(Mutation.java:1283)
at org.apache.core.data.Mutation.getUpdates(Mutation.java:1267)
at org.apache.tserver.InMemoryMap$DefaultMap.mutate(InMemoryMap.java:434)
at org.apache.tserver.InMemoryMap$SampleMap.mutate(InMemoryMap.java:243)
at org.apache.tserver.InMemoryMap.mutate(InMemoryMap.java:505)
at org.apache.tserver.tablet.CommitSession.mutate(CommitSession.java:117)
at org.apache.tserver.tablet.TabletMemory.mutate(TabletMemory.java:145)
at org.apache.tserver.tablet.Tablet.commit(Tablet.java:880)
at org.apache.tserver.tablet.CommitSession.commit(CommitSession.java:86)
```

in the `Tablet.commit` code:

https://github.com/apache/accumulo/blob/7b746cd08fc18ea3e75ea5f5180c1a6661367db5/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L869-L897

The runtime exception thrown from `getTabletMemory().mutate(commitSession, mutations, totalCount);` causes the code following to be skipped. This causes the writesInProgress counter to not be decremented, which impacts other Tablet operations.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.2

### PR DESCRIPTION
**Pull request by dlmarion**
Wrapped call to getTabletMemory().mutate() in try/finally so that a RuntimeException does not short circuit the code in the method that decrements the writes. Added logging in TabletClientHandler to note which client was causing the failure.

Closes #5208

### CODE REVIEW

**Review by cshannon — APPROVED** [review]

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 1]
```diff
@@ -877,22 +877,24 @@ public void commit(CommitSession commitSession, List<Mutation> mutations) {
...
+        getTabletMemory().updateMemoryUsageStats();
 
-      numEntries += totalCount;
-      numEntriesInMemory += totalCount;
-      ingestCount += totalCount;
-      ingestBytes += totalBytes;
+        numEntries += totalCount;
+        numEntriesInMemory += totalCount;
+        ingestCount += totalCount;
+        ingestBytes += totalBytes;
```
Comment (dlmarion) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:896]: I'm thinking these might need to go between the mutate call and the finally statement.

Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:896]: Could only place the `decrementWritesInProgress(commitSession);` in the finally statement and place all the other code in the try after the mutate call. 

Looking into this`decrementWritesInProgress(commitSession);` should always be done after the increment using a try/finally.  This change would need to be made in TabletClientHandler.flush(), however that code is a huge mess. Would be nice if TabletClientHandler.flush() did something like the following, but it seems like it would be a large change.

```java
incrementWritesInProgress();
try{
   // do the write
} finally {
   decrementWritesInProgress();
}
```

Could make this change for now as it incremental improvement to making sure the decrement happens and open a follow on issue about further improving the decrement case (assuming that is a massive refactor to get it done, but not completely sure about that).   I think this change makes the code more resilient, so its good on its own.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 2]
```diff
@@ -877,22 +877,21 @@ public void commit(CommitSession commitSession, List<Mutation> mutations) {
...
-      decrementWritesInProgress(commitSession);
-
+    try {
+      getTabletMemory().mutate(commitSession, mutations, totalCount);
       getTabletMemory().updateMemoryUsageStats();
-
       numEntries += totalCount;
       numEntriesInMemory += totalCount;
       ingestCount += totalCount;
       ingestBytes += totalBytes;
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:886]: The increments needs to be done in in sync block and maybe update of stats.  So would do something like the following.  The exception check would be best done outside the finally block, in the case where an exception is thrown and the finally block is running we do not want throw a new exception as it causes the old one to be lost.  Also validation is only needed when mutate was successful, if the mutate failed for some reason we do not need to do the validaiton.

```suggestion
synchronized (this) {
       getTabletMemory().updateMemoryUsageStats();
        if (isCloseComplete()) {
          throw new IllegalStateException(
              "Tablet " + extent + " closed with outstanding messages to the logger");
        }
      numEntries += totalCount;
      numEntriesInMemory += totalCount;
      ingestCount += totalCount;
      ingestBytes += totalBytes;
      }
```

Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:886]: ok, for some reason I misunderstood your previous suggestion.

**Review by keith-turner — APPROVED** [review]
