### PR TITLE
Always use retry backoff in ZooReader(Writer)

### LINKED ISSUE #3718: Mutating zookeeper may retry immediately in the case of collisions
**Describe the bug**

Accumulo has a generic utility for updating zookeeper that handles collisions and retries.  In some cases this utility code will do exponential backoff when retrying and in others cases it may always retry immediately.  For [this code](https://github.com/apache/accumulo/blob/cd7642988bac831292e988326aaa96e07938c641/core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java#L187) if `alwaysRetryCondition.test(e)` is true then it will short circuit and not call `useRetryForTransient(retries, e)`. Since useRetryForTransient is not called, no sleep or exponential backoff is done for retry, it retries immediately.

**Expected behavior**

When a zookeeper update will retry forvever, it should still do exponential backoff and not retry immediately inorder to avoid overwhelming ZK.

### PR DESCRIPTION
**Pull request by ctubbsii**
Always use the retry backoff when always retrying. This fixes an issue where an "always retry" condition is triggered, it will not barrage ZooKeeper with repeated immediate retries.

This fixes #3718

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java [hunk 1]
```diff
@@ -184,7 +184,11 @@ protected <R> R retryLoopMutator(ZKFunctionMutator<R> zkf,
       try {
         return zkf.apply(getZooKeeper());
       } catch (KeeperException e) {
-        if (alwaysRetryCondition.test(e) || useRetryForTransient(retries, e)) {
+        if (alwaysRetryCondition.test(e)) {
+          retries.waitForNextAttempt(log,
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:188]: Looking at RETRY_FACTORY at the top of the class it constructs a retry with `maxRetries(10)`.  Would this mean a different retry factory is needed for the always retry case?

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:188]: The maxRetries sets the counter. Calling the waitForNextAttempt does not decrement the counter. You have to call. `retries.useRetry()` to decrement the counter. This patch waits for the next retry using the backoff, but does not call `retries.useRetry()`.

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java [hunk 2]
```diff
@@ -184,7 +184,11 @@ protected <R> R retryLoopMutator(ZKFunctionMutator<R> zkf,
...
+              "attempting to communicate with zookeeper after exception that requires retry");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:189]: Would it make sense to add anything about that exception to the message?

**Review by keith-turner — APPROVED** [review]

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java (hunk 2 above)
Comment (ivakegg) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:189]: Like how long we are waiting each time?
Also can I presume that there is a cap as to the longest amount of period we will wait?

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:189]: > Would it make sense to add anything about that exception to the message?

I can do that, but since the retry condition is passed in as a parameter, it won't be clear what about the exception triggered the retry, without also injecting a parameter to customize the log message for the given condition... which I think would complicate the method's API too much.

> Like how long we are waiting each time? Also can I presume that there is a cap as to the longest amount of period we will wait?

The wait time is logged at debug by the Retry class already. We don't log the max wait time or the backoff or other configuration, but it's hard-coded in the ZooReader class. We could log it, but I'm not sure where the best place to do that is where it would be useful.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:189]: > which I think would complicate the method's API too much.

Agreed. Wondering if appending the message from the exception would be useful, but was not sure.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java:189]: > Like how long we are waiting each time? Also can I presume that there is a cap as to the longest amount of period we will wait?

Can find the config for the retry here :

https://github.com/apache/accumulo/blob/cd7642988bac831292e988326aaa96e07938c641/core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java#L45


Looks like max wait time is 5 seconds.  Wondering if that should be higher, like 30 seconds to a minute.  If collisions keep happening, backing off more is the best thing to do.

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooReader.java]: I added the exception message to the log in 023415ae75728f90dc56dd0f6f9b0c75a157a68a

**Comment by ctubbsii** [comment]
There was some discussion about changing the default maxWait interval being something longer than 5 seconds. I'm not so sure about that, but if that changes, it can be done in a separate change.

**Comment by keith-turner** [comment]
Created #3723 to increase the timeout.
