### PR TITLE
Handle exceptions during tablet metadata task

### LINKED ISSUE #3346: remote scan exception halts tserver
We we seeing cases where a scan on a remote tserver (possibly for data from accumulo.root) fails and this results in the local tserver be halted.  This happened on 3 tservers at the same time running a scan on the same remote tserver.  The exception looks something like this:
```
org.apache.accumulo.core.util.threads.ThreadPools$ExecutionError: Critical scheduled background task failed.
      at org.apache.accumulo.core.util.threads.ThreadPools.checkTaskfailed(ThreadPools.java.139)
...
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server RemoteHost:9997
...
Caused by: java.lang.RuntimeException: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server RemoteHost:9997
     at org.apache.accumujlo.core.clientImpl.TabletServerBatchReaderIterator.hasNext(TabletServerBatchReaderIterator.java:194)
...
Caused by: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server RemoteHost:9997
    at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderiterator.doLookup(TabletServerBatchReaderIterator.java:911)
...
```
I do not see any exceptions in the RemoteHost logs that correlate with these failures.  I see the accumulo.audit INFO message "operation: Permitted; user: <user>; client: <ip>:<port>; action: authenticate"  but I do not see any exceptions or other messages.

openjdk versio0n "11.0.15" 2022-04-19 LTS (Corretto)
CentOS 7.3.1611
Accumulo version 2.1.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by cshannon**
Make sure to catch and log any errors when the tablet metadata verification task runs to check tablet metadata so that errors do not cause the task and server to halt.

This closes #3346

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java [hunk 1]
```diff
@@ -841,7 +841,6 @@ public void run() {
         try (TabletsMetadata tabletsMetadata =
```
Comment (ivakegg) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java:841]: I believe this will absolutely fix the problem.  I am wondering if changing the "watchCriticalFixedDelay" on line 826 can simply be changed to "watchNonCriticalScheduledTask" ?

**Comment by EdColeman** [comment]
I am not sure that just logging the error and then waiting for the next check is appropriate, and a retry and fail after X attempts may be a better approach.

For the case that triggered this, it seems the error is transient, but what if it was not?  I think the check was to validate that the tserver can read the entire metadata table - if it cannot, it may not be "safe" to continue to run with incomplete metadata information.  Even if those operations "fail" because the metadata cannot be known to be consistent, if we allow the tserver to keep running, then it seems like work would be continued to be assigned / attempted even though it will not work with the current tserver state.

This would be similar the the issue where tservers could not host tablets, but the manager keeps seeing that tserver as having 0 tablets and kept trying to make assignments to that "under-utilized" tserver. (the solution was to detect and remove the tserver lock to stop assignment attempts.

This change shifts the priority to "keeping the tserver up" rather than killing the process is it cannot fill a basic requirement of being able to maintain a consistent view of the metadata.  A retry may provide a balance of having a better chance to ride out transient errors, but still provide a hard fail if it cannot.

**Comment by ivakegg** [comment]
Note that the validation was not throwing an exception and hence was not actually halting the server.  It was halting because the tserver had a failure when attempting to scan the metadata.  Hence catching Exception is OK here (or moving it to the non-critical thread pool) UNLESS you want to have the validation halt the server.  In any case a scan failure should NOT halt the server.

**Comment by cshannon** [comment]
> Note that the validation was not throwing an exception and hence was not actually halting the server (see Tablet.compareTabletInfo). It was halting because the tserver had a failure when attempting to scan the metadata. Hence catching Exception is OK here (or moving it to the non-critical thread pool) UNLESS you want to have the validation halt the server. In any case a scan failure should NOT halt the server.

Right I wouldn't think we should halt either on scan failure so that's what this fix does, is prevent that. In terms of making it a non critical task I guess that is fine too, if we are catching the exception and continuing I'm not sure it much matters at that point. Either way it seems like catching an exception and logging it there vs killing the task makes sense so it can be retried normally so the task and server don't fall over.

In terms of whether not we retry faster or some other logic on scan failure maybe that's a follow on issue if that is going to be more complex and maybe could be something for 2.1.2. This at least fixes the immediately issue that is a regression in 2.1 for 2.1.1 so the server doesn't fall over on a scan failure which just may be transient. Halting on metadata failure itself (not a scan failure) is another issue entirely of course and maybe that is valid but maybe shouldn't be a bug fix release and 3.0 instead.

**Comment by EdColeman** [comment]
My point is that the entire check seems to be trying to validate that the tserver can read and has a consistent view of the metadata tablet.   If this check cannot complete then I think the intention was to "hard" fail the tserver so that it was not trying to run with possibly incomplete / incorrect view of the metadata.

Because it seems a transient (but somehow repeating) failure is stopping the tserver - a more conservative change would be to retry the scan (or the entire check) to guard against transient failures - but if the check cannot complete within a reasonable period, then it would be safer to continue to stop the process.

Changing the check so that it only logs the exception seems that it could lead to cases where the tserver would continue to run when the intention is that it would have been halted.

We may want to add resiliency to the check, but the underlying issue seems to be something in the environment is repeatably causing a scan failure while reading the metadata - nurffing the check to accommodate that case my just be hiding an underlying issue that needs to be corrected.  This change seems that it could allow other issues to also be hidden.

Again, I am addressing the overall goal of the check - not the issue that a transient scan failure seems to be triggering more aggressively that necessary.

**Comment by EdColeman** [comment]
If I had the wrong impression of the check, then I am okay with the changes - maybe log the error and also move it to a non-critical thread check?

Are there things that we *should* be checking for a tserver to validate that it meets some minimal level of healthy?

**Comment by EdColeman** [comment]
I had been thinking that a metric for the elapsed time in this check would make a good metric - it might be a good proxy for health over time as well as possibly being useful to compare across servers.  But with the upcoming changes I thought it may be better to hold off until those settle.

**Comment by cshannon** [comment]
I moved the check to a non critical thread based on the feedback here. Is there anything else to do here or is this good to merge?

**Review by EdColeman — APPROVED** [review]

**Comment by cshannon** [comment]
After some discussion we decided to keep it as a critical task as it already was but to just keep the try/catch change so we don't fall over for normal exceptions.
