### PR TITLE
Fix history test inside ShellServerIT

### LINKED ISSUE #2091: Rewrite history test in ShellServerIT
There are a few problems with the `history` test in ShellServerIT. The test should be rewritten to create a table with a unique name and then look for that unique name using the history command.

### PR DESCRIPTION
**Pull request by Manno15**
Fixes #2091.

The history command was failing due to the executed commands not being written to the history file. This change will write the expected commands to the history file but solely for the history test at this moment since some tests broke with the change.

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 1]
```diff
@@ -1431,18 +1436,15 @@ public void help() throws Exception {
     }
   }
 
-  // TODO - evaluate this test is testing what is expected or history is working.
   @Test
   public void history() throws Exception {
-    final String table = name.getMethodName();
+    final String table = getUniqueNames(1)[0];
 
     ts.exec("history -c", true);
```
Comment (EdColeman) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1443]: There may be an opportunity here to validate that the clean command worked as expected.

Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1443]: Good idea.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 2]
```diff
@@ -1431,18 +1436,15 @@ public void help() throws Exception {
...
-    ts.exec("createtable " + table);
-    ts.exec("deletetable -f " + table);
-    // TODO - this may be passing only because method name is history.
+    ts.writeToHistory("createtable " + table);
+    ts.writeToHistory("deletetable -f " + table);
```
Comment (EdColeman) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1445]: Does the write to history perform an exec() - previously the test was executing a command, testing the command was successful (via the exec status) and then that appeared in the history - from a quick look I don't see where this performs the exec.  Not that these commands need tested, but is it a valid test of shell history?

**Review by EdColeman — COMMENTED** [review]
The changes look okay - if they are test what is expected.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 2 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1445]: These aren't executed. I felt it was safe to leave it out from an exec call since they aren't part of this test specifically. The exec command fails to write to the history file due how things are set up with the shell. The history file is part of the reader, but the reader isn't involved with the executions since I assume it doesn't interpret it as an input command. This is why only `ts.input` would show up in the history file since it was being read. 

From a validity standpoint, the exec of the history command does work properly and the contents of the reader's history file gets displayed.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 1 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java]: I added a short validity check for the clear command in my latest commit

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 3]
```diff
@@ -1431,18 +1436,20 @@ public void help() throws Exception {
...
-    final String table = name.getMethodName();
+    final String table = getUniqueNames(1)[0];
 
-    ts.exec("history -c", true);
-    ts.exec("createtable " + table);
-    ts.exec("deletetable -f " + table);
-    // TODO - this may be passing only because method name is history.
+    // test clear history command works
+    ts.writeToHistory("foo");
+    ts.exec("history -c", true, "foo", false);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1445]: This didn't first verify that "foo" was present, or that it was removed afterwards:

```suggestion
    ts.exec("history", true, "foo", true);
    ts.exec("history -c", true);
    ts.exec("history", true, "foo", false);
```

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 4]
```diff
@@ -1431,18 +1436,20 @@ public void help() throws Exception {
...
+
+    // write to history file. Does not execute functions
+    ts.writeToHistory("createtable " + table);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1448]: This could verify that the table name and these commands are not present first:

```suggestion
    // write to history file. Does not execute functions
    ts.exec("history", true, table, false);
    ts.exec("history", true, "createtable", false);
    ts.exec("history", true, "deletetable", false);
    ts.writeToHistory("createtable " + table);
```

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 5]
```diff
@@ -1431,18 +1436,20 @@ public void help() throws Exception {
...
+    ts.writeToHistory("deletetable -f " + table);
+
+    // test that history command prints contents of history file
     ts.exec("history", true, table, true);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1452]: This could be more thorough in checking that the createtable and deletetable commands were added:

```suggestion
    ts.exec("history", true, "createtable " + table, true);
    ts.exec("history", true, "deletetable -f " + table, true);
```

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java [hunk 6]
```diff
@@ -1431,18 +1436,20 @@ public void help() throws Exception {
...
-    // TODO - what is this testing?
-    ts.exec("history", true, "history", true);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1445]: I think this was just a basic test ensuring that exec caused the command to be added to the history. If that doesn't work in the test case, because of the way the test is written, that's fine to remove this, so long as executing commands in the shell still appends to the history.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 3 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1445]: Fair point, I was assuming the string present would account for the clear command as well and do the check after clearing. Unsure if that is the case but it was failing when I had the stringPresent set to true

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 4 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1448]: If validity check for the clear works correctly, then I am not sure this step is necessary but I don't have anything against being thorough so I will add.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 5 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1452]: I agree on this point, I should have done that earlier.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 6 above)
Comment (Manno15) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java:1445]: In a previous iteration, I kept this line but replaced the expected string with "foo". That is now being used in the validity check so I removed it here. The rest of what you said is still true and with your additions above, I believe the history command is thoroughly tested.

File: test/src/main/java/org/apache/accumulo/test/ShellServerIT.java (hunk 3 above)
Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/ShellServerIT.java]: I'm pretty sure `history -c` just clears, and doesn't print anything. So, a check for any string present at all would have been false.

**Review by ctubbsii — APPROVED** [review]
LGTM
