### PR TITLE
Fix use of ServiceLockData Optional and nulls

### LINKED ISSUE #3782: Compactor fails to start
Saw the following while doing testing on the elasticity branch and it caused a compactor to exit. I suspect the compactor started before the manager and there was no address for the manager in ZK yet, however not sure that is the actual cause.  Also not sure if this a bug in main or 2.1

```
 2023-09-27T11:44:42,835 [compactor.Compactor] ERROR: Unhandled error occurred in Compactor
java.lang.NullPointerException: null
        at org.apache.accumulo.core.util.AddressUtil.parseAddress(AddressUtil.java:36) ~[classes/:?]
        at org.apache.accumulo.core.lock.ServiceLockData.getAddress(ServiceLockData.java:160) ~[classes/:?]
        at org.apache.accumulo.core.util.compaction.ExternalCompactionUtil.findCompactionCoordinator(ExternalCompactionUtil.java:111) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.getCoordinatorClient(Compactor.java:462) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.lambda$getNextJob$3(Compactor.java:436) ~[classes/:?]
        at org.apache.accumulo.server.compaction.RetryableThriftCall.run(RetryableThriftCall.java:100) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.getNextJob(Compactor.java:452) ~[classes/:?]
        at org.apache.accumulo.compactor.Compactor.run(Compactor.java:627) [classes/:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

### PR DESCRIPTION
**Pull request by ctubbsii**
* Simplify ServiceLockData's if conditions in methods that return null
* Ensure ServiceLockData.getAddress() returns null when .getAddressString() returns null
* Handle null toString() in ServiceLockData.equals() using Objects.equals()
* Simplify TabletMetadata.checkServer(), TServerClient.getTabletServerConnection(), ExternalCompactionUtil.findCompactionCoordinator(), LiveTServerSet.checkServer(), and Monitor.fetchGcStatus() by using Optional.map(), Optional.ifPresent(), and Optional.orElse(null)
* Improve Monitor.fetchGcStatus() by short-circuiting the warning and returning null results when the address is null, rather than wait for an exception to be thrown while trying to connect to the service using a null address
* Update ServiceLockDataTest to ensure getAddress() returns null when it's expected to, instead of throwing a NullPointerException

This fixes #3782

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java [hunk 1]
```diff
@@ -164,30 +165,22 @@ public ServiceLockData(UUID uuid, String address, ThriftService service) {
...
-      return null;
-    }
-    return sd.getAddress();
+    return sd == null ? null : sd.getAddress();
   }
 
   public HostAndPort getAddress(ThriftService service) {
-    return AddressUtil.parseAddress(getAddressString(service), false);
+    String s = getAddressString(service);
+    return s == null ? null : AddressUtil.parseAddress(s, false);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java:173]: This is the main change that fixes things in this PR. The other changes in this class were just taking the opportunity to make the other methods that do the same thing a bit more concise and consistent with one another.

File: server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java [hunk 2]
```diff
@@ -428,10 +428,11 @@ private GCStatus fetchGcStatus() {
...
       if (locks != null && !locks.isEmpty()) {
-        Optional<ServiceLockData> sld =
-            ServiceLockData.parse(zk.getData(path + "/" + locks.get(0)));
-        if (sld.isPresent()) {
-          address = sld.orElseThrow().getAddress(ThriftService.GC);
+        address = ServiceLockData.parse(zk.getData(path + "/" + locks.get(0)))
+            .map(sld -> sld.getAddress(ThriftService.GC)).orElse(null);
+        if (address == null) {
+          log.warn("Unable to contact the garbage collector (no address)");
+          return null;
```
Comment (keith-turner) [inline server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java:435]: The rest of the code is ok with this returning null?

Before these change could this code have thrown an NPE?

Not sure about the log level of warn for the new log message.  Sometimes the GC is down and that is expected and the warn would not be useful in that case.  When the GC is down and its not expected, these log messages are probably not a great way to do detect that.  I would go with debug for this log message.

**Review by keith-turner — APPROVED** [review]

File: core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java:173]: Leveraging the existing optional and replacing if stmts with Optional.map stmts was a really nice change.

File: server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java (hunk 2 above)
Comment (ctubbsii) [reply server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java:435]: Before this change, this would have resulted in attempting to make a connection to a server using null for the address. That would have resulted in some exception, though I don't know off the top of my head whether that would be an NPE or an IOException, and caught further down, which would have resulted in a similar message, but reporting that it failed to connect to the GC at the "null" address. This just short-circuits that attempt to connect using a null address and fail later with a non-sensical message. It's not strictly necessary, but I thought it'd be a better behavior.

File: core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java (hunk 1 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/lock/ServiceLockData.java:173]: It wasn't strictly necessary to do that to fix the issue, but it made the code so much easier to understand while I was trying to track down and verify there were no negative side-effects by any of the existing callers when I changed the behavior of this getAddress method.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 3]
```diff
@@ -68,13 +64,9 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
       var zLocPath =
           ServiceLock.path(context.getZooKeeperRoot() + Constants.ZTSERVERS + "/" + tserver);
-      Optional<ServiceLockData> sld = zc.getLockData(zLocPath);
-      if (sld.isPresent()) {
-        HostAndPort address = sld.orElseThrow().getAddress(ThriftService.TSERV);
-        if (address != null) {
-          servers.add(new ThriftTransportKey(address, rpcTimeout, context));
-        }
-      }
+      zc.getLockData(zLocPath).map(sld -> sld.getAddress(ThriftService.TSERV))
```
[the remark this answers is not in the document]
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:67]: It could be possible that lock data was serialized to that node, but did not have the TSERV service registered (that would probably be a bigger bug if that were to happen). If that were to happen before my fix, this method would have blown up with an NPE in a similar way to the original reported issue. Now, the address would be null, and it simply won't get added to the list of detected servers... which was the original intent with the null check, as demonstrated by the way it behaved in previous versions of Accumulo (I consulted 2.1 behavior when making these changes).
