### PR TITLE
Block use of fate in Manager until fate is ready

### LINKED ISSUE #2980: FateServiceHandler process started before Fate is ready
When the Manager starts up, one of the first things it does is start the FateServiceHandler process. This process will quickly try to access the `manager.fate` object to do the work it needs to do. This object will be null and can cause many NullPointerExceptions before the `Fate` object is constructed by the Manager. For locking purposes it is important that the thrift process be started first but their may be room for improvement so that the logs don't get spammed with these messages.

### PR DESCRIPTION
**Pull request by ctubbsii**
Explicitly block use of fate in the Manager service until the Manager starts up the fate functionality and it is ready for use. Attempt to provide useful logging information when this occurs, to ease troubleshooting, because this should not normally happen.

Fix #2980

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 1]
```diff
@@ -225,6 +226,35 @@ public boolean stillManager() {
...
+
+    // it's not ready yet
+    long retryTime = 500; // millis
+
+    // create informative warning
+    String msgPrefix = "Unexpected use of fate in thread " + Thread.currentThread().getName()
+        + " at time " + System.currentTimeMillis();
+    log.warn("{} blocked until fate starts", msgPrefix,
+        new IllegalStateException("Attempted fate action before fate was started; "
+            + "if this doesn't make progress, please report it as a bug to the developers"));
```
Comment (ctubbsii) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:244]: We could reduce this to debug if this is a normal situation, and not something to warn the users about. I'm just not sure.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 2]
```diff
@@ -207,7 +208,7 @@ public class Manager extends AbstractServer
 
   private ManagerState state = ManagerState.INITIAL;
 
-  Fate<Manager> fate;
+  private final AtomicReference<Fate<Manager>> fateReady = new AtomicReference<>(null);
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:212]:
```suggestion
private final CountDownLatch fateLatch = new CountDownLatch(1);
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 3]
```diff
@@ -225,6 +226,35 @@ public boolean stillManager() {
...
+    log.warn("{} blocked until fate starts", msgPrefix,
+        new IllegalStateException("Attempted fate action before fate was started; "
+            + "if this doesn't make progress, please report it as a bug to the developers"));
+    UtilWaitThread.sleep(retryTime);
+
+    // retry, logging retries at trace level
+    while ((fate = fateReady.get()) == null) {
+      log.trace("{} still blocked", msgPrefix);
+      UtilWaitThread.sleep(retryTime);
+    }
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:251]:
```suggestion
  fateLatch.await();
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 4]
```diff
@@ -1145,8 +1175,9 @@ boolean canSuspendTablets() {
                   context.getZooReaderWriter()),
               TimeUnit.HOURS.toMillis(8), System::currentTimeMillis);
 
-      fate = new Fate<>(this, store, TraceRepo::toLogString);
-      fate.startTransactionRunners(getConfiguration());
+      Fate<Manager> f = new Fate<>(this, store, TraceRepo::toLogString);
+      f.startTransactionRunners(getConfiguration());
+      fateReady.set(f);
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1180]:
```suggestion
      fateReady.set(f);
      fateLatch.countDown();
```

**Review by dlmarion — COMMENTED** [review]
I wonder if this might be simpler.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 2 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:212]: I considered that, but having the fate object and the countdownlatch in separate variables means that separate threads wouldn't necessarily see the updated fate object unless I also made that voloatile, which seemed redundant. The best way to do it seemed to have the volatile reference be the same object that is monitored for readiness.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:212]: On second thought, I suppose I could still do this. It would save me from looping.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:212]: I was suggesting using both:
```
private final AtomicReference<Fate<Manager>> fateReady = new AtomicReference<>(null);
private final CountDownLatch fateLatch = new CountDownLatch(1);
```

You don't need to make `fateReady` volatile, as AtomicReference.get() and set() already have the memory semantics of volatile.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:212]: > On second thought, I suppose I could still do this. It would save me from looping.

Yes, that's the reason I suggested it. I should have been more clear.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:216]: Done in f9aa22b54853b5726945870ed575317f570843cf

**Review by dlmarion — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 5]
```diff
@@ -225,6 +230,33 @@ public boolean stillManager() {
...
+      fateReadyLatch.await();
+    } catch (InterruptedException e) {
+      Thread.currentThread().interrupt();
+      throw new IllegalStateException("Thread was interrupted; cannot proceed");
+    }
+
+    // report at debug when the issue is resolved
+    log.debug("{} no longer blocked", msgPrefix);
+    return fateRef.get();
+  }
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:258]: I think you could re-write this method to the following. It's functionally equivalent.
```
  if (fateReadyLatch.getCount() != 0) {
      String msgPrefix = "Unexpected use of fate in thread " + Thread.currentThread().getName()
        + " at time " + System.currentTimeMillis();
      log.warn("{} blocked until fate starts", msgPrefix,
        new IllegalStateException("Attempted fate action before fate was started; "
            + "if this doesn't make progress, please report it as a bug to the developers"));
    try {
      fateReadyLatch.await();
      // report at debug when the issue is resolved
      log.debug("{} no longer blocked", msgPrefix);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new IllegalStateException("Thread was interrupted; cannot proceed");
    }
  }
  return fateRef.get();
```

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:258]: Yeah, I was thinking that, too.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: @dlmarion Any thoughts on reducing this to debug?

**Review by dlmarion — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (milleruntime) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Could just log the warning. I am not sure how useful the full stack trace is.

**Comment by milleruntime** [comment]
I tested these changes and the new error is being printed just as much but with more information:
<pre>
2022-09-30T14:33:41,021 [manager.Manager] WARN : Unexpected use of fate in thread Manager-ClientPool-Worker-1 at time 1664562821016 blocked until fate starts
java.lang.IllegalStateException: Attempted fate action before fate was started; if this doesn't make progress, please report it as a bug to the developers
        at org.apache.accumulo.manager.Manager.fate(Manager.java:244) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.manager.FateServiceHandler.waitForFateOperation(FateServiceHandler.java:706) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:206) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at com.sun.proxy.$Proxy36.waitForFateOperation(Unknown Source) ~[?:?]
        at org.apache.accumulo.core.manager.thrift.FateService$Processor$waitForFateOperation.getResult(FateService.java:594) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.manager.thrift.FateService$Processor$waitForFateOperation.getResult(FateService.java:570) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:54) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
</pre>

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 6]
```diff
@@ -225,6 +230,36 @@ public boolean stillManager() {
...
+   * @return the Fate object, only after the fate components are running and ready
+   */
+  Fate<Manager> fate() {
+    // if it's not ready, then wait for it to be ready, but with some informative logging
+    if (fateReadyLatch.getCount() != 0) {
+      String msgPrefix = "Unexpected use of fate in thread " + Thread.currentThread().getName()
+          + " at time " + System.currentTimeMillis();
+      // include stack trace so we know where it's coming from, in case we need to troubleshoot it
+      log.warn("{} blocked until fate starts", msgPrefix,
+          new IllegalStateException("Attempted fate action before fate was started; "
```
Comment (milleruntime) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:250]: I like this message better first, as the msgPrefix and I don't think you need the IllegalStateException. 
```suggestion
          "Attempted fate action before manager finished starting up; "
```

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:250]: The IllegalStateException is just an exception we need to create in order to build a stack trace we can show in the logs. It could be any new exception. If we remove it, we remove the stack trace in the logs.

**Comment by ctubbsii** [comment]
> I tested these changes and the new error is being printed just as much but with more information:

I was hoping it might occur less often, because of the way it blocks, it might prevent noisy NPEs from retries.

I think the main concern is: do these make progress? Or do they block indefinitely?

If they make progress, it's probably fine. We can tune this a bit further... maybe instead of logging and waiting, we just wait for a certain amount of time, then log and throw an exception only if it times out, and fails to make progress. Setting a timeout is easy to do with the CountDownLatch. How much time does the Manager need, typically?

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: I was hoping that the stack trace would help us debug where it was coming from, if it was something that shouldn't be doing whatever it was doing.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: So, regarding the logging, you could do something like this instead:

```
  if (!fateReadyLatch.await(1, MINUTE)) {
    // LOG HERE
  }
```

The waiting should be short-circuited when the latch count goes to zero.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: I would suggest making the wait time large so that you don't have to put it into a loop. If the wait time has expired and the await() method returns false, then you could shut down the manager (if the wait time is like 10 mins or something ridiculous)

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: I'm not sure about shutting down the manager. The manager might not be able to help that a tserver or client is asking it to do something when it's not ready. But, I do like the idea of logging periodically if it isn't making progress. I'd rather put it into a loop for that. I could make it 5 minutes and log a warning. I used trace before when I was looping 250ms, but warning I think is most appropriate if it's stuck for 5 minutes.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: I'll make it so the first warning doesn't occur until at least 30 seconds of waiting. And subsequent warnings every 5 minutes that progress isn't made.

**Review by dlmarion — APPROVED** [review]

**Comment by milleruntime** [comment]
> I think the main concern is: do these make progress? Or do they block indefinitely?

In my limited testing, they do make progress.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 7]
```diff
@@ -225,6 +230,40 @@ public boolean stillManager() {
...
+        log.warn("{} blocked until fate starts", msgPrefix,
+            new IllegalStateException("Attempted fate action before manager finished starting up; "
+                + "if this doesn't make progress, please report it as a bug to the developers"));
+        int minutes = 0;
+        while (!fateReadyLatch.await(5, TimeUnit.MINUTES)) {
+          minutes += 5;
+          log.warn("{} still blocked after {} minutes; this is getting weird", msgPrefix, minutes);
+        }
+        log.debug("{} no longer blocked", msgPrefix);
+      }
```
Comment (milleruntime) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: This will block the current thread but there are multiple threads trying to access the fate object. It seems like there is one thread listening per each RPC method. So I am not sure how useful all the logic and complexity added for the blocking is. I would prefer a less complex change where we don't do any thread blocking. I do like the improved logging message. Anything is better, is better then NPEs.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: Instead of blocking here in `Manager.fate()` we could throw an exception. When called from the `FateServiceHandler` that exception could be turned into a Thrift exception and returned back to the caller. Would that be a better solution?

Comment (milleruntime) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: Maybe. We don't want to kill the thread though cause they were just started in the Manager as part of the startup.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: We were already throwing an exception... it was a NPE. I think it would have triggered a retry on the RPC loop, though. The whole point of this was to avoid the exception throwing.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: I'm not suggesting that we kill the thread, I'm suggesting that we throw an error in `Manager.fate()` when it's not ready, catch it in `FateServiceHandler`, and return a TException back to the originator of the call - likely the TabletServer.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: I think catching the exception, and throwing something the client code should handle differently is going to be a lot bigger of a change, involving updating the RPC method signatures, and adding client side code to handle it differently than the current loop.

I would prefer just giving it a bit of time, and waiting for the object to be ready, with some generous logging, as this PR is doing.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: Yeah, I agree with that too. I was just trying to understand what type of alternate solution would be acceptable.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:259]: > I'm not suggesting that we kill the thread, I'm suggesting that we throw an error in `Manager.fate()` when it's not ready, catch it in `FateServiceHandler`, and return a TException back to the originator of the call - likely the TabletServer.

Since this seems to be a routine case, and things should normally make progress within a few seconds, I don't think it's worthwhile using Exception handling as flow control for the tablet server.

**Review by milleruntime — APPROVED** [review]
This is probably the best we can do for now. In the next version we could take a deeper look at the timing between the tserver and the manager. Like ask the question... why are the tservers trying to perform these important functions before the manager is fully functioning?

**Comment by ctubbsii** [comment]
> This is probably the best we can do for now. In the next version we could take a deeper look at the timing between the tserver and the manager. Like ask the question... why are the tservers trying to perform these important functions before the manager is fully functioning?

It's probably just normal hello message check-ins because they detect the service address registration for the manager in ZK too quickly. They have no way to know that the service isn't fully functioning yet. The manager could delay registering its service address in ZK, even after it has started up the Thrift RPC, so they don't know how to find the manager yet... but I don't think it's much of a problem if they wait a few seconds.
