### PR TITLE
Print warning in log when user does not have permission to get config

### LINKED ISSUE #3010: Unable to get table configuration after #2994
So, I merged #2994 after multiple successful IT builds. Created a new cluster using Terraform and the head of `main`. Created the `ci` table, then I went into the shell to check that the encryption properties that I set it the configuration were there. And, permission denied. Even thought according to `userpermissions` I have the correct ones.

```
 root@accumulo-testing> userpermissions
System permissions: System.GRANT, System.CREATE_TABLE, System.DROP_TABLE, System.ALTER_TABLE, System.CREATE_USER, System.DROP_USER, System.ALTER_USER, System.SYSTEM, System.CREATE_NAMESPACE, System.DROP_NAMESPACE, System.ALTER_NAMESPACE, System.OBTAIN_DELEGATION_TOKEN

Namespace permissions (accumulo): Namespace.READ, Namespace.ALTER_TABLE

Table permissions (accumulo.metadata): Table.READ, Table.ALTER_TABLE
Table permissions (accumulo.replication): Table.READ
Table permissions (accumulo.root): Table.READ, Table.ALTER_TABLE
Table permissions (ci): Table.READ, Table.WRITE, Table.BULK_IMPORT, Table.ALTER_TABLE, Table.GRANT, Table.DROP_TABLE, Table.GET_SUMMARIES
root@accumulo-testing> config -t accumulo.root
2022-10-07T19:35:28,604 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
root@accumulo-testing> config -t accumulo.metadata
2022-10-07T19:35:31,563 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
root@accumulo-testing> config -t ci
2022-10-07T19:35:37,635 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
```

But, I have no issue scanning the tables:
```
root@accumulo-testing> table ci
root@accumulo-testing ci> scan
root@accumulo-testing ci> table accumulo.metadata
root@accumulo-testing accumulo.metadata> scan
+rep< srv:dir []	default_tablet
+rep< srv:time []	L0
+rep< ~tab:~pr []	\x00
...
```

### PR DESCRIPTION
**Pull request by dlmarion**
Catch security exceptions in ConfigCommand when printing the configuration and print a warning to the log that the user does not have permission to get the configuration object. The configuration that is printed will be what the user can see.

Fixes #3010

### CODE REVIEW

**Comment by dlmarion** [comment]
@cshannon  - this is an alternate to your # 2 . For the `root` user, I gave the permission `Namespace.ALTER_NAMESPACE` on the `accumulo` namespace manually. The configuration's printed normally for:

```
config
config -ns accumulo
config -t accumulo.metadata
```

I also create another user and this is what it looks like:

```
root@test> createuser dave
Enter new password for 'dave': ****
Please confirm new password for 'dave': ****
root@test> grant System.CREATE_NAMESPACE -s -u dave
root@test> user dave
Enter password for user dave: ****
dave@test> createnamespace dtest
dave@test> createtable dtest.foo
dave@test dtest.foo> config -t dtest.foo
2022-10-11T13:27:14,891 [shell.Shell] WARN : System Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
2022-10-11T13:27:14,893 [shell.Shell] WARN : Site Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
namespace  | table.balancer ................................................... | org.apache.accumulo.core.spi.balancer.SimpleLoadBalancer
namespace  | table.bloom.enabled .............................................. | false
namespace  | table.bloom.error.rate ........................................... | 0.5%
namespace  | table.bloom.hash.type ............................................ | murmur
...
```

**Review by cshannon — COMMENTED** [review]
I think this version is also fine. My PR shows a bit more detail and will print if something is an override of a default but the trade off is complexity as this PR is obviously a much simpler and smaller change compared to the version I submitted with #3012. 

I would say we should get some feedback from others and see what people think. Maybe we just go with the simplest approach for now for 2.1 and then enhance it for version 3.0 (move to server logic or something more complicated) if we want.

**Comment by EdColeman** [comment]
I am late to this, but it seems less important to display a value because that's what the users can see vs. what is set.  With the example above, if `table.bloom.enabled=true` was set at a level that the user cannot "see" - would it show that it was a) set to true somewhere, b) lie to the uses and say the value was "false", c) show that that value cannot be displayed because of permissions or d) just fail the entire command.

It seems that c) or d) are the only valid choices - we cannot display a value that is not what is used - even if there's a warning at the beginning - so b should be right out.  Allowing a seems a way to get around permissions that might not be ideal, but at least reflects the actual state of the system.

**Comment by dlmarion** [comment]
@EdColeman - I'm pretty sure the way that it works is the following:

The user will enter a command in the shell, one of:
```
config -t <table>
config -ns <namespace>
config
```

The user making the call will need the correct permissions on the object for which they are requesting the configuration information (table, namespace, system). If they don't have the permissions to see that, then they will get an error. The ConfigCommand also gets the configuration information at levels above what are requested solely for the purpose of showing the user what the value is at the higher level (and marking the current value with overridden). For example, if a user enters `config -t <table>`, then ConfigCommand also gets the site, system, and namespace configurations. If the user can't see the system/site configuration, but can see the namespace and table configuration, then that's all they will see as in my example above.

**Comment by dlmarion** [comment]
```
root@test> config -s table.bloom.enabled=true
root@test> config -f bloom
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                 | VALUE
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.bloom.enabled ................ | false
system     |    @override ....................... | true
default    | table.bloom.error.rate ............. | 0.5%
default    | table.bloom.hash.type .............. | murmur
default    | table.bloom.key.functor ............ | org.apache.accumulo.core.file.keyfunctor.RowFunctor
default    | table.bloom.load.threshold ......... | 1
default    | table.bloom.size ................... | 1048576
default    | tserver.bloom.load.concurrent.max .. | 4
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
root@test> config -t accumulo.metadata -f bloom
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                 | VALUE
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.bloom.enabled ................ | false
system     |    @override ....................... | true
default    | table.bloom.error.rate ............. | 0.5%
default    | table.bloom.hash.type .............. | murmur
default    | table.bloom.key.functor ............ | org.apache.accumulo.core.file.keyfunctor.RowFunctor
default    | table.bloom.load.threshold ......... | 1
default    | table.bloom.size ................... | 1048576
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
root@test> user dave
Enter password for user dave: ****
dave@test> config -ns dtest -f bloom
2022-10-11T15:57:16,072 [shell.Shell] WARN : System Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
2022-10-11T15:57:16,074 [shell.Shell] WARN : Site Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                 | VALUE
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
namespace  | table.bloom.enabled ................ | true
namespace  | table.bloom.error.rate ............. | 0.5%
namespace  | table.bloom.hash.type .............. | murmur
namespace  | table.bloom.key.functor ............ | org.apache.accumulo.core.file.keyfunctor.RowFunctor
namespace  | table.bloom.load.threshold ......... | 1
namespace  | table.bloom.size ................... | 1048576
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
dave@test> config -t dtest.foo -f bloom
2022-10-11T15:59:07,671 [shell.Shell] WARN : System Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
2022-10-11T15:59:07,672 [shell.Shell] WARN : Site Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                 | VALUE
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.bloom.enabled ................ | false
namespace  |    @override ....................... | true
default    | table.bloom.error.rate ............. | 0.5%
namespace  |    @override ....................... | 0.5%
default    | table.bloom.hash.type .............. | murmur
namespace  |    @override ....................... | murmur
default    | table.bloom.key.functor ............ | org.apache.accumulo.core.file.keyfunctor.RowFunctor
namespace  |    @override ....................... | org.apache.accumulo.core.file.keyfunctor.RowFunctor
default    | table.bloom.load.threshold ......... | 1
namespace  |    @override ....................... | 1
default    | table.bloom.size ................... | 1048576
namespace  |    @override ....................... | 1048576
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

In the last config print I'm working on a change showing the overrides from the default configuration when the user can't see the system & site config. I have some work to do, but you can see the change there. I think this shows that the answer is `a`.

**Comment by dlmarion** [comment]
In 4bd6b14 I made some modifications for users **without** the SystemPermission.SYSTEM permission. Before this commit, the password properties were shown. Now, `config` returns:

```
dave@test> config
2022-10-11T17:14:59,695 [shell.Shell] WARN : System Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
2022-10-11T17:14:59,697 [shell.Shell] WARN : Site Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
```

I also modified the namespace and table displays to include the default values if they were different from the current value.

```
dave@test> config -ns dtest -f bloom
2022-10-11T17:16:34,294 [shell.Shell] WARN : System Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
2022-10-11T17:16:34,296 [shell.Shell] WARN : Site Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.bloom.enabled .............................................. | false
namespace  |    @override ..................................................... | true
namespace  | table.bloom.error.rate ........................................... | 0.5%
namespace  | table.bloom.hash.type ............................................ | murmur
namespace  | table.bloom.key.functor .......................................... | org.apache.accumulo.core.file.keyfunctor.RowFunctor
namespace  | table.bloom.load.threshold ....................................... | 1
namespace  | table.bloom.size ................................................. | 1048576
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
```

```
dave@test> config -t dtest.foo -f bloom
2022-10-11T17:17:06,809 [shell.Shell] WARN : System Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
2022-10-11T17:17:06,810 [shell.Shell] WARN : Site Configuration: Error PERMISSION_DENIED for user dave - User does not have permission to perform this action
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.bloom.enabled .............................................. | false
namespace  |    @override ..................................................... | true
table      |    @override ..................................................... | false
namespace  | table.bloom.error.rate ........................................... | 0.5%
namespace  | table.bloom.hash.type ............................................ | murmur
namespace  | table.bloom.key.functor .......................................... | org.apache.accumulo.core.file.keyfunctor.RowFunctor
namespace  | table.bloom.load.threshold ....................................... | 1
namespace  | table.bloom.size ................................................. | 1048576
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
```

File: shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java [hunk 1]
```diff
@@ -155,14 +155,23 @@ public int execute(final String fullCommand, final CommandLine cl, final Shell s
...
       final String outputFile = cl.getOptionValue(outputFileOpt.getOpt());
       final PrintFile printFile = outputFile == null ? null : new PrintFile(outputFile);
 
       final TreeMap<String,String> siteConfig = new TreeMap<>();
-      siteConfig.putAll(shellState.getAccumuloClient().instanceOperations().getSiteConfiguration());
+      try {
+        siteConfig
+            .putAll(shellState.getAccumuloClient().instanceOperations().getSiteConfiguration());
+      } catch (AccumuloSecurityException e) {
+        Shell.log.warn("Site Configuration: " + e.getMessage());
```
Comment (ctubbsii) [inline shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java:173]: This is not a safe way to print with interpolation that logging provides. A better way is:

```suggestion
        Shell.log.warn("Site Configuration: {}", e.getMessage());
```

**Review by ctubbsii — COMMENTED** [review]
My comments from the related PR also apply here:  https://github.com/apache/accumulo/pull/3012#pullrequestreview-1138114217

In essence, I'm wondering what we're trying to protect, and from whom, because configs shouldn't contain sensitive things, with few exceptions.

**Comment by dlmarion** [comment]
I'm fine with punting on this post-2.1, but I don't understand why we would give a non-privileged user the ability to see how the instance and the server is configured. For example, paths to keys.

**Comment by dlmarion** [comment]
> If we're going to move forward with this, with warnings, then we can at least ensure that the warning explains to the user what the implications are in the output... like all changes shown might actually be set at a different (unseen) level that the user doesn't have permission. But then, that demonstrates, that at least for the properties that can be set at the table level, having permission on a table, allows you to probe the hidden levels anyway... so what exactly is this protecting?


I'm not sure that I understand the concern here. If a user asks for a table configuration, and is shown the actual table configuration, does it matter whether the table property value was inherited from the namespace or system configuration? The user requesting the system, namespace, or table configuration has the ability to change the values if they need to be changed.

**Comment by dlmarion** [comment]
I'm going to commit my changes. Here's the output of a test I ran.

```
root@test> tables
accumulo.metadata
accumulo.replication
accumulo.root
root@test> users
root
root@test> config -f table.file.max
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
system     |    @override ..................................................... | 30
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
root@test> config -s table.file.max=30
root@test> config -f table.file.max
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
system     |    @override ..................................................... | 30
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
root@test> createuser user1
Enter new password for 'user1': *****
Please confirm new password for 'user1': *****
root@test> grant System.CREATE_NAMESPACE -s -u user1
root@test> createuser user2
Enter new password for 'user2': *****
Please confirm new password for 'user2': *****
root@test> user user1
Enter password for user user1: *****
user1@test> config -f table.file.max
2022-10-12T16:55:17,012 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T16:55:17,013 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T16:55:17,014 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown may be set at a higher level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> createnamespace user1
user1@test> config -ns user1 -f table.file.max
2022-10-12T16:55:26,178 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T16:55:26,180 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T16:55:26,180 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown may be set at a higher level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
namespace  |    @override ..................................................... | 30
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> config -ns user1 -s table.file.max=60
user1@test> config -ns user1 -f table.file.max
2022-10-12T16:55:32,684 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T16:55:32,685 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T16:55:32,685 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown may be set at a higher level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
namespace  |    @override ..................................................... | 60
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> createtable user1.table1
user1@test user1.table1> grant Table.ALTER_TABLE -t user1.table1 -u user2
user1@test user1.table1> user user2
Enter password for user user2: *****
user2@test user1.table1> config -t user1.table1 -f table.file.max
2022-10-12T16:55:53,259 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T16:55:53,261 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T16:55:53,263 [shell.Shell] WARN : User unable to retrieve user1 namespace configuration (requires Namespace.ALTER_NAMESPACE permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T16:55:53,263 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown may be set at a higher level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
table      |    @override ..................................................... | 60
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by dlmarion** [comment]
Looks like the first config output contained a leftover from a previous test run, it should have only printed the default of 15 for `table.file.max`.

**Comment by dlmarion** [comment]
I do need to fix the root user perms though:

```
root@test user1.table1> config -t user1.table1
2022-10-12T17:10:58,987 [shell.Shell] WARN : User unable to retrieve user1 namespace configuration (requires Namespace.ALTER_NAMESPACE permission), error: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
2022-10-12T17:10:58,987 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown may be set at a higher level.
2022-10-12T17:10:58,989 [shell.Shell] ERROR: User unable to retrieve user1.table1 table configuration (requires Table.ALTER_TABLE permission)
2022-10-12T17:10:58,989 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
```

**Comment by dlmarion** [comment]
I think I am done with changes here. Latest working example:

```
root@test> config -f table.file.max
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
root@test> config -s table.file.max=30
root@test> config -f table.file.max
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
system     |    @override ..................................................... | 30
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
root@test> createuser user1
Enter new password for 'user1': *****
Please confirm new password for 'user1': *****
root@test> grant System.CREATE_NAMESPACE -s -u user1
root@test> createuser user2
Enter new password for 'user2': *****
Please confirm new password for 'user2': *****
root@test> user user1
Enter password for user user1: *****
user1@test> config -f table.file.max
2022-10-12T18:24:30,695 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T18:24:30,697 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> createnamespace user1
user1@test> config -ns user1 -f table.file.max
2022-10-12T18:24:49,306 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T18:24:49,307 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T18:24:49,308 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the namespace level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
namespace  |    @override ..................................................... | 30
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> config -ns user1 -s table.file.max=60
user1@test> config -ns user1 -f table.file.max
2022-10-12T18:25:07,215 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T18:25:07,216 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action
2022-10-12T18:25:07,216 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the namespace level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
namespace  |    @override ..................................................... | 60
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> createtable user1.table1
user1@test user1.table1> user user2
Enter password for user user2: *****
user2@test user1.table1> config -ns user1 -f table.file.max
2022-10-12T18:26:00,768 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T18:26:00,770 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T18:26:00,770 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the namespace level.
2022-10-12T18:26:00,772 [shell.Shell] ERROR: User unable to retrieve user1 namespace configuration (requires Namespace.ALTER_NAMESPACE permission)
2022-10-12T18:26:00,772 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
user2@test user1.table1> user user1
Enter password for user user1: *****
user1@test user1.table1> grant Table.ALTER_TABLE -t user1.table1 -u user2
user1@test user1.table1> user user2
Enter password for user user2: *****
user2@test user1.table1> config -t user1.table1 -f table.file.max
2022-10-12T18:26:24,345 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T18:26:24,347 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T18:26:24,351 [shell.Shell] WARN : User unable to retrieve user1 namespace configuration (requires Namespace.ALTER_NAMESPACE permission), error: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
2022-10-12T18:26:24,351 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the table level.
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
table      |    @override ..................................................... | 60
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
user2@test user1.table1> user root
Enter password for user root: ******
root@test user1.table1> config -t user1.table1 -f table.file.max
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max ................................................... | 15
system     |    @override ..................................................... | 30
namespace  |    @override ..................................................... | 60
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------
```

**Review by cshannon — CHANGES_REQUESTED** [review]
I just tested this this looks good to me, nice work @dlmarion . I really like the recent changes here as the messages are very informative/helpful for the user so they know exactly what they are allowed to see. I also think the addition of using the SYSTEM permission check is a good solution as now the root user can see configs so solves that problem.

The only small nit I had is I noticed that when the error message prints for the default namespace it just shows up as an empty space since there's no name:

`2022-10-13T05:36:56,430 [shell.Shell] WARN : User unable to retrieve  namespace configuration (requires Namespace.ALTER_NAMESPACE permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action`

I was thinking maybe we should do something like print it's default if it's the default namespace (empty name), something like this maybe:

`2022-10-13T05:36:56,430 [shell.Shell] WARN : User unable to retrieve 'default' namespace configuration (requires Namespace.ALTER_NAMESPACE permission), error: Error PERMISSION_DENIED for user user1 - User does not have permission to perform this action`

**Review by cshannon — APPROVED** [review]

**Comment by dlmarion** [comment]
@cshannon - I addressed your change request in 8687df0. I also shortened the warning, removing the error message and only printing the warning if the error code is PERMISSION_DENIED.

**Comment by cshannon** [comment]
> @cshannon - I addressed your change request in [8687df0](https://github.com/apache/accumulo/commit/8687df06978bb734e543f4daf6fa8a6415060c3c). I also shortened the warning, removing the error message and only printing the warning if the error code is PERMISSION_DENIED.

LGTM now.

**Comment by dlmarion** [comment]
Here is the latest example. I think this is what we all discussed. I don't have anymore planned changes.


```
root@test> config -f table.file.max
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max .. | 15
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
root@test> config -s table.file.max=30
root@test> config -f table.file.max
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max .. | 15
system     |    @override .... | 30
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
root@test> createuser user1
Enter new password for 'user1': *****
Please confirm new password for 'user1': *****
root@test> grant System.CREATE_NAMESPACE -s -u user1
root@test> createuser user2
Enter new password for 'user2': *****
Please confirm new password for 'user2': *****
root@test> user user1
Enter password for user user1: *****
user1@test> config -f table.file.max
2022-10-13T14:28:02,120 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission)
2022-10-13T14:28:02,121 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission)
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> createnamespace user1
user1@test> config -ns user1 -f table.file.max
2022-10-13T14:28:14,029 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission)
2022-10-13T14:28:14,030 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission)
2022-10-13T14:28:14,031 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the namespace level.
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max .. | 15
namespace  |    @override .... | 30
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> config -ns user1 -s table.file.max=60
user1@test> config -ns user1 -f table.file.max
2022-10-13T14:28:28,287 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission)
2022-10-13T14:28:28,288 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission)
2022-10-13T14:28:28,289 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the namespace level.
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max .. | 15
namespace  |    @override .... | 60
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user1@test> createtable user1.table1
user1@test user1.table1> grant Table.ALTER_TABLE -t user1.table1 -u user2
user1@test user1.table1> user user2
Enter password for user user2: *****
user2@test user1.table1> config -t user1.table1 -f table.file.max
2022-10-13T14:28:55,114 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission)
2022-10-13T14:28:55,116 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission)
2022-10-13T14:28:55,119 [shell.Shell] WARN : User unable to retrieve user1 namespace configuration (requires Namespace.ALTER_NAMESPACE permission)
2022-10-13T14:28:55,119 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the table level.
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max .. | 15
table      |    @override .... | 60
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
user2@test user1.table1> user root
Enter password for user root: ******
root@test user1.table1> config -t user1.table1 -f table.file.max
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME              | VALUE
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.file.max .. | 15
system     |    @override .... | 30
namespace  |    @override .... | 60
-----------+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
root@test user1.table1> user user2
Enter password for user user2: *****
user2@test user1.table1> config -ns ""
2022-10-13T14:31:29,248 [shell.Shell] WARN : User unable to retrieve system configuration (requires System.SYSTEM permission)
2022-10-13T14:31:29,249 [shell.Shell] WARN : User unable to retrieve site configuration (requires System.SYSTEM permission)
2022-10-13T14:31:29,249 [shell.Shell] WARN : User does not have permission to see entire configuration heirarchy. Property values shown below may be set above the namespace level.
2022-10-13T14:31:29,251 [shell.Shell] ERROR: User unable to retrieve default namespace configuration (requires Namespace.ALTER_NAMESPACE permission)
2022-10-13T14:31:29,251 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user user2 - User does not have permission to perform this action
```

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java [hunk 2]
```diff
@@ -667,12 +667,14 @@ void removeProperty(String tableName, String property)
...
    *         recently changed properties may not be visible immediately.
+   * @throws AccumuloSecurityException
+   *           if the user does not have permission
    * @throws TableNotFoundException
    *           if the table does not exist
    * @since 1.6.0
    */
   default Iterable<Entry<String,String>> getProperties(String tableName)
-      throws AccumuloException, TableNotFoundException {
+      throws AccumuloException, AccumuloSecurityException, TableNotFoundException {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:677]: This is a breaking API change, so we probably can't do this. In other places, we sometimes wrap the checked exception in an AccumuloException, in order to avoid changing the API. It's a hack, but it gets around the restriction on breaking the API.

**Review by ctubbsii — COMMENTED** [review]
I like the changes overall, but we're really constrained by semver not to make the breaking API changes.

File: core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java (hunk 2 above)
Comment (cshannon) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java:677]: Can we make this change in 3.0? That might be a good time to clean some of this stuff up with a major version release.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java]: Backed out API changes in a38afd6

**Comment by dlmarion** [comment]
Kicked off full IT build
