### PR TITLE
Fix #933 RuntimeException while stopping Accumulo

### LINKED ISSUE #933: RuntimeException while stopping Accumulo
```
$ ./bin/accumulo-cluster stop
Stopping Accumulo cluster...
2019-02-01 13:50:15,801 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /path/to/accumulo-2.0.0-SNAPSHOT/conf/accumulo.properties
Exception in thread "Thread-2" java.lang.RuntimeException: No files-cache implementation set.
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getCache(AbstractFileSystem.java:209)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getFileFromCache(AbstractFileSystem.java:222)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:332)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFile(AbstractFileObject.java:2007)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFiles(AbstractFileObject.java:2052)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:1222)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.checkForNewChildren(DefaultFileMonitor.java:553)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.check(DefaultFileMonitor.java:667)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.access$200(DefaultFileMonitor.java:423)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor.run(DefaultFileMonitor.java:376)
	at java.lang.Thread.run(Thread.java:748)
Accumulo shut down cleanly
```

### PR DESCRIPTION
**Pull request by jzgithub1**
Upgrade vfs2 to version 2.3 and close vfs more cleanly.

I will keep looking at this issue.

### CODE REVIEW

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java [hunk 1]
```diff
@@ -199,6 +200,9 @@ public AccumuloReloadingVFSClassLoader(String uris, FileSystemManager vfs,
    * thread
    */
   public void close() {
+    for (FileObject file : Arrays.asList(this.files)) {
+      monitor.removeFile(file);
+    }
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Could do something like: `Stream.of(this.files).forEach(monitor::removeFile);` instead.

File: start/pom.xml [hunk 2]
```diff
@@ -45,6 +45,7 @@
     <dependency>
       <groupId>org.apache.commons</groupId>
       <artifactId>commons-vfs2</artifactId>
+      <version>2.3</version>
```
Comment (ctubbsii) [inline start/pom.xml]: This shouldn't be set here. It should be set in the root `pom.xml` file under the `dependencyManagement` section. I see a comment there that it was held back at 2.1 instead of using 2.2 at some point, due to a bug in 2.2. I wonder if those issues have been fixed in 2.3.

Comment (mikewalch) [inline start/pom.xml]: The place to change this is [here](https://github.com/apache/accumulo/blob/c97342000136c731eaf0990bc9aaa33be05ac53a/pom.xml#L433).  There is a note about issues upgrading to 2.2. However, maybe these issues are fixed in 2.3.  You should try tests and ITs related to this and see if a 2.3 update makes sense.

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java [hunk 3]
```diff
@@ -199,6 +200,9 @@ public AccumuloReloadingVFSClassLoader(String uris, FileSystemManager vfs,
    * thread
    */
   public void close() {
+    for (FileObject file : Arrays.asList(this.files)) {
+      monitor.removeFile(file);
```
Comment (mikewalch) [inline start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Interesting fix. Can you explain how this prevents the RuntimeException?  Is the upgrade to 2.3 needed for this change?

**Comment by jzgithub1** [comment]
I don't think it will fix this problem but removing the cache files when the daemon is closing seems like a good idea.  We are running old vfs2 binaries so maybe the problem we are having will get solved with the new version of vfs.  I am trying to get a better handle on how the caching is really working so I can come up with a really  clear solution to this issue.  The pull request is just the best I can come up with now.

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java (hunk 3 above)
Comment (ctubbsii) [reply start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: I was curious about that, too. I'm not even sure we ever bother to close this ClassLoader, so I'm not even sure this would run.

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java [hunk 4]
```diff
@@ -270,6 +270,8 @@ public static FileSystemManager generateVfs() throws FileSystemException {
     vfs.addProvider("tbz2", new org.apache.commons.vfs2.provider.tar.TarFileProvider());
     vfs.addProvider("tgz", new org.apache.commons.vfs2.provider.tar.TarFileProvider());
     vfs.addProvider("bz2", new org.apache.commons.vfs2.provider.bzip2.Bzip2FileProvider());
+    vfs.addProvider("files-cache",
+        new org.apache.commons.vfs2.provider.local.DefaultLocalFileProvider());
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java]: Out of curiosity, why choose this one over the alternatives, such as org.apache.commons.vfs2.cache.SoftRefFilesCache
 (the current default of org.apache.commons.vfs2.impl.DefaultFileSystemManager) or org.apache.commons.vfs2.cache.DefaultFilesCache (the old default for the org.apache.commons.vfs2.impl.DefaultFileSystemManager)?

This isn't a leading question... I'm genuinely curious if there's an advantage of one over another... I don't know the difference between the implementations, or whether it matters.

**Comment by jzgithub1** [comment]
I was getting syntax errors in the Intellij IDE working with the objects in the cache package.  I agree with you.  That looked like the better way to go.  I will give it another look in the morning.

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java (hunk 4 above)
Comment (jzgithub1) [reply start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java]: Those classes don't extend  AbstractFileProvider.  Only the classes under the package 'org.apache.commons.vfs2.provider' have providers from what I see.  You could do:
org.apache.commons.vfs2.impl.DefaultFileSystemManager().addProvider(String urlScheme, FileProvider fileprovider) but then you need to know the urlScheme and the FileProvider implementation or program it.  Then we are introducing new code with chances for regression.

I have not been able to replicate this issue.  I am just assuming that the bug reporter has a different system configuration than mine and a solution I propose disposes of the bug for that situation.  I will keep working on this along with some UI issues.

Comment (ctubbsii) [reply start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java]: Interesting. I wonder if this is just an upstream bug. It seems weird that we'd need to add this provider at all. Perhaps this was fixed in 2.3?

**Comment by jzgithub1** [comment]
@ctubbsii. You had an interesting idea about some xml file where this may be all set up.  Like a context dependency injection type of thing like Spring. They have something like that for the Android OS but I couldn't find a java example for Linux.  I think what I checked in won't produce any runtime errors.  I did test it with Fluo-uno on my system which is running Centos-7.  We are onto a solution here but I think something more customized to our LRU caching is in order.  But that will be a vector for regression and bugs.

**Comment by ctubbsii** [comment]
I don't think we should set up our own dependency injection stuff for VFS... I was mainly just wondering if VFS already supported config-only setup of this stuff, so we can just use it.

Long-term, I'd like to strip VFS out of Accumulo, and instead provide a simple entry point for user-specified (admin-specified) classloader for our existing named context classloaders. I don't think Accumulo should be in the business of maintaining custom classloaders for users inside the project... but should instead empower users to provide their own classloader from outside the project, if they so desire. Then, if they wish to use one that is based on VFS, they are free to do so, but it is their responsibility to initialize it and pass it to Accumulo.

But, that's a long-term vision, and we'd need to get there incrementally. One step could be: do less VFS setup in code, if VFS is already configurable outside of code.

**Comment by jzgithub1** [comment]
I will keep looking around.

**Comment by mjwall** [comment]
VFS has been nothing but headaches.  I would be in favor of ripping it out
completely.

**Comment by jzgithub1** [comment]
I removed the vfs handler for "files-cache" because I don't think it will do anything.  I left the exception handling and logging.

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java [hunk 5]
```diff
@@ -183,12 +184,23 @@ public AccumuloReloadingVFSClassLoader(String uris, FileSystemManager vfs,
...
     }
     monitor.start();
   }
 
+  private void addFileToMonitor(FileObject file) {
+    try {
+      monitor.addFile(file);
+    } catch (RuntimeException re) {
+      if (re.getMessage().contains("files-cache"))
+        log.error("There is no implementation for files-cache in VFS2");
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Nice. Turn the exception into a log message and move on. I like this strategy. It will keep things working, but not prevent us from being able to debug.

One suggestion: please include the stack trace in the log message:

```suggestion
        log.error("files-cache error adding {} to VFS monitor. There is no implementation for files-cache in VFS2", file, re);
```

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java [hunk 6]
```diff
@@ -183,12 +184,23 @@ public AccumuloReloadingVFSClassLoader(String uris, FileSystemManager vfs,
...
+      else
+        log.error(re.getMessage());
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Not sure, but maybe we should re-throw here?

```suggestion
        throw re;
```

At the very least, we should include the stack trace.

```suggestion
        log.error("Unknown error adding {} to VFS monitor", file, re);
```

File: start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java [hunk 7]
```diff
@@ -199,6 +211,12 @@ public AccumuloReloadingVFSClassLoader(String uris, FileSystemManager vfs,
    * thread
    */
   public void close() {
+    try {
+      Stream.of(this.files).forEach(monitor::removeFile);
+    } catch (RuntimeException re) {
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: It might be best to collect all these errors and throw it once at the end:

https://stackoverflow.com/a/30118121/196405

Comment (jzgithub1) [reply start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Great idea.  I will implement that.  Thanks for the style suggestion.

Comment (ctubbsii) [reply start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Since this is a common, reusable pattern, it might be possible to put it into a reusable static method like:

```java
public static <T> void forEachCatchRTEs(Stream<T> stream, Consumer<T> consumer) {
  stream.flatMap(o -> {
￼       try {
         consume(o);
￼         return null;
￼       } catch (RuntimeException e) {
￼         return Stream.of(e);
￼       }
￼     }).reduce((e1, e2) -> {
￼           e1.addSuppressed(e2);
￼           return e1;
￼         }).ifPresent(e -> {
￼           throw e;
￼         });
}
```

Then, each time you need it:

```java
forEachCatchRTEs(pathsToMonitor.stream(), o -> { addFileToMonitor(o); log.debug("monitoring {}", o); });
```

Comment (jzgithub1) [reply start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java]: Thanks for the good idea.   I will put that function in now.
