### PR TITLE
Fixes #600 - TransportCachingIT fills up disk with messages

### LINKED ISSUE #600: TransportCachingIT fills up disk with infinite loop of log messages
Saw this in Jenkins for 2.0. TransportCachingIT fills up the disk (first it filled up a 32GB disk, then when I moved the output to a 240GB disk, it filled that up) with tons of WARNINGs:

```
2018-08-13 17:44:37,310 [test.TransportCachingIT] WARN : Failed to obtain transport to []
2018-08-13 17:44:37,310 [test.TransportCachingIT] WARN : Failed to obtain transport to []
2018-08-13 17:44:37,310 [test.TransportCachingIT] WARN : Failed to obtain transport to []
2018-08-13 17:44:37,310 [test.TransportCachingIT] WARN : Failed to obtain transport to []
```

### PR DESCRIPTION
**Pull request by jzgithub1**
Count the number of times the log message is printed and limit it.   Also kick out of loops after 1000 failed attempts at calling pool.getAnyTransport.

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/TransportCachingIT.java [hunk 1]
```diff
@@ -88,7 +90,14 @@ public void testCachedTransport() throws InterruptedException {
           // Get a transport (cached or not)
           first = pool.getAnyTransport(servers, true).getSecond();
         } catch (TTransportException e) {
-          log.warn("Failed to obtain transport to {}", servers);
+          failTransportCount++;
+          if (failTransportCount > MAX_FAILURES) {
+            log.warn(
+                "Failed to obtain transport to {} over 1000 times and will stop outputing this log message",
+                servers);
+            break;
```
Comment (mikewalch) [inline test/src/main/java/org/apache/accumulo/test/TransportCachingIT.java]: I am not sure what the desired behavior should be but it looks like this `break` will break out of the while loop. Therefore, the log message is not really correct. It's not that you are no longer printing messages, but rather no longer trying to obtain transport. Is that the desired behavior?

**Comment by jzgithub1** [comment]
You have to break out of the while loop to stop calling pool.getAnyTransport and also stop printing out log messages.  Since we govern the amount of log messages we should stop filling up the disk.  You will still see plenty of messages in the logs.

**Comment by jzgithub1** [comment]
I have to shorten the log message.  The style checker doesn't like that.

**Comment by ctubbsii** [comment]
The main problem isn't the infinite set of log messages... the main problem is that the test enters some failure state, and never exits that state. Yes, suppressing the log message will help not fill up disk... but it's also not a solution to the underlying problem of the test never realizing it's in a failure state and continuing forever.

**Comment by jzgithub1** [comment]
I totally agree with you Christopher.  I am really just checking this in as an interim fix.  I should have made that clear.

**Comment by mikewalch** [comment]
> The main problem isn't the infinite set of log messages... the main problem is that the test enters some failure state, and never exits that state. Yes, suppressing the log message will help not fill up disk... but it's also not a solution to the underlying problem of the test never realizing it's in a failure state and continuing forever.

From the error message it looks like the `servers` variable is not getting populated and is an empty list. I bet there is a timing issue and could be fixed with retries.

```
2018-08-13 17:44:37,310 [test.TransportCachingIT] WARN : Failed to obtain transport to []
```

The following code should probably be wrapped in a while loop that repeats (with a 100ms sleep each time) until `servers` is not empty.  There could be a check that just fails the test if this code is retried like 100 times and servers is still empty.

```
    ArrayList<ThriftTransportKey> servers = new ArrayList<>();
      for (String tserver : children) {
        String path = zkRoot + Constants.ZTSERVERS + "/" + tserver;
        byte[] data = ZooUtil.getLockData(zc, path);
        if (data != null) {
          String strData = new String(data, UTF_8);
          if (!strData.equals("master"))
            servers.add(new ThriftTransportKey(
                new ServerServices(strData).getAddress(Service.TSERV_CLIENT), rpcTimeout, context));
        }
      }
```

**Comment by jzgithub1** [comment]
I'll give it a try tomorrow.  Your code is in the vein of what I am trying to do but a better solution.  Thanks.

**Comment by jzgithub1** [comment]
I implemented Mike's recommendation.

**Comment by keith-turner** [comment]
@mikewalch do you think this is ready to merge?
