### PR TITLE
Optimized logic for getting a random TabletServer connection

### LINKED ISSUE #4303: Shell performance issue with large number of tservers
**Describe the bug**
When monitoring zookeeper connections on a large cluster the shell makes 2 * ( number of tservers) + 1 connections to zookeeper on connect when trying to determine tablet server to connect to.

It looks like it is retrieving from ZK:

1. The node that contains all tservers ( in our case `/accumulo/<instance id>/tservers`)
2. The list of locks under `/accumulo/<instance id>/tservers/<server id>`
3. The lock at `/accumulo/<instance id>/tservers/<server id>/<lock id>`

It would make sense to cut this off once it has a valid tserver, until such time as talking to other tservers is necessary.

**Versions (OS, Maven, Java, and others, as appropriate):**
Affected Version -  2.1.2

**To Reproduce**
1. Enable ZK logging at DEBUG
2. Connect to shell, monitoring ClientCnxn messages from zk
3. Observe requests to ZK for each tserver

**Expected behavior**
Accumulo should only make as many connections as necessary to function. Making extra calls wastes time and resources.

**Additional context**
This problem would probably not have a noticable affect on small systems.

### PR DESCRIPTION
**Pull request by dlmarion**
The previous logic in this class would gather all of the Tserver ZNodes in ZooKeeper, then get the data for each ZNode and validate their ServiceLock. Then, after all of that it would randomly pick one of the TabletServers to connect to. It did this through the ZooCache object which on an initial connection would be empty and causes a lot of back and forth to ZooKeeper. The side effect of this is that the ZooCache would be populated with TabletServer information.

This change modifies the ClientContext to populate the ZooCache in a single-shot background task and modifies the default logic for getting a connection to a TabletServer. The new logic will make 2 calls to ZooKeeper in the best case scenario, one to get the list of TServer ZNodes in Zookeeper and another to get the ZNode data for one of them.

Fixes #4303

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 1]
```diff
@@ -57,44 +60,54 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
-          ServiceLock.path(context.getZooKeeperRoot() + Constants.ZTSERVERS + "/" + tserver);
-      byte[] data = zc.getLockData(zLocPath);
-      if (data != null) {
-        String strData = new String(data, UTF_8);
-        if (!strData.equals("manager")) {
-          servers.add(new ThriftTransportKey(
-              new ServerServices(strData).getAddress(Service.TSERV_CLIENT), rpcTimeout, context));
+    final ZooCache zc = context.getZooCache();
+    final List<String> tservers = new ArrayList<>();
+    final AtomicBoolean warnedAboutTServersBeingDown = new AtomicBoolean(false);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:67]: There is a method argument passed in named `warned`, it should probably be used instead.  I think that variable is used among many threads and prevents lots of threads from separately attempting to log the same warning.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 2]
```diff
@@ -57,44 +60,54 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
-            LOG.warn("Failed to find an available server in the list of servers: {}", servers);
+      // Try to connect to an online tserver
+      Collections.shuffle(tservers);
+      for (String tserver : tservers) {
+        var zLocPath =
+            ServiceLock.path(context.getZooKeeperRoot() + Constants.ZTSERVERS + "/" + tserver);
+        byte[] data = zc.getLockData(zLocPath);
+        if (data != null) {
+          String strData = new String(data, UTF_8);
+          if (!strData.equals("manager")) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:93]: This is a pre-existing problem unrelated to this PR.  Is there a constant we could use here instead of the literal `"manager"`?  I  took a quick look around and did not find anything.  I can open an issue about this if needed.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 3]
```diff
@@ -57,44 +60,54 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
-      if (data != null) {
-        String strData = new String(data, UTF_8);
-        if (!strData.equals("manager")) {
-          servers.add(new ThriftTransportKey(
-              new ServerServices(strData).getAddress(Service.TSERV_CLIENT), rpcTimeout, context));
+    final ZooCache zc = context.getZooCache();
+    final List<String> tservers = new ArrayList<>();
+    final AtomicBoolean warnedAboutTServersBeingDown = new AtomicBoolean(false);
+
+    for (int retries = 0; retries < 10; retries++) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:69]: The existing code did not retry and poking around it seems that code that calls this method does retry at higher levels. It would probably be better to not retry here and defer to the calling code.  Although I don't fully understand the overall behavior of the existing code when the set of tservers in ZK is empty, sitll trying to understand that.  Not exaclty sure how the existing code would retry. It seems like the addition of throwing TTransportException in this PR will help with the higher level code that retries, but not sure how it worked before these changes.

**Review by keith-turner — COMMENTED** [review]
With the changes in this PR [this method](https://github.com/apache/accumulo/blob/c72bf8c00cb196d048d1aa35077327c55d6e58e2/core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java#L128) may only be called by test code now, so may be able to clean up and adjust the test code.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 3 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:69]: This is [one example](https://github.com/apache/accumulo/blob/c72bf8c00cb196d048d1aa35077327c55d6e58e2/core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java#L100-L125) of code I was looking at where retry happens at a higher level that calls this method indirectly.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java [hunk 4]
```diff
@@ -249,6 +251,27 @@ public ClientContext(SingletonReservation reservation, ClientInfo info,
         clientThreadPools = ThreadPools.getClientThreadPools(ueh);
       }
     }
+    // Kick off a task to try and populate the ZooCache with TabletServer
+    // information. It may not be complete as the cluster may be starting.
+    // It's a best effort
+    clientThreadPools
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java:257]: I have no issue removing this, I was just trying to keep the same behavior - the current code loads ZooCache on first connection, which is the cause of the delay. You are suggesting that we don't need to preload ZooCache? Do you think there is a downside to removing this?

[the remark this answers is not in the document]
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java:257]: > You are suggesting that we don't need to preload ZooCache?

Thinking in a client instance that is busy that eventually the cache will be populated.  On a client that is not busy the cache will not be populated, but thats ok it does not need the data.

> Do you think there is a downside to removing this?

There may be a downside, but can not think of something specific.  Thinking we are not sure if there is an upside and the behavior could cause uneeded ZK load, so maybe its ok to omit.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 3 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java]: I removed the retry and while loop in aecd790

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 2 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java]: We probably need an issue for this then.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java]: Good catch. I used the warn variable in aecd790

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java]: I removed this in in aecd790

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 5]
```diff
@@ -57,44 +60,54 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
       ClientContext context, boolean preferCachedConnections, AtomicBoolean warned)
       throws TTransportException {
     checkArgument(context != null, "context is null");
-    long rpcTimeout = context.getClientTimeoutInMillis();
-    // create list of servers
-    ArrayList<ThriftTransportKey> servers = new ArrayList<>();
+    final long rpcTimeout = context.getClientTimeoutInMillis();
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java]: I'm using the preferCachedConnections parameter and implemented something in ThriftTransportPool in in aecd790

**Comment by dlmarion** [comment]
> With the changes in this PR [this method](https://github.com/apache/accumulo/blob/c72bf8c00cb196d048d1aa35077327c55d6e58e2/core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportPool.java#L128) may only be called by test code now, so may be able to clean up and adjust the test code.

I  got rid of the method in aecd790

**Review by ctubbsii — COMMENTED** [review]
I'm still in process of reviewing this, but based on the description, I'm not sure it needs to populate ZK in a single shot background process. It should only populate it as-needed, on access. But, I do think there's value in changing the logic, so it doesn't require accessing ZK so much to pick a random server. It should be able to pick a random potential server first, check to see if it has a lock and other checks (basically by doing the same thing that the pre-populated retrieval was doing), and then pick a different one if that first random one is not acceptable. That will still eventually populate the cache, on access, but not waste time pre-populating it before randomly picking one, since there's a high probability that the first one chosen will be acceptable.

I will have to finish reviewing this PR to see if the changes here implement that behavior, and if not, how it differs from what I described. If it differs, I'd be curious to know in what way, and whether that is better than what I described.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java [hunk 6]
```diff
@@ -81,7 +92,7 @@ public boolean equals(Object o) {
       return false;
     }
     ThriftTransportKey ttk = (ThriftTransportKey) o;
-    return server.equals(ttk.server) && timeout == ttk.timeout
+    return type.equals(ttk.type) && server.equals(ttk.server) && timeout == ttk.timeout
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java:95]: Looked at ThriftClientTypes and did not see that it implements equals() or hashCode().  Seems like the intention is that there is only one instance of type in the JVM so its ok to fall back to the object hashCode.  This makes it tricky to reason about the correctness, not sure of a way to improve this.  If possible it would be good to reduce/localize the amount of assumptions being made around this.  Thought through the following possible solutions, but they seemed like dead ends.

 * could we make ThriftClientTypes an enum?  Does not seem like this would work with the type parameter.
 * could we make ThriftClientTypes constructor private?  This makes it easier to reason about single instances.  The subclasses would probably need to be pulled in as inner classes to do this.  Not sure if its workable even then though.
 * could we add equals and hashCode impls that only look at the service name?  This feels dubious because it excludes the factory

This issue does not need to hold up this PR if the current code does only create a single instance per type in the JVM.  Did not attempt to verify if this is the case or not.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 7]
```diff
@@ -57,44 +59,56 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
+
+    final long rpcTimeout = context.getClientTimeoutInMillis();
+    final ZooCache zc = context.getZooCache();
+    final List<String> tservers = new ArrayList<>();
+
+    tservers.addAll(zc.getChildren(context.getZooKeeperRoot() + Constants.ZTSERVERS));
+
+    if (tservers.isEmpty()) {
+      if (warned.compareAndSet(false, true)) {
+        LOG.warn("There are no tablet servers: check that zookeeper and accumulo are running.");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:81]: Is this code used for more than tservers now?  Should the log message replace `tablet servers` with the type?

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 8]
```diff
@@ -57,44 +59,56 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
+            warned.set(false);
+            return new Pair<String,C>(tserverClientAddress.toString(), client);
+          } catch (TTransportException e) {
+            LOG.trace("Error creating transport to {}", tserverClientAddress);
+            continue;
           }
         }
       }
     }
+    LOG.warn("Failed to find an available server in the list of servers: {}", tservers);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:110]: Maybe this should use the warned atomic bool.  Also could include the type in the log message.

File: core/src/test/java/org/apache/accumulo/core/clientImpl/ThriftTransportKeyTest.java [hunk 9]
```diff
@@ -136,8 +138,8 @@ public void testSimpleEquivalence() {
 
     replay(clientCtx);
 
-    ThriftTransportKey ttk =
-        new ThriftTransportKey(HostAndPort.fromParts("localhost", 9999), 120_000, clientCtx);
+    ThriftTransportKey ttk = new ThriftTransportKey(ThriftClientTypes.CLIENT,
+        HostAndPort.fromParts("localhost", 9999), 120_000, clientCtx);
 
     assertEquals(ttk, ttk, "Normal ThriftTransportKey doesn't equal itself");
```
Comment (keith-turner) [inline core/src/test/java/org/apache/accumulo/core/clientImpl/ThriftTransportKeyTest.java:144]: This is a preexisting problem with this test, would be nice to make it follow the pattern in the other existing test.

```suggestion
    assertEquals(ttk, ttk, "Normal ThriftTransportKey doesn't equal itself");
    assertEquals(ttk.hashCode(), ttk.hashCode());
```

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java [hunk 10]
```diff
@@ -57,44 +59,56 @@ default Pair<String,C> getTabletServerConnection(Logger LOG, ThriftClientTypes<C
...
+    throw new TTransportException("Failed to connect to any server");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:111]: could include type in the message

**Review by keith-turner — APPROVED** [review]

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java (hunk 6 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java:95]: > could we make ThriftClientTypes an enum? Does not seem like this would work with the type parameter.

IIRC I tried this when I originally created ThriftClientTypes and it didn't work with the generics

> could we make ThriftClientTypes constructor private? This makes it easier to reason about single instances. The subclasses would probably need to be pulled in as inner classes to do this. Not sure if its workable even then though.

I think we could probably make it `protected` vs `public`, or remove the modifier and make it package protected. I looked at all of the impls and their constructors have no modifier, so they are package protected.

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 7 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:81]: > Is this code used for more than tservers now? 

No, it's only used by the ClientServiceThriftClient (the generic Client API) and the TabletServerThriftClient (for the TabletClientService).

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java (hunk 6 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ThriftTransportKey.java:95]: I could not make ThriftClientTypes constructor package protected. The ThriftProcessorTypes class in server-base needs access. I was able to make it `protected` however in 1a3d5e0

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 8 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:110]: Added this in 1a3d5e0

File: core/src/test/java/org/apache/accumulo/core/clientImpl/ThriftTransportKeyTest.java (hunk 9 above)
Comment (dlmarion) [reply core/src/test/java/org/apache/accumulo/core/clientImpl/ThriftTransportKeyTest.java:144]: Added this in 1a3d5e0

File: core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java (hunk 10 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java:111]: Added this in 1a3d5e0

**Comment by dlmarion** [comment]
Full IT build based off commit aecd79064602b2dca413e4274e2c1ba98bbfc048 passed successfully.
