### PR TITLE
Fix #1273 Fix Bulk Messages

### LINKED ISSUE #1273: Master prints unnecessary warnings about bulk import _SUCCESS and loadmap.json files
Saw the following in the monitor (coming from the master logs) while testing 2.0.0 with accumulo-testing's `bin/cingest bulk`:

```
hdfs://burninator:8020/tmp/bt/15/files/_SUCCESS does not have a valid extension, ignoring
hdfs://burninator:8020/tmp/bt/15/files/loadmap.json does not have a valid extension, ignoring
```

I'm pretty sure these files are expected, and shouldn't trigger any warnings.

### PR DESCRIPTION
**Pull request by hkeebler**
Improved some of the logging and messages during a Bulk Import.

Note that TabletServer.java came along for the ride.

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/file/FileOperations.java [hunk 1]
```diff
@@ -42,10 +42,18 @@
...
 
+  // Sometimes we want to know what files accumulo creates
+  private static final HashSet<String> workingFiles =
+      new HashSet<>(Arrays.asList(Constants.BULK_LOAD_MAPPING, Constants.BULK_RENAME_FILE));
+
   public static Set<String> getValidExtensions() {
     return validExtensions;
   }
 
+  public static Set<String> getWorkingFiles() {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/file/FileOperations.java]: Since this method is not in a class that only deals with bulk import a more specific name like `getBulkWorkingFiles()` would be better.

File: server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java [hunk 2]
```diff
@@ -179,37 +181,23 @@ private void checkForMerge(final Master master) throws Exception {
...
+      // since these are only valid files we know it has an extension
+      String newName =
+          "I" + namer.getNextName() + "." + FilenameUtils.getExtension(file.getPath().getName());
+      oldToNewNameMap.put(file.getPath().getName(), new Path(bulkDir, newName).getName());
     }
 
     // also have to move mapping file
-    Path newMappingFile = new Path(bulkDir, mappingFile.getName());
-    oldToNewNameMap.put(mappingFile.getName(), newMappingFile.getName());
+    oldToNewNameMap.put(mappingFile.getName(), new Path(bulkDir, mappingFile.getName()).getName());
```
Comment (keith-turner) [inline server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java]: seems like this could be further simplified like :

```java
oldToNewNameMap.put(mappingFile.getName(), mappingFile.getName());
```

File: server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java [hunk 3]
```diff
@@ -179,37 +181,23 @@ private void checkForMerge(final Master master) throws Exception {
     VolumeManager fs = master.getFileSystem();
     final UniqueNameAllocator namer = master.getContext().getUniqueNameAllocator();
     Path sourceDir = new Path(bulkInfo.sourceDir);
-    FileStatus[] files = fs.listStatus(sourceDir);
+    List<FileStatus> files = BulkImport.filterInvalid(fs.listStatus(sourceDir));
```
Comment (keith-turner) [inline server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java]: very nice

File: server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java (hunk 2 above)
Comment (hkeebler) [reply server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java]: except the latter is a "new" directory path "bulkdir"

File: core/src/main/java/org/apache/accumulo/core/file/FileOperations.java (hunk 1 above)
Comment (hkeebler) [reply core/src/main/java/org/apache/accumulo/core/file/FileOperations.java]: Yes.  I'm not sure if FileOperations is the best place but getValidExtensions was there.

File: server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java (hunk 2 above)
Comment (milleruntime) [reply server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java]: Yeah I think @keith-turner is correct.  The map should just contain the name of the mappingFile.  Since it won't change, it will just be the same name again.  It looks strange but it should work with the next step, which is the move.

Comment (keith-turner) [reply server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java]: But I don't think the bulkDir matters.  I wrote the following test program

```java
public class Test {
  public static void main(String[] args) {
    Path mappingFile = new Path("/some/source", Constants.BULK_LOAD_MAPPING);
    
    System.out.println("name 1 : " + mappingFile.getName());
    
    new Path("/some/bulk", mappingFile.getName()).getName();
    
    System.out.println("name 2 : " +  new Path("/some/bulk", mappingFile.getName()).getName());
  }
}
```

Which prints :

```
name 1 : loadmap.json
name 2 : loadmap.json
```

File: core/src/main/java/org/apache/accumulo/core/file/FileOperations.java (hunk 1 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/file/FileOperations.java]: Yeah it feels like it should go elsewhere, but I am not sure where.  I think its ok where it is if it has a more specific name.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/file/FileOperations.java]: You could put it in BulkImport since its only used by the bulk import classes.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java [hunk 4]
```diff
@@ -449,31 +450,31 @@ private Text toText(byte[] row) {
...
     for (FileStatus fileStatus : files) {
 
       String fname = fileStatus.getPath().getName();
 
+      if (fileStatus.isDirectory()) {
+        log.debug("{} is a directory, ignoring.", fileStatus.getPath());
+        continue;
+      }
+
       if (fname.equals("_SUCCESS") || fname.equals("_logs")) {
```
Comment (milleruntime) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: It would be good to add these files to the list of working files.

Comment (hkeebler) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: Agree, they are hadoop working files that occur during the Bulk processing. Also, found a hadoop constant ...FileOutputCommitter.SUCCEEDED but can not locate a constant for "_logs".

**Comment by hkeebler** [comment]
Limited the new BulkImport unit test to FilterInvalid since that is what was altered and it was easy to test.  Some of the other static methods require a richer test environment setup and more time to complete.  Ultimately it would be good to check the logging in the test , i.e., what type of file is logged as debug, warn and message type but again I was having trouble determining a good way to test that and didn't see in any existing tests that something like that had been done before.
