### PR TITLE
Use LogEntry to parse log entries

### LINKED ISSUE #4065: WALSunnyDayIT test failure.
**Describe the bug**
The WALSunnyDayIT test is failing wit what seems to be a constraint violation when run from current main branch (4d38127e5a)

From the manager log:
```
2023-12-13T19:07:30,209 [constraints.MetadataConstraints] DEBUG: violating metadata mutation : +r<
2023-12-13T19:07:30,209 [constraints.MetadataConstraints] DEBUG:  update: future:1000137ff6a0004 value [delete]
2023-12-13T19:07:30,209 [constraints.MetadataConstraints] DEBUG:  update: loc:1000137ff6a0004 value [delete]
2023-12-13T19:07:30,209 [constraints.MetadataConstraints] DEBUG:  update: log:-/file:[..deleted..]/target/mini-tests/org.apache.accumulo.test.functional.WALSunnyDayIT_test/accumulo/wal/ip-10-113-15-130+39093/9e1553ad-e353-486a-8e0e-419b680e0031 value 
2023-12-13T19:07:30,209 [constraints.MetadataConstraints] DEBUG:  update: log:-/file:[...deleted...]/test/target/mini-tests/org.apache.accumulo.test.functional.WALSunnyDayIT_test/accumulo/wal/ip-10-113-15-130+39093/6f156a10-949e-402e-b212-249c9b34a791 value 
2023-12-13T19:07:30,209 [manager.Manager] ERROR: Error processing table state for store Root Table
java.lang.IllegalStateException: Mutation for root tablet metadata violated constraints : [6, 6]
	at org.apache.accumulo.server.metadata.RootTabletMutatorImpl.mutate(RootTabletMutatorImpl.java:87) ~[accumulo-server-base-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.server.manager.state.ZooTabletStateStore.unassign(ZooTabletStateStore.java:185) ~[accumulo-server-base-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.server.manager.state.LoggingTabletStateStore.unassign(LoggingTabletStateStore.java:76) ~[accumulo-server-base-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.TabletGroupWatcher.handleDeadTablets(TabletGroupWatcher.java:1385) ~[accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.TabletGroupWatcher.flushChanges(TabletGroupWatcher.java:1436) ~[accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.TabletGroupWatcher.run(TabletGroupWatcher.java:372) [accumulo-manager-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT]

```

### PR DESCRIPTION
**Pull request by ctubbsii**
Use LogEntry.fromMetaWalEntry to parse log entries from the metadata table in MetaDataTableScanner. It previously implemented a manual parsing of a very old and outdated schema that just happened to still work with the current format.

This fixes #4065 and will be compatible with the changes in PR #3997.

### CODE REVIEW

**Review by EdColeman — DISMISSED** [review]

**Review by EdColeman — COMMENTED** [review]
There is a compile error

**Comment by ctubbsii** [comment]
The previous build failure was because I tried to apply this to the 2.1 branch. But LogEntry is too different there and I didn't realize that when I cherry-picked it to 2.1. The incorrect parsing is still happening in 2.1, but it has no impact, so it's fine to leave alone in 2.1 and only fix with the newer LogEntry improvements in 3.1. I cherry-picked it back to main and force pushed.

File: server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java [hunk 1]
```diff
@@ -176,8 +176,7 @@ public static TabletLocationState createTabletLocationState(Key k, Value v)
         }
         current = location;
       } else if (cf.compareTo(LogColumnFamily.NAME) == 0) {
-        String[] split = entry.getValue().toString().split("\\|")[0].split(";");
-        walogs.add(Arrays.asList(split));
+        walogs.add(Collections.singleton(LogEntry.fromMetaWalEntry(entry).getFilePath()));
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java:179]: There's probably additional room for improvement in here, because walogs doesn't need to be a collection of collections of strings anymore (probably), but this is a sufficient fix for now. I can look at more changes later.

**Review by EdColeman — APPROVED** [review]
