### PR TITLE
Fix ImportConfiguration.builder().setKeepOffline()

### LINKED ISSUE #4045: ImportConfiguration.builder().setKeepOffline(true) does not create a table offline - table stuck in NEW state
**Describe the bug**
A table gets stuck in the `NEW` state when the scenario below happens. See comments in the code.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.3-SNAPSHOT and 3.1.0-SNAPSHOT

**To Reproduce**
Run the test added this branch: [DomGarguilo:accumulo:newTableStateBug] (https://github.com/DomGarguilo/accumulo/tree/newTableStateBug). This was branched from 3.1.0-SNAPHOT but the changes can also be applied to 2.1.
Pasted here in case the branch ever gets deleted. This test case was added to ImportExportIT:
```java
@Test
  public void testBug() throws Exception {
    try (AccumuloClient client = Accumulo.newClient().from(getClientProps()).build()) {

      String[] tableNames = getUniqueNames(3);
      String srcTable = tableNames[0], destTable1 = tableNames[1], destTable2 = tableNames[2];
      client.tableOperations().create(srcTable);

      try (BatchWriter bw = client.createBatchWriter(srcTable)) {
        for (int row = 0; row < 1000; row++) {
          Mutation m = new Mutation("row_" + String.format("%010d", row));
          for (int col = 0; col < 100; col++) {
            m.put(Integer.toString(col), "", Integer.toString(col * 2));
          }
          bw.addMutation(m);
        }
      }

      final Path testDir = new Path("/tmp/manysplitsTableExport");
      final Path tableExportDir = new Path(testDir, srcTable);
      final Path copyDir = new Path(testDir, "_tmp");
      FileSystem fs = cluster.getFileSystem();
      fs.delete(testDir, true); // remove the dir if it exists from a previous run
      fs.mkdirs(tableExportDir);
      fs.mkdirs(copyDir);

      log.info("Exporting table data to {}", tableExportDir);
      client.tableOperations().offline(srcTable);
      client.tableOperations().exportTable(srcTable, tableExportDir.toString());
      // copy files
      try (FSDataInputStream fsDataInputStream = fs.open(new Path(tableExportDir, "distcp.txt"));
          InputStreamReader inputStreamReader = new InputStreamReader(fsDataInputStream, UTF_8);
          BufferedReader reader = new BufferedReader(inputStreamReader)) {
        String file;
        while ((file = reader.readLine()) != null) {
          Path src = new Path(file);
          Path dest = new Path(copyDir, src.getName());
          FileUtil.copy(fs, src, fs, dest, false, true, cluster.getServerContext().getHadoopConf());
        }
      }

      // create the table before trying to import to it
      client.tableOperations().create(destTable1);

      ImportConfiguration importConfig =
          ImportConfiguration.builder().setKeepOffline(true).setKeepMappings(true).build();

      // since the table already exists we expect this to be thrown
      assertThrows(TableExistsException.class, () -> client.tableOperations()
          .importTable(destTable1, Set.of(copyDir.toString()), importConfig));

      client.tableOperations().importTable(destTable2, Set.of(copyDir.toString()), importConfig);

      Map<String,String> tableIdMap = getServerContext().tableOperations().tableIdMap();
      TableId tid = TableId.of(tableIdMap.get(destTable2));
      var context = getServerContext();

      // for some reason when we try to import to a table that already exists and then use that same
      // dir to import to another table (that doesn't yet exist) the new table is created but does
      // not leave the NEW table state.
      Wait.waitFor(() -> context.getTableState(tid) != TableState.NEW, SECONDS.toMillis(30),
          SECONDS.toMillis(1), "Table stuck in NEW table state");

    }
  }
```

**Expected behavior**
A table should not get stuck in `NEW` table state

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #4045 

This PR adds logic to properly transition the state of a new table created via `importTable()` to offline (or online) depending on the value supplied via the `ImportConfiguration`.

This was corrected by the change in `FinishImportTable` where the table was never transitioned from the NEW to OFFLINE table state when the (then `onlineTable`) param was set.

Other changes:
* added a check in the IT to make sure the new table is in the OFFLINE state instead of just "not online"
* renamed the member variable from `onlineTable` to `keepOffline` for clarity and consistency

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/ImportExportIT.java [hunk 1]
```diff
@@ -294,6 +295,7 @@ public void testExportImportOffline() throws Exception {
 
       // verify the new table is offline
       assertFalse(client.tableOperations().isOnline(destTable), "Table should have been offline.");
+      assertEquals(getServerContext().getTableState(TableId.of(tableId)), TableState.OFFLINE);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/ImportExportIT.java:298]: Does the following sound correct?  Want to make sure I understand these changes.

 * Without these changes the table would be in the new state, so `client.tableOperations().isOnline(destTable)` would have returned false.  
 * The call to `client.tableOperations().online(destTable, true)` just kinda fix things for the rest of the test.

If that is true, it makes me wonder if the call `client.tableOperations().online(destTable, true)` should be a bit more strict about what table states it will transition.

**Review by keith-turner — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/ImportExportIT.java (hunk 1 above)
Comment (DomGarguilo) [reply test/src/main/java/org/apache/accumulo/test/ImportExportIT.java:298]: Yea I think you are understanding things correctly.

I think it could make sense to be more strict about transition states but could that cause issues if a similar situation arises where a table is stuck in a state and we want to manually transition it but if the tableOp does not allow for it, then it would be really stuck without being able to manually transition. For example if for some reason a table is stuck in NEW and we want to online it but that is not an allowed transition, then it would remain stuck in that state.

Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/ImportExportIT.java:298]: Yeah it can fix things, but it can also hide bugs in other parts of the code.  If it were more strict maybe this bug would have been found sooner.  I think it would be good to make it more strict and leave fixing buggy situations to something else like zookeeper surgery or a specialized tool if the need arises frequently enough.
