### PR TITLE
fixes #1111 support reading unencrypted WALs from 1.9

### LINKED ISSUE #1111: Unable to upgrade from 1.9 to 2.0 with walogs
I tried to upgrade a 1.9 instance that was not cleanly shutdown to 2.0.  The upgrade failed because the write ahead logs were unreadable.

```
2019-04-18 19:17:17,468 [log.DfsLogger] ERROR: Unsupported WAL version.
2019-04-18 19:17:17,468 [log.DfsLogger] ERROR: Unsupported WAL version.
2019-04-18 19:17:17,504 [log.LogSorter] ERROR: Caught throwable
java.io.IOException: Invalid LogEvent type, got ordinal 45, but only know about 6 possible types.
        at org.apache.accumulo.tserver.logger.LogFileKey.readFields(LogFileKey.java:46)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.sort(LogSorter.java:138)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.process(LogSorter.java:92)
        at org.apache.accumulo.server.zookeeper.DistributedWorkQueue$1.run(DistributedWorkQueue.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
2019-04-18 19:17:17,508 [log.LogSorter] ERROR: Caught throwable
java.io.IOException: Invalid LogEvent type, got ordinal 45, but only know about 6 possible types.
        at org.apache.accumulo.tserver.logger.LogFileKey.readFields(LogFileKey.java:46)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.sort(LogSorter.java:138)
        at org.apache.accumulo.tserver.log.LogSorter$LogProcessor.process(LogSorter.java:92)
        at org.apache.accumulo.server.zookeeper.DistributedWorkQueue$1.run(DistributedWorkQueue.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by keith-turner**
Also fixed a problem in VerifyIngest that I found while trying to use it for upgrade testing.

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java [hunk 1]
```diff
@@ -361,11 +361,16 @@ public static DFSLoggerInputStreams readHeaderAndReturnStream(FSDataInputStream
       AccumuloConfiguration conf) throws IOException {
     DataInputStream decryptingInput;
 
-    byte[] magic = DfsLogger.LOG_FILE_HEADER_V4.getBytes(UTF_8);
-    byte[] magicBuffer = new byte[magic.length];
+    byte[] magic4 = DfsLogger.LOG_FILE_HEADER_V4.getBytes(UTF_8);
+    byte[] magic3 = DfsLogger.LOG_FILE_HEADER_V3.getBytes(UTF_8);
+
+    if (magic4.length != magic3.length)
+      throw new IllegalStateException();
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java]: This could use a message. Could also use AssertionError here, since it's being used that way.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java [hunk 2]
```diff
@@ -375,10 +380,19 @@ public static DFSLoggerInputStreams readHeaderAndReturnStream(FSDataInputStream
...
+        String cryptoModuleClassname = input.readUTF();
+        if (!cryptoModuleClassname.equals("NullCryptoModule")) {
+          throw new IllegalArgumentException(
+              "Old encryption modules not supported at this time.  Unsupported module : "
+                  + cryptoModuleClassname);
+        }
+
         decryptingInput = input;
+      } else {
+        throw new IllegalArgumentException(
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java]: This will catch immediately in the catch block below, and print the incorrect message about getting an EOFException (which isn't true in this case). This is probably doing the right thing, but the catch block should be corrected to match.

Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java]: Good catch.  I am going to change it to catch EOFException, which seems like the right thing to do.  The change could cause it fail in some cases where it used to succeed.  However the current code could succeed when it should fail.

Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java]: I think that would be misleading to a user debugging the failure. The end of file hasn't been reached. Rather, the content in the file is unexpected. I think it would be better to simply update the message in the catch block, since there is more than one exception which could be caught there.

Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java]: @ctubbsii  is your last comment about the code before or after b3f9d45 ?

Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java]: I misunderstood that you were going to throw EOFException, not catch it. Catching the more specific error makes sense to me... but we should take care that the RTE that will now fall through is handled (or propagated) appropriately by the caller(s).

From a quick examination, it looks like the callers are also logging... so you should probably just include whatever message stuff you want in the thrown exception, instead of logging first, and then throwing it, where it will be logged again, and then thrown again... etc.
