### PR TITLE
Print exceptions that cause the server process to exit to stderr

### LINKED ISSUE #2885: Log4j2 Async Logging may not log error before Process terminates
Was setting up a new install of 2.1.0-SNAPSHOT. I added the property for the context class loader factory class to accumulo.properties with the default value. This was a mistake on my part as it sends the code down the wrong path and a NoSuchMethodException was being thrown from ClassloaderUtil as part of the server startup. The problem was that nothing was logged and all of the server processes were terminating at the same exact place. Disabling the log4j2 async logging, by commenting out [this](https://github.com/apache/accumulo/blob/main/assemble/conf/accumulo-env.sh#L107) property, enabled the exception to be logged before the process exited.

I wonder if there is a way to programmatically turn on async logging after the server process initializes.

### PR DESCRIPTION
**Pull request by dlmarion**
Async Logging may not flush the exception to the file before the
process terminates. Print the error to stderr as well.

Closes #2885

### CODE REVIEW

File: start/src/main/java/org/apache/accumulo/start/Main.java [hunk 1]
```diff
@@ -51,26 +51,23 @@ public static void main(final String[] args) throws Exception {
       var deprecatedConfClass = org.apache.accumulo.start.classloader.AccumuloClassLoader
           .getClassLoader().loadClass("org.apache.hadoop.conf.Configuration");
       confClass = deprecatedConfClass;
+      Object conf = null;
```
Comment (EdColeman) [inline start/src/main/java/org/apache/accumulo/start/Main.java:54]: null initializer is redundant (as is the one for `confClass` at line 48)

**Review by EdColeman — APPROVED** [review]

File: start/src/main/java/org/apache/accumulo/start/Main.java (hunk 1 above)
Comment (dlmarion) [reply start/src/main/java/org/apache/accumulo/start/Main.java:54]: Redundant, but not an error / issue. I assume the compiler does the right thing. I didn't write it, I just moved lines around.

Comment (EdColeman) [reply start/src/main/java/org/apache/accumulo/start/Main.java:54]: While you are in the neighborhood - its a chance to remove a checkstyle warning and a) means we don't need to clean it up later and b) makes finding other checkstyle issues because there  would be 2 fewer if you fix both now.

**Comment by ctubbsii** [comment]
Ideally, instead of explicitly printing, we should just make sure the exception gets thrown out of the main method... let the JVM do its own printing to STDERR, as this is the expected behavior.
