### PR TITLE
Fix wait timeout logic for available tservers

### LINKED ISSUE #3159: Tserver wait timeout is not forcing startup to continue
**Describe the bug**
If accumulo is started with the following properties, startup will exceed `5min` as `max.wait` never forces the startup process to continue. 
`master.startup.tserver.avail.min.count=<# of tservers>`
`master.startup.tserver.avail.max.wait=5min`

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.10.x, 2.1.x

**To Reproduce**
I used [Fluo-uno](https://github.com/apache/fluo-uno) to replicate this bug:
Note: The minimum number of tservers available should be set higher than your expected total tserver count.

***Accumulo 1.10.2***
1. Add the following properties to `conf/accumulo/1/accumulo-site.xml`
```
<property>
   <name>master.startup.tserver.avail.max.wait</name>
   <value>5m</value>
</property>
<property>
    <name>master.startup.tserver.avail.min.count</name>
    <value>3</value>
</property>
```
 2. Modify the `ACCUMULO_VERSION` in `conf/uno.conf` to match 1.10.2. 
`export ACCUMULO_VERSION=${ACCUMULO_VERSION:-1.10.2}`

3. Fetch & Start accumulo
`source <(./bin/uno env)`
`uno fetch accumulo`
`uno start accumulo`

4. View logs to see startup continuing to be blocked after 300 seconds 
`tail -f install/logs/accumulo/master_<hostname>.log`
```
2023-01-10 03:53:22,451 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 15 sec.
2023-01-10 03:53:52,501 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 45 sec.
2023-01-10 03:54:37,552 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 90 sec.
2023-01-10 03:55:37,602 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 150 sec.
2023-01-10 03:56:52,652 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 225 sec.
2023-01-10 03:58:22,703 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 315 sec.
2023-01-10 04:00:07,753 [master.Master] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 420 sec.
```

***Accumulo 2.1***
1. Add the following properties to `fluo-uno/conf/accumulo/2/accumulo.properties`
```
manager.startup.tserver.avail.min.count=3
manager.startup.tserver.avail.max.wait=5m
```
2. Fetch & start accumulo
`source <(./bin/uno env)`
`uno fetch accumulo`
`uno setup accumulo`

4. View logs to see startup continuing to be blocked after 300 seconds
`cat install/logs/accumulo/manager_<hostname>.log | grep Blocking`
```
2023-01-11T13:46:08,511 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 0 sec.
2023-01-11T13:46:23,562 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 15 sec.
2023-01-11T13:46:53,612 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 45 sec.
2023-01-11T13:47:38,662 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 90 sec.
2023-01-11T13:48:38,713 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 150 sec.
2023-01-11T13:49:53,763 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 225 sec.
2023-01-11T13:51:23,813 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 315 sec.
2023-01-11T13:53:08,864 [manager.Manager] INFO : Blocking for tserver availability - need to reach 3 servers. Have 1 Time spent blocking 420 sec.
```

**Expected behavior**
Given `manager.startup.tserver.avail.min.count` and `manager.startup.tserver.avail.max.wait` are set. 
When `tserver.avail.min.count` is not reached by the time specified in `tserver.avail.max.wait`,
Then the startup process continues on.

**Additional context**
This is related to issue #3157 but is only focused on the expected behavior of the `tserver.avail.max.wait` property.

### PR DESCRIPTION
**Pull request by ddanielr**
Replaces the retry object with a wait loop.
Log messages are generated independent of max wait time.

Closes #3159

### CODE REVIEW

**Comment by ddanielr** [comment]
I don't think the `sleepInterval` is calculated elegantly. Dividing the wait interval into 10  sleep periods seemed to be ok for now, but I welcome better suggestions.

I wanted to get this change in to close out the open items for 1.10.3

File: server/master/src/main/java/org/apache/accumulo/master/Master.java [hunk 1]
```diff
@@ -1498,51 +1498,47 @@ private void blockForTservers() throws InterruptedException {
...
-    // honor Retry condition that initial wait < max wait, otherwise use small value to allow thread
-    // yield to happen
-    long initialWait = Math.min(50, maxWait / 2);
-
-    Retry tserverRetry =
-        Retry.builder().infiniteRetries().retryAfter(initialWait, TimeUnit.MILLISECONDS)
-            .incrementBy(15_000, TimeUnit.MILLISECONDS).maxWait(maxWait, TimeUnit.MILLISECONDS)
-            .logInterval(30_000, TimeUnit.MILLISECONDS).createRetry();
+    // Set a incremental logging delay
+    long logIncrement = 15_000;
```
Comment (EdColeman) [inline server/master/src/main/java/org/apache/accumulo/master/Master.java:1504]: When using TimeUnits, this may be clearer if it was logIncrementSec = 15 and then use the timeunit conversions.

File: server/master/src/main/java/org/apache/accumulo/master/Master.java [hunk 2]
```diff
@@ -1498,51 +1498,47 @@ private void blockForTservers() throws InterruptedException {
...
       }
     }
 
     if (tserverSet.size() < minTserverCount) {
       log.warn(
           "tserver availability check time expired - continuing. Requested {}, have {} tservers on line. "
-              + " Time waiting {} ms",
+              + " Time waiting {} sec",
           tserverSet.size(), minTserverCount,
           TimeUnit.MILLISECONDS.toSeconds(System.currentTimeMillis() - waitStart));
```
Comment (EdColeman) [inline server/master/src/main/java/org/apache/accumulo/master/Master.java:1532]: You can static import the time units so that it would be `MILLISECONDS` rather than `TimeUnit.MILLISECONDS`

File: server/master/src/main/java/org/apache/accumulo/master/Master.java [hunk 3]
```diff
@@ -1498,51 +1498,47 @@ private void blockForTservers() throws InterruptedException {
...
 
     } else {
       log.info(
           "tserver availability check completed. Requested {}, have {} tservers on line. "
-              + " Time waiting {} ms",
+              + " Time waiting {} sec",
           tserverSet.size(), minTserverCount,
           TimeUnit.MILLISECONDS.toSeconds(System.currentTimeMillis() - waitStart));
     }
+    sleepUninterruptibly(sleepInterval, TimeUnit.MILLISECONDS);
```
Comment (EdColeman) [inline server/master/src/main/java/org/apache/accumulo/master/Master.java:1541]: You should check the interrupt status.  This could be done with Thread.sleep() and a catch clause.  If `sleepUninterruptibly` is necessary because we *must* wait for the entire duration, the it should be noted with a comment that that behavior is necessary.

File: server/master/src/main/java/org/apache/accumulo/master/Master.java [hunk 4]
```diff
@@ -1498,51 +1498,47 @@ private void blockForTservers() throws InterruptedException {
...
-    // yield to happen
-    long initialWait = Math.min(50, maxWait / 2);
-
-    Retry tserverRetry =
-        Retry.builder().infiniteRetries().retryAfter(initialWait, TimeUnit.MILLISECONDS)
-            .incrementBy(15_000, TimeUnit.MILLISECONDS).maxWait(maxWait, TimeUnit.MILLISECONDS)
-            .logInterval(30_000, TimeUnit.MILLISECONDS).createRetry();
+    // Set a incremental logging delay
+    long logIncrement = 15_000;
+    long logWait = 0, lastLog = 0;
```
Comment (EdColeman) [inline server/master/src/main/java/org/apache/accumulo/master/Master.java:1505]: I think style conventions are that this should be two lines 
```
 long logWait = 0;
 long lastLog = 0;
```
but not sure if checksytle will complain - if not the it can be left as is.

**Review by EdColeman — COMMENTED** [review]
Overall this looks okay, but removing the retry in favor of a wait loop looses some functionality - mainly that there was a small pause at start. It also seems cleaner because the wait times do not need to be calculated.  Also, with the retry, there would be a most 3 log messages generated for the wait.

Why did you choose not to use retry?

File: server/master/src/main/java/org/apache/accumulo/master/Master.java [hunk 5]
```diff
@@ -1498,51 +1498,47 @@ private void blockForTservers() throws InterruptedException {
...
-
-      tserverRetry.waitForNextAttempt();
-
+    while (needTservers && ((System.currentTimeMillis() - waitStart) < maxWait)) {
       needTservers = tserverSet.size() < minTserverCount;
 
-      // suppress last message once threshold reached.
-      if (needTservers) {
+      // Determine when to log a message
+      if (needTservers && ((System.currentTimeMillis() - lastLog) > logWait)) {
```
[the remark this answers is not in the document]
Comment (ddanielr) [reply server/master/src/main/java/org/apache/accumulo/master/Master.java]: Switched all the logic over to use `System.nanoTime()`

File: server/master/src/main/java/org/apache/accumulo/master/Master.java (hunk 2 above)
Comment (ddanielr) [reply server/master/src/main/java/org/apache/accumulo/master/Master.java]: Ended up static importing `NANOSECONDS` instead, due to the switch to`System.nanoTime()`

File: server/master/src/main/java/org/apache/accumulo/master/Master.java (hunk 4 above)
Comment (ddanielr) [reply server/master/src/main/java/org/apache/accumulo/master/Master.java]: checkstyle didn't complain, but I switched it while I was in there.

**Comment by ddanielr** [comment]
> Overall this looks okay, but removing the retry in favor of a wait loop looses some functionality - mainly that there was a small pause at start. It also seems cleaner because the wait times do not need to be calculated. Also, with the retry, there would be a most 3 log messages generated for the wait.
> 
> Why did you choose not to use retry?

I attempted using a Retry with an earlier version of this fix. However, while wait times do not need to be calculated with a Retry, the amount of retries in the given time duration window still need to be calculated. Otherwise it never completes and just keeps retrying.  

In my first iteration, the retry never matched up to my time value as the increment value would always cause the retry to overshoot the defined property value. 

https://github.com/ddanielr/accumulo/pull/5/commits/f93c327073d660039716e21330deb98986b19494#diff-56945d7261689b2323a668699ab5865a1e48ec8424b0d612091d29ae0f2fc67cR1510

Because of the complications with the Retry object, and the fact that`blockForTservers()` is not attempting an operation as it's just blocking, I chose to simplify it for a wait loop.

I can add in a small wait at the start if you'd prefer, or I'm happy to dig further into the Retry object with someone and see if I'm just completely missing something.

I'm not super concerned about the logs being spammed as this is a block on the main thread so nothing else should really be showing up in the logs until this method has completed.

**Comment by EdColeman** [comment]
The following seems close to what is wanted (I build this against 3.0, so there may be changes needed for 1.10)  Ignore the time and count values - they were picked for convenience and not what we'd what to use here.

```
     Retry.builder().maxRetries(10).retryAfter(50, MILLISECONDS).incrementBy(100, MILLISECONDS)
                        .maxWait(maxWaitSec, SECONDS).backOffFactor(2.0).logInterval(1, SECONDS).createRetry();

...
  while(retry.canRetry()){
            attempts++;
            retry.logRetry(log, "current counts " + attempts);
            retry.waitForNextAttempt(log, "pause for next attempt");
            retry.useRetry();
        }
```

I think things to note:  

- maxWait set the max delay and factors in with the backoff, the delay time will increase up to that value with each attempt.
- maxRetries is a count 
- removing infiniteRetries() and then adding useRetry is required to advance the retry attempt logic

File: server/master/src/main/java/org/apache/accumulo/master/Master.java (hunk 3 above)
Comment (ddanielr) [reply server/master/src/main/java/org/apache/accumulo/master/Master.java]: Switched back to using a retry object so this is OBE

**Comment by ddanielr** [comment]
Dug into the retry object a bit with @EdColeman and found that removing the incrementing backoff and just using maxRetries makes the Retry object function as expected. 

I've pushed an updated commit that switches back to the Retry object, but calculates an exact max wait vs an approximate value. 
It also switches the logging statement to use the Retry logging method which takes advantage of the Retry object's logging interval.

File: server/master/src/main/java/org/apache/accumulo/master/Master.java [hunk 6]
```diff
@@ -1489,40 +1490,41 @@ private void blockForTservers() throws InterruptedException {
...
-    long logIncrement = TimeUnit.SECONDS.toNanos(15);
-    long logWait = 0;
-    long lastLog = 0;
+    long retries = 10;
+    long waitPeriod = maxWait / retries;
+
+    Retry tserverRetry =
+        Retry.builder().maxRetries(retries).retryAfter(waitPeriod, TimeUnit.MILLISECONDS)
+            .incrementBy(0, TimeUnit.MILLISECONDS).maxWait(waitPeriod, TimeUnit.MILLISECONDS)
+            .logInterval(30_000, TimeUnit.MILLISECONDS).createRetry();
```
Comment (EdColeman) [inline server/master/src/main/java/org/apache/accumulo/master/Master.java:1507]: just a nit - you can static import `TimeUnit.MILLISECONDS` so these are shorten to `MILLISECONDS`

**Review by EdColeman — APPROVED** [review]
You may want to use the TimeUnit static imports - but LGTM

**Review by EdColeman — APPROVED** [review]

**Comment by ctubbsii** [comment]
GitHub's UI seems to create a new branch to revert the change if you click the revert button, even if you abort the process and don't actually follow through with reverting anything. I'll delete the unintentionally created revert branch. #3235 is a fix subsequent to this PR that should be finished before merging the 1.10 branch forward into 2.1 and on.
