### PR TITLE
Invalid External Compaction Progress Fix

### LINKED ISSUE #4422: External Compaction Progress is inaccurate
**Describe the bug**
When an external compactor reports progress, it reports back the number of entries written and reports that as a percentage of number of total entries. 

However, when compaction jobs contain bulk import files, their number of entries value is 0. 
This means that compaction jobs will still total up the number of entries written and report back a percentage greater than 100%. 

This renders the progress percentage to be inaccurate. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1 
 - OS: [e.g. CentOS 7.5]
 - Others:

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Trigger an external compaction job against a table that contains files which were bulk imported
2. Review the compaction-coordinator log (or monitor's external compactions#Running Compactions page) to see percentages greater than 100% being reporting while the the job status is still "In Progress" 

**Expected behavior**
The compaction progress percentage should be accurate and never report progress greater than 100%.

**Additional context**
The number of estimated entries is coming from Bulk.FileInfo 
https://github.com/apache/accumulo/blob/33894e69979afc70efca448ea31fb29ac73288f3/core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/Bulk.java#L107

It's likely that fixing the progress bar is a change to the bulk import code to correctly set the number of estimated entries. 
If the bulk Import code always sets that value to 0 then having it provides little benefit.

### PR DESCRIPTION
**Pull request by kevinrr888**
closes #4422

This fixes the error with external compactions reporting invalid (>100%) progress when the compactions include bulk imported files. This occurs because the estimated number of entries for bulk imported files is 0. Following the suggestion of Keith, instead of modifying the bulk import code to compute the estimated entries, I modified the Compactor code to compute the estimated number of entries on files with 0 entries. This value is computed by opening the RFile and summing the number of entries in each of the IndexEntry's which overlap with the extent of the external compaction.

Also added a test to ExternalCompactionProgressIT to ensure that this fix works as intended. This tests that the Compactor and CompactionCoordinator report a valid progress.

I unfortunately was not able to ensure that these changes are also reflected in the Accumulo Monitor page. Large compactions would only briefly show up in the Running Compactions table, always with a progress of 0. I also could not use something like a SlowIterator to slow the progress down (I believe since SlowIterator is part of a test package, it isn't available). If anyone is able to ensure that these changes are reflected in the Monitor page, or is able to provide guidance on how I can better test this against the Monitor page, that would be helpful. The environment I used to run an external compaction was jshell using uno.

### CODE REVIEW

**Comment by ddanielr** [comment]
@kevinrr888 when I wrote #4422 I had confirmed that the progress counts in the compaction-coordinator log files matched the monitor output because I wasn't sure if it was just a monitor specific problem. 

So if the log files report the correct progress I wouldn't worry about the monitor output.

File: core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java [hunk 1]
```diff
@@ -1555,5 +1561,42 @@ private void setInterruptFlagInternal(AtomicBoolean flag) {
...
+          if (extent.contains(indexEntry.getKey().getRow())) {
+            totalEntries += indexEntry.getNumEntries();
+            prevEntryOverlapped = true;
+          } else if (prevEntryOverlapped) {
+            // The last index entry included in the count is the one after the last contained by the
+            // extent. This is because it is possible for the extent to overlap this index entry
+            // but there is no way to check whether it does or not. The index entry only contains
+            // info about the last key, but the extent may overlap but not with the last key.
+            totalEntries += indexEntry.getNumEntries();
+            prevEntryOverlapped = false;
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java:1594]: could break out early here. 

```suggestion
            prevEntryOverlapped = false;
            break;
```

File: core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java [hunk 2]
```diff
@@ -1555,5 +1561,42 @@ private void setInterruptFlagInternal(AtomicBoolean flag) {
     public void setCacheProvider(CacheProvider cacheProvider) {
       reader.setCacheProvider(cacheProvider);
     }
+
+    /**
+     * Returns an estimate of the number of entries that overlap the given extent. This is an
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java:1566]: Could move this javadoc up to FileSKVIterator.estimateEntries().  Its nice javadoc, putting it there would make it more widely visible.

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java [hunk 3]
```diff
@@ -97,14 +104,90 @@ public void testProgress() throws Exception {
...
+    /*
+     * Tests the progress of an external compaction done on a table with bulk imported files.
+     * Progress should stay 0-100. There was previously a bug with the Compactor showing a >100%
+     * progress for compactions with bulk import files.
+     */
+    String[] tableNames = getUniqueNames(2);
+    String tableName1 = tableNames[0];
+    String tableName2 = tableNames[1];
+
+    try (AccumuloClient client = Accumulo.newClient().from(getClientProps()).build()) {
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:132]: Does this test fail w/o the new changes?

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java [hunk 4]
```diff
@@ -97,14 +104,90 @@ public void testProgress() throws Exception {
...
+      client.tableOperations().setProperty(tableName1, Property.TABLE_MAJC_RATIO.getKey(), "1000");
+      client.tableOperations().setProperty(tableName2, Property.TABLE_MAJC_RATIO.getKey(), "1000");
+
+      getCluster().getClusterControl().startCoordinator(CompactionCoordinator.class);
+      getCluster().getClusterControl().startCompactors(Compactor.class, 1, QUEUE1);
+
+      String dir = getDir(client, tableName1);
+
+      log.info("Bulk importing files in dir " + dir + " to table " + tableName2);
+      client.tableOperations().importDirectory(dir).to(tableName2).load();
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:151]: What is the intent of this?  It seems like it will bulk import files from a dir in table 1 into table 2.  Bulk import moves files so that would delete files from table1, but table1 would still have refs to those files in the metadata table.  So seems like it will leave table1 broken.  Not a change for this PR, but thinking we should update bulk import to throw an exception if the bulk source dir is under a configured accumulo volume dir.

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java [hunk 5]
```diff
@@ -97,14 +104,90 @@ public void testProgress() throws Exception {
...
+      log.info("Finished bulk import");
+
+      log.info("Starting a compaction progress checker thread");
+      Thread checkerThread = startChecker();
+      checkerThread.start();
+
+      log.info("Attaching a slow iterator to table " + tableName2);
+      IteratorSetting setting = new IteratorSetting(50, "Slow", SlowIterator.class);
+      SlowIterator.setSleepTime(setting, 1);
+      client.tableOperations().attachIterator(tableName2, setting,
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:161]: Instead of adding the iterator to the table could set it on the CompactionConfig object.  Setting it on the table is eventually consistent, so its not certain the compaction will see the iterator.  If the iterator is set on the compaction config, then it will be seen.

**Comment by keith-turner** [comment]
Testing the monitor may be possible by pulling json from it, but not sure.  Did you manually try looking at the monitor with this change?

**Review by ddanielr — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java (hunk 5 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:161]: I see. There are other places where this is done as well--setting it on the table and then compacting. I can fix these in another PR, or in this PR. Whichever you think would be better.

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java (hunk 3 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:132]: Yes

**Comment by kevinrr888** [comment]
> Testing the monitor may be possible by pulling json from it, but not sure. Did you manually try looking at the monitor with this change? Personally I think a manual check would be good.

Okay, had just tried my test using uno again with an even larger compaction and now I can see that the progress does in fact go above 100% prior to these changes. Perhaps my compaction wasn't large enough before to show any progress, I'm not sure. Will build uno using my changes and check the monitor page and get back to you.

**Comment by kevinrr888** [comment]
Just confirmed that these changes are reflected in the monitor page. So the logs and the monitor page both no longer show >100% progress

**Review by dlmarion — COMMENTED** [review]
I reviewed this, I see no issues but I think we should have @keith-turner review again. It looks like you have answered some of his questions, I just want to make sure that he sees that and concurs. Have you run any other ITs?

**Comment by kevinrr888** [comment]
> I reviewed this, I see no issues but I think we should have @keith-turner review again. It looks like you have answered some of his questions, I just want to make sure that he sees that and concurs. Have you run any other ITs?

Sounds good. I have only run `ExternalCompactionProgressIT.java` and those that github runs. Let me know if there are others you think that should also be verified.

File: core/src/main/java/org/apache/accumulo/core/file/FileSKVIterator.java [hunk 6]
```diff
@@ -33,6 +34,16 @@ public interface FileSKVIterator extends InterruptibleIterator, AutoCloseable {
...
 
+  /**
+   * Returns an estimate of the number of entries that overlap the given extent. This is an estimate
+   * because the extent may or may not entirely overlap with each of the index entries included in
+   * the count. Will never underestimate but may overestimate.
+   *
+   * @param extent the key extent
+   * @return the estimate
+   */
+  long estimateEntries(KeyExtent extent) throws IOException;
```
Comment (DomGarguilo) [inline core/src/main/java/org/apache/accumulo/core/file/FileSKVIterator.java:45]: Would including the word `overlap` or `overlapping` in the method name make it more self-evident? Maybe something like `estimateOverlappingEntries`?

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java [hunk 7]
```diff
@@ -148,6 +230,10 @@ private void checkRunning() throws TException {
               progressList.add(EC_PROGRESS.HALF);
             } else if (rci.progress > 75 && rci.progress <= 100) {
               progressList.add(EC_PROGRESS.THREE_QUARTERS);
+            } else {
+              progressList.add(EC_PROGRESS.INVALID);
+              log.warn("An invalid progress {} has been seen. This should never occur.",
+                  rci.progress);
```
Comment (DomGarguilo) [inline test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:236]: I think it would be nice to either fail the test here instead of adding it to the list, or where all the progress states are checked at the end, check them all by using Junits `assertAll()` that way it will alert us if multiple asserts fail instead of just stop at the first failure.

**Review by DomGarguilo — COMMENTED** [review]
I have verified that the test fails before these changes are applied and passes afterwards.

File: test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java (hunk 7 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:237]: Changed to use `assertAll()`. Could have it fail for that specific check there, but we already need to add to a list for the other checks (or at least some way to signal that those progresses have been seen), so I think it is more consistent to just add INVALID to the list. This way also won't end the progress early, which may be better for debugging to see how high the progress goes.

Comment (DomGarguilo) [reply test/src/main/java/org/apache/accumulo/test/compaction/ExternalCompactionProgressIT.java:237]: Yea I agree. I like checking them all instead of failing early in this case.

**Review by keith-turner — APPROVED** [review]
