### PR TITLE
Replaced tserv block cache mgr property with a more general one

### LINKED ISSUE #4663: scan servers use tserver prefix for cache manager property
**Describe the bug**
When trying to set the class to use for the cache manager, the scan servers do not use a 
`sserver` property prefix. Instead the scan servers only load in a different manager if `tserver.cache.manager.class` is set. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.x

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Setup an fluo-uno instance
2. Modify the properties to set `sserver.cache.manager.class=test.example` in the property file.
3. Try starting a scan server (This should succeed)
4. Modify the properties file to set `tserver.cache.manager.class=test.example`
5. Try starting a scan server (This will fail with a class not found error)

**Expected behavior**
The scan server should use the `sserver` prefix when loading in instance properties.

**Additional context**
There may be additional properties that are still only loaded in via the `tserver` prefix.

### PR DESCRIPTION
**Pull request by dlmarion**
The block cache manager is not only used in the tserver, it's also used in the sserver and by a client that might be reading from an RFile.

Closes #4663

### CODE REVIEW

**Review by ddanielr — APPROVED** [review]
Tested and verified that the new property is picked up by tserver and sserver processes. 

If users want to use a separate block cache between tservers and scan servers then they'll have to use a different resource group name and use the `includeOptional` logic in accumulo.properties.

File: core/src/main/java/org/apache/accumulo/core/conf/Property.java [hunk 1]
```diff
@@ -294,6 +294,12 @@ public enum Property {
           + " user-implementations of pluggable Accumulo features, such as the balancer"
           + " or volume chooser.",
       "2.0.0"),
+  GENERAL_CACHE_MANAGER_IMPL("general.block.cache.manager.class",
+      "org.apache.accumulo.core.file.blockfile.cache.lru.LruBlockCacheManager", PropertyType.STRING,
+      "Specifies the class name of the block cache factory implementation."
+          + " Alternative implementation is"
+          + " org.apache.accumulo.core.file.blockfile.cache.tinylfu.TinyLfuBlockCacheManager.",
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/conf/Property.java:301]: Why change the default impl from LruBlockCacheManager to TinyLfuBlockCacheManager?

**Review by keith-turner — APPROVED** [review]
Would it make sense in a follow on change to make the cache size props be general? Like the `tserver.cache.data.size` and `sserver.cache.data.size` props.

File: core/src/main/java/org/apache/accumulo/core/conf/Property.java (hunk 1 above)
Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/conf/Property.java:301]: The default is `LruBlockCacheManager`, I just copied the code from `TSERV_CACHE_MANAGER_IMPL`. The default was changed to the TinyLfuBlockCacheManager in a later release IIRC.

**Comment by dlmarion** [comment]
> Would it make sense in a follow on change to make the cache size props be general? Like the `tserver.cache.data.size` and `sserver.cache.data.size` props.

I think it's ok to leave them separate that way if you have different settings in the same resource group, then you won't need different configs.

**Comment by ddanielr** [comment]
Discovered #5234 when testing this PR.

**Comment by dlmarion** [comment]
I removed the deprecated property when I merged this into `main`.
