### PR TITLE
Setting empty property value no longer deletes property

### LINKED ISSUE #4456: Setting empty property value via the shell deletes the property
**Describe the bug**
Setting a table property to an empty string deletes the property from ZK vs overriding the value to an empty string.

This was verified by using the accumulo admin dumpConfig  -a tool to pull down the table configs and verify that the property no longer existed as a per-table override 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.x
 - OS: [e.g. CentOS 7.5] centos 7
 - Others:

**Expected behavior**
The property value is overridden to an empty string and is only deleted if the `-d` flag is used. 

**Additional context**
@ctubbsii  had some ideas on why this was happening

### PR DESCRIPTION
**Pull request by jmark99**
Modifed ManagerServiceClientHandler alterProperty method so it no longer removes/deletes a property when set to null or empty string.

Added configPropertyTest integration tests to ShellIT.

Fixes #4456

### CODE REVIEW

**Review by DomGarguilo — APPROVED** [review]

**Review by ddanielr — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java [hunk 1]
```diff
@@ -555,10 +555,13 @@ private void alterTableProperty(TCredentials c, String tableName, String propert
     }
 
     try {
-      if (value == null || value.isEmpty()) {
+      if (op == TableOperation.REMOVE_PROPERTY) {
         PropUtil.removeProperties(manager.getContext(),
             TablePropKey.of(manager.getContext(), tableId), List.of(property));
-      } else {
+      } else if (op == TableOperation.SET_PROPERTY) {
+        if (value == null || value.isEmpty()) {
```
Comment (ctubbsii) [inline server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java:562]: It probably shouldn't be possible for most properties to set it to a non-empty string of whitespace. So, `value.isBlank()` might be better. However, I don't want to make assumptions about what custom properties or SPI opts properties might do, so probably best to leave it alone. This is good.
