### PR TITLE
Closes #1349 - Throw errors from Main instead of using System.exit()

### LINKED ISSUE #1349: Throw exceptions from the main thread so they show on STDERR
https://issues.apache.org/jira/browse/ACCUMULO-2628 removed the use of `printStackTrace` from our code in 1.7, which itself is a good thing, because we didn't need to be manually doing that. However, in doing so, there is now no indication on STDERR that anything went wrong when a component dies for any reason, because Main now just logs to the log4j/slf4j logger and exists with a bad error code.

I think the logging of the error is okay, but instead of calling `System.exit(1)` after the logging, we should just re-throw the exception that caused the problem. This will cause the JVM to die with a bad exit code, but it will also provide meaningful output on STDERR to the user that is running the program. This is the expected behavior of exceptions in a Java main function.

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

File: start/src/main/java/org/apache/accumulo/start/Main.java [hunk 1]
```diff
@@ -41,63 +41,57 @@
...
-      String keywordOrClassName = args[0];
-      KeywordExecutable keywordExec = getExecutables(loader).get(keywordOrClassName);
-      if (keywordExec != null) {
-        execKeyword(keywordExec, stripArgs(args, 1));
-      } else {
-        execMainClassName(keywordOrClassName, stripArgs(args, 1));
-      }
+    if (args.length == 0) {
+      printUsage();
+      throw new IllegalArgumentException("No arguments passed to Main");
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/Main.java:78]: This one might actually be a legitimate use for `System.exit(1)`, since the expectation here is that it scripts or users should see a non-zero return code, and that our usage information that we print is more useful than any ugly stack trace.

**Review by ctubbsii — COMMENTED** [review]
I like all the changes, except for the one that I specifically questioned, which I'm not sure about. It's unfortunate that Java didn't anticipate needing a return code from main methods, and we can't just `return 1` there.

**Review by ctubbsii — APPROVED** [review]
It's frustrating that we can't have a non-zero return code on the main method. This change looks fine to me.

File: start/src/main/java/org/apache/accumulo/start/Main.java [hunk 2]
```diff
@@ -41,63 +41,57 @@
...
+      log.error("Error pre-loading JobConf and JobConfigurable classes, VFS classloader with "
+          + "system classes in HDFS may not work correctly", e);
+      throw e;
+    }
 
-    } catch (Throwable t) {
-      log.error("Uncaught exception", t);
+    if (args.length == 0) {
+      printUsage();
       System.exit(1);
```
Comment (ctubbsii) [inline start/src/main/java/org/apache/accumulo/start/Main.java:78]: Even though this is a legitimate use of exit, if we want consistency with the help options, we could just return without an exit code here as well. I'm fine either way, as long as we don't throw an exception here.

Comment (ctubbsii) [reply start/src/main/java/org/apache/accumulo/start/Main.java:78]: @dlmarion Not sure if you saw this comment. I made it after marking "Approve" on my last review. Feel free to mark this as "resolved" if you're fine with it as-is.

Comment (dlmarion) [reply start/src/main/java/org/apache/accumulo/start/Main.java:78]: I'm fine with it as is.
