### PR TITLE
Fixes for new Admin fate command

### LINKED ISSUE #2974: Fate Admin print doesn't filter on status
The status filter on the new Admin fate command does not change the results:
<pre>
04:26:21 {main} ~/workspace/uno/install/logs/accumulo$ accumulo admin fate -p -s IN_PROGRESS
2022-09-27T16:26:29,795 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
2022-09-27T16:26:31,085 [metrics.MetricsUtil] INFO : Metric producer PropStoreMetrics initialize
TABLE_BULK_IMPORT2 txid: 6324179035588914  status: SUBMITTED          locked: []              locking: [R:3]           op: PrepBulkImport  created: 2022-09-27T20:25:40.716Z
TABLE_COMPACT   txid: 4d7bf30c0676eb5d  status: SUBMITTED          locked: [R:+default]    locking: [R:3]           op: CompactRange    created: 2022-09-27T20:26:09.732Z
TABLE_BULK_IMPORT2 txid: 0176dfaebcec9591  status: SUBMITTED          locked: []              locking: [R:3]           op: PrepBulkImport  created: 2022-09-27T20:26:10.648Z
TABLE_MERGE     txid: 1eeba54e6e769e7c  status: IN_PROGRESS        locked: [R:+default, W:3] locking: []              op: TableRangeOpWait created: 2022-09-27T20:25:39.58Z
TABLE_COMPACT   txid: 09760433eb43a5ce  status: IN_PROGRESS        locked: [R:+default, R:1] locking: []              op: CompactionDriver created: 2022-09-27T20:26:00.977Z
TABLE_MERGE     txid: 37d000bf5948ab30  status: SUBMITTED          locked: [R:+default]    locking: [W:1]           op: TableRangeOp    created: 2022-09-27T20:26:25.915Z
</pre>

### PR DESCRIPTION
**Pull request by milleruntime**
* Closes #2974

### CODE REVIEW

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java [hunk 1]
```diff
@@ -224,7 +225,7 @@ static class RestoreZooCommand {
   @Parameters(commandNames = "fate",
       commandDescription = "Operations performed on the Manager FaTE system.")
   static class FateOpsCommand {
-    @Parameter(description = "[<txId>...]")
+    @Parameter(description = "[<txId> <txId>...]")
```
Comment (DomGarguilo) [inline server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:228]:
```suggestion
    @Parameter(description = " <txId> { <txId> ... } ")
```
It looks like for other parameters that accept a list we use this format

Comment (milleruntime) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:228]: I was trying to show that the `txId` is not always required.

**Review by DomGarguilo — APPROVED** [review]
Tested this out and seems to work well.

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java (hunk 1 above)
Comment (milleruntime) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:228]: I was trying to base it on `git` sytnax guidelines and actually found them [here](https://github.com/git/git/blob/master/Documentation/CodingGuidelines#L639). After reading through their guidelines, I think I could make the list for 0 or more shorter, like `[<txId>...]` and 1 or more like `<txId>...`.

```
[<patch>...]
   (Zero or more of <patch>.  Note that the dots are inside, not
   outside the brackets.)
```

**Comment by milleruntime** [comment]
Another advantage to have the fate command run in Admin is that it doesn't require Accumulo to be running. So an admin can shut the cluster down and perform actions using the new command. The only exception is cancel requires the Manager to be running.

File: server/base/src/main/java/org/apache/accumulo/server/util/Admin.java [hunk 2]
```diff
@@ -250,7 +251,7 @@ static class FateOpsCommand {
     boolean printJson;
 
     @Parameter(names = {"-s", "--state"},
-        description = "<state>[ -s <state>...] Print transactions in the state(s) {NEW, IN_PROGRESS, FAILED_IN_PROGRESS, FAILED, SUCCESSFUL}")
+        description = "<state>... Print transactions in the state(s) {NEW, IN_PROGRESS, FAILED_IN_PROGRESS, FAILED, SUCCESSFUL}")
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:254]: I still don't think we need this filtering. Users can filter by piping the output to grep, or whatever they like. We can put the list of states elsewhere in the help/description. The output should be easily computer-readable, to make parsing the output easy... but otherwise, we don't need to bake in too many filtering/display options. Let's keep it simple.

Comment (EdColeman) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:254]: Except that its just carrying over functionality from when it was a shell command - but either way....

Comment (ctubbsii) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:254]: Okay. I don't know that we need to be tied to that same flag in the new tool, as long as we preserve all the same functionality, and filtering functionality is still easy and convenient, regardless of whether we carry over this flag. I'm not a big fan of carrying it over, but I'm not strongly opposed either... I just think it's unnecessary and redundant, and I'd prefer to delete it.

Comment (dlmarion) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:254]: Be sure to check FateSummaryIT

Comment (milleruntime) [reply server/base/src/main/java/org/apache/accumulo/server/util/Admin.java:254]: Thanks for the reminder. FateSummaryIT is passing.

The functionality of the filtering is pretty simple and just calls the same methods as FateCommand. It is only a few lines of code to make the option available in the new command.
