### PR TITLE
fixes #800 avoid importing files for completed bulk transactions

### LINKED ISSUE #800: Bulk import process can result in a lost file
In the 1.8, 1.9 line of code (unsure about 2.0), we can get into a situation where a major compaction starts failing because of a missing file.  The scenario is as follows:

master asked to import directory
tserver1 asked the assign a file
tserver1 askes tserver2 to load a file
tserver2 loads the file successfully but not not respond to tserver1 in a timely manor
tserver2 major compacts and adds a ~del entry for the file
tserver1 times out and retries asking tserver2 to load the file
tserver2 starts to load the same file a second time
garbage collector deletes the file
tserver2 attempts to major compact the file away but now it does not exist.

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: server/master/src/main/java/org/apache/accumulo/master/tableOps/BulkImport.java [hunk 1]
```diff
@@ -177,9 +181,10 @@ private Path createNewBulkDir(VolumeManager fs, String tableId) throws IOExcepti
     }
   }
 
-  private String prepareBulkImport(Master master, final VolumeManager fs, String dir,
-      String tableId) throws Exception {
-    final Path bulkDir = createNewBulkDir(fs, tableId);
+  @VisibleForTesting
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/tableOps/BulkImport.java]: I don't think it's really necessary to use this annotation, especially  in classes that aren't public API. It will be obvious that it's needed for testing, because removing it will affect a test. An inline comment serves the same purpose, but without the dependency on guava.

Comment (keith-turner) [reply server/master/src/main/java/org/apache/accumulo/master/tableOps/BulkImport.java]: I think I can inline this method.   

I am neutral on using or not using `@VisibleForTesting`.  If there is going to be a change I think it would be best to do it everywhere for consistency.  To me the annotation means that code should only be called by test code and the declaring class.  Theoretically deviations from this could be detected using static analysis.  If such a static analysis tool exists it may be nice to leave it as an annotation.

**Comment by keith-turner** [comment]
All ITs ran successfully for this change.

File: test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java [hunk 2]
```diff
@@ -0,0 +1,265 @@
...
+    assertEquals(testData, readTable(table, c));
+
+    // After this, all load request should fail.
+    ZooArbitrator.stop(Constants.BULK_ARBITRATOR_TYPE, fateTxid);
+
+    try {
+      // expect this to fail
+      assignMapFiles(fateTxid, asCtx, extent, bulkLoadPath.toString(), status.getLen());
+      fail();
+    } catch (TApplicationException tae) {
```
Comment (milleruntime) [inline test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java]: Could use ExpectedException here.

File: server/master/src/main/java/org/apache/accumulo/master/tableOps/BulkImport.java (hunk 1 above)
Comment (keith-turner) [reply server/master/src/main/java/org/apache/accumulo/master/tableOps/BulkImport.java]: Nevermind about inlining I was thinking of a change I made for #840 to use @VisibleForTesting.  For this code I think I will leave it as is.  I am ok with changing it everywhere in another PR.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java [hunk 3]
```diff
@@ -460,42 +461,54 @@ private static long jitter(long ms) {
...
-        Map<String,MapFileInfo> fileMap = entry.getValue();
-        Map<FileRef,MapFileInfo> fileRefMap = new HashMap<>();
-        for (Entry<String,MapFileInfo> mapping : fileMap.entrySet()) {
-          Path path = new Path(mapping.getKey());
-          FileSystem ns = fs.getVolumeByPath(path).getFileSystem();
-          path = ns.makeQualified(path);
-          fileRefMap.put(new FileRef(path.toString(), path), mapping.getValue());
-        }
+          @Override
+          public List<TKeyExtent> call() throws Exception {
```
Comment (milleruntime) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java]: Was moving the Arbitrator thread here the fix?

Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java]: Yeap.   Also I forgot to mention that ignoring whitespace makes this diff really small.

File: test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java (hunk 2 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java]: I think that has to be the final step in the test because the exception is caught by junit and therefore jumps out of the function.  I still want to do some verification after this so I don't think I can use that.

Comment (milleruntime) [reply test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java]: Interesting.  I thought the ExpectedException worked just like a try/catch, but reported exceptions that didn't get thrown at the end.
