### PR TITLE
fixes #558 use copy to avoid deadlock in tserver

### LINKED ISSUE #558: Saw deadlock when two tablets tried to close around the same time.
Saw a deadlock while running continuous ingest to test 1.9.2 RC1.  I was looking into why a long hold time was happening.  Luckily I got this stack trace before the agitator wacked the tserver.  

What is going on is that two tablets both try close around the same time.  The two tablets minor compact, with that tablet lock held (which only happens at close).  At the end of the minor compaction, the tablets run a check to see which WALs are referenced.  This check attempts to get each tablets lock.  Locking needs to be avoided in this check.

I am not 100% sure, but this issue may occur in 1.9.1 with locking that was added in 84791ec78086474b4b69281c72aab5c3983831b0 for the `removeInUseLogs()` method.  It may be that the only continuous ingest test that was done for 1.9.1 was with agitation.  This is why its important to test with and without agitation, because agitation hides bugs like this unless someone is closely watching the test. I got lucky when I found this.

```
Java stack information for the threads listed above:
===================================================
"Minor compacting !0;~<":
        at org.apache.accumulo.tserver.tablet.Tablet.removeInUseLogs(Tablet.java:2462)
        - waiting to lock <0x000000079ca85988> (a org.apache.accumulo.tserver.tablet.Tablet)
        at org.apache.accumulo.tserver.TabletServer$12.removeInUse(TabletServer.java:3413)
        at org.apache.accumulo.tserver.TabletServer.findOldestUnreferencedWals(TabletServer.java:3370)
        at org.apache.accumulo.tserver.TabletServer.markUnusedWALs(TabletServer.java:3421)
        at org.apache.accumulo.tserver.TabletServer.minorCompactionFinished(TabletServer.java:3245)
        at org.apache.accumulo.tserver.tablet.DatafileManager.bringMinorCompactionOnline(DatafileManager.java:459)
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:914)
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:90)
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompactNow(Tablet.java:1047)
        at org.apache.accumulo.tserver.TabletServer$AssignmentHandler.run(TabletServer.java:2388)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:64)
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
"Minor compacting 2;42005;41804":
        at org.apache.accumulo.tserver.tablet.Tablet.removeInUseLogs(Tablet.java:2462)
        - waiting to lock <0x0000000794a37d20> (a org.apache.accumulo.tserver.tablet.Tablet)
        at org.apache.accumulo.tserver.TabletServer$12.removeInUse(TabletServer.java:3413)
        at org.apache.accumulo.tserver.TabletServer.findOldestUnreferencedWals(TabletServer.java:3370)
        at org.apache.accumulo.tserver.TabletServer.markUnusedWALs(TabletServer.java:3421)
        at org.apache.accumulo.tserver.TabletServer.minorCompactionFinished(TabletServer.java:3245)
        at org.apache.accumulo.tserver.tablet.DatafileManager.bringMinorCompactionOnline(DatafileManager.java:459)
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:914)
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:90)
        at org.apache.accumulo.tserver.tablet.Tablet.completeClose(Tablet.java:1428)
        - locked <0x000000079ca85988> (a org.apache.accumulo.tserver.tablet.Tablet)
        at org.apache.accumulo.tserver.tablet.Tablet.split(Tablet.java:2291)
        - locked <0x000000079ca85988> (a org.apache.accumulo.tserver.tablet.Tablet)
        at org.apache.accumulo.tserver.TabletServer.splitTablet(TabletServer.java:2109)
        at org.apache.accumulo.tserver.TabletServer.splitTablet(TabletServer.java:2089)
        at org.apache.accumulo.tserver.TabletServer.access$2300(TabletServer.java:271)
        at org.apache.accumulo.tserver.TabletServer$SplitRunner.run(TabletServer.java:1978)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
"Minor compacting 2;69c0cc;6980bb":
        at org.apache.accumulo.tserver.tablet.Tablet.removeInUseLogs(Tablet.java:2462)
        - waiting to lock <0x000000079ca85988> (a org.apache.accumulo.tserver.tablet.Tablet)
        at org.apache.accumulo.tserver.TabletServer$12.removeInUse(TabletServer.java:3413)
        at org.apache.accumulo.tserver.TabletServer.findOldestUnreferencedWals(TabletServer.java:3370)
        at org.apache.accumulo.tserver.TabletServer.markUnusedWALs(TabletServer.java:3421)
        at org.apache.accumulo.tserver.TabletServer.minorCompactionFinished(TabletServer.java:3245)
        at org.apache.accumulo.tserver.tablet.DatafileManager.bringMinorCompactionOnline(DatafileManager.java:459)
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:914)
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:90)
        at org.apache.accumulo.tserver.tablet.Tablet.completeClose(Tablet.java:1428)
        - locked <0x0000000794a37d20> (a org.apache.accumulo.tserver.tablet.Tablet)
        at org.apache.accumulo.tserver.tablet.Tablet.close(Tablet.java:1318)
        at org.apache.accumulo.tserver.TabletServer$UnloadTabletHandler.run(TabletServer.java:2206)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 1]
```diff
@@ -2457,19 +2464,25 @@ public void importMapFiles(long tid, Map<FileRef,MapFileInfo> fileMap, boolean s
...
-      // remove logs related to tablets in memory data
-      candidates.removeAll(currentLogs);
-      // remove logs related to minor compaction file being added to the metadata table
-      candidates.removeAll(doomedLogs);
-    }
+    candidates.removeAll(referencedLogs);
   }
 
   Set<String> beginClearingUnusedLogs() {
+    Set<String> doomed = new HashSet<>();
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java]: I know I raised this before, but hopefully I can make my objection more clear this time around:

"Doomed" is an extremely ambiguous concept (it conveys no information about the end state, only that it will be "unfortunate", whatever that means in any given context). Using it here, especially in already error prone WAL code, introduces unnecessary confusion to subsequent contributors/debuggers. It should either be clearly documented when it is declared, with a direct, complete, and unambiguous answer to the question "What does it mean to be 'doomed' here?" or avoided entirely. I prefer to avoid: If we mean "logs to clear" then let's just say what we mean and call the variable "logsToClear". If we mean something else, then let's use similarly simple language to convey what we mean.

Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java]: I reverted changes to this code since 1.9.1 in order to minimize what I had to consider.  In this process I lost the doomed comment.   I can make the variable name more clear.

**Comment by keith-turner** [comment]
It would be useful if someone else could double check my anaylsis of `otherLogs` and `currentLogs`.  In Eclipse I looked for any place one of the sets was mutated. When mutated I rebuilt the immutable copy.  If someone else could pull this patch into an IDE and make sure I didn't miss any mutations of the sets I would appreciate it.

**Comment by keith-turner** [comment]
All ITs passed for merge of ec3b7ed into 42a3534

**Comment by keith-turner** [comment]
I ran a ~1hr CI test w/ agitation against this branch and it went well.  I can run longer test w/ and w/o agitation against RC2 Mon.

```
		REFERENCED=648712264
		UNREFERENCED=8000024
```

**Comment by keith-turner** [comment]
This is the proper fix to #441 and #539.
