### PR TITLE
Don't advertise Manager address until upgrade done and fully started

### LINKED ISSUE #5411: Wrong error being logged during upgrade
During the upgrade process the HighlyAvailableServiceInvocationHandler blocks all incoming Thrift requests and raises a ThriftNotActiveServiceException (see below).

https://github.com/apache/accumulo/blob/4cba6dee3e89960bbaac2f9c86eb34a3a0426779/server/base/src/main/java/org/apache/accumulo/server/rpc/HighlyAvailableServiceInvocationHandler.java#L51-L56

However, what I'm seeing in the log looks like the following (note the null message):

```
2025-03-17T18:26:00,241 [thrift.ProcessFunction] ERROR: Internal error processing reportTabletStatus
org.apache.accumulo.core.clientImpl.thrift.ThriftNotActiveServiceException: null
        at org.apache.accumulo.server.rpc.HighlyAvailableServiceInvocationHandler.invoke(HighlyAvailableServiceInvocationHandler.java:54) ~[accumulo-server-base-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at jdk.proxy2/jdk.proxy2.$Proxy33.reportTabletStatus(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
        at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:203) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at jdk.proxy2/jdk.proxy2.$Proxy37.reportTabletStatus(Unknown Source) ~[?:?]
        at org.apache.accumulo.core.manager.thrift.ManagerClientService$Processor$reportTabletStatus.getResult(ManagerClientService.java:2565) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.manager.thrift.ManagerClientService$Processor$reportTabletStatus.getResult(ManagerClientService.java:2543) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:50) ~[accumulo-server-base-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492) ~[libthrift-0.17.0.jar:0.17.0]

```

From what I can tell the logging is coming from the Thrift ProcessFunction class at:

https://github.com/apache/thrift/blob/60655d2de79e973b89fab52af82f9628d4843b0f/lib/java/src/main/java/org/apache/thrift/ProcessFunction.java#L48-L49

`ex` being passed to `LOGGER` is ThriftNotActiveServiceException and the message is null because ThriftNotActiveServiceException is not passing a message using a TException constructor. I'm thinking that all of our Thrift generated Thrift exceptions have this issue.

### PR DESCRIPTION
**Pull request by dlmarion**
Removed HighlyAvailableService and associated code, which was only really used by the Manager, and instead modified the Manager to only advertise the Manager address with the Thrift services after the upgrade process has completed and the Manager is fully started.

This change removes the HighlyAvailableServiceInvocationHandler which was throwing an exception when the Manager was not ready to accept Thrift RPC calls and causing stack traces in the Manager log during the upgrade process. These stack traces could be construed as a problem to the user, when in reality they were benign.

Closes #5411

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 1]
```diff
@@ -1402,7 +1395,11 @@ boolean canSuspendTablets() {
       log.info("AuthenticationTokenSecretManager is initialized");
     }
 
-    UUID uuid = sld.getServerUUID(ThriftService.MANAGER);
+    // Replace the ServiceLockData informion in the Manager lock node in ZooKeeper.
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1398]:
```suggestion
    // Replace the ServiceLockData information in the Manager lock node in ZooKeeper.
```

**Review by ctubbsii — APPROVED** [review]
Seems like a nice solution!

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]:
```suggestion
    // Replace the ServiceLockData information in the Manager lock node in ZooKeeper.
```

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 2]
```diff
@@ -1146,14 +1139,9 @@ public void run() {
     managerClientHandler = new ManagerClientServiceHandler(this);
     compactionCoordinator = new CompactionCoordinator(context, security, fateRefs, this);
 
-    // Start the Manager's Client service
-    // Ensure that calls before the manager gets the lock fail
-    ManagerClientService.Iface haProxy =
-        HighlyAvailableServiceWrapper.service(managerClientHandler, this);
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: Realized we could have a situation like the following where a client contacts a manager that does not yet hold a lock.

 1. Manager1 starts, gets its lock and advertises itself
 2. Client1 get the address of Manager1
 3. Manager1 dies
 4. Manager2 starts and creates its client service w/ the same host/port as Manager1, but does not get its lock
 5. Client1 makes an RPC request to Manager2 using the host:port it got for Manager1

Is there anything besides this HighlyAvailableService code that will make the RPC above fail?  If not we may need to keep this or move starting the client service until after the lock is obtained.   

We could keep the HighlyAvailableService for safety and delay advertisement to have clean logs in the normal case.  If moving where the client service starts to after the lock is obtained is easy, then that removes the needs for the HighlyAvailableService

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: > Is there anything besides this HighlyAvailableService code that will make the RPC above fail?

Why would we want this to fail?

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: @keith-turner  - I think I see what you are saying, that a client that already has the address could communicate with Manager 2 as soon as the Thrift server starts, but before Manager2 is fully up. I don't know of anything in the codebase that would prevent this from happening, except for the HA code I removed in this PR or the alternate TMultiplexedProcessor I put in the other PR.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: Even if we have nothing to prevent this, I still don't know what this would be protecting. Just as an example, let's say I call waitForFateOperation... do I really care that it's the second manager that tells me the fate operation finished? As long as it has the lock, it should be okay that it is the one that answered. I'm not sure why we would want it to fail.

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: So, I think the solution here is to modify TServerUtils to **not** start the Thrift TServer and instead do it in each of the server processes. The relevant portion of code that needs to be removed from TServerUtils and maybe put into ServerAddress is:

https://github.com/apache/accumulo/blob/d1ea90fa8503fc31a6bedb1d267e38debb18106d/server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java#L656-L671

For most server processes, they would start the TServer right after creating it. For the Manager, it could wait until all of the dependencies are started.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: To close the loop on my question about why we care that a client talks to the restarted server: it's because the restarted server may not be fully up yet. So, we need to not just avoid advertising until the server is up and ready, but we also need to wait until the restarted server is fully up and ready before we allow clients to talk to it.

**Comment by dlmarion** [comment]
I re-tested the 2.1 to 4.0 upgrade with the latest changes and things went well, no errors in the logs except for the Monitor complaining that it couldn't get data from the Manager which was happening before with the HA code.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 2 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1152]: I implemented the change that I described above in 0db6fc6

**Review by keith-turner — APPROVED** [review]

**Comment by ctubbsii** [comment]
@dlmarion I think these changes broke several tests. There are NPEs from parsing host and port in a few ITs now. See `org.apache.accumulo.test.functional.GracefulShutdownIT.testGracefulShutdown`, `org.apache.accumulo.test.functional.KerberosIT.testRestartedManagerReusesSecretKey`, and `org.apache.accumulo.test.functional.ManagerFailoverIT.test`

**Comment by dlmarion** [comment]
Ok, I will look at them.

**Comment by dlmarion** [comment]
Created #5429 which resolves the issue, the ITs mentioned above pass with the fix in #5429.
