### PR TITLE
Block changing manager NORMAL state until fate is ready

### LINKED ISSUE #3716: Error thrown when switching from SAFE_MODE to NORMAL manager state
**Describe the bug**
While testing the changes for #3711 I was using `accumulo org.apache.accumulo.manager.state.SetGoalState`. Every time I switch the goal state from `SAFE_MODE` to `NORMAL` the following shows up in the logs:
```
2023-08-22T13:30:51,611 [manager.EventCoordinator] INFO : State changed from NORMAL to SAFE_MODE
2023-08-22T13:30:51,744 [manager.EventCoordinator] INFO : [Normal Tablets]: 1 tablets are UNASSIGNED
2023-08-22T13:30:51,744 [manager.EventCoordinator] INFO : [Metadata Tablets]: 2 tablets are HOSTED
2023-08-22T13:31:11,805 [manager.EventCoordinator] INFO : State changed from SAFE_MODE to NORMAL
2023-08-22T13:31:11,805 [manager.Manager] ERROR: Error occurred reading / switching manager goal state. Will continue with attempt to update status
java.lang.IllegalStateException: Access to Fate should not have been initialized prior to the Manager finishing upgrades. Please save all logs and file a bug.
	at org.apache.accumulo.manager.Manager.setManagerState(Manager.java:310) ~[accumulo-manager-2.1.2-SNAPSHOT.jar:2.1.2-SNAPSHOT]
	at org.apache.accumulo.manager.Manager$StatusThread.run(Manager.java:767) ~[accumulo-manager-2.1.2-SNAPSHOT.jar:2.1.2-SNAPSHOT]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.2-SNAPSHOT.jar:2.1.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The goal state always seems to switch correctly. I'm not too sure whats going on here or if this is truly a bug but wanted to double check.

The error is thrown here:
https://github.com/apache/accumulo/blob/fcaf4d35a67089b60b87f19f7f1a32e1d74a75df/server/manager/src/main/java/org/apache/accumulo/manager/Manager.java#L308-L315

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.3-SNAPSHOT (fcaf4d35a67089b60b87f19f7f1a32e1d74a75df)

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. setup accumulo with uno
2. set the goal state to safe mode: `accumulo org.apache.accumulo.manager.state.SetGoalState SAFE_MODE`
3. set the goal state back to normal: `accumulo org.apache.accumulo.manager.state.SetGoalState NORMAL`

### PR DESCRIPTION
**Pull request by ctubbsii**
* Block switching manager state to NORMAL when the goal state is specified as NORMAL, periodically logging a message about waiting (related to #2990)
* Also fix some code quality issues by removing redundant check for `oldState != newState`, using a switch statement for newState instead, and using enum equality check as `==` instead of `.equals()`

This fixes #3716

### CODE REVIEW

**Review by EdColeman — APPROVED** [review]

**Comment by ctubbsii** [comment]
@DomGarguilo Are you able to test this? I'm curious if you'll be able to reproduce what you saw, or if this fixes it.

**Comment by DomGarguilo** [comment]
> @DomGarguilo Are you able to test this? I'm curious if you'll be able to reproduce what you saw, or if this fixes it.

Just tested this out and I am still seeing error after switching the goal state from safe mode to normal

**Comment by ctubbsii** [comment]
> > @DomGarguilo Are you able to test this? I'm curious if you'll be able to reproduce what you saw, or if this fixes it.
> 
> Just tested this out and I am still seeing error after switching the goal state from safe mode to normal

It didn't block? Did it change the error message at least? Are you seeing the notice about blocking, or the same message you had before?

**Comment by DomGarguilo** [comment]
> > > @DomGarguilo Are you able to test this? I'm curious if you'll be able to reproduce what you saw, or if this fixes it.
> > 
> > 
> > Just tested this out and I am still seeing error after switching the goal state from safe mode to normal
> 
> It didn't block? Did it change the error message at least? Are you seeing the notice about blocking, or the same message you had before?

I am seeing the same thing as before:
```
2023-08-23T09:42:14,932 [manager.EventCoordinator] INFO : State changed from NORMAL to SAFE_MODE
2023-08-23T09:42:14,959 [balancer.TableLoadBalancer] INFO : Loaded class org.apache.accumulo.core.spi.balancer.SimpleLoadBalancer for table +rep
2023-08-23T09:42:15,046 [manager.EventCoordinator] INFO : [Metadata Tablets]: 2 tablets are HOSTED
2023-08-23T09:42:15,048 [manager.EventCoordinator] INFO : [Normal Tablets]: 1 tablets are UNASSIGNED
2023-08-23T09:43:00,229 [manager.EventCoordinator] INFO : State changed from SAFE_MODE to NORMAL
2023-08-23T09:43:00,229 [manager.Manager] ERROR: Error occurred reading / switching manager goal state. Will continue with attempt to update status
java.lang.IllegalStateException: Access to Fate should not have been initialized prior to the Manager finishing upgrades. Please save all logs and file a bug.
	at org.apache.accumulo.manager.Manager.setManagerState(Manager.java:309) ~[accumulo-manager-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
	at org.apache.accumulo.manager.Manager$StatusThread.run(Manager.java:769) ~[accumulo-manager-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.3-SNAPSHOT.jar:2.1.3-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ctubbsii** [comment]
Oh, I see. I misread the code. It's assuming that the transition to NORMAL only occurs once, so it is expected that the fateRef *is* null at this point. The error message occurs only if fateRef is *not* null. All I've done in this change is ensure it definitely is *not* null, so the error message is guaranteed to appear after blocking until it is non-null.

I'm not sure if we can do anything to avoid the error message now... I think you're just going to see that if you manually change it to safe mode after fate has started, and then back to normal, because of course fate would be running, since it was previously in a normal mode. We could shut down fate when going into safe mode, and then bring it back after going back to normal... but I don't think that's a great idea.

**Comment by EdColeman** [comment]
`We could shut down fate when going into safe mode` - that would prevent using SAFE_MODE in an emergency if you wanted to prevent additional damage, but needed things up to troubleshoot / fix.

Could adding a check to see if the upgrade code actually needs to run before the fate check matter?  If the code is already the correct version, having FATE running may not matter.  I believe that FATE check is to protect from upgrading with outstanding operation that may have different serializations.  If an upgrade *IS NOT* required - then there should not be a serialization concern - so having FATE initialized may not matter.

However, there may be reasons not to have FATEs running in SAFE_MODE because they could be doing things that SAFE_MODE is trying to prevent.

**Comment by ctubbsii** [comment]
I pushed up a different change. This one avoids the error message if it transitions to NORMAL after the upgrade is complete. However, I think there could be a race condition in this implementation...  there's a small window of time where fate could be running while the upgrade is not complete, but this implementation won't notice because by the time it checks, the upgrade completes. I think that's probably okay, though.

**Comment by ctubbsii** [comment]
@DomGarguilo Would appreciate it if you were able to try to reproduce with the latest change in this PR.

**Review by DomGarguilo — APPROVED** [review]
I confirmed that with the current changes, the error no longer comes up when switching the manager to NORMAL goal state.

**Comment by ctubbsii** [comment]
@keith-turner I think this is ready to merge, but was wondering if you had thoughts on the race condition that might get overlooked if the fate object is created while it is still upgrading, but the upgrade finishes before we check it.

**Review by Manno15 — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 1]
```diff
@@ -280,38 +280,42 @@ Fate<Manager> fate() {
...
       /* STOP */                    {O, O, O, O, O, X, X}};
   //@formatter:on
-  synchronized void setManagerState(ManagerState newState) {
-    if (state.equals(newState)) {
+  synchronized void setManagerState(final ManagerState newState) {
+    if (state == newState) {
       return;
     }
     if (!transitionOK[state.ordinal()][newState.ordinal()]) {
       log.error("Programmer error: manager should not transition from {} to {}", state, newState);
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:288]: Not requesting any change, this is just a question.  Would anyone happen to know why this does not throw an exception instead of or in addition to logging?

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 2]
```diff
@@ -280,38 +280,42 @@ Fate<Manager> fate() {
...
+        }, 100L, 1000L, MILLISECONDS);
+        ThreadPools.watchNonCriticalScheduledTask(future);
+        break;
+      case HAVE_LOCK:
+        upgradeCoordinator.upgradeZookeeper(getContext(), nextEvent);
+        break;
+      case NORMAL:
+        // fate isn't started until after upgrades are done, so non-null fateRef implies isUpgrading
+        // should return false
+        if (fateRef.get() != null && isUpgrading()) {
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:310]: The manager starts off assuming an upgrade is not happening, thinking this assumption could be improved by changing the following variable creation to start off as true.  Then the manager would assume an upgrade is happening until it gets positive evidence otherwise.  Not sure if that change breaks anything, it would make this validation a bit stronger.

```java
private final AtomicBoolean managerUpgrading = new AtomicBoolean(true);
```

Alternatively the instance variable `managerUpgrading` could be dropped and the method ` isUpgrading()` changed to have the following impl.   This would have the same effect where the manager assumes an upgrade is in progress from startup until it determines its done or not needed.

```java
  @Override
  public boolean isUpgrading() {
    return upgradeCoordinator.getStatus() != UpgradeCoordinator.UpgradeStatus.COMPLETE;
  }
```

**Review by keith-turner — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 2 above)
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:310]: The way other code sets these, it seems important to read `fateRef.get()` first and then `isUpgrading()`. The code is doing that, not sure if `&&` allows the reads to happen in different orders at runtime though.

**Comment by keith-turner** [comment]
> @keith-turner I think this is ready to merge, but was wondering if you had thoughts on the race condition that might get overlooked if the fate object is created while it is still upgrading, but the upgrade finishes before we check it.

The check may not catch that, but I don't think the code currently does that.  It we wanted to get more defensive about that could add an explicit check in the fate startup code that ensures upgrade is not running.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:288]: Good question. I checked the history, and it looks like this behavior has been the same since the initial commit at the ASF. I could try to investigate the history prior to the software grant agreement, but it would take time and I doubt I'll find any explanation or documentation to explain why.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 2 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:310]: > not sure if `&&` allows the reads to happen in different orders at runtime though

No. Java defines this pretty well. Just like C/C++, it is defined to be a left-to-right short-circuiting operation. If it short-circuits, then nothing on the right is evaluated and has no side effects.

**Comment by ctubbsii** [comment]
I had a few ideas for what to do next with this, but they aren't ready. I can update this PR later this evening.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 1 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: @keith-turner This made sense to change to a thrown exception. I don't think it'd be safe to merely log an error. Even though I've never actually seen this error... if it happened, I think I'd prefer to see the stack trace and the state change to be prevented from occurring, rather than just see the error message and the state change occur anyway.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 2 above)
Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: I ended up going the second route with this. It made things much nicer to reason about, and I could use isUpgrading for more strict checks elsewhere.
