### PR TITLE
Retain recently failed servers in monitor status and server views

### LINKED ISSUE #6345: Inconsistent monitor handling for dead servers
**Describe the bug**
When a server component is killed, its row in its corresponding monitor page just shows an empty row of metrics. It also does not affect the status indicators so if a server dies it can look as if everything is green.

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. With two tservers running, kill the process of one of them
2. Watch the tservers table and status indicators

**Expected behavior**
Recently dead servers should stay visible briefly then eventually expire. The status indicators for that server type should show ERROR or WARN in this case.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #6345 

Before these changes, when a server process died, the dead server would linger on a server page with empty metrics but the corresponding status indicators (LEDs and banners) did not reflect that a server was down since it was still "present" in the incoming data. This PR fixes that by caching the recently failed servers for 10 mins, counting them as unavailable in the eyes of the status calculations, and using that same retained set when building the server process views.

I manually tested this by killing some servers and observing the correct statuses and expire behavior.

### CODE REVIEW

**Comment by DomGarguilo** [comment]
Added a small fix in 3e2f3e1 that i noticed while testing these changes. It removes duplicate banner hide/show paths that caused some inconsistencies between the banner(s) state on manual refresh vs auto-refresh.

**Comment by dlmarion** [comment]
If I understand the issue correctly, it's that `allMetrics` is a Cache with a 10 minute expiration. In the InformationFetcher we spin up a task for each known server to get an updated view of its metrics. If there is an exception then we call `allMetrics.invalidate(ServerId)`. However, we don't remove servers from `allMetrics` that are not in the current server set in the code snippet below.

https://github.com/apache/accumulo/blob/9eef27060407549f477aec47e78bc582896867cf/server/monitor/src/main/java/org/apache/accumulo/monitor/next/InformationFetcher.java#L285-L292

Would doing that fix the issue? If so, then it might point to the fact that we don't need a Cache at all and retaining old information is presenting a problem. Maybe we can just replace it with a Map instead.

**Comment by DomGarguilo** [comment]
> If I understand the issue correctly, it's that `allMetrics` is a Cache with a 10 minute expiration. In the InformationFetcher we spin up a task for each known server to get an updated view of its metrics. If there is an exception then we call `allMetrics.invalidate(ServerId)`. However, we don't remove servers from `allMetrics` that are not in the current server set in the code snippet below.
> 
> https://github.com/apache/accumulo/blob/9eef27060407549f477aec47e78bc582896867cf/server/monitor/src/main/java/org/apache/accumulo/monitor/next/InformationFetcher.java#L285-L292
> 
> Would doing that fix the issue? If so, then it might point to the fact that we don't need a Cache at all and retaining old information is presenting a problem. Maybe we can just replace it with a Map instead.

I think that would mostly just make the dead servers disappear faster. The real problem was the status data and the server page data could get out of sync about a recently dead server. The current implementation still makes sense to me because it keeps the metrics cache doing what its intended to do (cache metrics) and a separate, explicit collection for the dead servers so they still show up as dead for a short period.

File: server/monitor/src/main/java/org/apache/accumulo/monitor/next/SystemInformation.java [hunk 1]
```diff
@@ -667,6 +670,13 @@ public void processMetricsError(ServerId server) {
     allMetrics.invalidate(server);
   }
 
+  public void retainProblemServer(ServerId server) {
+    problemHosts.add(server);
+    metricProblemHosts.add(server);
+    retainedProblemHosts.add(server);
```
Comment (dlmarion) [inline server/monitor/src/main/java/org/apache/accumulo/monitor/next/SystemInformation.java:678]: We need a better name. Not for this PR, but host implies server name without port.

**Review by dlmarion — APPROVED** [review]
