### PR TITLE
Added RootRecoveryIT that exhibits bug in root table assignment

### LINKED ISSUE #5566: Broken or Flaky test: ScanServerUpgrade11to12TestIT.testScanRefTableCreation
**Test name(s)**
 - ScanServerUpgrade11to12TestIT.testScanRefTableCreation

**Describe the failure observed**
This test seems to hang a lot, and causes a bunch of internal exceptions, and possibly dead threads inside Accumulo, because ZooPropStore throws an IllegalStateException when the table doesn't exist.

I propose to remove the test.

```
java.lang.IllegalStateException: Invalid request for TablePropKey{path=/tables/+scanref/config}, the property node does not exist
  at org.apache.accumulo.server.conf.store.impl.ZooPropStore.get(ZooPropStore.java:157) ~[classes/:?]
  at org.apache.accumulo.server.conf.util.PropSnapshot.updateSnapshot(PropSnapshot.java:104) ~[classes/:?]
  at org.apache.accumulo.server.conf.util.PropSnapshot.getVersionedProperties(PropSnapshot.java:69) ~[classes/:?]
  at org.apache.accumulo.server.conf.ZooBasedConfiguration.getSnapshot(ZooBasedConfiguration.java:148) ~[classes/:?]
  at org.apache.accumulo.server.conf.ZooBasedConfiguration.getProperties(ZooBasedConfiguration.java:129) ~[classes/:?]
  at org.apache.accumulo.core.conf.AccumuloConfiguration.get(AccumuloConfiguration.java:113) ~[classes/:?]
  at org.apache.accumulo.core.util.ConfigurationImpl.get(ConfigurationImpl.java:72) ~[classes/:?]   
  at org.apache.accumulo.core.spi.balancer.TableLoadBalancer.getResourceGroupNameForTable(TableLoadBalancer.java:89) ~[classes/:?]
  at org.apache.accumulo.core.spi.balancer.TableLoadBalancer.balance(TableLoadBalancer.java:218) ~[classes/:?]
  at org.apache.accumulo.manager.Manager$StatusThread.balanceTablets(Manager.java:942) ~[classes/:?]
  at org.apache.accumulo.manager.Manager$StatusThread.updateStatus(Manager.java:803) ~[classes/:?]  
  at org.apache.accumulo.manager.Manager$StatusThread.run(Manager.java:769) ~[classes/:?]           
  at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[classes/:?]
  at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Testing Environment:**
 - Version of this project: 4.0.0-SNAPSHOT
 - First commit known to fail (or current commit): 77078f321fb492c0d80499973df04b386282e06f (probably was failing before this)
 - OS: Fedora 42
 - Java: temurin-17-jdk
 - Maven: 3.9.6
 - Other environment details: Fails in Jenkins, locally in Eclipse IDE, and on CLI via a timeout

**What have you tried already?**

I attempted to identify whether more needed to be done in the test to put the table in a safe to delete state before removing it. However, because it breaks so many assumptions about built-in tables, it seems like it would add too much complexity to accommodate this test.

**Additional context**

This test is generally a problem because it breaks critical assumptions that built-in tables always exist, and cannot be created or removed after upgrades. This test tries to simulate a pre-upgrade state by manually deleting the table, and re-running the upgrade steps as an integration test. However, that causes a lot of errors because the built-in table must exist. So, this isn't really safe to do in a running system for an integration test. A separate upgrade test process should be used to test upgrade code across versions for anything that can't be tested using a unit test.

### LINKED ISSUE #5577: Create an IT for the race condition identified in #5531
> I think the issue in #5531 was revealed by the presence of this test, but this test, trying to simulate a portion of a previous version's state to exercise a specific upgrade step on a live system is inherently flaky, because it breaks core assumptions about the state of the built-in tables on a running system. That has consequences in other areas of the code than just the balancer race condition that was identified in #5531. I still think this test should be deleted, but agree that we need a new, more narrow, test to check for that race condition that was identified in #5531. 

 _Originally posted by @ctubbsii in [#5566](https://github.com/apache/accumulo/issues/5566#issuecomment-2902351595)_

I believe the test discussed in #5566 wrote to the accumulo.root table when the metadata table changes to delete the accumulo.scanref table were flushed, resulting in a new RFile for the accumulo.metadata table. A new test should do something similar by causing changes to the root table, but should not do so by attempting to remove a built-in table, which breaks other assumptions on the live system.

### PR DESCRIPTION
**Pull request by dlmarion**
Created IT that exhibits an issue introduced with #5416 that moved migrations from an in-memory object to a entries in the root and metadata table. Deleted ScanServerUpgrade11to12TestIT.testScanRefTableCreation.

Closes  #5566 #5577

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+
+    // This scan should not time out
+    try (AccumuloClient c = Accumulo.newClient().from(getClientProps()).build()) {
+      Wait.waitFor(() -> c.instanceOperations().getServers(Type.MANAGER).size() == 1);
+      Wait.waitFor(() -> c.instanceOperations().getServers(Type.TABLET_SERVER).size() == 2);
+
+      LOG.info("Scanning root table");
+      Scanner s = c.createScanner(SystemTables.ROOT.tableName());
+      @SuppressWarnings("unused")
+      int ignoredSize = Iterables.size(s);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java:114]: I think spotbugs will flag on Iterables here. Can also suppress the warning with a more specific assertion on the returned size.

```suggestion
      LOG.info("Scanning root table");
      try (Scanner s = c.createScanner(SystemTables.ROOT.tableName())) {
        assertTrue(s.stream().count() > 0);
      }
```

File: test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    try (BatchWriter writer =
+        getCluster().getServerContext().createBatchWriter(SystemTables.METADATA.tableName())) {
+      var mutation = new Mutation("3;<");
+      mutation.putDelete(TabletColumnFamily.AVAILABILITY_COLUMN.getColumnFamily(),
+          TabletColumnFamily.AVAILABILITY_COLUMN.getColumnQualifier());
+      writer.addMutation(mutation);
+      writer.flush();
+    } catch (TableNotFoundException | MutationsRejectedException e) {
+      throw new RuntimeException(e);
+    }
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java:89]: The test class already throws Exception. You don't need to catch and convert the exception here.

```suggestion
    }
```

**Review by ctubbsii — CHANGES_REQUESTED** [review]
Small suggestions. Overall, looks fine.

Optional: Could remove ScanServerUpgrade11to12TestIT.testScanRefTableCreation here to close #5566 at the same time.

File: test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java (hunk 2 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java:89]: This was a copy/paste issue. I'll fix.

File: test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java (hunk 1 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java:114]: It doesn't look like SpotBugs failed on this.

Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/RootRecoveryIT.java:110]: It's also nice to avoid unnecessary 3rd party libraries when we can do the same thing with a built-in Java construct that is just as easy to read.
