### PR TITLE
Move DataTable errors to console to avoid alerts

### LINKED ISSUE #3057: Annoying pop-up in Monitor
During testing of 2.1.0 RC4 I shut down the compaction coordinator. I had the monitor open and was on the `/ec` page to look at the external compaction information. It appears that when the ajax calls to refresh the tables failed,  a pop-up would appear that said:

`DataTables warning: table id=<tableName> - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Is there a way to suppress this and do something different? When the `manager` is down, there is just a message on the main page saying it's down - no popup.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Closes #3057

This change makes DataTable errors get logged to console instead of creating many, spammy alerts on the page.

### CODE REVIEW

File: server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js [hunk 1]
```diff
@@ -31,6 +31,10 @@ $(document).ready(function () {
   if (sessionStorage.ecDetailsJSON === undefined) {
     sessionStorage.ecDetailsJSON = JSON.stringify([]);
   }
+
+  // display datatables errors in the console instead of in alerts
+  $.fn.dataTable.ext.errMode = 'throw';
```
Comment (ctubbsii) [inline server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js:36]: This looks like a global parameter. Do we want to set this globally? Is this okay for other tables that might be displayed on the page (if there are any)?

Comment (DomGarguilo) [reply server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/ec.js:36]: The other tables will create similar alerts when the scenario outlined in #3057 happens, so I think its best that it affects all of the tables in this case.

**Review by ctubbsii — APPROVED** [review]

**Review by cshannon — APPROVED** [review]
