### PR TITLE
Ensure compaction duration is not reset on coordinator restart

### LINKED ISSUE #4570: Moving the coordinator resets compaction duration
**Describe the bug**
When the coordinator is restarted, the duration reported on the external compactions page in the monitor changes and reports a new time that is never greater than the coordinators uptime. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.x
 - OS: [e.g. CentOS 7.5] centos

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Run a compaction that should take a time longer than your test (30min)
2. Wait until the monitor shows the compaction duration being greater than 5min.
3. Stop the coordinator and start it again (alternatively, start it on a completely different node).
4. Check the monitor, the duration time should now roughly match the time since the coordinator's start time 

**Expected behavior**
The coordinator should report back the compaction duration based on state and this value should be consistent throughout coordinator process restarts.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #4570 

This PR changes the way the duration of a compaction is calculated. The main change is the addition of a field, that was added to `FileCompactor`, which denotes the age of the current running compaction. This field is ultimately propagated to the monitor.

Before these changes, the age of a compaction was calculated by the coordinator which took the difference between the timestamps of the first and last update it had for that compaction. The bug where the duration was never older than the age of the coordinator came from this map of updates it used to calculate the compactor age being reinitialized when the coordinator started up.

Details to help with review:
* `RunningCompactionInfo` is where the diff of timestamps used to be calculated and now it just uses the duration value
* `FileCompactor` now has `currentCompactionStartTime` which is used to calculate the age of the current compaction
* A test case was added to ensure that the age of a duration is greater than the age of the compactor

Most other changes are thrift changes or intermediate objects that needed to be adjusted to carry this new value.

### CODE REVIEW

**Comment by dlmarion** [comment]
Another approach, which may touch less files, would be to just track the start time in the Compactor itself vs in the FileCompactor. [FileCompactorRunnable.initialize](https://github.com/apache/accumulo/blob/2.1/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L521) could return the start time and use it in the STARTED status message. That method is called [here](https://github.com/apache/accumulo/blob/2.1/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L736) and most of the other status messages are sent from that method. The SUCCEEDED message is sent from FileCompactorRunnable, so the start time could be used there if it was a member variable of the object that was set by initialize. Just a thought.

**Comment by keith-turner** [comment]
> I haven't looked into it very much yet but it seems like using the new currentCompactionStartTime would more accurately represent the age of an active compaction. This would allow us to remove the other variable too.
>
>Any thoughts on this?

Starting to track time in call() vs the constructor seems a bit better to me.  It would need to be set before [this line in calls()](https://github.com/apache/accumulo/blob/751c549108aff51cf55d93861cc254b743d54e5a/server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java#L283) so that it is visible to the code that inspects running compactions.

**Comment by DomGarguilo** [comment]
> Another approach, which may touch less files, would be to just track the start time in the Compactor itself vs in the FileCompactor. [FileCompactorRunnable.initialize](https://github.com/apache/accumulo/blob/2.1/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L521) could return the start time and use it in the STARTED status message. That method is called [here](https://github.com/apache/accumulo/blob/2.1/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L736) and most of the other status messages are sent from that method. The SUCCEEDED message is sent from FileCompactorRunnable, so the start time could be used there if it was a member variable of the object that was set by initialize. Just a thought.

I think it seems like a good idea to track the time in `FileCompactorRunnable` but this seems to also imply that we keep track and send the start time of the compaction as opposed to the changes that I made that send the duration of the compaction at the time of the update. To me it seems to make sense to send the duration but I am not sure if you had a reason it should be the other way?

File: server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java [hunk 1]
```diff
@@ -107,6 +108,11 @@ public AtomicReference<FileCompactor> getFileCompactor() {
       return new AtomicReference<>(compactor);
     }
 
+    @Override
+    public Duration getCompactionAge() {
```
Comment (dlmarion) [inline server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java:112]: `toNanos` is called on the return value in almost all cases. I'm wondering if you want to change this to `Duration.ZERO` to prevent a `NullPointerException`. Same comment for the same change in `ExternalDoNothingCompactor`.

**Review by dlmarion — COMMENTED** [review]
The changes look good. One comment about possibly preventing a NPE in a test. CompactorTest is failing, not sure if it's due to a NPE or not.

File: server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java [hunk 2]
```diff
@@ -515,13 +518,15 @@ protected FileCompactorRunnable createCompactionJob(final TExternalCompactionJob
 
     return new FileCompactorRunnable() {
 
-      private AtomicReference<FileCompactor> compactor = new AtomicReference<>();
+      private final AtomicReference<FileCompactor> compactor = new AtomicReference<>();
+      private long startTimeNanos = -1;
```
Comment (keith-turner) [inline server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java:522]: I think multiple threads are reading/writing this.  Should probably make it volatile or use AtomicLong

File: server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java (hunk 1 above)
Comment (DomGarguilo) [reply server/compactor/src/test/java/org/apache/accumulo/compactor/CompactorTest.java:112]: Yea good idea. This was causing the test failure but is fixed as of 12dc0f6.

**Comment by DomGarguilo** [comment]
> > I haven't looked into it very much yet but it seems like using the new currentCompactionStartTime would more accurately represent the age of an active compaction. This would allow us to remove the other variable too.
> > Any thoughts on this?
> 
> Starting to track time in call() vs the constructor seems a bit better to me. It would need to be set before [this line in call()](https://github.com/apache/accumulo/blob/751c549108aff51cf55d93861cc254b743d54e5a/server/base/src/main/java/org/apache/accumulo/server/compaction/FileCompactor.java#L283) so that it is visible to the code that inspects running compactions.

I made this change in 09a495c. Changed the method name and return type to force the calling code to explicitly deal with the time units.

**Review by keith-turner — APPROVED** [review]
