### PR TITLE
Validate Property Values

### LINKED ISSUE #3145: Shell commands allow for invalid Property types to be set
**Describe the bug**

When using the accumulo shell to set properties, a user is able to set an invalid property value for value types such as Boolean and Port. 

Example: 
This property is a boolean type.
https://github.com/apache/accumulo/blob/fbe1ee8cfc98f788329208419d682429c90784c2/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L438-L439

However, it can be set to an integer value.
```        
root@uno> config -s tserver.monitor.fs=345                                      
root@uno> config -f tserver.monitor.fs                                          
-----------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------                       
SCOPE      | NAME                                                               | VALUE                            
-----------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------                       
default    | tserver.monitor.fs ............................................... | false
system     |    @override ..................................................... | 345                                                                                                      
-----------+--------------------------------------------------------------------+-----------------------------------------------------------------------------------
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.x, 1.10.x
 - OS: Centos7
 - Others:

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Start accumulo Shell
2. Use the Config Command to find a Boolean or Port Property Type `config -f <property>`
3. Use the `config -s <property>=<invalid value>` command to set that type to an invalid value
4. Use `config -f <property>` to show the invalid value is set

**Expected behavior**
The Shell tool should check the property value and error on invalid values instead of allowing them to be set. 

**Additional context**
I assume that all versions of accumulo have this bug, but I have only checked against 1.10, 2.1, and main.

### PR DESCRIPTION
**Pull request by ddanielr**
Closes #3145 
These changes add the ability to validate system, namespace, and table-specific properties for accumulo.

Values are now being validated on the backend and client validation exceptions show as a `ThriftPropertyException` exception type. 

See #3173 for WIP feedback if desired.

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java [hunk 1]
```diff
@@ -470,6 +472,93 @@ public void grepTest() throws IOException {
...
+          break;
+        case FRACTION:
+          invalidValue = "10Percent";
+          break;
+        case ABSOLUTEPATH:
+          invalidValue = "~/foo";
+          break;
+        case CLASSNAME:
+          Shell.log.debug("CLASSNAME properties currently fail this test");
+          Shell.log.debug("Regex used for CLASSNAME property types may need to be modified");
```
Comment (dlmarion) [inline test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java:525]: Should we fix the regex as part of this PR?

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 2]
```diff
@@ -205,6 +205,17 @@ public void createTableWithTableNameLengthLimit()
     assertFalse(tableOps.exists(t2));
   }
 
+  @Test
+  public void createTableWithBadProperties()
+      throws AccumuloException, AccumuloSecurityException, TableExistsException {
+    TableOperations tableOps = accumuloClient.tableOperations();
+    String t0 = StringUtils.repeat('a', MAX_TABLE_NAME_LEN - 1);
```
Comment (dlmarion) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java:212]: We typically create table names with something like `String t0 = getUniqueNames(1)[0];

**Comment by dlmarion** [comment]
Kicked off full IT build

File: test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java (hunk 1 above)
Comment (ddanielr) [reply test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java:525]: Currently, all of these changes don't alter property structure, they just enforce the previously defined types. 

Modifying a property regex has the potential to break legitimate uses.
So, I'd rather open an issue for the regex fix and track that as a separate action.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 2 above)
Comment (ddanielr) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java:212]: Ah I see that on line 221. 
So does this need to change?

Comment (EdColeman) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java:212]: It would be nice for consistency - and the getUniqueNames uses the test and the function in the name to allow multiple tests in the same file to avoid collisions.  Not sure if it would apply here, but that would also pop up in the logs if anyone was trying to chase something down.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java:212]: Sorry @EdColeman  - I think I was typing and didn't see your response.

**Comment by dlmarion** [comment]
Full IT build succeeded.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 2 above)
Comment (ddanielr) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java:212]: Ok, I changed it and I'm running the `TableOperationsIT` now. Once it's done I'll push the commit up.

**Review by dlmarion — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java [hunk 3]
```diff
@@ -470,6 +472,93 @@ public void grepTest() throws IOException {
...
+          break;
+        case BOOLEAN:
+          invalidValue = "fooFalse";
+          break;
+        case URI:
+          invalidValue = "12///\\{}:;123!";
+          break;
+        default:
+          Shell.log
+              .debug("Property Type: " + propertyType.toString() + " has no defined test case");
```
Comment (EdColeman) [inline test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java:544]: The toString() on `propertyType.toString()` is unnecessary.

File: test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java [hunk 4]
```diff
@@ -470,6 +472,93 @@ public void grepTest() throws IOException {
...
+          invalidValue = "foo";
+      }
+      String setCommand = "config -s ";
+      if (Property.isValidTablePropertyKey(property.getKey())) {
+        setCommand = "config -t " + testTable + " -s ";
+      }
+      Shell.log.debug("Testing Property {} with Type {}", property.getKey(),
+          propertyType.toString());
```
Comment (EdColeman) [inline test/src/main/java/org/apache/accumulo/test/shell/ShellIT.java:552]: The toString() on `propertyType.toString()` is unnecessary.

File: core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java [hunk 5]
```diff
@@ -88,13 +88,28 @@ public void testPorts() {
...
         assertFalse(usedPorts.contains(port), "Port already in use: " + port);
         usedPorts.add(port);
         assertTrue(port > 1023 && port < 65536, "Port out of range of valid ports: " + port);
       }
     }
   }
 
+  @Test
+  public void testBooleans() {
+    for (Property prop : Property.values()) {
```
Comment (EdColeman) [inline core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java:101]: Is this loop necessary?  The test would be valid with any single boolean property.  Also, the test in ShellIT that you added is more comprehensive, testing each type - would it be better to test those conditions here?  Not sure if it needs to be in both places, but unit testing would be faster than needing to run an IT.

**Review by EdColeman — COMMENTED** [review]
Looks good - just some minor suggestions.

File: core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java (hunk 5 above)
Comment (ddanielr) [reply core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java]: Replaced `testBooleans` with `testPropertyValidation` that runs through the property possibilities and attempts invalid types. 

I left the ShellIT alone since it's a client test of the RPC calls. If the shell is ever spun out of this codebase it would remain valuable.

**Review by EdColeman — APPROVED** [review]
LGTM - maybe as a follow-on the tests in PropertyTest could be expanded to test variations of valid values.  The boolean test that was modified was testing combinations of true, True, false, False, my initial though that it was unnecessary to loop through all of the properties, not the condition.

The testPropertyValidation test is a nice addition to check that each type will fail validation.

While the is a specific host:port test in PropertyTest, it may be an improvement if tests were included for things like 100M, 100m, 100G, 100g for memory, (or whatever is valid) for each of the expected types (assuming that they are not tested elsewhere)

**Review by EdColeman — CHANGES_REQUESTED** [review]
Noticed that the check failed with a junit package issue:

```
Expected 0, but found 1 classes using the wrong JUnit APIs:
core/src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java
Error: Process completed with exit code 1.
```

Not sure where that is coming from, but it should be corrected before merging

**Comment by EdColeman** [comment]
The offending import in TabletLocatorImplTest  is 
```
import org.junit.Assert;
```

Also, there may be other checkstyle issues that need to be addressed:
```
[WARNING] src/main/java/org/apache/accumulo/core/clientImpl/TabletLocatorImpl.java:[356,9] (blocks) NeedBraces: 'if' construct must use '{}'s.
[WARNING] src/test/java/org/apache/accumulo/core/clientImpl/TabletLocatorImplTest.java:[61] (regexp) RegexpSinglelineJava: Use static imports for Assert.* methods for consistency

```

**Comment by ddanielr** [comment]
@EdColeman those changes weren't introduced in this PR. 

I think the latest merge to 2.1 caused the problem 
https://github.com/apache/accumulo/commit/cb22cc46bb4b8792c5b4c7a7a301b224ca1684c1

**Comment by EdColeman** [comment]
I have a PR incoming to fix 2.1

**Comment by ddanielr** [comment]
@EdColeman I merged in the latest changes from 2.1 and all tests are now passing.

**Review by EdColeman — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/NamespacesIT.java [hunk 6]
```diff
@@ -263,6 +263,20 @@ public void deleteNonEmptyNamespace() throws Exception {
     assertThrows(NamespaceNotEmptyException.class, () -> c.namespaceOperations().delete(namespace));
   }
 
+  @Test
+  public void setProperties() throws Exception {
+    String namespace = "nsTest";
+    c.namespaceOperations().create(namespace);
```
[the remark this answers is not in the document]
Comment (ddanielr) [reply test/src/main/java/org/apache/accumulo/test/NamespacesIT.java]: nope, that's an oversight on my part.

File: core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java [hunk 7]
```diff
@@ -88,13 +88,80 @@ public void testPorts() {
...
     }
   }
 
+  @Test
+  public void testPropertyValidation() {
+
+    for (Property property : Property.values()) {
+      PropertyType propertyType = property.getType();
+      String invalidValue, validValue = property.getDefaultValue();
+      System.out.printf("Testing property: %s with type: %s\n", property.getKey(), propertyType);
```
[the remark this answers is not in the document]
Comment (ddanielr) [reply core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java]: Implemented a `Logger` and removed the default print statements.

File: server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java [hunk 8]
```diff
@@ -74,7 +76,13 @@ private static String validateSystemProperty(String property, final String value
     if (!Property.isValidZooPropertyKey(property)) {
       IllegalArgumentException iae =
           new IllegalArgumentException("Zookeeper property is not mutable: " + property);
-      log.debug("Attempted to set zookeeper property.  It is not mutable", iae);
+      log.error("Encountered error setting zookeeper property", iae);
```
Comment (EdColeman) [inline server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java:79]: Did you happen to look at the exceptions as printed in the logs?  It seems likely that the method that catches the exception will also printout the stack trace.  If there was additional info to help development, maybe a trace statement?  Otherwise the logs may end up with two identical stack traces without adding additional information.

Also, error seems rather aggressive, services are going to keep running, 

If this code get reworked, it may be worth considering.

(I realize this has been merged, it was changed, committed before I got back to it. Just wanted to mention it if it helps going forward)

Comment (ddanielr) [reply server/base/src/main/java/org/apache/accumulo/server/util/SystemPropUtil.java:79]: @EdColeman confirmed that the calling method does in fact log the exceptions at the `error` level. 
I've opened https://github.com/apache/accumulo/pull/3184 to revert this change.
