### PR TITLE
Fixed ScanServerGroupConfigurationIT

### LINKED ISSUE #6154: Broken test: ScanServerGroupConfigurationIT
I noticed this test was failing when merging #6146 from 2.1 to main. I went back and tested it at the commit prior to the merge and it is still failing. Turning on trace logging, the client is choosing the TabletServer instead of the ScanServer in the ThriftScanner.

### PR DESCRIPTION
**Pull request by dlmarion**
ScanServerGroupConfigurationIT was failing because the ConfigurableScanServerSelector only checks for new ScanServers at 5 second intervals and the test was doing a lookup too quickly. The fix for the test is to just wait 5 seconds.

This change includes adding trace logging into the ConfigurableScanServerSelector for better debugging and formatting some of the large JSON blocks using Java text blocks.

Closes #6154

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java [hunk 1]
```diff
@@ -46,56 +46,60 @@
...
-     "     },"+
-     "     {"+
-     "       \"servers\": \"100%\","+
-     "       \"busyTimeout\": \"33ms\""+
-     "     }"+
-     "   ]"+
-     "  }"+
-     "]";
+  public static final String clientConfiguration = """
+  [ \
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java]: What is the purpose of these trailing slashes?

**Review by keith-turner — APPROVED** [review]
The logging changes look really useful.

File: test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java (hunk 1 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java]: It suppresses the newline character (ref [this](https://docs.oracle.com/en/java/javase/17/text-blocks/index.html#new-escape-sequences)). With the newlines in the JSON the json parsing was failing because it was only seeing the first line. So it appears that the client properties don't support a newline in the property value.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java]: I think I tracked down the issue. It has to do with the properties being written to a file and then read back in. When using ` \` at the end of each line in the text block, then the newlines are suppressed so that when the property is written out to a file it's just one line. Without the ` \` at the end of the line, each line contains a newline.

In MiniAccumuloCluster, the client properties are written to a file at

https://github.com/apache/accumulo/blob/4a4d84b3a955716a9a6751d2addd3cbcb5fc2a58/minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java#L271-L272

and then read back in at

https://github.com/apache/accumulo/blob/4a4d84b3a955716a9a6751d2addd3cbcb5fc2a58/minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java#L192-L193

After reading the client properties back in, the profile property contains just one line, which in this case is `[` and the json parsing fails.

Comment (DomGarguilo) [reply test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java]: Was going to leave a comment but ended up just throwing up a quick PR #6179 

Looked into where the properties were being written to the file and I think thats where the disconnect might have been. We manually wrote the .properties file without proper escaping. #6179 uses `.store()` off of  a properties object instead.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/ScanServerGroupConfigurationIT.java]: i'll merge your changes in and then update this PR to remove the ` \` chars.
