### PR TITLE
addSplits() improvement - start all fate ops before waiting on any

### LINKED ISSUE #4633: Speed of splitting lots of tablets could be improved
When the API is called to add splits to a table it currently does the following.

 1. Create a thread pool of size 16.  [Code link](https://github.com/apache/accumulo/blob/bfc5fc1dd80e6a4db57a1f233639b06433c29fee/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L476)
 2. Map provided split points to tablets.  [Code link](https://github.com/apache/accumulo/blob/bfc5fc1dd80e6a4db57a1f233639b06433c29fee/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L483)
 3. For each tablet run a split fate operation to completion by creating and waiting on a fate operation.  This is done in the thread pool created earlier.  [Code link](https://github.com/apache/accumulo/blob/bfc5fc1dd80e6a4db57a1f233639b06433c29fee/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L490)

If 1,000 splits are added and those map to 1,000 tablets, then the above algorithm would only work on 16 tablets at a time.  If all 1,000 tablets are hosted on tablet servers then it will probably take a while because only 16 will be unassigned and split at a time.

Fate operations always work through the same 4 rpcs, which are begin, execute, wait, and then finish.   The above situation could be improved by [starting](https://github.com/apache/accumulo/blob/bfc5fc1dd80e6a4db57a1f233639b06433c29fee/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L401-L402) all 1,000 fate operations before [waiting](https://github.com/apache/accumulo/blob/bfc5fc1dd80e6a4db57a1f233639b06433c29fee/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L407) on them.  Somehow this refactoring should avoid duplicating this [exception handling code](https://github.com/apache/accumulo/blob/bfc5fc1dd80e6a4db57a1f233639b06433c29fee/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java#L408-L440)

If all of the fate split operations could be started before waiting on them, then in the situation of splitting 1000 tablets that were all hosted it would allow all 1,000 to be unassigned and split concurrently in fate.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #4633 

This PR changes the way split fate operations are carried out in `addSplits()`. Before these changes, `addSplits()` would call `doFateOperation()` for each split which would start then wait for it to finish. The changes in this PR start all of the fate ops and then once all have started, wait for them all to finish.

So that error handling was not duplicated, I created a new method that executes a lambda within the original try-catch block from `doFateOperation()`

I did some crude benchmarking using `SplitMillionIT` and saw a decrease in time taken per 10,000 splits in the test. Per 10,000 splits, over 5 runs I saw an average time of 827.8ms on elasticity and 822.4ms on this branch. This difference seems negligible but I at least did not notice a performance decrease.

### CODE REVIEW

**Comment by keith-turner** [comment]
> I did some crude benchmarking using SplitMillionIT and saw a decrease in time taken per 10,000 splits in the test. Per 10,000 splits, over 5 runs I saw an average time of 827.8ms on elasticity and 822.4ms on this branch. This difference seems negligible but I at least did not notice a performance decrease.

For SplitMillionIT it is adding splits in order so it always splits the last tablet in the table.  So its only ever splitting a single a tablet at a time, so should not see much difference for that case.  Wrote the test below and  saw big time differences for it.  This test creates a lot of tablets, waits for them to be hosted, then splits many of the tablets.  For this scenario, lots of tablets need to be unassigned inorder to split.  Included time I saw after the test code.


```java
public class SpliRandomIT extends ConfigurableMacBase {

  private static final Logger log = LoggerFactory.getLogger(SpliRandomIT.class);

  @Override
  public void configure(MiniAccumuloConfigImpl cfg, Configuration hadoopCoreSite) {
    cfg.setMemory(ServerType.MANAGER, 1, MemoryUnit.GIGABYTE);
    cfg.setMemory(ServerType.TABLET_SERVER, 1, MemoryUnit.GIGABYTE);
    cfg.setProperty(Property.MANAGER_FATE_THREADPOOL_SIZE, "64");
  }

  @SuppressFBWarnings(value = {"PREDICTABLE_RANDOM", "DMI_RANDOM_USED_ONLY_ONCE"},
      justification = "predictable random is ok for testing")
  @Test
  public void testRandom() throws Exception {

    try (AccumuloClient c = Accumulo.newClient().from(getClientProperties()).build()) {
      String tableName = getUniqueNames(1)[0];

      Random rand = new Random();
      var ntc = new NewTableConfiguration().withInitialTabletAvailability(TabletAvailability.HOSTED)
          .withSplits(createSplits(rand, 1000));
      c.tableOperations().create(tableName, ntc);

      // wait for all 1000 tablets to be assigned, split will have to get them unassigned
      Wait.waitFor(() -> countLocationless(c, tableName) == 0);

      addSplits(c, tableName, createSplits(rand, 1000));

      Wait.waitFor(() -> countLocationless(c, tableName) == 0);

      addSplits(c, tableName, createSplits(rand, 1000));
    }
  }

  private static SortedSet<Text> createSplits(Random random, int num) {
    return random.longs().limit(num).mapToObj(l -> String.format("%016x", l)).map(Text::new)
        .collect(Collectors.toCollection(TreeSet::new));
  }

  private static void addSplits(AccumuloClient c, String tableName, SortedSet<Text> splits)
      throws Exception {
    long t1 = System.currentTimeMillis();
    c.tableOperations().addSplits(tableName, splits);
    long t2 = System.currentTimeMillis();
    log.info("Added {} splits in {}ms", splits.size(), t2 - t1);
  }

  private long countLocationless(AccumuloClient c, String tableName) throws Exception {
    return c.tableOperations().getTabletInformation(tableName, new Range())
        .filter(ti -> ti.getLocation().isEmpty()).count();
  }
}

```

Without the change in this PR, saw the following times for the test above.

```
2024-06-24T18:41:32,787 35 [functional.SpliRandomIT] INFO : Added 1000 splits in 37640ms
2024-06-24T18:42:23,246 35 [functional.SpliRandomIT] INFO : Added 1000 splits in 50408ms
```

with the changes in this PR, saw the times below.

```
2024-06-24T18:32:11,098 35 [admin.TableOperations] INFO : time to seed 518 14615ms
2024-06-24T18:32:12,599 35 [functional.SpliRandomIT] INFO : Added 1000 splits in 16209ms
2024-06-24T18:32:20,655 35 [admin.TableOperations] INFO : time to seed 654 7953ms
2024-06-24T18:32:22,538 35 [functional.SpliRandomIT] INFO : Added 1000 splits in 9877ms
```

The `time to seed` log message comes from making the following change.

```diff
diff --git a/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java b/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
index 213e8ba291..62ceb4b618 100644
--- a/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
+++ b/core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
@@ -162,6 +162,7 @@ import org.apache.accumulo.core.util.OpTimer;
 import org.apache.accumulo.core.util.Pair;
 import org.apache.accumulo.core.util.Retry;
 import org.apache.accumulo.core.util.TextUtil;
+import org.apache.accumulo.core.util.time.NanoTime;
 import org.apache.accumulo.core.volume.VolumeConfiguration;
 import org.apache.hadoop.fs.FileStatus;
 import org.apache.hadoop.fs.FileSystem;
@@ -498,6 +499,7 @@ public class TableOperationsImpl extends TableOperationsHelper {
       final ByteBuffer EMPTY = ByteBuffer.allocate(0);
 
       // begin the fate operation for each tablet without waiting for the operation to complete
+      var start = NanoTime.now();
       for (Entry<KeyExtent,List<Text>> splitsForTablet : tabletSplits.entrySet()) {
         var extent = splitsForTablet.getKey();
 
@@ -519,6 +521,7 @@ public class TableOperationsImpl extends TableOperationsHelper {
           throw new RuntimeException(e);
         }
       }
+      log.info("time to seed {} {}ms", tabletSplits.size(), start.elapsed().toMillis());
 
       // after all operations have been started, wait for them to complete
       for (Pair<TFateId,List<Text>> entry : opids) {
```

The times from  `time to seed` suggest we could still benefit from using a thread pool for the RPCs to seed the fate operations.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 1]
```diff
@@ -472,59 +485,66 @@ public void addSplits(String tableName, SortedSet<Text> splits)
...
-        List<Future<List<Text>>> splitTasks = new ArrayList<>();
+      ArrayList<Pair<TFateId,List<Text>>> opids = new ArrayList<>(tabletSplits.size());
 
-        for (Entry<KeyExtent,List<Text>> splitsForTablet : tabletSplits.entrySet()) {
-          Callable<List<Text>> splitTask = createSplitTask(tableName, splitsForTablet);
-          splitTasks.add(executor.submit(splitTask));
+      final ByteBuffer EMPTY = ByteBuffer.allocate(0);
+
+      // begin the fate operation for each tablet without waiting for the operation to complete
+      for (Entry<KeyExtent,List<Text>> splitsForTablet : tabletSplits.entrySet()) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java:501]: Based on the top level comment I made, if we really wanted to speed this up then the RPCs being executed in this loop could be done in a thread pool.  Does not have to be done in this PR, these changes already speed things up.  Running RPCs in a thread pool would speed things up even more.

**Comment by DomGarguilo** [comment]
Since this is approved and is an improvement on its own ill merge this in and make a follow on PR to add the other suggested optimization.
