### PR TITLE
Closes #1689: Don't catch Throwable (unless it's rethrown)

### LINKED ISSUE #1689: Tserver in bad state may be writing corrupted files during compactions.
The symptom is that the system is encountering an IOException (incorrect data check) where the zlib decompressor cannot uncompress a file.  The file would have been created during a previous compaction.

The tserver seems to be in a bad state, and rather than writing corrupt files, it would be preferable if the condition(s) can't be corrected, then stop the server.

On processing the corrupted files:

The IOException is being thrown on lines 348 or 385 of Compactor.compactLocalityGroup. (exceptions occur on both)
https://github.com/apache/accumulo/blob/7a2d12eaf785f924f555733a54f40828cdb2414f/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java#L348
or
https://github.com/apache/accumulo/blob/7a2d12eaf785f924f555733a54f40828cdb2414f/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java#L385

The file(s) can be partially processed with rfile-info.  You can examine the file metadata, but if you do something that reads the entire file (like -keyStats) then it fails with an exception reported in line 815 of RFile LocalityGroupReader.

When the files are being compacted it looks like the tserver was in an unhealthy state.  Potential contributors:

1) The dynamic class loader kept continually rebuilding.  AccumuloReloadingVFSClassLoader run loop just keeps executing - the message at line 83 appears frequently in the log.
https://github.com/apache/accumulo/blob/7a2d12eaf785f924f555733a54f40828cdb2414f/start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java#L83

2) The tablet servers are throwing a null pointer exception that is being logged by https://github.com/apache/accumulo/blob/7a2d12eaf785f924f555733a54f40828cdb2414f/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java#L452

There may be other issues, but these stand out in the logs.

### PR DESCRIPTION
**Pull request by dlmarion**
Modified code that was catching Throwable to mostly catch Exception, unless Throwable was being re-thrown. This, in conjunction with https://github.com/apache/accumulo/pull/1818, should expose issues that might be getting silently ignored.

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java [hunk 1]
```diff
@@ -177,9 +177,13 @@ public void run() {
       }
     } catch (SampleNotPresentException e) {
       addResult(e);
-    } catch (Throwable e) {
+    } catch (Exception e) {
       log.warn("exception while doing multi-scan ", e);
       addResult(e);
+    } catch (Error t) {
+      log.warn("Error while doing multi-scan ", t);
+      addResult(t);
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java:185]: Is there value in adding this to the result if we're re-throwing?

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java [hunk 2]
```diff
@@ -89,14 +88,16 @@ public void run() {
       }
     } catch (TooManyFilesException | SampleNotPresentException e) {
       addResult(e);
-    } catch (OutOfMemoryError ome) {
-      Halt.halt("Ran out of memory scanning " + scanSession.extent + " for " + scanSession.client,
-          1);
-      addResult(ome);
-    } catch (Throwable e) {
+    } catch (Exception e) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java:91]: Should this be more specific, like RuntimeException?

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java [hunk 3]
```diff
@@ -89,14 +88,16 @@ public void run() {
...
       log.warn("exception while scanning tablet "
           + (scanSession == null ? "(unknown)" : scanSession.extent), e);
       addResult(e);
+    } catch (Error t) {
+      log.warn(
+          "Error while scanning tablet " + (scanSession == null ? "(unknown)" : scanSession.extent),
+          t);
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java:98]: The message here has changed and no longer has the scan session client included. Also, you should use slf4j substitution syntax to format the message.

Are we sure we want to change the behavior to no longer Halt here? Is this change dependent on the one in #1818 to handle the shutdown?

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java [hunk 4]
```diff
@@ -111,7 +111,7 @@ public void run() {
       if (tablet.needsSplit()) {
         tablet.getTabletServer().executeSplit(tablet);
       }
-    } catch (Throwable t) {
+    } catch (Exception t) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactionTask.java:114]: This seems to be wrapping the exception with a RTE. Are there even checked exceptions that can occur here? If so, we probably should enumerate them explicitly, and only wrap checked exceptions, leaving RTEs unwrapped.

**Review by ctubbsii — COMMENTED** [review]
In general, I'm in favor of these changes. However, I'm concerned:

1. the change in the behavior to stop halting in the tserver,
2. we should try to be more specific and explicitly enumerate the checked exceptions when checked exceptions are caught (using multi-catch),
3. we shouldn't re-wrap RTEs with a new RTE when we `catch (Exception e)` and re-throw as `new RuntimeException(e)` or similar, and
4. in the case of Error/Throwable that are re-thrown, I noticed that some of them attempt to do additional work before re-throwing (like `addResult(e)`). In those cases, the additional work being performed risks swallowing the error being handled, especially if an RTE occurs while performing that other work.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java (hunk 1 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java:185]: I was following what the other catch clauses were doing here. I assume that the addResult() call is putting the exception on the result queue to be sent back to the client. It's possible that this error could make it's way back to the client before the tserver is halted.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java (hunk 2 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java:91]: I can do that.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java (hunk 3 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java:98]: > The message here has changed and no longer has the scan session client included.
I'm not sure what yo umean, this is an copy of the log message in the catch clause above it.

> Also, you should use slf4j substitution syntax to format the message.
I can do that

> Is this change dependent on the one in #1818 to handle the shutdown?
Yes, I mentioned that in the initial comment on the PR. These changes assume that #1818 gets merged.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java (hunk 1 above)
Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java:185]: If there's an actual Error, we probably shouldn't leak those details to the client. The client will get a TApplicationException when the server fails. It's probably not worth creating new work before the Error falls through and is ultimately handled. We probably also don't need the log message, either, because the code that will eventually handle the Error should provide a useful message/stack trace, and this would be redundant. It's probably better to just let it fall through and not even try to catch-handle-rethrow.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java (hunk 3 above)
Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java]: > I'm not sure what yo umean, this is an copy of the log message in the catch clause above it.

The previous message from the Halt had `" for " + scanSession.client`, but this log message does not mention the `scanSession.client` at all.

> Yes, I mentioned that in the initial comment on the PR. These changes assume that #1818 gets merged.

Thanks, I must've missed that.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java [hunk 5]
```diff
@@ -89,14 +89,15 @@ public void run() {
...
     } catch (TooManyFilesException | SampleNotPresentException e) {
       addResult(e);
-    } catch (OutOfMemoryError ome) {
-      Halt.halt("Ran out of memory scanning " + scanSession.extent + " for " + scanSession.client,
-          1);
-      addResult(ome);
-    } catch (Throwable e) {
-      log.warn("exception while scanning tablet "
-          + (scanSession == null ? "(unknown)" : scanSession.extent), e);
+    } catch (IOException | RuntimeException e) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java:92]: This is good because it preserves existing behavior with regard to RTEs, but I suspect that eventually, we'll want to reconsider whether we want RTEs to get sent back to the client, or if we would want them to fall through and trigger a TApplicationException (which is like an HTTP 500 error), so that we don't leak arbitrary exceptions back to the client.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java (hunk 1 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java:185]: I can remove this Error handling, I was just trying to follow the pattern.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java (hunk 3 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java]: As the log message you are referencing is in an Error handler, I should remove it as well given your comments in LookupTask?

Comment (ctubbsii) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/scan/NextBatchTask.java]: probably :smiley_cat:

**Review by ctubbsii — APPROVED** [review]
