### PR TITLE
Optimize GC getReferences iteration

### LINKED ISSUE #3499: The Reference Stream is taking a long time to iterate through
**Describe the bug**
The Reference Stream created in GCRun.getReferences() appears to be taking longer to iterate through than the Reference iterator that was implemented in 1.10.

Our GC cycles are taking at least 3x longer on accumulo 2.1.1 than they did in 1.10. We performed a jstack on the gc cycle and virtually all the time was spent iterating through the stream.

Note: The GC cycles are taking 3x when candidate batching does not occur. When candidate batching occurs GC cycle times increase by X more times (where X is the number of batches) (For example: when we perform 4 batches, the GC cycles were about 12x longer than they were in 1.10)
**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.1

**To Reproduce**
Run a Jstack on a GC cycle on a cluster

**Expected behavior**
The GC cycle times would not signifcantly increase between versions

### PR DESCRIPTION
**Pull request by dtspence**
* Creates TabletFile path with URI, which avoids a regex validation.
* Updates validateFileName to check explicit characters.
* Unit test for ValidationUtil.

Fixes #3499

-- 

The following are pre/post benchmarks for updates:

```
Accumulo 2.1.2-SNAPSHOT (current):
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score     Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    1.665 ±   0.211  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.017 ±   0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3   10.139 ±  16.299  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.010 ±   0.016  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   62.035 ±  24.129  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.006 ±   0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  521.994 ± 228.079  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.005 ±   0.002  ms/op


Accumulo 2.1.2-SNAPSHOT (PR changes):
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    1.374 ±  0.160  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.014 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    6.562 ±  2.008  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.007 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   38.382 ± 10.472  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.004 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  233.692 ± 14.204  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±  0.001  ms/op
```

### CODE REVIEW

File: core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    validateFileName(value);
+  }
+
+  @ParameterizedTest
+  @ValueSource(strings = {"hdfs://nn:8020/accumulo/tables/2/default_tablet/F0001acd.rf",
+      "./F0001acd.rf", "/F0001acd.rf"})
+  public void testValidateFileNameException(String value) {
+    Exception ex = assertThrows(IllegalArgumentException.class, () -> validateFileName(value));
+    assertEquals("Provided filename (" + value + ") contains invalid characters.", ex.getMessage());
+  }
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java:42]: Parameterized tests are overkill here. It's more readable, and less overhead (less test code to maintain, and update across JUnit versions), if you just did:

```java
Set.of(item1, item2, item3).forEach(value -> {
  assertEquals(...);
});
```

File: core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java [hunk 2]
```diff
@@ -62,9 +62,12 @@ public static void validateRFileName(String fileName) {
...
     Objects.requireNonNull(fileName);
-    if (!fileName.matches("[\\dA-Za-z._-]+")) {
-      throw new IllegalArgumentException(
-          "Provided filename (" + fileName + ") contains invalid characters.");
+    for (int i = 0; i < fileName.length(); i++) {
+      final char ch = fileName.charAt(i);
+      if (!(Character.isLetterOrDigit(ch) || ch == '-' || ch == '.' || ch == '_')) {
+        throw new IllegalArgumentException(
+            "Provided filename (" + fileName + ") contains invalid characters.");
+      }
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java:70]: This would separate out the predicate, and I think makes it a bit more readable instead of constantly calling "charAt" and worrying about off-by-one errors on the loop variable.

```suggestion
    IntPredicate validFileChar = ch -> Character.isLetterOrDigit(ch) || ch == '-' || ch == '.' || ch == '_';
    if (!fileName.codePoints().allMatch(validFileChar)) {
      throw new IllegalArgumentException(
          "Provided filename (" + fileName + ") contains invalid characters.");
    }
```

File: core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.apache.accumulo.core.util;
+
+import static org.apache.accumulo.core.metadata.ValidationUtil.validateFileName;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertThrows;
+
+import org.junit.Test;
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java:25]: This is a JUnit4 import statement. It should be JUnit5

```suggestion
import org.junit.jupiter.api.Test;
```

Comment (ctubbsii) [reply core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java]: I went ahead and pushed the fix for this one, so the rest of the build test would run.

File: core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java [hunk 4]
```diff
@@ -22,7 +22,7 @@
 import static org.junit.Assert.assertEquals;
 import static org.junit.Assert.assertThrows;
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java]:
```suggestion
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
```

Comment (ctubbsii) [reply core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java]: Fixed these too.

**Comment by ctubbsii** [comment]
@dtspence I fixed the trivial JUnit5 imports so we could get the build checks going, but I'll leave my substantive suggestions there for your consideration/further discussion.

**Comment by dtspence** [comment]
> @dtspence I fixed the trivial JUnit5 imports so we could get the build checks going, but I'll leave my substantive suggestions there for your consideration/further discussion.

Thank you for updating the JUnit5 imports.

File: core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java (hunk 1 above)
Comment (dtspence) [reply core/src/test/java/org/apache/accumulo/core/util/ValidationUtilTest.java:42]: I will update to remove the parameterized tests.

File: core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java (hunk 2 above)
Comment (dtspence) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java:70]: I initially tested a similar version to the suggested code (and re-verified with the suggested code). In the benchmark tests I used a for-loop version ran in roughly half the time and selected based on performance. I can update to use the more readable version and/or analyze further if needed.

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java:70]: I would be interested in the benchmark numbers with the final implementation.

Comment (dtspence) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java:70]: The following benchmark used the final implementation:
```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    1.385 ±  0.070  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.014 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    6.865 ±  3.233  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.007 ±  0.003  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   40.292 ± 14.152  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.004 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  245.171 ± 46.164  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±  0.001  ms/op
```

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java:70]: How do I run the benchmark myself?

Comment (dtspence) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java]: The link to the benchmark is below. The `gc-test-update` branch has not been merged yet, it has updates from #3499. It should be possible to run with `mvn verify`:
https://github.com/dtspence/accumulo-jmh-test/tree/gc-test-update

Comment (dlmarion) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java]: So, for 1000 iterations we went from 233ms to 245ms with this change, but we down from 521ms using the HEAD of 2.1 branch, am I reading that right?

Comment (dtspence) [reply core/src/main/java/org/apache/accumulo/core/metadata/ValidationUtil.java]: I unsure what the `validateFileName` change is doing to the overall GC references benchmark. The last number has variance and looking at it further now. The average time observed across multiple benchmark executions based on A/B for `validateFileName`, seemed to show some difference (i.e. 233ms vs 245ms). The HEAD difference from 521ms to 233ms/245ms is accurate and had a larger impact from the `URI` and `validateFileName` regex removal. In context of the `validateFileName` I had used a separate benchmark for the method itself.

Just as minor note the `splitRfile` parameter is saying (for the larger number) 1K splits w/100 r-files per split. I am investigating the iterations question further.

**Review by ctubbsii — APPROVED** [review]

**Comment by ctubbsii** [comment]
For what it's worth, I got substantially wider error bars a few times when I ran the gc-test-update branch (at commit b27d9fa56b68e7ab58a9e6c4d9b894ae35724c80) locally. Each run took about 10 minutes (using `mvn clean verify -Dit.test=GarbageCollectorPerformanceIT -Dversion.accumulo=2.1.2-SNAPSHOT`), and all were very spammy with regard to hadoop log messages about decompressors.

Click each to expand/collapse details.

<details>
<summary>Current 2.1.2-SNAPSHOT at 544ef01681e1b1080fa6afbb17a24721e20b638b:</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.892 ±  0.181  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.009 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    6.250 ±  2.679  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.006 ±  0.003  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   39.701 ±  2.739  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.004 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  314.899 ± 34.392  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.003 ±  0.001  ms/op
```

</details>

<details>
<summary>Current PR merged onto 2.1.2-SNAPSHOT at 544ef01681e1b1080fa6afbb17a24721e20b638b:</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score     Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.812 ±   0.150  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.008 ±   0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.501 ±   2.058  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.005 ±   0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   28.047 ±  12.950  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  176.200 ± 289.206  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±   0.003  ms/op
```

</details>

<details>
<summary>Slight change to move the IntPredicate outside the method to a private static final variable at the top of the file:</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score     Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.710 ±   0.083  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.007 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.269 ±   1.178  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.004 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   25.945 ±   6.227  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  177.723 ± 427.999  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±   0.004  ms/op
```

</details>

<details>
<summary>Ran that same one again, because the error bars looked crazy to me (`±428` is crazy for a value of 178... there must've been some kind of outlier due to some other activity on the box):</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.706 ±  0.186  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.007 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.315 ±  1.793  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.004 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   26.623 ± 12.256  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  168.236 ± 47.627  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±  0.001  ms/op
```

</details>

<details>
<summary>Second slight change to use for loop with indexed pointer, keeping the predicate and calling `predicate.test(ch)`:</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.713 ±  0.089  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.007 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.440 ±  1.746  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.004 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   27.450 ± 13.024  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  165.311 ± 68.361  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±  0.001  ms/op
```

</details>

<details>
<summary>Third slight change to use for loop with indexed pointer, and getting rid of the predicate in favor of inlining the checks into the `if` statement's condition:</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.714 ±  0.019  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.007 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.318 ±  0.779  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.004 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   27.488 ±  9.656  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  166.778 ± 60.033  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±  0.001  ms/op
```

</details>

<details>
<summary>Fourth slight change to cover case where the string is empty (this case was initially omitted from this PR, even though the regex checked for it):</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score     Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.788 ±   0.658  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.008 ±   0.007  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.453 ±   2.814  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.004 ±   0.003  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   27.361 ±  12.971  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  168.248 ± 105.847  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.002 ±   0.001  ms/op
```

</details>

<details>
<summary>Instead of doing the change in this PR, merely using a precompiled Pattern rather than calling `String.matches` results in:</summary>

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score    Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.875 ±  0.162  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.009 ±  0.002  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    6.026 ±  0.598  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.006 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   38.700 ±  7.029  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.004 ±  0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  292.542 ± 44.951  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.003 ±  0.001  ms/op
```

</details>

So, these lower numbers look promising, but the outliers that widen the error bars make me skeptical of how consistent these are, as they seem to show some sensitivity to the environment, even though I wasn't actively using my machine for much else while they ran.

My conclusions:

1. the for loop does not matter over the codePoints IntStream, so the current IntStream is fine
2. the predicate object does not matter over inlining the `if` condition into the method, so the current use of the predicate is fine
3. moving the predicate out of the method doesn't hurt or help, but is better code structure
4. adding coverage for the empty string case is needed
5. the regex pattern is worse, even if pre-compiled, which only helped a little, and is not worth doing

I can add a commit to this PR for 3 and 4, then merge this, because I think it will be done after that.

**Review by ctubbsii — APPROVED** [review]
With these changes, and the changes I already included in #3554 , I now am seeing:

```
Benchmark                                                   (splitsRfile)  Mode  Cnt    Score     Error  Units
GarbageCollectorPerformanceIT.benchmarkReferences                   1,100  avgt    3    0.717 ±   0.091  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op          1,100  avgt    3    0.007 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                  10,100  avgt    3    4.469 ±   1.262  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op         10,100  avgt    3    0.004 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                 100,100  avgt    3   28.373 ±  12.132  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op        100,100  avgt    3    0.003 ±   0.001  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences                1000,100  avgt    3  139.866 ± 203.803  ms/op
GarbageCollectorPerformanceIT.benchmarkReferences:rfile/op       1000,100  avgt    3    0.001 ±   0.002  ms/op
```

**Comment by ctubbsii** [comment]
I moved the new unit test to the correct package and pushed it to 2.1 in 2ec2321df8da0c90d2836561a2d16895e9bad0b5 so it can provide test coverage, regardless of what we want to do here.

I updated the title of this PR since it's no longer about removing regexes, which perform similarly to the alternatives previously proposed in this PR according to the benchmarks, once the Pattern is compiled once, instead of each time it is evaluated. Of course, you can still update this PR to remove the regex now and replace it with one of the alternatives, but I don't think it's necessary anymore, and I dropped it when I resolved this PR's merge conflicts with the 2.1 branch after #3554 was merged.

Based on the benchmarking, the main optimization that was included here was the use of the URI-based constructor for Path. So now, after resolving merge conflicts, that's the only thing left in this PR. I would have already merged that in, as well, but I am not sure about the TabletFile changes in 3.0, and this doesn't merge forward cleanly, since the TabletFile code changed. I'm not sure where this equivalent code moved to, if it even still applies to the main brnch. I don't want to merge it in to 2.1 until there's a plan for merging it forward into the main branch, even if that plan is to just make the change in 2.1, and do benchmarking and further changes separately for the main branch.

**Comment by dlmarion** [comment]
@ctubbsii - For 3.0, I believe it's AbstractTabletFile and any descendents that create a Path without calling URI.create. @cshannon  - any thoughts on what changes need to be made in the merge to 3.0 for this change?

**Comment by cshannon** [comment]
> @ctubbsii - For 3.0, I believe it's AbstractTabletFile and any descendents that create a Path without calling URI.create. @cshannon - any thoughts on what changes need to be made in the merge to 3.0 for this change?

I will take care of merging into main when this is in 2.1

**Comment by cshannon** [comment]
So this actually merged pretty easily as the creation of the Path is still in StoredTabletFile and wasn't moved to AbstractTabletFile.

The only thing I noticed when going through the different implementations to check for Path creation was that ScanServerRefTabletFile [creates](https://github.com/apache/accumulo/blob/5174be131aa3818c5fe7c7f310fd1130ffef08dc/core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java#L35) a Path as well so I am wondering if this change should be made there too.

**Comment by cshannon** [comment]
I should add the harder place to merge is in the no chop merge stuff since that redoes metadata to be Json but I will also handle that of course.

**Comment by dlmarion** [comment]
> The only thing I noticed when going through the different implementations to check for Path creation was that ScanServerRefTabletFile [creates](https://github.com/apache/accumulo/blob/5174be131aa3818c5fe7c7f310fd1130ffef08dc/core/src/main/java/org/apache/accumulo/core/metadata/ScanServerRefTabletFile.java#L35) a Path as well so I am wondering if this change should be made there too.

Can you create a ticket for this in 2.1.2?
