### PR TITLE
Fix #1373 Support the init scope in some VolumeChoosers

### LINKED ISSUE #1373: Could the preferred volume chooser support the init scope?
While [experimenting with S3](https://accumulo.apache.org/blog/2019/09/10/accumulo-S3-notes.html) I tried to use the INIT scope with the Preferred volume choose and it did not work because of [PreferredVolumeChooser.java line 60](https://github.com/apache/accumulo/blob/f5314b7e2a49cd315a16a72fe93c6828f4c7ba98/server/base/src/main/java/org/apache/accumulo/server/fs/PreferredVolumeChooser.java#L60).   If I had been able to use the init scope, then that would have made the S3 instructions much simpler.  Would it be possible to make the init scope work with site configuration?

### PR DESCRIPTION
**Pull request by karthick-rn**
When multiple volumes are used, the accumulo init step can randomly create the system tables in any of the volumes. This change introduces the init property in the volume chooser & let the user configure in which volume the system tables like metadata & root tables are to be created. 
For ex: `general.custom.volume.preferred.init=hdfs://<namenode>/accumulo` creates the system tables in HDFS during accumulo init. 
Additionally it was observed, after the init step, starting accumulo creates metadata and root tables on the default volume with rfiles. Trying to fix this with `config -t accumulo.metadata -s table.custom.volume.preferred=hdfs://<namenode>/accumulo` and `compact -w` did not help. May be something to discuss separately.

### CODE REVIEW

File: server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import org.apache.accumulo.core.conf.AccumuloConfiguration;
+import org.apache.accumulo.core.data.TableId;
+import org.apache.accumulo.core.spi.common.ServiceEnvironment;
+import org.apache.accumulo.server.ServiceEnvironmentImpl;
+import org.apache.hadoop.conf.Configuration;
+import org.apache.hadoop.fs.FileSystem;
+import org.apache.hadoop.fs.Path;
+import org.apache.hadoop.io.Text;
+
+public class InitVolumeChooserEnvironmentImpl implements VolumeChooserEnvironment {
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java]: Three alternatives/variations to consider (if you haven't already) instead of having this class as-is:

1. Could make this extend VolumeChooserEnvironmentImpl, and only override those methods that are necessary,
2. Could make this an anonymous inner class inside Initialize, and
3. Could move this class to the init package, since it's an init-specific class.

Some of these variations could be combined.

In any case, I think some of this comes down to personal-preference/style. It's fine as-is (other comments aside).

File: server/base/src/main/java/org/apache/accumulo/server/fs/PerTableVolumeChooser.java [hunk 2]
```diff
@@ -68,11 +68,6 @@ public String choose(VolumeChooserEnvironment env, String[] options)
   // visible (not private) for testing
   VolumeChooser getDelegateChooser(VolumeChooserEnvironment env) {
     switch (env.getScope()) {
-      case INIT:
-        // TODO should be possible to read from SiteConfiguration during init
-        log.warn("Not possible to determine delegate chooser at '{}' scope. Using {}.",
-            ChooserScope.INIT, RandomVolumeChooser.class.getName());
-        return randomChooser;
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/fs/PerTableVolumeChooser.java]: At this point, the switch statement (here and in the other class) could be turned into a simple conditional:

```java
if (env.getScope() == ChooserScope.TABLE) {
    return getVolumeChooserForTable(env);
}
return getVolumeChooserForScope(env);
```

This probably comes down to style also... both work fine, but the conditional is slightly shorter and probably easier to read, since the choice is binary.

File: server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java (hunk 1 above)
Comment (billierinaldi) [reply server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java]: Thanks for the review, @ctubbsii! I am helping Karthick figure out the changes needed for this issue and your suggestions make sense. Regarding "only override those methods that are necessary," do you mean that we wouldn't need to include the methods that throw UnsupportedOperationException? I was thinking these would be helpful to make it clear which fields have not been initialized for the INIT scope.

File: server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+
+  private final AccumuloConfiguration conf;
+  private final VolumeManager volumeManager;
+
+  public InitVolumeChooserEnvironmentImpl(AccumuloConfiguration acfg) {
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java]: Could pass a KeyExtent here, which would provide the information needed to implement `getEndRow()`, `getTableId()`, and  `hasTableId()`.  These are know by the initialization code.

File: server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java [hunk 4]
```diff
@@ -362,7 +361,7 @@ private boolean initialize(SiteConfiguration siteConfig, Configuration hadoopCon
     UUID uuid = UUID.randomUUID();
     // the actual disk locations of the root table and tablets
     String[] configuredVolumes = VolumeConfiguration.getVolumeUris(siteConfig, hadoopConf);
-    VolumeChooserEnvironment chooserEnv = new VolumeChooserEnvironmentImpl(ChooserScope.INIT, null);
+    VolumeChooserEnvironment chooserEnv = new InitVolumeChooserEnvironmentImpl(siteConfig);
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: If passing a keyextent could do the following here.

```suggestion
    VolumeChooserEnvironment chooserEnv = new InitVolumeChooserEnvironmentImpl(siteConfig, RootTable.EXTENT);
```

File: server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java [hunk 5]
```diff
@@ -504,7 +503,7 @@ private void initFileSystem(SiteConfiguration siteConfig, Configuration hadoopCo
     // initialize initial system tables config in zookeeper
     initSystemTablesConfig(zoo, Constants.ZROOT + "/" + uuid, hadoopConf);
 
-    VolumeChooserEnvironment chooserEnv = new VolumeChooserEnvironmentImpl(ChooserScope.INIT, null);
+    VolumeChooserEnvironment chooserEnv = new InitVolumeChooserEnvironmentImpl(siteConfig);
```
Comment (keith-turner) [inline server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: If passing keyextents here, would need to create three keyextents and pass those to three separate InitVolumeChooserEnvironmentImpl.  The key extents would be something like the following.

```java
// move creation of splitPoint here.
var tableMetadataExtent = new KeyExtent(MetadataTable.ID, splitPoint, null);
var defaultMetadataExtent = new KeyExtent(MetadataTable.ID, null, splitPoint);
var replicationExtent = new KeyExtent(ReplicationTable.ID, null, null);
```

If doing this, I think it would make sense to refactor the internal Tablet object to take a KeyExtent.

File: server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java (hunk 1 above)
Comment (keith-turner) [reply server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java]: I made some suggestions about passing a KeyExtent to InitVolChooserEnvImpl.  If that works out, I don't think there would be any methods throwing UnsupportedOperationException

Comment (billierinaldi) [reply server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java]: I think I see what you mean now. The VolumeChooserEnvironmentImpl methods are already checking for the TABLE scope and returning IllegalStateException otherwise, so they would handle the INIT scope appropriately.

File: server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java (hunk 4 above)
Comment (billierinaldi) [reply server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: Thanks for the review, @keith-turner! If we end up implementing an InitServerContext as per Christopher's suggestion, then I think we won't need to introduce an InitVolumeChooserEnvironmentImpl. In that case, do you think we should improve the VolumeChooserEnvironmentImpl to have a table ID and endRow for the INIT scope?

Comment (keith-turner) [reply server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: I am not sure, because I have not looked into the details enough. Would the user have to ensure they provide a chooser to init that does not call these methods?

Comment (keith-turner) [reply server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: I looked into this some more and I see that those three methods are currently related to the table scope.  Seems like the init scope may only be used for tables.  If so maybe its ok to make the info available w/ an update to the javadocs to clarify the init scope is more like init_table.  Could also update the javadocs for the three methods in VolumeChooserEnvironment that return tablet info to say they can only be called for TABLE or INIT scope.  This could be follow on work, it seems like the information could be useful to some chooser impls.

Comment (ctubbsii) [reply server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: The INIT scope is for all initial tables during the INIT phase... since those tables can't be individually configured in ZK yet and our config isn't expressive enough to distinguish between the different tables whose initial files are created during INIT. So, I never thought a chooser would be able to (or care to) make different choices for different tables during INIT. However, I wasn't thinking about the possibility of having a chooser make hard-coded decisions, or use some external configuration system (Java system props or ENV variables). So, I agree that adding table information to the VolumeChooserEnvironment may be useful as follow-on work to support some chooser implementations.

File: server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java (hunk 1 above)
Comment (ctubbsii) [reply server/base/src/main/java/org/apache/accumulo/server/fs/InitVolumeChooserEnvironmentImpl.java]: > The VolumeChooserEnvironmentImpl methods are already checking for the TABLE scope and returning IllegalStateException otherwise, so they would handle the INIT scope appropriately.

That's what I was thinking, but Keith makes a good point about the possibility of providing table information, even during the INIT scope, in case a chooser wanted to use that information (though it wouldn't be able to use it to access per-table configuration in ZK).

Initially, I was thinking that I probably would have just make this an anonymous inner-class inside `Initialize`, only overriding those methods which would require a `ServerContext` (since we don't have one yet). Those methods are currently only `getServiceEnv()` and `getFileSystem(String)`. So, an anon-inner-class that extended `VolumeChooserEnvironmentImpl` would be very short. But, a concrete class is fine, too.

**Comment by karthick-rn** [comment]
> Thanks for the PR! The changes look really good. I only have very minor comments/suggestions. The test changes are also really nice.

Thanks for reviewing the PR @ctubbsii @keith-turner. Based on the comments, I worked with @billierinaldi & committed the new changes to the PR. Let us know for any further comments/questions?

File: server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java [hunk 6]
```diff
@@ -44,6 +44,11 @@ public ServiceEnvironmentImpl(ServerContext ctx) {
     this.conf = new ConfigurationImpl(srvCtx.getConfiguration());
   }
 
+  public ServiceEnvironmentImpl(ServerContext ctx, AccumuloConfiguration acfg) {
+    this.srvCtx = ctx;
+    this.conf = new ConfigurationImpl(acfg);
+  }
+
```
[the remark this answers is not in the document]
Comment (billierinaldi) [reply server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java]: Thanks for the new patch, @karthick-rn! I believe these lines can be removed from ServiceEnvironmentImpl since they are no longer used.

File: server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java [hunk 7]
```diff
@@ -497,24 +498,32 @@ private static void initDirs(VolumeManager fs, UUID uuid, String[] baseDirs, boo
...
 
     // initialize initial system tables config in zookeeper
     initSystemTablesConfig(zoo, Constants.ZROOT + "/" + uuid, hadoopConf);
 
-    VolumeChooserEnvironment chooserEnv = new VolumeChooserEnvironmentImpl(ChooserScope.INIT, null);
+    Text splitPoint = TabletsSection.getRange().getEndKey().getRow();
+
+    VolumeChooserEnvironment chooserEnv = new VolumeChooserEnvironmentImpl(
+        VolumeChooserEnvironment.ChooserScope.INIT, MetadataTable.ID, splitPoint,
+        new ServerContext(siteConfig, instanceName, uuid.toString()));
```
Comment (ctubbsii) [inline server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: The ServerContext object could be re-used.

File: server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (karthick-rn) [reply server/base/src/main/java/org/apache/accumulo/server/ServiceEnvironmentImpl.java]: done. Thanks @billierinaldi

File: server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java (hunk 7 above)
Comment (karthick-rn) [reply server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java]: done

**Comment by karthick-rn** [comment]
> Looks really good! Awesome, @karthick-rn !

Thanks @ctubbsii

**Comment by ctubbsii** [comment]
I'm just kicking off the ITs with this change, in my Jenkins instance, to be sure there aren't any surprises in our testing suite, but then I can merge after that.

GitHub is indicating you are a first-time contributor to this repository. I thought you had contributed to Accumulo before (perhaps accumulo-testing?), but if not:

If you wish to be added as a contributor to https://accumulo.apache.org/people/ , please open a pull request to add yourself at https://github.com/apache/accumulo-website/edit/master/pages/people.md

If you haven't already, please consider subscribing to our developer mailing list (https://accumulo.apache.org/contact-us/) and introducing yourself. :smiley_cat:

**Comment by karthick-rn** [comment]
> I'm just kicking off the ITs with this change, in my Jenkins instance, to be sure there aren't any surprises in our testing suite, but then I can merge after that.
> 
> GitHub is indicating you are a first-time contributor to this repository. I thought you had contributed to Accumulo before (perhaps accumulo-testing?), but if not:
> 
> If you wish to be added as a contributor to https://accumulo.apache.org/people/ , please open a pull request to add yourself at https://github.com/apache/accumulo-website/edit/master/pages/people.md
> 
> If you haven't already, please consider subscribing to our developer mailing list (https://accumulo.apache.org/contact-us/) and introducing yourself. 😺

Thanks for the update.
GitHub is right there!, this is my first contribution to Accumulo. In the past I had contributed to fluo-muchos & accumulo-website.

**Comment by ctubbsii** [comment]
I ran the ITs, and it looks like VolumeChooserIT has some tests failing with these changes. It's probably some no-longer-valid assumptions some of the old tests were making during the Initialize phase.

You should be able to reproduce the failures with:
`mvn clean verify -Dtest=blah -Dit.test=VolumeChooserIT -Dcheckstyle.skip -Dspotbugs.skip`

 @karthick-rn Are you able to take a look at those tests and include a fix with this PR?

**Comment by karthick-rn** [comment]
> I ran the ITs, and it looks like VolumeChooserIT has some tests failing with these changes. It's probably some no-longer-valid assumptions some of the old tests were making during the Initialize phase.
> 
> You should be able to reproduce the failures with:
> `mvn clean verify -Dtest=blah -Dit.test=VolumeChooserIT -Dcheckstyle.skip -Dspotbugs.skip`
> 
> @karthick-rn Are you able to take a look at those tests and include a fix with this PR?

Sure! @ctubbsii

**Comment by karthick-rn** [comment]
> > I ran the ITs, and it looks like VolumeChooserIT has some tests failing with these changes. It's probably some no-longer-valid assumptions some of the old tests were making during the Initialize phase.
> > You should be able to reproduce the failures with:
> > `mvn clean verify -Dtest=blah -Dit.test=VolumeChooserIT -Dcheckstyle.skip -Dspotbugs.skip`
> > @karthick-rn Are you able to take a look at those tests and include a fix with this PR?
> 
> Sure! @ctubbsii

Hi @ctubbsii, Sorry for the delay in getting back on this. I worked with @billierinaldi to get through the failing tests and pushed the new changes to this PR. Thanks @billierinaldi for your help!
We also noticed the test phase of maven sometimes times out with the below error

`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.accumulo.test.VolumeChooserIT
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 300.273 s <<< FAILURE! - in org.apache.accumulo.test.VolumeChooserIT
[ERROR] waLogsSentToConfiguredVolumes(org.apache.accumulo.test.VolumeChooserIT)  Time elapsed: 60.014 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at app//org.apache.accumulo.test.VolumeChooserIT.waLogsSentToConfiguredVolumes(VolumeChooserIT.java:349)

[ERROR] twoTablesPreferredVolumeChooser(org.apache.accumulo.test.VolumeChooserIT)  Time elapsed: 60.006 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at app//org.apache.accumulo.test.VolumeChooserIT.configureNamespace(VolumeChooserIT.java:221)
	at app//org.apache.accumulo.test.VolumeChooserIT.twoTablesPreferredVolumeChooser(VolumeChooserIT.java:279)

[ERROR] twoTablesDiffChoosers(org.apache.accumulo.test.VolumeChooserIT)  Time elapsed: 60.005 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at app//org.apache.accumulo.test.VolumeChooserIT.createAndVerify(VolumeChooserIT.java:306)
	at app//org.apache.accumulo.test.VolumeChooserIT.twoTablesDiffChoosers(VolumeChooserIT.java:323)

[ERROR] includeSpecialVolumeForTable(org.apache.accumulo.test.VolumeChooserIT)  Time elapsed: 60.003 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at app//org.apache.accumulo.test.VolumeChooserIT.configureNamespace(VolumeChooserIT.java:221)
	at app//org.apache.accumulo.test.VolumeChooserIT.includeSpecialVolumeForTable(VolumeChooserIT.java:337)

[ERROR] twoTablesRandomVolumeChooser(org.apache.accumulo.test.VolumeChooserIT)  Time elapsed: 60.007 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at app//org.apache.accumulo.test.VolumeChooserIT.createAndVerify(VolumeChooserIT.java:306)
	at app//org.apache.accumulo.test.VolumeChooserIT.twoTablesRandomVolumeChooser(VolumeChooserIT.java:299)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   VolumeChooserIT.includeSpecialVolumeForTable:337->configureNamespace:221 » TestTimedOut
[ERROR]   VolumeChooserIT.twoTablesDiffChoosers:323->createAndVerify:306 » TestTimedOut ...
[ERROR]   VolumeChooserIT.twoTablesPreferredVolumeChooser:279->configureNamespace:221 » TestTimedOut
[ERROR]   VolumeChooserIT.twoTablesRandomVolumeChooser:299->createAndVerify:306 » TestTimedOut
[ERROR]   VolumeChooserIT.waLogsSentToConfiguredVolumes:349 » TestTimedOut test timed ou...
[INFO] 
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0`

**Comment by billierinaldi** [comment]
@ctubbsii After fixing the first error in VolumeChooserIT (which was that ClientContext was always reading the instance ID from ZooKeeper), we saw another error from PerTableVolumeChooser that was due to no volume chooser being configured for the init or default scope. Previously, the user could just configure a volume chooser for the logger scope, since that was the only scope where we were constructing a volume chooser. Since introducing volume choosers for the init scope would require the user to change their config, Karthick's latest patch falls back to a random chooser when the neither the desired nor the default scope are specified. This preserves the old behavior for the init scope, but changes the behavior for the logger scope (which previously threw an error instead of falling back to random).

**Comment by keith-turner** [comment]
> Karthick's latest patch falls back to a random chooser when the neither the desired nor the default scope are specified.

@billierinaldi the comments on #253 discuss reasons for avoiding falling back to the random chooser.  I am not sure if those reasons apply to these changes though, just wanted to make you aware of those.

**Comment by billierinaldi** [comment]
Thanks, @keith-turner. I did see that issue, which was why I wanted to explicitly discuss the desired behavior. My impression from reading over the comments was that it was decided that misconfiguration should definitely throw an error, but I was less clear on whether it is important that absent configuration should throw an error. I suppose there are three possibilities:

1. require a new configuration property when using the preferred and per table volume choosers (general.custom.volume.preferred.default or general.custom.volume.preferred.init must be specified)
2. fall back to the random chooser instead of throwing an exception when scope-specific and default properties are not specified (absent configuration no longer throws an error for the logger scope, implemented in the current patch)
3. handle absent configuration differently for the logger and init scopes, so that init falls back to random while logger throws an exception (preserving existing behavior for both scopes, while allowing new configurability for the init scope).

My order of preference is 2, 3, 1, but I am open to any of these and to other suggestions.

**Comment by ctubbsii** [comment]
Based on the intent of the previous issue, only option 1 seems acceptable to me, as it is the only one that properly protects against partial / improper configuration. Any fall-back to a random chooser can place data improperly on a system, that is very expensive to correct later. In general, I think it's a good idea to require explicit configuration from a user, rather than the system to try to infer user's intentions from incomplete or incorrect configuration.

The behavior I strongly prefer: the default config should work out of the box, without any special configuration (it does, as the default is the `RandomVolumeChooser`), but if the other choosers are used, they *must* be fully configured, with explicit configuration for any relevant scope they will be executed for. Here, I think this means that during system initialization, the corresponding init scope configuration property, or the default scope property, must be set.

**Comment by billierinaldi** [comment]
@ctubbsii Are there semver implications to changing how the PerTableVolumeChooser and PreferredVolumeChooser need to be configured?

**Comment by ctubbsii** [comment]
> @ctubbsii Are there semver implications to changing how the PerTableVolumeChooser and PreferredVolumeChooser need to be configured?

I don't think we consider our configuration to be "public API" in the same way that our Java API is "public API" for the purposes of semver. The "custom" props that we support for various implementation-specific classes of server-side plugin mechanisms even less so (they are more like API for that specific plugin, rather than "Accumulo" API), but it's all still user-facing, so we should be careful. What did you have in mind?

**Comment by karthick-rn** [comment]
The new commit implements option 1, the VolumeChooserIT passed for @billierinaldi however the same resulted in time out for me. It would be good if someone else could verify the IT passes as well. Thanks

**Comment by ctubbsii** [comment]
> The new commit implements option 1, the VolumeChooserIT passed for @billierinaldi however the same resulted in time out for me. It would be good if someone else could verify the IT passes as well. Thanks

I'll try to run them and report back here.

By the way, the timeouts we set on our ITs are often arbitrary... as a last-ditch effort to not let a stuck test run forever. For most of these ITs, the actual run time depends greatly on the hardware you're using, and are much more likely to time out on a VM or laptop than they are on a dedicated bare metal server used for CI. Most of the ITs can flex their timeout by passing `-Dtimeout.factor=2` (or 3, or whatever) to the `mvn` command used to build them, but some of them have hard-coded timeouts that can't be changed. If you're using reasonably good hardware and it still times out with the default timeout factor of `1`, then it might indicate a need to adjust the default timeout. But, I would recommend trying to increase the timeout factor first.

**Comment by karthick-rn** [comment]
> > The new commit implements option 1, the VolumeChooserIT passed for @billierinaldi however the same resulted in time out for me. It would be good if someone else could verify the IT passes as well. Thanks
> 
> I'll try to run them and report back here.
> 
> By the way, the timeouts we set on our ITs are often arbitrary... as a last-ditch effort to not let a stuck test run forever. For most of these ITs, the actual run time depends greatly on the hardware you're using, and are much more likely to time out on a VM or laptop than they are on a dedicated bare metal server used for CI. Most of the ITs can flex their timeout by passing `-Dtimeout.factor=2` (or 3, or whatever) to the `mvn` command used to build them, but some of them have hard-coded timeouts that can't be changed. If you're using reasonably good hardware and it still times out with the default timeout factor of `1`, then it might indicate a need to adjust the default timeout. But, I would recommend trying to increase the timeout factor first.

I have already tried increasing the timeout to `-Dtimeout.factor=3` that @billierinaldi provided upon noticing the timeout earlier, however in my case it doesn't seem to fix. I'm running the mvn on my mac, could be there is a subtle difference on the hardware that might be causing this.

**Comment by keith-turner** [comment]
@karthick-rn  I checked out your branch locally and ran VolumeChooserIT.  I did not hang for me.

**Comment by karthick-rn** [comment]
> @karthick-rn I checked out your branch locally and ran VolumeChooserIT a few times. I did not hang for me.

Thanks @keith-turner for checking this. As I'm the only one facing the timeout, it should be something down to my machine. Let me know if you have any further comments on the PR?

**Comment by ctubbsii** [comment]
My IT run aged out of my CI server over the December holiday season... I'll re-run to verify. I expect it to pass, but will confirm tomorrow and merge if there are no issues.

**Comment by karthick-rn** [comment]
The timeout issue that I was facing when running maven disappeared after increasing the maven heap (export MAVEN_OPTS="-Xmx4G"). Thanks @billierinaldi for the suggestion.

**Comment by keith-turner** [comment]
@ctubbsii are you finished reviewing this?  I can merge it if you are done.

**Comment by ctubbsii** [comment]
No. My CI server got stuck on some old builds, and the one I had queued to test this change never ran. I rebooted it. It should be done today, and I can get this merged before the weekend is over.

**Comment by ctubbsii** [comment]
All build tests passed, except for two flaky tests that are unrelated to this. Going to merge now.
