### PR TITLE
Fix #1430 Enforce table name limit for new tables

### LINKED ISSUE #1430: Limit the size of new table names
Giant table names can take down ZooKeeper and the master server. There should be a reasonable limit on table name sizes. This can be imposed on the server side for creating tables, renaming tables, and cloning tables. Existing tables need not be affected.

Client code can be updated for fast-failure (and to limit the number of invalid requests sent to the server-side).

For reference, the information I found while searching the web (not necessarily accurate, but good enough to give us an idea) gives the following limits to identifier sizes:

| Item | Number of characters (or sometimes, bytes) |
| ---- | ---- |
| Oracle DB table names | 30 |
| MySQL table names | 64 |
| PostgreSQL table names | 63 |
| DNS identifier | 63 |
| Most filesystem file names (EXT/XFS/ZFS/exFAT/HFS+/Brtfs/NTFS | 255 |
| EXT4 max path | 4096 |
| Java identifiers | unlimited |
| longest English word | 45 |
| "supercalifragilisticexpialidocious" | 34 |

My original opinion was 63, because this is what DNS uses, and because it is similar to what common relational databases use which, like us, have a very DNS-like naming convention of dot-separated components, as in `namespace.tablename` or `database.tablename`

However, I think that's probably going to be too limiting, so I think 255 is a more reasonable limit.

The server-side code for validating table names is located in the `FateServiceHandler` class, in a method called `validateTableNameArgument`. However, that method is currently being used for existing tables, in order to validate the parameters sent over the wire to the server. A similar method would have to be created to specifically validate *new* destination table names from creating, renaming, or cloning a table. That way, we don't impose the name limit on existing tables, only on new ones. For existing tables, it may be worth adding a warning log message to the current validator method that the table name is longer than what Accumulo now supports, and it may cause unexpected behavior if not renamed to something shorter.

(Originally reported at [ACCUMULO-2366](https://issues.apache.org/jira/browse/ACCUMULO-2366))

### PR DESCRIPTION
**Pull request by cradal**
- Created new validator method for CREATE_TABLE w/ Exception
- Added log warning re: name length to CLONE and RENAME
- Created test under TableOperationsIT (createTableWithTableNameLengthLimit)
- Implemented client fast-failure under TableOperationsImpl via new checkArg statement

### CODE REVIEW

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 1]
```diff
@@ -162,10 +162,11 @@ public void executeFateOperation(TInfo tinfo, TCredentials c, long opid, FateOpe
               TableOperationExceptionType.OTHER,
               "Expected at least " + SPLIT_OFFSET + " arguments, saw :" + arguments.size());
         }
-        String tableName = validateTableNameArgument(arguments.get(0), tableOp, NOT_SYSTEM);
+        String tableName = validateNewTableNameArgument(arguments.get(0), tableOp, NOT_SYSTEM);
         TimeType timeType = TimeType.valueOf(ByteBufferUtil.toString(arguments.get(1)));
         InitialTableState initialTableState =
             InitialTableState.valueOf(ByteBufferUtil.toString(arguments.get(2)));
+        log.info("Init Table State: " + ByteBufferUtil.toString(arguments.get(2)));
```
Comment (keith-turner) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: Was this added for debugging?

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 2]
```diff
@@ -189,6 +189,18 @@ public void createTable() throws TableExistsException, AccumuloException,
...
 
+  @Test
+  public void createTableWithTableNameLengthLimit()
+      throws AccumuloException, AccumuloSecurityException, TableExistsException {
+    StringBuilder tableNameBuilder = new StringBuilder();
+    for (int i = 0; i < 1026; i++) {
+      tableNameBuilder.append('a');
+    }
+    String tableName = tableNameBuilder.toString();
+    accumuloClient.tableOperations().create(tableName);
```
[the remark this answers is not in the document]
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: @keith-turner That method throws the following: TableExistsException, AccumuloException,
      AccumuloSecurityException, TableNotFoundException

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java (hunk 1 above)
Comment (cradal) [reply server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: @keith-turner Yes, it was. I need to take that out.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 3]
```diff
@@ -189,6 +189,18 @@ public void createTable() throws TableExistsException, AccumuloException,
     accumuloClient.tableOperations().delete(tableName);
   }
 
+  @Test
+  public void createTableWithTableNameLengthLimit()
+      throws AccumuloException, AccumuloSecurityException, TableExistsException {
+    StringBuilder tableNameBuilder = new StringBuilder();
+    for (int i = 0; i < 1026; i++) {
```
[the remark this answers is not in the document]
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: @keith-turner I wasn't sure if we wanted a constant that was that long. I could just add it in as a 1025 char constant, since 1024 is the limit we are going for.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: When this test is run, will it throw an exception because the table name is too long?

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: @keith-turner Ignore my last comment. I was thinking about the actual test string.

[the remark this answers is not in the document]
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: One nice thing about using a single constant in the code is that it makes it easier for someone to later search for all code that references that const.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: @keith-turner Yes, it throws an IllegalArgumentExc when I run the TableOperationsIT. I'll rework it so it can test without throwing the exc.

[the remark this answers is not in the document]
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: You can make the test expect the exception and only pass when it is thrown.  JUnit offers two ways to do this.

[the remark this answers is not in the document]
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: @keith-turner I incorporated the expected = exception.class feature. TableOperationsIT passed.

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 4]
```diff
@@ -701,6 +702,24 @@ private TableId validateTableIdArgument(ByteBuffer tableIdArg, TableOperation op
   private String validateTableNameArgument(ByteBuffer tableNameArg, TableOperation op,
       Validator<String> userValidator) throws ThriftTableOperationException {
     String tableName = tableNameArg == null ? null : ByteBufferUtil.toString(tableNameArg);
+    if ((tableName != null) && (tableName.length() > MAX_TABLE_NAME_LEN)) {
+      log.warn(
+          "Table names greater than 1024 characters should be renamed to conform to a 1024 character limit. "
```
Comment (keith-turner) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: Could use constant in this message

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 5]
```diff
@@ -216,6 +217,7 @@ public void create(String tableName, NewTableConfiguration ntc)
       throws AccumuloException, AccumuloSecurityException, TableExistsException {
     checkArgument(tableName != null, "tableName is null");
     checkArgument(ntc != null, "ntc is null");
+    checkArgument(tableName.length() < MAX_TABLE_NAME_LEN + 1, "tableName is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]:
```suggestion
    checkArgument(tableName.length() <= MAX_TABLE_NAME_LEN, "tableName is longer than %s characters", MAX_TABLE_NAME_LEN);
```

**Comment by cradal** [comment]
@ctubbsii @keith-turner I'm not sure if you all get notifications of new commits, but I added the table name limits to the rest of the table operations. Also I did the same for namespaces, including fast-fails and unit test.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java [hunk 6]
```diff
@@ -119,7 +121,8 @@ public boolean exists(String namespace) {
   public void create(String namespace)
       throws AccumuloException, AccumuloSecurityException, NamespaceExistsException {
     checkArgument(namespace != null, "namespace is null");
-
+    checkArgument(namespace.length() <= MAX_NAMESPACE_LEN,
+        "Namespace is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java]:
```suggestion
        "Namespace is longer than "+MAX_NAMESPACE_LEN+" characters");
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java [hunk 7]
```diff
@@ -163,7 +166,11 @@ public void delete(String namespace) throws AccumuloException, AccumuloSecurityE
   public void rename(String oldNamespaceName, String newNamespaceName)
       throws AccumuloSecurityException, NamespaceNotFoundException, AccumuloException,
       NamespaceExistsException {
-
+    checkArgument(oldNamespaceName.length() <= MAX_NAMESPACE_LEN,
+        "Namespaces longer than 1024 characters"
+            + "are no longer supported and may result in unexpected behavior");
+    checkArgument(newNamespaceName.length() <= MAX_TABLE_NAME_LEN,
+        "Namespace is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java]:
```suggestion
        "Namespace is longer than "+MAX_NAMESPACE_LEN+" characters");
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 8]
```diff
@@ -217,7 +217,8 @@ public void create(String tableName, NewTableConfiguration ntc)
       throws AccumuloException, AccumuloSecurityException, TableExistsException {
     checkArgument(tableName != null, "tableName is null");
     checkArgument(ntc != null, "ntc is null");
-    checkArgument(tableName.length() < MAX_TABLE_NAME_LEN + 1, "tableName is longer than 1024 characters");
+    checkArgument(tableName.length() <= MAX_TABLE_NAME_LEN,
+        "Table name is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]:
```suggestion
        "Table name is longer than "+ MAX_TABLE_NAME_LEN +" characters");
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 9]
```diff
@@ -753,6 +754,8 @@ public void clone(String srcTableName, String newTableName, CloneConfiguration c
 
     checkArgument(srcTableName != null, "srcTableName is null");
     checkArgument(newTableName != null, "newTableName is null");
+    checkArgument(newTableName.length() <= MAX_TABLE_NAME_LEN,
+        "Table name is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]:
```suggestion
        "Table name is longer than "+ MAX_TABLE_NAME_LEN +" characters");
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 10]
```diff
@@ -788,7 +791,11 @@ public void clone(String srcTableName, String newTableName, CloneConfiguration c
   @Override
   public void rename(String oldTableName, String newTableName) throws AccumuloSecurityException,
       TableNotFoundException, AccumuloException, TableExistsException {
-
+    checkArgument(oldTableName.length() <= MAX_TABLE_NAME_LEN,
+        "Table names longer than 1024 characters"
+            + "are no longer supported and may result in unexpected behavior");
+    checkArgument(newTableName.length() <= MAX_TABLE_NAME_LEN,
+        "Table name is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]:
```suggestion
        "Table name is longer than "+ MAX_TABLE_NAME_LEN +" characters");
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 11]
```diff
@@ -1499,6 +1506,8 @@ public void importTable(String tableName, String importDir)
       throws TableExistsException, AccumuloException, AccumuloSecurityException {
     checkArgument(tableName != null, "tableName is null");
     checkArgument(importDir != null, "importDir is null");
+    checkArgument(tableName.length() <= MAX_TABLE_NAME_LEN,
+        "Table name is longer than 1024 characters");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]:
```suggestion
        "Table name is longer than "+ MAX_TABLE_NAME_LEN +" characters");
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java [hunk 12]
```diff
@@ -163,7 +166,11 @@ public void delete(String namespace) throws AccumuloException, AccumuloSecurityE
   public void rename(String oldNamespaceName, String newNamespaceName)
       throws AccumuloSecurityException, NamespaceNotFoundException, AccumuloException,
       NamespaceExistsException {
-
+    checkArgument(oldNamespaceName.length() <= MAX_NAMESPACE_LEN,
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java]: Why does the old namespace need to be less than the len?  If the old namespace was created in an older version of Accumulo then it could be over the limit.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 13]
```diff
@@ -788,7 +791,11 @@ public void clone(String srcTableName, String newTableName, CloneConfiguration c
   @Override
   public void rename(String oldTableName, String newTableName) throws AccumuloSecurityException,
       TableNotFoundException, AccumuloException, TableExistsException {
-
+    checkArgument(oldTableName.length() <= MAX_TABLE_NAME_LEN,
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: Why does the old table need to be below limit?

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 14]
```diff
@@ -434,7 +435,7 @@ public String invalidMessage(String argument) {
       case TABLE_BULK_IMPORT: {
         TableOperation tableOp = TableOperation.BULK_IMPORT;
         validateArgumentCount(arguments, tableOp, 4);
-        String tableName = validateTableNameArgument(arguments.get(0), tableOp, NOT_SYSTEM);
+        String tableName = validateNewTableNameArgument(arguments.get(0), tableOp, NOT_SYSTEM);
```
Comment (keith-turner) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: This operation is not creating a new table, so it should not do this check.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java (hunk 12 above)
Comment (cradal) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java]: @keith-turner Thanks for looking things over. I might be misunderstanding ctubbsii's feedback on this one. I thought the intention in the new version was to essentially force user's to rename namespaces to something that conforms to the 1024 char limit.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 13 above)
Comment (cradal) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @keith-turner Again, I might be misunderstanding ctubbsii's feedback on this one. I thought the intention in the new version was to essentially force user's to rename tables to something that conforms to the 1024 char limit.

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java (hunk 14 above)
Comment (cradal) [reply server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: @keith-turner Is the same case for TABLE_IMPORT? Again, in this case, I thought that ctubbsii wanted the limit check applied during imports, as well.

Comment (keith-turner) [reply server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: table import is creating a new table in the system.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 13 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: It seems like if the user had created a table name of len 1234 in ver 2.0.0 that with this check they would never be able to rename that table in version 2.1.0.

Comment (cradal) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @keith-turner Ok. I feel foolish now. You are correct. My goal was to generate a warning message to the user. In doing so, I am preventing the operation from even occuring! I will remove the old name check for renaming namespaces and tables. Also, I will generate the warning message without using checkArgument.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java (hunk 12 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/NamespaceOperationsImpl.java]: @cradal No. Sorry for the confusion. The intention was:

1. prevent the creation of new objects over the limit, and
2. log a warning when we discover any object over the limit (with the understanding that this would only be possible for objects created before the limit was imposed)

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java (hunk 14 above)
Comment (ctubbsii) [reply server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: @cradal Although similarly named "bulk import" (aka "import directory") is when a new RFile is added to an existing table, whereas "import table" creates a new table from a previously exported table.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 13 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: >  I will generate the warning message without using checkArgument

Are you thinking of a warning for the case where the old name is too long?  Personally I would skip that.

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: > Are you thinking of a warning for the case where the old name is too long? Personally I would skip that.

For rename, I agree. There's no point in warning when the user is currently performing an action that makes the problem go away.

Comment (cradal) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @keith-turner @ctubbsii Thanks for being patient with me, guys. I think I have addressed the current issues with my latest commits.

Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: No problem! I'll try to take a look soon.

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 15]
```diff
@@ -697,10 +699,28 @@ private TableId validateTableIdArgument(ByteBuffer tableIdArg, TableOperation op
...
   }
 
-  // Verify table name arguments are valid, and match any additional restrictions
+  // Verify older table name arguments are valid, and match any additional restrictions
   private String validateTableNameArgument(ByteBuffer tableNameArg, TableOperation op,
       Validator<String> userValidator) throws ThriftTableOperationException {
     String tableName = tableNameArg == null ? null : ByteBufferUtil.toString(tableNameArg);
+    if ((tableName != null) && (tableName.length() > MAX_TABLE_NAME_LEN)) {
+      log.warn("Table names greater than " + MAX_TABLE_NAME_LEN
+          + " characters should be renamed to conform to a 1024 character limit. "
```
Comment (lbschanno) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]:
```suggestion
          + " characters should be renamed to conform to a "+MAX_TABLE_NAME_LEN+" character limit. "
```

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 16]
```diff
@@ -716,6 +736,24 @@ private void validateArgumentCount(List<ByteBuffer> arguments, TableOperation op
   private String validateNamespaceArgument(ByteBuffer namespaceArg, TableOperation op,
       Validator<String> userValidator) throws ThriftTableOperationException {
     String namespace = namespaceArg == null ? null : ByteBufferUtil.toString(namespaceArg);
+    if ((namespace != null) && (namespace.length() > MAX_NAMESPACE_LEN)) {
+      log.warn("Namespaces greater than " + MAX_NAMESPACE_LEN
+          + " characters should be renamed to conform to a 1024 character limit. "
```
Comment (lbschanno) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]:
```suggestion
          + " characters should be renamed to conform to a "+MAX_NAMESPACE_LEN+" character limit. "
```

File: test/src/main/java/org/apache/accumulo/test/NamespacesIT.java [hunk 17]
```diff
@@ -191,6 +192,18 @@ public void createTableInMissingNamespace() throws Exception {
...
+  @Test(expected = IllegalArgumentException.class)
+  public void createNamespaceWithNamespaceLengthLimit()
+      throws AccumuloException, AccumuloSecurityException, NamespaceExistsException {
+    StringBuilder namespaceBuilder = new StringBuilder();
+    for (int i = 0; i <= MAX_NAMESPACE_LEN; i++) {
+      namespaceBuilder.append('a');
+    }
+    String namespace = namespaceBuilder.toString();
+    c.namespaceOperations().create(namespace);
+    assertTrue(!c.namespaceOperations().exists(namespace));
```
Comment (lbschanno) [inline test/src/main/java/org/apache/accumulo/test/NamespacesIT.java]:
```suggestion
    assertFalse(c.namespaceOperations().exists(namespace));
```

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 18]
```diff
@@ -189,6 +190,18 @@ public void createTable() throws TableExistsException, AccumuloException,
...
+  @Test(expected = IllegalArgumentException.class)
+  public void createTableWithTableNameLengthLimit()
+      throws AccumuloException, AccumuloSecurityException, TableExistsException {
+    StringBuilder tableNameBuilder = new StringBuilder();
+    for (int i = 0; i <= MAX_TABLE_NAME_LEN; i++) {
+      tableNameBuilder.append('a');
+    }
+    String tableName = tableNameBuilder.toString();
+    accumuloClient.tableOperations().create(tableName);
+    assertTrue(!accumuloClient.tableOperations().exists(tableName));
```
Comment (lbschanno) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]:
```suggestion
    assertFalse(accumuloClient.tableOperations().exists(tableName));
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 13 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @cradal did you see the suggestions I made to replace 1024 with constants in some error message strings?

Comment (cradal) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @keith-turner Yessir. I rolled them into my commits.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @cradal  when I look at the diffs on github I still see some error messages with 1024 in them.

Comment (cradal) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: @keith-turner Apologies. I thought we caught them all with the peer review and commits last week. I went through the relevant classes and did a string search for 1024. I think we finally got them all with my latest commit.

File: test/src/main/java/org/apache/accumulo/test/NamespacesIT.java (hunk 17 above)
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/NamespacesIT.java]: This code will never execute when the previous line throws an exception.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 18 above)
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: When the previous line throws an exception, this line will not execute.

File: test/src/main/java/org/apache/accumulo/test/NamespacesIT.java (hunk 17 above)
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/NamespacesIT.java]: The assertion line is not needed if we depend on the throw/not thrown status of the expected exception for testing. However, that does not really test for the existence of a table with an invalid name. So...I removed the expected notation and put the assertion in a try-catch block in the newest commit.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 18 above)
Comment (cradal) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: Please see NamespacesIT comment.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 19]
```diff
@@ -189,6 +190,22 @@ public void createTable() throws TableExistsException, AccumuloException,
...
+    for (int i = 0; i <= MAX_TABLE_NAME_LEN; i++) {
+      tableNameBuilder.append('a');
+    }
+    String tableName = tableNameBuilder.toString();
+    try {
+      accumuloClient.tableOperations().create(tableName);
+      fail("IllegalArgumentException was not thrown");
+    } catch (IllegalArgumentException exc) {
+      assertTrue(!accumuloClient.tableOperations().exists(tableName));
+    }
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: These can be simplified like:

```suggestion
    assertThrows(IllegalArgumentException.class, () -> accumuloClient.tableOperations().create(tableName));
    assertFalse(accumuloClient.tableOperations().exists(tableName));
```

The `Assert.assertThrows` also returns the exception, so you can do additional checks to check the exception's `getMessage()` and, if you wish, the `getCause()`.

You can also create the name using commons-lang3's `String tableName = StringUtils.repeat('a', MAX_TABLE_NAME_LEN);`

You can also verify the length of the string in an assert statement. Additional checks would include max length plus and minus one.

These comments also apply to the namespace checks.

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 20]
```diff
@@ -716,6 +738,25 @@ private void validateArgumentCount(List<ByteBuffer> arguments, TableOperation op
...
+    return _validateArgument(namespace, op, Namespaces.VALID_NAME.and(userValidator));
+  }
+
+  // Verify namespace arguments are valid, and match any additional restrictions
+  private String validateNewNamespaceArgument(ByteBuffer namespaceArg, TableOperation op,
+      Validator<String> userValidator) throws ThriftTableOperationException {
+    String namespace = namespaceArg == null ? null : ByteBufferUtil.toString(namespaceArg);
+    if ((namespace != null) && (namespace.length() > MAX_NAMESPACE_LEN)) {
+      throw new ThriftTableOperationException(null, namespace, op,
+          TableOperationExceptionType.OTHER,
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: There is an `INVALID_NAME` type you can use instead of `OTHER`. (Same for the NAMESPACE validation method).

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 21]
```diff
@@ -697,10 +700,29 @@ private TableId validateTableIdArgument(ByteBuffer tableIdArg, TableOperation op
...
+  // Verify older table name arguments are valid, and match any additional restrictions
   private String validateTableNameArgument(ByteBuffer tableNameArg, TableOperation op,
       Validator<String> userValidator) throws ThriftTableOperationException {
     String tableName = tableNameArg == null ? null : ByteBufferUtil.toString(tableNameArg);
+    if ((tableName != null) && (tableName.length() > MAX_TABLE_NAME_LEN)) {
+      log.warn("Table names greater than " + MAX_TABLE_NAME_LEN
+          + " characters should be renamed to conform to a " + MAX_TABLE_NAME_LEN
+          + " character limit. Longer table names are no longer supported and may result in "
+          + " unexpected behavior.");
+    }
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: As follow-on, it might be useful to create a cache of recent warnings, so tables which aren't immediately renamed, but are relatively active, don't spam the logs too much.

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 22]
```diff
@@ -206,7 +208,8 @@ public void executeFateOperation(TInfo tinfo, TCredentials c, long opid, FateOpe
         final String oldTableName =
             validateTableNameArgument(arguments.get(0), tableOp, NOT_SYSTEM);
         String newTableName =
-            validateTableNameArgument(arguments.get(1), tableOp, new Validator<>() {
+
+            validateNewTableNameArgument(arguments.get(1), tableOp, new Validator<String>() {
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]:
```suggestion
            validateNewTableNameArgument(arguments.get(1), tableOp, new Validator<>() {
```

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java [hunk 23]
```diff
@@ -697,10 +700,29 @@ private TableId validateTableIdArgument(ByteBuffer tableIdArg, TableOperation op
     }
   }
 
-  // Verify table name arguments are valid, and match any additional restrictions
+  // Verify older table name arguments are valid, and match any additional restrictions
```
Comment (ctubbsii) [inline server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]:
```suggestion
  // Verify existing table's name argument is valid, and match any additional restrictions
```

File: server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java (hunk 20 above)
Comment (ctubbsii) [reply server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java]: I added a commit to take care of this.

**Comment by ctubbsii** [comment]
Thanks @cradal ! I was able to go ahead and implement the minor suggestions I had made myself, resolved the merge conflict with master, and got this pushed to master.
