### PR TITLE
Use double‑checked locking to eliminate redundant metadata lookups

### LINKED ISSUE #5535: Broken or Flaky test: ClientTabletCacheImplTest.testMultithreadedLookups
**Test name(s)**
 - ClientTabletCacheImplTest.testMultithreadedLookups()

**Describe the failure observed**
I have seen this test case fail twice now in the github actions builds. I have not been able to reproduce this failure or seen it fail in other builds.

```
[ERROR] Failures: 
[ERROR]   ClientTabletCacheImplTest.testMultithreadedLookups:2027 [!0<;foo\\;m, !0;foo\\;m<, !0<;foo\\;m, !0;foo\\;m<] ==> expected: <true> but was: <false>
```

I am not sure what is causing this failure yet.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #5535

Swap out the Timer‑based check for a double‑checked‑locking pattern on the lock, and only short‑circuit when the cached tablet actually has a valid location.

Also made the failing IT case more concurrently strenuous to better exercise this new logic.

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java [hunk 1]
```diff
@@ -690,25 +690,28 @@ private void lookupTablet(ClientContext context, Text row, LockCheckerSession lc
...
-        // the lock is important as it ensures other threads that are waiting on the lock will see
-        // what this thread found and may be able to avoid metadata lookups.
-        lookupTablet(context, lcSession, ptl, metadataRow);
+    if (ptl == null) {
+      return;
+    }
+
+    CachedTablet now = findTabletInCache(row);
+    if (now != null) {
+      if (now.getTserverLocation().isPresent() && lcSession.checkLock(now) != null) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java:699]: In support of ondemand tablets, tablets w/o a location can be cached in 4.0 (was not the case in 2.1).  So these checks that look for the presence of a location do not seem correct.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java [hunk 2]
```diff
@@ -690,25 +690,28 @@ private void lookupTablet(ClientContext context, Text row, LockCheckerSession lc
...
 
-    if (ptl != null) {
-      // Only allow a single lookup at time per parent tablet. For example if a tables tablets are
-      // all stored in three metadata tablets, then that table could have up to three concurrent
-      // metadata lookups.
-      Timer timer = Timer.startNew();
-      try (var unused = lookupLocks.lock(ptl.getExtent())) {
-        // See if entry was added to cache by another thread while we were waiting on the lock
-        var cached = findTabletInCache(row);
-        if (cached != null && cached.getCreationTimer().startedAfter(timer)) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java:701]: What made you suspect the timer here?  I looked into the specifics of the timer and found how its implemented here https://github.com/openjdk/jdk/blob/b6b5ac1ef9042ed62a8358aa6943b8dc87dcf0ab/src/hotspot/os/posix/os_posix.cpp#L1474 .  Looking at the docs for that system call it does mention that it will not go backwards but also there is no gaurantee it wil go forward between two calls.   So its possible two threads got the exact same nanoTime causing the entry to look stale, that is probably ok.   We could make the time comparison `>=` instead of `>`.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java:701]: Changing the `>` to a `>=` is iffy and probably not good so please ignore that suggestion.  One way we could avoid comparing the time or anything else is to just look for change in the object reference.  So maybe could do the following?

```java
   CachedTablet before = findTabletInCache(row);
  try (var unused = lookupLocks.lock(ptl.getExtent())) {
       CachedTablet after = findTabletInCache(row);
       if(after != before){
           // another thread probably did the lookup while we were waiting on the lock, so let use that
           return;
       }
   
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java (hunk 1 above)
Comment (DomGarguilo) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java]: Removed in 5268f73ffc36550c0b30726c1f879dc02275c76c

File: core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java (hunk 2 above)
Comment (DomGarguilo) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImpl.java:701]: Added the object reference check in 5268f73ffc36550c0b30726c1f879dc02275c76c

File: core/src/test/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImplTest.java [hunk 3]
```diff
@@ -1986,45 +1987,56 @@ public void testMultithreadedLookups() throws Exception {
     setLocation(tservers, "tserver3", mte2, ke3, "tserver9");
 
     var executor = Executors.newCachedThreadPool();
-    List<Future<CachedTablet>> futures = new ArrayList<>();
+    final int lookupCount = 128;
```
Comment (keith-turner) [inline core/src/test/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImplTest.java:1990]: Without the fix is the test more likely to fail w/ these changes?

**Review by keith-turner — APPROVED** [review]

File: core/src/test/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImplTest.java (hunk 3 above)
Comment (DomGarguilo) [reply core/src/test/java/org/apache/accumulo/core/clientImpl/ClientTabletCacheImplTest.java:1990]: I have not been able to intentionally get the test to fail, with or without these changes. I have only ever seen the test fail when the build is run for something else.
