### PR TITLE
fixes #538 fix WAL recovery code

### LINKED ISSUE #538: Stateful compaction checking in write ahead log recovery is incorrect
When a tablet server dies, all of the tablets it was serving are assigned its active WALs.  See #537 for a more detailed description.  Therefore its possible that a clean tablet (had no data in memory when tserver died) is assigned WALs for recovery.  Its also possible that the clean tablet only has a compaction finish even in the WAL.  However there is checking in the recovery code that checks for only a compaction finish event and flags it as an error.  This is not an error.   This check made sense before 1.8.0 when WALs were tracked per tablet, because in this case a lone compaction finish event should not happen.  After 1.8.0, this check needs to be reconsidered.  Discovered this issue as a result of looking into and discussing #535 with @ctubbsii.

### PR DESCRIPTION
**Pull request by keith-turner**
There were two changes in this patch. First, removed a sanity check from the code
that resulted in false positives.  Second, changed recovery code to use last
compaction finish event for recovery seq #.

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 1]
```diff
@@ -190,38 +189,29 @@ private long findLastStartToFinish(List<Path> recoveryLogs, Set<String> tabletFi
...
 
-      if (firstEventWasFinish && !sawStartFinish) {
-        throw new IllegalStateException("COMPACTION_FINISH (without preceding COMPACTION_START)"
-            + " is not followed by a successful minor compaction.");
-      }
-
-      if (lastStartFile != null && suffixes.contains(getPathSuffix(lastStartFile))) {
-        // There was no compaction finish event, however the last compaction start event has a file
-        // in the metadata table, so the compaction finished.
+      if (lastStart > lastFinish && lastStartFile != null
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: This might be more clear if it just said something like `if lastEvent == COMPACTION_START`.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 2]
```diff
@@ -190,38 +189,29 @@ private long findLastStartToFinish(List<Path> recoveryLogs, Set<String> tabletFi
...
+          && suffixes.contains(getPathSuffix(lastStartFile))) {
+        // There was no compaction finish event following this start, however the last compaction
+        // start event has a file in the metadata table, so the compaction finished.
         log.debug("Considering compaction start {} {} finished because file {} in metadata table",
             tabletId, lastStart, getPathSuffix(lastStartFile));
         recoverySeq = lastStart;
+      } else {
+        recoverySeq = Math.max(0, lastFinish - 1);
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: This else statement covers the case where `lastEvent == COMPACTION_FINISH` (last successful event anyway...). That could be more clear in a comment. Also, would be good to mention why `lastFinish - 1` is used here (because that's the sequence id for the `COMPACTION_START` which corresponds to this `COMPACTION_FINISH`.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 3]
```diff
@@ -183,34 +183,37 @@ private long findRecoverySeq(List<Path> recoveryLogs, Set<String> tabletFiles, i
...
+        switch (key.event) {
+          case COMPACTION_START:
+            lastStart = key.seq;
+            lastStartFile = key.filename;
+            break;
+          case COMPACTION_FINISH:
+            checkState(key.seq > lastStart, "Compaction finish <= start %s %s %s", key.tabletId,
+                key.seq, lastStart);
+            checkState(lastEvent != COMPACTION_FINISH,
+                "Saw consecutive COMPACTION_FINISH events %s %s %s", key.tabletId, lastFinish,
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Might be useful if the parameter order in these messages were consistent. (tabletId, seq, then lastX); in the first message, seq is second, in the second message, seq is third.

**Comment by mikewalch** [comment]
I just want to document my testing for this PR. I ran continuous ingest on a 10 node cluster. I shortened agitation for to only 1-2 min for tservers. I made the wal log max size about 2MB. I ran one ingest test with 9 ingesters and no pausing and several other ingest tests with 1 ingester and pausing every few minutes. After the tests had run over night, I stopped the ingesters and ran verify.
