### PR TITLE
limits memory and cpu used by compaction reservation request

### LINKED ISSUE #5177: Unlimited threads for compaction reservation can oversubscribe manager memory
**Describe the bug**

When a compactor request a compaction job from the manager the following things happen.

 * The request runs in the general client thrift thread pool (note this thread pool will slowly automatically increase)
 * The request reads tablet metadata and then writes a conditional mutation to add the the compaction to tablet metadata.

When there are lots of compactors and there is a problem writing to the metadata table these threads will grow in an unlimited manner. Saw this problem occur and it was probably caused by not having the fixes for #5155 and #5168, however there are many other potential causes that could cause threads to get stuck or be slow.

**Expected behavior**

The number of threads concurrently executing compaction reservation is somehow constrained.  This must be done w/o blocking other manager functionality.   A simple way to achieve this goal would be to add a semaphore around this functionality, however this would cause general thrift threads that execute all manager functionality to block which could cause other problems but maybe that is ok since the manager thread pool always grows.

One possible way to achieve this goal would be to use #5018 and in the async code for executing compaction reservation runs in a limited thread pool. #5018 was created for performance reason, but it can also easily satisfy this goal of protecting manager memory.  

Another possible way to achieve this goal would be run another thrift server w/ its own port for getting compaction jobs and limit the thread pool size for this.

### PR DESCRIPTION
**Pull request by keith-turner**
Added threads pools to execute compaction reservation request in order to limit memory and cpu used by executing reservations.  Request queued up for the pool could still potentially use a lot of memory.  Did two things to control memory of things in the queue.  First only allow a compactor process to have one reservation processing at time.  Second made the data related to a resevation request a soft reference which should allow it be garbage collected if memory gets low while it sitting in the queue.  Once the request starts executing it obtains a strong refrence to the data so it can no longer be garbage collected.

fixes #5177

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java [hunk 1]
```diff
@@ -528,82 +551,138 @@ protected CompactionMetadata createExternalCompactionMetadata(CompactionJob job,
...
+      } finally {
+        Preconditions.checkState(activeCompactorReservationRequest.remove(compactorAddress));
       }
     }
+  }
+
+  protected CompactionMetadata reserveCompaction(CompactionJobQueues.MetaJob metaJob,
+      String compactorAddress, ExternalCompactionId externalCompactionId) {
+
+    if (activeCompactorReservationRequest.contains(compactorAddress)) {
```
Comment (cshannon) [inline server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java:666]: I was trying to think if there would be a race condition here if the thread pool was configured to be greater than 1 to handle multiple requests. I don't think there is because the same compactor should not be sending in multiple requests at the exact same time, so if there was multiple attempts and that leads to one of the Preconditions.checkState() checks on the add/remove failing then that is probably a good thing as it means there is an issue.

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java [hunk 2]
```diff
@@ -528,82 +551,138 @@ protected CompactionMetadata createExternalCompactionMetadata(CompactionJob job,
...
   }
 
-  protected CompactionMetadata reserveCompaction(CompactionJobQueues.MetaJob metaJob,
-      String compactorAddress, ExternalCompactionId externalCompactionId) {
+  private class ReserveCompactionTask implements Supplier<CompactionMetadata> {
+
+    // Use a soft reference for this in case free memory gets low while this is sitting in the queue
+    // waiting to process. This object can contain the tablets list of files and if there are lots
+    // of tablet with lots of files then that could start to cause memory problems.
+    private final SoftReference<CompactionJobQueues.MetaJob> metaJobRef;
```
Comment (cshannon) [inline server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java:559]: This is a neat way to help with the memory issue. I haven't looked but I am curious if there's some way to get statistics from the JVM to find out how often this reference is being freed that could be useful to monitor this. It may not be necessary though as the just watching total memory usage is probably good enough as this reference should only get cleared when low in memory.

**Review by cshannon — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java (hunk 2 above)
Comment (keith-turner) [reply server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java:560]: This was trying to deal with a problem I have been seeing while testing using the [FlakyBulkBatchWriter](https://github.com/apache/accumulo-testing/blob/807b62c01c4aae422a155be549fbf19664157b9c/src/main/java/org/apache/accumulo/testing/continuous/FlakyBulkBatchWriter.java#L55) in accumulo-testing that will sometimes submits large numbers of files for a tablet.   This can cause lots of memory pressure on the manager when lots of tablet have lots of files and the manager is trying to keep a lot of that in memory.  For this case its really hard to reason about what will be on the thread pool queue and how much memory it is using.  So decided to use a soft refernce for now, but I am uncertain about it.   Opened #5188 and added comment pointing to that issue in this PR.  I think if #5188 were implemented that this soft reference could be removed.  Would still want to restrict compactors from having multiple request queued/running.  I think if compactors can only have one thing queued for reservation and the queued data is only compaction jobs and no tablet metadata, then the memory usage would be unlikely to cause a problem.

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java (hunk 1 above)
Comment (keith-turner) [reply server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java:667]: Yeah if something really unusual is going on that Precondition check would catch it.  Under normal case of compactor retrying the first check will catch it.  It would probably be good add some info to the preconditions check in case it does fire.
