### PR TITLE
Handles exceptions during close

### LINKED ISSUE #3764: ScanDataSource could fail to handle exceptions during close
**Describe the bug**

The close method of ScanDataSource contains thrown exceptions that are not caught and handled which could cause the close operation to fail in a half-completed state. 

https://github.com/apache/accumulo/blob/22621258743aa28ee1337be5523602c2704fccc2/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java#L238-L263

If memIters is not null, then two methods are called before removing the scan from the tablet's activeScans.
The first method closes the InMemoryMap iterators and the other calls the DatafileManager to return files for scanning.

However, the code for `returnFilesForScan` can throw two different exceptions.
 
`IllegalArgumentException` 
https://github.com/apache/accumulo/blob/ff916e6759fbfd88d09b2ff0b3681d082c1e342e/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java#L125-L127

`IllegalStateException`
https://github.com/apache/accumulo/blob/ff916e6759fbfd88d09b2ff0b3681d082c1e342e/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java#L137-L139

These exceptions are not caught and could cause the close operation to fail. 
This would result in a ScanDataSource with memIters set to null, a fileReservationId not set to `-1` and a non-null fileManager. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.2

**Expected behavior**
If exceptions are thrown during close they are caught and either the close operation continues to completion OR it is retried.

**Additional context**

When troubleshooting shutdown issues related to #3512, activeScans that were holding up the Tablet's completeClose operation had a `memIters=null`, a non-null fileManager, and a fileReservationId set to a number other than `-1`. 

https://github.com/apache/accumulo/blob/ff916e6759fbfd88d09b2ff0b3681d082c1e342e/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1009-L1011 

While the exception messages were not found in the logs, the state of the particular ScanDataSource object matches a potentially failed close condition.

### PR DESCRIPTION
**Pull request by ddanielr**
Fixes #3764 
Also adds debug logging statement to help troubleshooting

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 1]
```diff
@@ -238,10 +238,16 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
...
       tablet.returnMemIterators(memIters);
       memIters = null;
-      tablet.returnFilesForScan(fileReservationId);
-      fileReservationId = -1;
+      log.debug("Returning files for scanning");
+      try {
+        tablet.returnFilesForScan(fileReservationId);
+        fileReservationId = -1;
+      } catch (IllegalArgumentException | IllegalStateException e) {
+        log.debug("Error Returning files for scanning {}", e.getMessage());
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:249]:
```suggestion
        log.warn("Error Returning files for scanning {}",extent, e));
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 2]
```diff
@@ -238,10 +238,16 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
   public void close(boolean sawErrors) {
 
     if (memIters != null) {
+      log.debug("Returning mem iterators");
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:241]: Logging debug per scan would be a lot of logging.  I would put these two debugs at trace.  Would also be good to include something that identifies the scan, like the extent.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java (hunk 1 above)
Comment (ivakegg) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:249]: Do we not want to still throw an exception and then add the remainder of the close method in a finally block?

Comment (ivakegg) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:249]: Also I see that the returning of the files for scan may also result in the MetadataTableUtil.removeScanFiles at the end of the method which could throw a host of other errors, mostly variants of IOException.

**Comment by ivakegg** [comment]
Looking for other holes, I am thinking that the Datafilemanager returnFilesForScan should be putting the synchronized block in a try catch and the final section that deletes the file scan entries in a finally block.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java (hunk 1 above)
Comment (keith-turner) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:249]: > Do we not want to still throw an exception and then add the remainder of the close method in a finally block?

It would be good to still throw the exception somehow.  If these exceptions are an indication that the scan was not correct, then do not want the scan to continue.  For example maybe a scan erroneously returns empty data instead of an error because an exception was logged and not rethrown.

Wondering if removing from the set could be moved earlier in the method.

Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java]: Changes applied

**Comment by ddanielr** [comment]
Added some updates from @ivakegg. 

Kicking off full ITs locally.

**Comment by ddanielr** [comment]
FullITs passed. 

Confirmed that new logging statements will show up regardless if `memIters` is set to `null` before entering close method.

**Review by keith-turner — COMMENTED** [review]
This code moves some complex code into finally blocks which could result in lost information if two exceptions are thrown.  For example with the following code the information related to the first exception will be completely lost when the 2nd is thrown.

```java
        try{
            throw new IllegalStateException("E1");
        } finally {
            throw new IllegalArgumentException("E2");
        }
```

Try with resources has much nicer handling of this where it will attach suppressed exceptions so potentially valuable information is not lost, but try finally does not have this.   Thought through refactoring these changes to use try with resources a little bit and it seemed ugly, but maybe there is a nice way to do it.

One possible solution is to log things just in case like the following.

```java
try {
  compexCode1ThatMayThrowException();
} catch(Exception e){
   // log exception here in case finally throws an exception so that the exception is not lost
   log.warn(e.getMessage(), e);
} finally {
   compexCode2ThatMayThrowException();
}
```

Not all of the finally blocks in this change are executing complex code that would need to worry about this.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java [hunk 3]
```diff
@@ -121,36 +121,40 @@ void returnFilesForScan(Long reservationId) {
...
           }
-          notify = true;
-        } else if (refCount < 0) {
-          throw new IllegalStateException("Scan ref count for " + path + " is " + refCount);
         }
       }
-
-      if (notify) {
-        tablet.notifyAll();
+    } finally {
```
[the remark this answers is not in the document]
Comment (ivakegg) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java:151]: because notify could be set to true prior to hitting the IllegalStateException.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 4]
```diff
@@ -149,6 +148,7 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
       if (fileManager == null) {
         fileManager = tablet.getTabletResources().newScanFileManager(scanParams.getScanDispatch());
         tablet.getScanMetrics().incrementOpenFiles(fileManager.getNumOpenFiles());
+        log.trace("Adding active scan for " + tablet.getExtent());
```
[the remark this answers is not in the document]
Comment (ivakegg) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:151]: +1

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java (hunk 1 above)
Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java]: This is a bit outdated now, but the latest commit logs the current stack trace and then re-throws the exception for handling.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java:154]: Added comment

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 5]
```diff
@@ -234,32 +234,50 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
...
-      fileManager.releaseOpenFiles(sawErrors);
-      fileManager = null;
-    }
+  @Override
+  public void close(boolean sawErrors) {
+    try {
+      returnIterators();
+    } finally {
+      synchronized (tablet) {
+        log.trace("Removing active scan for {}", tablet.getExtent());
```
[the remark this answers is not in the document]
Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java]: Added an AtomicLong for ScanDataSource and attributed a unique ScanDataSourceId to each object. 

I started looking into pulling the scan session ID down but that appears to be a larger refactor than what's in scope for this PR.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 6]
```diff
@@ -234,32 +234,50 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
...
-      tablet.returnMemIterators(memIters);
-      memIters = null;
-      tablet.returnFilesForScan(fileReservationId);
-      fileReservationId = -1;
-    }
-
-    synchronized (tablet) {
-      if (tablet.removeScan(this) == 0) {
-        tablet.notifyAll();
+      log.trace("Returning mem iterators for {}", tablet.getExtent());
```
[the remark this answers is not in the document]
Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java]: Added an AtomicLong for ScanDataSource and attributed a unique ScanDataSourceId to each object.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 7]
```diff
@@ -234,32 +239,60 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
...
+      try {
+        tablet.returnMemIterators(memIters);
+      } finally {
+        memIters = null;
+        log.trace("Returning file iterators for {}, scanId:{}, fid:{}", tablet.getExtent(),
+            scanDataSourceId, fileReservationId);
+        try {
+          tablet.returnFilesForScan(fileReservationId);
+        } catch (IllegalArgumentException | IllegalStateException e) {
+          if (log.isTraceEnabled()) {
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:255]: Its only logging at warn if trace is enabled

```suggestion
          if (log.isWarnEnabled()) {
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 8]
```diff
@@ -80,33 +84,33 @@ class ScanDataSource implements DataSource {
     this.interruptFlag = interruptFlag;
     this.loadIters = loadIters;
     this.defaultLabels = tablet.getDefaultSecurityLabels();
+    this.scanDataSourceId = nextSourceId.incrementAndGet();
     if (log.isTraceEnabled()) {
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:88]: This doesn't even need the check if the trace is enabled. That's already built in to the logging API. We typically only need to do that when we need to do work to construct the message, and we want to avoid that work if we don't need to log the message. In this case, the only work we'd be avoiding is the construction of the varargs array for the format string's parameters, and that's assuming it's not hitting one of the optimized fixed-parameter overloaded versions of the log method from the logging library. Even if it was calling a varargs version, I doubt that would be measurable. We can just get rid of the isTraceEnabled check here.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 9]
```diff
@@ -234,32 +239,60 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
...
+        log.trace("Returning file iterators for {}, scanId:{}, fid:{}", tablet.getExtent(),
+            scanDataSourceId, fileReservationId);
+        try {
+          tablet.returnFilesForScan(fileReservationId);
+        } catch (IllegalArgumentException | IllegalStateException e) {
+          if (log.isWarnEnabled()) {
+            log.warn("Error Returning file iterators for scan: {}, :{}", scanDataSourceId,
+                e.getMessage());
+            log.warn("{}", ExceptionUtils.getStackTrace(e));
+          }
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:259]: Use of ExceptionUtils is not needed here at all. If we want the stack trace, that can be done as a built-in feature of the logging framework. We also don't need the check if the warning level is enabled. Just make the exception the last parameter after all the formatString's parameters, and the logging framework will automatically include the exception's message and stack trace.

```suggestion
          log.warn("Error returning file iterators for scan: {}", scanDataSourceId, e);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java [hunk 10]
```diff
@@ -234,32 +239,60 @@ private SortedKeyValueIterator<Key,Value> createIterator() throws IOException {
...
+          // Continue bubbling the exception up for handling.
+          throw e;
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java:261]: I've said before that in general, we should choose to either log and handle an exception, or we should choose to pass it through to be logged and handled at another layer. When we do both, this tends to result in multiple log messages for the same exception logged at different layers.

In this case, we're dealing with RTEs, so it's possible we're just throwing it out and not expecting something else to handle it... so this might be the only time it gets logged. But, if that's the case, it's weird that we're just catching 2 specific RTEs and logging, but other possible RTEs that might get thrown.

I'm not sure exactly what the intent here is, so it's hard to make a concrete suggestion, but if we're going to both log and throw, I think the reasoning should be clear why we're doing both.

Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java]: > In this case, we're dealing with RTEs, so it's possible we're just throwing it out and not expecting something else to handle it... so this might be the only time it gets logged. But, if that's the case, it's weird that we're just catching 2 specific RTEs and logging, but other possible RTEs that might get thrown.
> 
I made a change to log any exception rather than just two specific RTEs.


> I'm not sure exactly what the intent here is, so it's hard to make a concrete suggestion, but if we're going to both log and throw, I think the reasoning should be clear why we're doing both.

In this case, the exceptions are being swallowed somewhere in the code. 
The logging would help identity them, while re-throwing the exception ensures that code behavior doesn't change due to the new `catch` block.

I strongly suspect that there are some thrift calls that only recreate Thrift exceptions for the clients and miss other important exception types.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java [hunk 11]
```diff
@@ -968,9 +969,19 @@ public List<TCMResult> conditionalUpdate(TInfo tinfo, long sessID,
...
+      errorThrown = true;
+      throw e;
     } finally {
-      writeTracker.finishWrite(opid);
-      server.sessionManager.unreserveSession(sessID);
+      try {
+        writeTracker.finishWrite(opid);
+        server.sessionManager.unreserveSession(sessID);
+      } catch (Exception e) {
+        var message = errorThrown ? "Second Exception" : "Exception";
```
Comment (ivakegg) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java:981]: Is this block really needed?  This is presuming that we can thrown an exception from finishWrite or unreserveSession.  If we can thrown an exception from the former, then this should be split into 2 finally blocks.  If not, then perhaps this block is not needed.  It appears that we are guarenteed that the writeTracker.startWrite was called and returned a valid opid.  In addition the sessID must have been reserved.  The only way these would throw exceptions is if some other thread for the same opid or sessID and I do not see that as being possible.

Comment (ddanielr) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/TabletClientHandler.java]: Yeah you're right. While the sessionID is passed in to `conditionalUpdate`, the session is reserved on line 926 and the write opid is also generated on line 944. 
I agree that it should be impossible for another thread to have the same opid or reserved sessID at the same time, so the exceptions from finishWrite and unreserveSession wouldn't happen here. 

I've gone ahead and pulled this block out.

**Review by ivakegg — APPROVED** [review]
LGTM
