### PR TITLE
Move fate summary IT from ShellServerIT to its own class

### LINKED ISSUE #2948: Broken or Flaky test: ShellServerIT.testFateSummaryCommandWithSlowCompaction
**Test name(s)**
[ERROR] org.apache.accumulo.test.shell.ShellServerIT.testFateSummaryCommandWithSlowCompaction  Time elapsed: 4.365 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
reportTime present in root@miniInstance ns1.ShellServerIT_testFateSummaryCommandWithSlowCompaction0> fate -summary -np json -t NEW IN_PROGRESS FAILED
 was not true ==> expected: <true> but was: <false>

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #2948

### CODE REVIEW

**Comment by dlmarion** [comment]
I didn't port the full test, think it's needed?

File: test/src/main/java/org/apache/accumulo/test/FateSummaryIT.java [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+      String result = p.readStdOut();
+      result = result.substring(result.indexOf("{"), result.lastIndexOf("}") + 1);
+      FateSummaryReport report = FateSummaryReport.fromJson(result);
+      assertNotNull(report);
+      assertNotEquals(0, report.getReportTime());
+      Set<String> expected = new HashSet<>();
+      expected.add("FAILED");
+      expected.add("IN_PROGRESS");
+      expected.add("NEW");
+      assertEquals(expected, report.getStatusFilterNames());
```
Comment (dlmarion) [inline test/src/main/java/org/apache/accumulo/test/FateSummaryIT.java:97]: using Set.of("FAILED", "IN_PROGRESS", "NEW") didn't work here, hence the HashSet above.

**Review by EdColeman — APPROVED** [review]
We may want to look at creating an AdminIT test that tests all off the Admin options that are being moved and eventually removed from the Shell - similar to the ShellServerIT test - but this is a good start.
