### PR TITLE
Modified Manager.run startup to account for upgrade stages

### LINKED ISSUE #5368: TableDeletedException in Manager during 4.0.0 upgrade
The Manager kicks off a background thread to perform the upgrade, then in the main thread it continues starting the metrics subsystem, starting various threads, waiting for the tservers to come up, starting the compaction coordinator, starting the Splitter, and starting the TabletGroupWatchers before waiting for the upgrade to complete.

I saw the following exception while the Manager was starting while the upgrade process was upgrading the root tablet from version 11 to 12.

```
2025-02-28T20:55:07,307 [fate.FateMetrics] INFO : Failed to update userfate metrics due to exception
org.apache.accumulo.core.client.TableDeletedException: Table ID +fate was deleted
        at org.apache.accumulo.core.clientImpl.ClientContext.requireNotDeleted(ClientContext.java:621) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ThriftScanner.getNextScanAddress(ThriftScanner.java:561) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:659) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ScannerIterator.readBatch(ScannerIterator.java:162) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:180) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ScannerIterator.hasNext(ScannerIterator.java:112) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at org.apache.accumulo.core.fate.AdminUtil.lambda$getTransactionStatus$2(AdminUtil.java:353) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.util.Map.forEach(Map.java:713) ~[?:?]
        at org.apache.accumulo.core.fate.AdminUtil.getTransactionStatus(AdminUtil.java:351) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.fate.AdminUtil.getTransactionStatus(AdminUtil.java:206) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.FateMetricValues.getFateMetrics(FateMetricValues.java:82) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.user.UserFateMetricValues.getUserStoreMetrics(UserFateMetricValues.java:42) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.user.UserFateMetrics.getMetricValues(UserFateMetrics.java:41) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.user.UserFateMetrics.getMetricValues(UserFateMetrics.java:27) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.FateMetrics.update(FateMetrics.java:77) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.manager.metrics.fate.FateMetrics.lambda$registerMetrics$2(FateMetrics.java:119) ~[accumulo-manager-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

I'm thinking we might want to re-organize the Manager startup sequence such that the metrics, Splitter, and compaction coordinator are started after the upgrade is complete. We may also want to wait to start the metadata TGW until after the Root upgrade is complete, and the user TGW until after the entire upgrade is complete.

### PR DESCRIPTION
**Pull request by dlmarion**
Updated Manager to account for the status of an upgrate when starting processes. For example, the new fate table is created during the 4.0 upgrade, so we can't start Fate or anything that uses Fate (e.g. Splitter) until after the table has been created.

Closes #5368

### CODE REVIEW

**Review by ctubbsii — COMMENTED** [review]
Reordering some things and tracking extra state might work, but it also seems that some of this could be solved more easily by an upgrade step that runs before the manager. It is an extra step we've tried very hard to avoid in the past... for user convenience, but maybe it's necessary for the sake of overall simplicity. I'm not sure.

**Comment by dlmarion** [comment]
> Reordering some things and tracking extra state might work, but it also seems that some of this could be solved more easily by an upgrade step that runs before the manager. It is an extra step we've tried very hard to avoid in the past... for user convenience, but maybe it's necessary for the sake of overall simplicity. I'm not sure.

That would work for updating ZooKeeper, but I think you also need a TabletServer up at some point to host the root and metadata tablets so that they can be upgraded.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 1]
```diff
@@ -1259,18 +1246,65 @@ boolean canSuspendTablets() {
...
+        case UPGRADED_METADATA:
+          // Start processing user tables
+          userTableTGW.start();
+          userTGWStarted = true;
+          break;
+        case UPGRADED_ROOT:
+          // Start processing the metadata table
+          metadataTableTGW.start();
+          metaTGWStarted = true;
+          break;
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1281]: The upgrade code may or may not block waiting on the TGW for each level, it depends on if it reads something or not.  So this code may not see each UPGRADED_XXX.  Maybe it needs to check the earlier TGW to be safe.

```suggestion
         // TODO check if rootTableTGW needs to be started
          break;
```

Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1287]: Changed this in cceb9fb

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 2]
```diff
@@ -1259,18 +1246,65 @@ boolean canSuspendTablets() {
...
+    while (isUpgrading()) {
+      UpgradeStatus currentStatus = upgradeCoordinator.getStatus();
+      if (currentStatus == UpgradeStatus.FAILED || currentStatus == UpgradeStatus.COMPLETE) {
+        break;
+      }
+      switch (currentStatus) {
+        case UPGRADED_METADATA:
+          // Start processing user tables
+          userTableTGW.start();
+          userTGWStarted = true;
```
[the remark this answers is not in the document]
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java]: Implemented this in cceb9fb

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 3]
```diff
@@ -1259,18 +1247,71 @@ boolean canSuspendTablets() {
...
             // Never allow root tablet to enter suspended state.
             return false;
           }
-        });
-    for (TabletGroupWatcher watcher : watchers) {
-      watcher.start();
+        };
+    watchers.add(rootTableTGW);
+
+    while (isUpgrading()) {
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1263]: Wonder if some logging in this loop would be useful, depends on what is currently be logged on by other code like TGW.

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java [hunk 4]
```diff
@@ -1259,18 +1247,71 @@ boolean canSuspendTablets() {
...
+            rootTableTGW.start();
+          }
+          break;
+        case FAILED:
+        case COMPLETE:
+        case INITIAL:
+        default:
+          break;
+      }
+    }
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1300]: This loop could sleep for a short period, its could be checking these things really frequently.

**Review by keith-turner — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/Manager.java (hunk 3 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/Manager.java:1263]: `UpgradeCoordinator.setStatus ` calls the EventCoordinator when the status of the upgrade changes. These messages get logged.
