### PR TITLE
Close #1739. Cleanup Splits file if CreateTable FaTE operation fails.

### LINKED ISSUE #1739: CreateTable FaTE operation may not clean up splits files if operation is killed
The CreateTable FaTE operation creates files in DFS for storing split points, if the user is creating a pre-split table. If the task completes, it should delete these files. However, if the job fails, it may not delete one or both. The `undo` method for the `ChooseDir` step should delete one of the files, but nothing seems like it will delete the other one, unless the operation completes successfully.

Found on main/2.1.0-SNAPSHOT branch while working on PR #1738 ; it may affect other versions as well

### PR DESCRIPTION
**Pull request by Manno15**
Uses the same cleanup logic that is used if the operation is successful. Closes #1739

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java [hunk 1]
```diff
@@ -78,7 +79,11 @@ public long isReady(long tid, Master environment) throws Exception {
   }
 
   @Override
-  public void undo(long tid, Master env) {
+  public void undo(long tid, Master env) throws Exception {
+    // Clean up split files if create table operation fails
+    Path p = tableInfo.getSplitPath().getParent();
+    FileSystem fs = p.getFileSystem(env.getContext().getHadoopConf());
+    fs.delete(p, true);
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java:86]: returns boolean, should we log when delete fails?

Comment (Manno15) [reply server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java:86]: I can add a log for it if it is necessary but I should also add a check to make sure there is even a split file to begin with... I will add that.

**Review by ctubbsii — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java [hunk 2]
```diff
@@ -78,7 +80,13 @@ public long isReady(long tid, Master environment) throws Exception {
   }
 
   @Override
-  public void undo(long tid, Master env) {
+  public void undo(long tid, Master env) throws IOException {
+    // Clean up split files if create table operation fails
+    if(tableInfo.getInitialSplitSize() > 0) {
+      Path p = tableInfo.getSplitPath().getParent();
+      FileSystem fs = p.getFileSystem(env.getContext().getHadoopConf());
+      fs.delete(p, true);
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java:88]: @Manno15 if this throws an Exception, then unreserveNamespace() will not execute and that may not be good.

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java:88]: We could wrap this and put the unreserve call in the finally block.

Comment (Manno15) [reply server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java:88]: I will make a new pull request with these changes

Comment (ctubbsii) [reply server/manager/src/main/java/org/apache/accumulo/master/tableOps/create/CreateTable.java:88]: Follow up made on #1759
