### PR TITLE
New IteratorMincClassCastBugIT and fixes to #1411

### LINKED ISSUE #2341: Minor compactions failing on 2.1.0-SNAPSHOT
Discovered this while testing DataWave on 2.1.0-SNAPSHOT (5f20e386)....
Minor compactions are failing as a result of `ClassCastException`, as shown below, which arises from a `deepCopy` call in this [DataWave iterator](https://github.com/NationalSecurityAgency/datawave/blob/feature/accumulo-2.0/warehouse/ingest-core/src/main/java/datawave/iterators/PropogatingIterator.java#L285), which is configured for all scopes on the given table

I note that [org.apache.accumulo.core.iterators.SortedMapIterator](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java) no longer implements `InterruptibleIterator` as in previous versions. That appears to explain the issue, but perhaps there's a workaround, or something we're doing in DW that no longer makes sense for 2.1.x(?)
```
[compaction.FileCompactor] ERROR: class org.apache.accumulo.core.iterators.SortedMapIterator cannot be cast to class org.apache.accumulo.core.iteratorsImpl.system.InterruptibleIterator (org.apache.accumulo.core.iterators.SortedMapIterator and org.apache.accumulo.core.iteratorsImpl.system.InterruptibleIterator are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.apache.accumulo.core.iterators.SortedMapIterator cannot be cast to class org.apache.accumulo.core.iteratorsImpl.system.InterruptibleIterator (org.apache.accumulo.core.iterators.SortedMapIterator and org.apache.accumulo.core.iteratorsImpl.system.InterruptibleIterator are in unnamed module of loader 'app')
        at org.apache.accumulo.core.iteratorsImpl.system.LocalityGroupIterator$LocalityGroup.<init>(LocalityGroupIterator.java:48) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.LocalityGroupIterator.deepCopy(LocalityGroupIterator.java:307) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.MultiIterator.<init>(MultiIterator.java:54) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.MultiIterator.deepCopy(MultiIterator.java:46) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.MultiIterator.deepCopy(MultiIterator.java:38) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.CountingIterator.<init>(CountingIterator.java:44) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.CountingIterator.deepCopy(CountingIterator.java:40) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.CountingIterator.deepCopy(CountingIterator.java:32) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.DeletingIterator.<init>(DeletingIterator.java:51) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.DeletingIterator.deepCopy(DeletingIterator.java:47) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.DeletingIterator.deepCopy(DeletingIterator.java:37) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.iteratorsImpl.system.ColumnFamilySkippingIterator.deepCopy(ColumnFamilySkippingIterator.java:107) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at datawave.iterators.PropogatingIterator.init(PropogatingIterator.java:285) ~[?:?]
        at org.apache.accumulo.core.conf.IterConfigUtil.loadIterators(IterConfigUtil.java:221) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.conf.IterConfigUtil.convertItersAndLoad(IterConfigUtil.java:188) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.compactLocalityGroup(FileCompactor.java:359) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.compaction.FileCompactor.call(FileCompactor.java:222) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.MinorCompactor.call(MinorCompactor.java:97) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompact(Tablet.java:800) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.MinorCompactionTask.run(MinorCompactionTask.java:99) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.minorCompactNow(Tablet.java:933) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.AssignmentHandler.run(AssignmentHandler.java:174) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:63) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.htrace.wrappers.TraceRunnable.run(TraceRunnable.java:57) ~[htrace-core-3.2.0-incubating.jar:3.2.0-incubating]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2021-10-28T18:29:47,925 [tablet.MinorCompactor] WARN : MinC failed ....
```
**And here's the table config...**
```
config -t datawave.shard -np
-----------+---------------------------------------------+----------------------------------------------------------------
SCOPE      | NAME                                        | VALUE
-----------+---------------------------------------------+----------------------------------------------------------------
default    | table.balancer ............................ | org.apache.accumulo.core.spi.balancer.SimpleLoadBalancer
table      |    @override .............................. | datawave.ingest.table.balancer.ShardedTableTabletBalancer
default    | table.bloom.enabled ....................... | false
default    | table.bloom.error.rate .................... | 0.5%
default    | table.bloom.hash.type ..................... | murmur
default    | table.bloom.key.functor ................... | org.apache.accumulo.core.file.keyfunctor.RowFunctor
default    | table.bloom.load.threshold ................ | 1
default    | table.bloom.size .......................... | 1048576
default    | table.bulk.max.tablets .................... | 0
default    | table.cache.block.enable .................. | false
default    | table.cache.index.enable .................. | true

default    | table.class.loader.context ................ |         ## From my accumulo.properties:
system     |    @override .............................. | extlib  ##   general.vfs.context.classpath.extlib=file://${ACCUMULO_HOME}/lib/ext/.*.jar"

default    | table.classpath.context ................... |
default    | table.compaction.configurer ............... |
default    | table.compaction.dispatcher ............... | org.apache.accumulo.core.spi.compaction.SimpleCompactionDispatcher
default    | table.compaction.major.everything.idle .... | 1h
default    | table.compaction.major.ratio .............. | 3
default    | table.compaction.minor.idle ............... | 5m
default    | table.compaction.minor.logs.threshold ..... | 3
default    | table.compaction.selection.expiration.ms .. | 2m
default    | table.compaction.selector ................. |
table      | table.constraint.1 ........................ | org.apache.accumulo.core.constraints.DefaultKeySizeConstraint
default    | table.durability .......................... | sync
default    | table.failures.ignore ..................... | false
default    | table.file.blocksize ...................... | 0B
default    | table.file.compress.blocksize ............. | 100k
default    | table.file.compress.blocksize.index ....... | 128k
default    | table.file.compress.type .................. | gz
default    | table.file.max ............................ | 15
default    | table.file.replication .................... | 0
default    | table.file.summary.maxSize ................ | 256k
default    | table.file.type ........................... | rf
default    | table.formatter ........................... | org.apache.accumulo.core.util.format.DefaultFormatter
table      | table.group.fullcontent ................... | d
table      | table.group.termfrequency ................. | tf
default    | table.groups.enabled ...................... |
table      |    @override .............................. | termfrequency,fullcontent
default    | table.interepreter ........................ | org.apache.accumulo.core.util.interpret.DefaultScanInterpreter
table      | table.iterator.majc.agg ................... | 10,datawave.iterators.PropogatingIterator
table      | table.iterator.majc.agg.opt.tf ............ | datawave.ingest.table.aggregator.TextIndexAggregator
table      | table.iterator.majc.vers .................. | 20,org.apache.accumulo.core.iterators.user.VersioningIterator
table      | table.iterator.majc.vers.opt.maxVersions .. | 1
table      | table.iterator.minc.agg ................... | 10,datawave.iterators.PropogatingIterator
table      | table.iterator.minc.agg.opt.tf ............ | datawave.ingest.table.aggregator.TextIndexAggregator
table      | table.iterator.minc.vers .................. | 20,org.apache.accumulo.core.iterators.user.VersioningIterator
table      | table.iterator.minc.vers.opt.maxVersions .. | 1
table      | table.iterator.scan.agg ................... | 10,datawave.iterators.PropogatingIterator
table      | table.iterator.scan.agg.opt.tf ............ | datawave.ingest.table.aggregator.TextIndexAggregator
table      | table.iterator.scan.vers .................. | 20,org.apache.accumulo.core.iterators.user.VersioningIterator
table      | table.iterator.scan.vers.opt.maxVersions .. | 1
default    | table.majc.compaction.strategy ............ | org.apache.accumulo.tserver.compaction.DefaultCompactionStrategy
default    | table.replication ......................... | false
default    | table.sampler ............................. |
default    | table.scan.dispatcher ..................... | org.apache.accumulo.core.spi.scan.SimpleScanDispatcher
default    | table.scan.max.memory ..................... | 512k
default    | table.security.scan.visibility.default .... |
default    | table.split.endrow.size.max ............... | 10k
default    | table.split.threshold ..................... | 1G
default    | table.suspend.duration .................... | 0s
default    | table.walog.enabled ....................... | true
```

### PR DESCRIPTION
**Pull request by milleruntime**
* Create new IT for testing runtime bug that was introduced when moving
the iterators to declare them public API in #1411. The other changes in
this commit are for fixing the bug.
* Drop new class InterruptibleMapIterator that was created in #1411
* Revert SortedMapIterator back to previous implementation where it
was an InterruptibleIterator but keep it in core.iterators pkg
* Move InterruptibleIterator interface to API and add javadoc
* Move ColumnFamilySkippingIterator to API
* Add javadoc to IterationInterruptedException
* Fixes #2341

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java [hunk 1]
```diff
@@ -0,0 +1,516 @@
...
+      if (chunkSize == 0)
+        return "";
+      md5digest.reset();
+      String uid = hexString(md5digest.digest(filename.getBytes()));
+
+      // read through file once, calculating hashes
+      md5digest.reset();
+      InputStream fis = null;
+      int numRead = 0;
+      // try (var reader = new InputStreamReader(accumuloPropsLocation.openStream(), UTF_8)) {
```
Comment (Manno15) [inline test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java:162]:
```suggestion

```

File: core/src/main/java/org/apache/accumulo/core/iterators/InterruptibleIterator.java [hunk 2]
```diff
@@ -16,14 +16,22 @@
...
 import org.apache.accumulo.core.data.Key;
 import org.apache.accumulo.core.data.Value;
-import org.apache.accumulo.core.iterators.SortedKeyValueIterator;
 
+/**
+ * Allows an iterator to be interrupted. Typically, once the interrupt flag is set the iterator will
+ * throw an {@link InterruptedException} if the interrupt is detected. Some iterators have been
+ * optimized to not always check the flag.
+ *
+ * One example of a system interrupt is when a Tablet is being closed. If a Tablet has an active
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/iterators/InterruptibleIterator.java:31]: Blank line in javadoc without a `<p>` isn't correct

File: core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java [hunk 3]
```diff
@@ -16,7 +16,7 @@
  * specific language governing permissions and limitations
  * under the License.
  */
-package org.apache.accumulo.core.iteratorsImpl.system;
+package org.apache.accumulo.core.iterators;
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java:19]: Moving the interface back to public API seems like the obvious fix, but are we expecting users to actually use this interface? I haven't followed all the details, but my understanding was that this was a feature intended solely for internal use with some of our own system iterators. But, maybe I'm wrong? Is this something that is useful to user iterators and safe for them to use?

File: core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java [hunk 4]
```diff
@@ -36,28 +37,40 @@
...
  */
-public class SortedMapIterator implements SortedKeyValueIterator<Key,Value> {
+public class SortedMapIterator implements InterruptibleIterator {
   private Iterator<Entry<Key,Value>> iter;
   private Entry<Key,Value> entry;
 
   private SortedMap<Key,Value> map;
   private Range range;
 
+  private AtomicBoolean interruptFlag;
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java:52]: Atomic references are typically `final` whenever possible, to prevent bugs where atomicity is broken because the reference is changed. I see this can't be made final because there's a setter... but that seems like bad API design. Is there something we can do to fix this?

File: core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java [hunk 5]
```diff
@@ -95,6 +111,9 @@ public void next() throws IOException {
   public void seek(Range range, Collection<ByteSequence> columnFamilies, boolean inclusive)
       throws IOException {
 
+    if (interruptFlag != null && interruptFlag.get())
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java:114]: `interruptFlag` should never be null. We can require non-null anywhere we accept it.

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java [hunk 6]
```diff
@@ -0,0 +1,516 @@
...
+
+      if (depth != 0)
+        throw new IllegalArgumentException("Invalid vis " + cv);
+
+    }
+
+    private void insert(ByteSequence cv) {
+      for (int i = 0; i < cv.length(); i++) {
+
+      }
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java:456]: What is this loop doing?

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java [hunk 7]
```diff
@@ -0,0 +1,516 @@
...
+
+  public static final byte[] nullbyte = new byte[] {0};
+
+  /**
+   * Join some number of strings using a null byte separator into a text object.
+   *
+   * @param s
+   *          strings
+   * @return a text object containing the strings separated by null bytes
+   */
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java:506]: This could probably just be a one-line inline comment. We're not publishing javadocs for ITs. This method can probably also be private... as could some others added in this file for testing.

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java [hunk 8]
```diff
@@ -0,0 +1,516 @@
...
+    byte[] get() {
+      StringBuilder sb = new StringBuilder();
+      String sep = "";
+      for (String cvs : visibilities) {
+        sb.append(sep);
+        sep = "|";
+        sb.append(cvs);
+      }
+
+      return sb.toString().getBytes();
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java:494]: Should be `getBytes(UTF_8)`

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java [hunk 9]
```diff
@@ -0,0 +1,516 @@
...
+   *
+   * @param s
+   *          strings
+   * @return a text object containing the strings separated by null bytes
+   */
+  public static Text buildNullSepText(String... s) {
+    Text t = new Text(s[0]);
+    for (int i = 1; i < s.length; i++) {
+      t.append(nullbyte, 0, 1);
+      t.append(s[i].getBytes(), 0, s[i].length());
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java:511]: should be `getBytes(UTF_8)`

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java [hunk 10]
```diff
@@ -0,0 +1,516 @@
...
+          if (numRead > 0) {
+            md5digest.update(buf, 0, numRead);
+          }
+          numRead = fis.read(buf);
+        }
+      } finally {
+        if (fis != null) {
+          fis.close();
+        }
+      }
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java:176]: Our test file is small enough that this can be reduced to two simple lines... one to read the file fully into a String, and another to compute the digest from the String's bytes. This would improve the comprehensibility of the test, since we don't actually need to chunk and buffer the tiny test file.

File: core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java (hunk 4 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java:52]: We should be able to make this final with an initial value of `false`. I haven't really touched the iterators since most of them have been around since forever but I think this would be a good fix. FYI I had a hell of a time tracking down where we actually do the interrupt. As a reference, it seems like the only place we actually interrupt iterators is in `ScanDataSource`:
https://github.com/apache/accumulo/blob/8a636a3ba91f5dae1d8b09b095178889a7d79c1d/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanDataSource.java#L256-L258
When a tablet is closed:
https://github.com/apache/accumulo/blob/b5ca15806659efbbd6f5d158be8648cc2cd13593/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1288

We have a ton of calls to pass the flag around between iterators, readers and RFile code but that seems to be the only place where the actual interrupt takes place.

**Comment by milleruntime** [comment]
@Manno15 @ctubbsii thanks for taking a look at this. I guess I should have been more explicit or made this a draft PR because a lot of the code in your feedback was just yanked from the examples repo, specifically the [ChunkCombiner](https://github.com/apache/accumulo-examples/blob/main/src/main/java/org/apache/accumulo/examples/filedata/ChunkCombiner.java) to try and simulate what Datawave is doing with iterators. I am not sure if I should clean it up or just stick it in a test jar so we don't have to look at it. 

Do either of you know how to get MiniAccumuloCluster to load classes from a jar during runtime? I thought it might be a better test to do that but couldn't get it working.

File: core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java (hunk 3 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java:19]: That is what I had originally thought but after investigating this bug it seems like `SortedMapIterator` and this one could be cast to an InterruptibleIterator in the `LocalityGroupIterator`
https://github.com/apache/accumulo/blob/8d33bc4d489880f15950189d20287262ce46e68e/core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/LocalityGroupIterator.java#L49

I think if a user extends one of them and configures it to run in certain situations it could be created through deepCopy(). But it also seems dangerous either way.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java:19]: Also, my original intention in #1411 was since SortedMapIterator was used so much in our Tests that it would be useful to users as well. But I could be wrong in that thinking. It could be unsafe to expose it to users so a better option may be to move it in with the other system iterators. I can't remember if I attempted this or how difficult this would be though.

File: core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java (hunk 4 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java:52]: I thought about changing the `AtomicBoolean` to be final but now I am wondering if it was written this way with performance in mind. We do a lot of passing around of the flag across the iterator stack but only ever set it in one place.  If we were to make it final, then I think that would be a lot of extra memory accesses to the atomic value vs just passing around a reference.

I thought of doing something like this in the setter, but like I said, I think it would be less efficient:
<pre>
public void setInterruptFlag(AtomicBoolean flag) {
    boolean newFlag = flag.get();
    boolean previousFlag = this.interruptFlag.getAndSet(newFlag);
    if (previousFlag == newFlag && newFlag)
      log.warn("Interrupt called on iterator that was previously interrupted.");
  }
</pre>

**Comment by milleruntime** [comment]
@ctubbsii @Manno15 This PR changed significantly since your initial reviews. I moved the iterators back to the iteratorsImpl package, along with moving SortedMapIterator there. The more I thought about it, the less I liked including InterruptibleIterator in the public API. We created the `YieldingKeyValueIterator` interface with the intention of public use so we don't need InterruptibleIterator in the API. I also rewrote the IT to just use a simple iterator that will still cause the class cast exception to happen without the fix.

File: test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java (hunk 10 above)
Comment (milleruntime) [reply test/src/main/java/org/apache/accumulo/test/functional/IteratorMincClassCastBugIT.java]: I rewrote the IT so it doesn't need to ingest a file now.

File: core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java (hunk 3 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iterators/ColumnFamilySkippingIterator.java]: Moved this iterator back to iteratorsImpl package in 1a4bb21607324ef6a9d2a0eeb458c0cdb3c59681

**Review by Manno15 — APPROVED** [review]
Changes look good, I don't fully know the impact of the interuptible changes but I didn't run into any issues while testing. Confirmed that these changes to fix the reported issue.

**Comment by milleruntime** [comment]
> Changes look good, I don't fully know the impact of the interuptible changes but I didn't run into any issues while testing. Confirmed that these changes to fix the reported issue.

Thanks for testing these changes. Just curious, how did you reproduce the issue?

**Comment by Manno15** [comment]
> Thanks for testing these changes. Just curious, how did you reproduce the issue?

Using the IT you created. So maybe that isn't a definitive test but it did fail against main while working with the rest of these changes.

File: core/src/main/java/org/apache/accumulo/core/iterators/IterationInterruptedException.java [hunk 11]
```diff
@@ -18,6 +18,9 @@
  */
 package org.apache.accumulo.core.iterators;
 
+/**
+ * Exception thrown if an interrupt flag is detected.
+ */
 public class IterationInterruptedException extends RuntimeException {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/iterators/IterationInterruptedException.java:24]: Should this RTE exist in public API, or should it be in iteratorsImpl as well?

File: core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SortedMapIterator.java [hunk 12]
```diff
@@ -121,4 +143,9 @@ public void init(SortedKeyValueIterator<Key,Value> source, Map<String,String> op
       IteratorEnvironment env) throws IOException {
     throw new UnsupportedOperationException();
   }
+
+  @Override
+  public void setInterruptFlag(AtomicBoolean flag) {
+    this.interruptFlag = flag;
+  }
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SortedMapIterator.java:150]: Because changing the reference breaks atomicity guarantees, this method looks dubious. It looks like the way this is intended to be used is like a BooleanSupplier (or even more strictly, a one-way latch that can move from false to true, but never back to false). I'm not sure the right solution, but if the interruptible stuff is only on the server-side, it could be cleaned up to avoid using AtomicBoolean and use something more appropriate instead.

**Review by ctubbsii — APPROVED** [review]
I like the consolidation of InterruptibleMapIterator into SortedMapIterator, and I like keeping these out of the public API. I'm not sure I understand how it fixed the reported issue, but these changes look okay to me.

File: core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SortedMapIterator.java (hunk 12 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SortedMapIterator.java:150]: I agree. I am hesitant to go changing internals with the iterators though since they are so heavily reliant on runtime configuration (one of the reasons it took so long to find this bug in the first place) and I don't think we have adequate test coverage for their behavior.

File: core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java (hunk 4 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/iterators/SortedMapIterator.java:55]: It's not a performance thing. It's an implementation injection mechanism (see where we're notifying the iterators by changing the value in the scan code: `grep -lR 'interruptFlag.set(true)' .`. AtomicBoolean is being used like a BooleanSupplier. This was probably fine at one point, since BooleanSupplier was introduced in Java 8, and before that, AtomicBoolean was an attractive alternative to a built-in supplier. But, having the type be AtomicBoolean implies atomicity, and that can be confusing, since atomicity guarantees are clearly broken by having a setter that can swap out the reference itself in addition to the value. We're not actually relying on the atomicity guarantees in these cases, though, as far as I can tell, so BooleanSupplier would suffice as the type.

Your code above wouldn't work. I had a similar idea initially (`this.interruptFlag.set(flag.get())`). However, it's not sufficient to set the value. We need to set the containing object reference, so we can communicate the change in value when the caller updates the source.

File: core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SortedMapIterator.java (hunk 12 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/iteratorsImpl/system/SortedMapIterator.java:150]: My suggestion would be to use BooleanSupplier in the InterruptibleIterator interface, and call `setInterruptFlag(interruptFlag::get)` (where `interruptFlag` in the caller is of type `AtomicBoolean`). That would remove any confusion over implied atomicity guarantees inside the InterruptibleIterator interface, but wouldn't change any behavior. But, obviously, that would be a follow-on issue. It need not be done as part of this PR.

File: core/src/main/java/org/apache/accumulo/core/iterators/IterationInterruptedException.java (hunk 11 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/iterators/IterationInterruptedException.java:24]: Good catch. I moved it to iteratorsImpl in 892a867. Thankfully, nothing outside of the tserver code and Rfile use it.
