### PR TITLE
Validate seek range in TabletManagementIterator

### LINKED ISSUE #4496: Validate keys in tablet management iterator seek
The tablet management iterator should validate the ranges it receives in seek to ensure they work well for the whole row iterator and also ensure the range does not start or stop in the middle of a tablet.

One possible way to do this validation is to check that if keys exist in the range that columns are not set.  If the range does not meet expectations then an exception should be thrown.  The offending range should be included in a log message and/or the exception.

This would be a follow on improvement to #4457.

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #4496

### CODE REVIEW

File: server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementIteratorTest.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    Key badStartKey = new Key("row", "colf", "colq", 1234L);
+    Key badEndKey = new Key("rowEnd", "colf", "colq", 1234L);
+
+    assertThrows(IllegalStateException.class, () -> iter.seek(null, Set.of(), false));
+    assertThrows(IllegalStateException.class,
+        () -> iter.seek(new Range((Key) null, (Key) null), Set.of(), false));
+    assertThrows(IllegalStateException.class,
+        () -> iter.seek(new Range(goodStartKey, goodEndKey), Set.of(), false));
+    assertThrows(IllegalArgumentException.class,
+        () -> iter.seek(new Range(goodStartKey, badEndKey), Set.of(), false));
```
Comment (keith-turner) [inline server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementIteratorTest.java:50]: Could checks the message to make sure the IllegalArgumentException is coming from the expected place and not something like Range constructor.

```suggestion
        () -> iter.seek(new Range(goodStartKey, badEndKey), Set.of(), false)).getMessage().contains("TabletManagementIterator must be seeked");
```

**Review by keith-turner — APPROVED** [review]

File: server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementIteratorTest.java (hunk 1 above)
Comment (dlmarion) [reply server/base/src/test/java/org/apache/accumulo/server/manager/state/TabletManagementIteratorTest.java]: Interesting, I didn't realize that the `assertThrows` method actually returns the Exception. I added your suggestion to each of the tests that should fail in 6659ab3, but also wrapped them in an `assertTrue`.
