### PR TITLE
Fixes #1841 - Broken or Flaky test: ConcurrentDeleteTableIT takes 30 minutes to run

### LINKED ISSUE #1841: Broken or Flaky test: ConcurrentDeleteTableIT takes 30 minutes to run!!!
**Test name(s)**
 - ConcurrentDeleteTableIT.testConcurrentDeleteTablesOps took 587 seconds (nearly 10 minutes)
 - ConcurrentDeleteTableIT.testConcurrentFateOpsWithDelete took 1,152 seconds (nearly 20 minutes)

**Describe the failure observed**
These tests take *WAY* too long to run. There has to be a better way to get the coverage needed from these tests.

**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit): 243e5771b03281c64115a625da83a20cd586adde
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/christopher/apps/maven/current
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-4.fc32.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.13-100.fc32.x86_64", arch: "amd64", family: "unix"
```

**What have you tried already?**
```
mvn clean verify -Dtest=nosuchtest -Dit.test=ConcurrentDeleteTableIT -PskipQA -DskipTests=false -DskipITs=false
```

**Additional context**
On a Jenkins instance I run, I've seen these tests time out after 10 minutes before retrying them. I'm not sure why, though, because the test doesn't have a timeout configured. It's possible Jenkins does, though. If that's the case, it'd be weird that it wouldn't fail more often if one test takes 20 minutes to pass... it would mean that sometimes it takes less than 10 minutes to pass, which is a wide variance, even on different hardware.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Added a timeout to both of the tests in this IT because they were observed taking far too long to complete as detailed in #1841. When I run these tests they both take about 40 seconds so I added a 3 minute timeout which should be plenty of time if they are running correctly. Not too sure why these tests took so long to complete, but these timeouts should ensure they are not running incorrectly for a long period of time.

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/ConcurrentDeleteTableIT.java [hunk 1]
```diff
@@ -52,7 +52,7 @@
 
 public class ConcurrentDeleteTableIT extends AccumuloClusterHarness {
 
-  @Test
+  @Test(timeout = 3 * 60 * 1000)
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ConcurrentDeleteTableIT.java:55]: In the super class, we have a method that can be overridden called `defaultTimeoutSeconds`, which probably would work better for this. The timeout for that is scalable on the command-line with `-Dtimeout.factor=2` or similar. See `SplitIT.java` for an example.

**Review by ctubbsii — CHANGES_REQUESTED** [review]

**Comment by DomGarguilo** [comment]
For some reason I am now experiencing much longer run times for these tests. As noted earlier, they each ran in about 40 seconds. Now, with no changes, they are both running about 4.5 minutes each. Not sure why this is happening but I will add a longer timeout for now and then look deeper into what takes these tests so long.

**Comment by DomGarguilo** [comment]
I commented this on the issue page as well ([linked here](https://github.com/apache/accumulo/issues/1841#issuecomment-751815511)), but it seems that the number of splits in this test significantly impacts the duration of the tests. If we wanted these tests to be shorter, this might be a good change as long as it does not have any adverse implications if changed.

**Comment by ctubbsii** [comment]
> ... as long as it does not have any adverse implications if changed.

Right. That is what needs to be investigated.

For now, I can merge this timeout change.

**Review by ctubbsii — APPROVED** [review]

**Comment by ctubbsii** [comment]
Accidentally edited out the reference to this issue when updating the commit message during the merge. dd637c350b388e31aadad85f3616f6f0a1d07272 should reference this issue, #1847
