### PR TITLE
 Fix check for Standalone properties file. Fixes #1168 

### LINKED ISSUE #1168: Standalone IT with system property set improperly should fail
While trying to run the ITs against a standalone cluster, the system properties "-Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties"
are required but if the path is wrong to the file or there are problems with the properties file, then the framework will default to Mini, and pass.  

It would be nice if these properties are set, most importantly the property file, that we do some validation and at the very least fail fast with a clear error ascertaining the problem.

### PR DESCRIPTION
**Pull request by milleruntime**
Revert the revert for #1189 and cleanup the check to only throw error when appropriate.

### CODE REVIEW

**Comment by milleruntime** [comment]
All ITs are passing now with this fix to the change

File: test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java [hunk 1]
```diff
@@ -57,33 +57,13 @@ public static AccumuloClusterPropertyConfiguration get() {
...
-        }
-      } else {
-        log.debug("Property file ({}) is not a readable file", propertyFile);
+      Properties fileProperties = new Properties();
+      try (FileReader reader = new FileReader(f)) {
+        fileProperties.load(reader);
+        clusterTypeValue = fileProperties.getProperty(ACCUMULO_CLUSTER_TYPE_KEY);
+        clientConf = fileProperties.getProperty(ACCUMULO_CLUSTER_CLIENT_CONF_KEY);
+      } catch (IOException e) {
+        throw new RuntimeException("Could not read properties from file: " + propertyFile, e);
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java]: For future reference, there is an UncheckedIOException since Java 8 that works well for situations like this.

Comment (milleruntime) [reply test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java]: Oh yeah... I always forget about that guy.
