### PR TITLE
fixes verification of walog location in VolumeChooserIT

### LINKED ISSUE #5917: Test VolumeChooserIT.waLogsSentToConfiguredVolumes() could result in false positive
**Describe the bug**

VolumeChooserIT.waLogsSentToConfiguredVolumes() can pass w/o verifying write ahead logs were in the expected volume when [this loop](https://github.com/apache/accumulo/blob/5eb04ebce328d3441b9721d7a548cbcf71b563e1/test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java#L254)  executes zero times.  There is a variable in the method named `volumesSeens` that is never used also.  

**Expected behavior**

The test actually verifies that write ahead logs are placed on the expected volume.   

The way the test is using the metadata table to verify this is not a good approach. Write ahead logs are only temporarily in the metadata table (in older versions of Accumulo this was not the case).   The test should instead look in zookeepeer and/or HDFS to verify walogs are in the correct volume.

### PR DESCRIPTION
**Pull request by keith-turner**
fixes #5917

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java [hunk 1]
```diff
@@ -205,17 +205,6 @@ public static void verifyVolumes(AccumuloClient accumuloClient, Range tableRange
     assertEquals(26, fileCount, "Wrong number of files");
   }
 
-  public static void verifyNoVolumes(AccumuloClient accumuloClient, Range tableRange)
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java:208]: This method was unused.
