### PR TITLE
IteratorEnvironment bug fixes and improved testing

### LINKED ISSUE #5504: Extract useful parts of #4816 and apply to changes from #5490
https://github.com/apache/accumulo/pull/5490#issuecomment-2825283630

Should extract the useful bits from #4816 and merge in separately. Most importantly, want the IteratorEnvIT changes which will test the changes done here.

### PR DESCRIPTION
**Pull request by kevinrr888**
- Improved IteratorEnvIT:
	- Added means of verifying that the checks done in testEnv() actually ran
	- Added testing for more usages of IteratorEnvironment, specifically all usages of the new ClientIteratorEnvironment
	- Added more env tests in testEnv()
	- Avoid repeated strings throughout IT
	- Simplified assertions (can simply use junit assertions as assertions work outside of testing process)
- Fixed some of the bugs found with new ClientIteratorEnvironment when adding more testing
- Javadoc fixes and improvements

closes #5504

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java [hunk 1]
```diff
@@ -71,121 +92,123 @@ public void configureMiniCluster(MiniAccumuloConfigImpl cfg, Configuration hadoo
...
-      throw new RuntimeException("Test failed - isSamplingEnabled returned true, expected false");
-    }
-    if (!expectedTableId.equals(env.getTableId())) {
-      throw new RuntimeException("Test failed - Error getting Table ID");
+    assertEquals(scope, env.getIteratorScope(), "Test failed - Error getting iterator scope");
+    assertFalse(env.isSamplingEnabled(),
+        "Test failed - isSamplingEnabled returned true, expected false");
+    assertEquals(expectedTableId, env.getTableId(), "Test failed - Error getting Table ID");
+    assertNull(env.getSamplerConfiguration());
+    assertThrows(Exception.class, env::cloneWithSamplingEnabled);
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java:206]: should we configure sampling for the tables in this test somehow and verify the result of env.cloneWithSamplingEnabled? Or is this check sufficient for this test

**Review by dlmarion — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java (hunk 1 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java:206]: good question for @keith-turner

File: test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java [hunk 2]
```diff
@@ -227,43 +253,134 @@ public void testCompact(String tableName,
...
+  private String createRFile(FileSystem fs, TreeMap<Key,Value> data) throws Exception {
+    File dir = new File(System.getProperty("user.dir") + "/target/rfilescan-iterenv-test");
+    assertTrue(dir.mkdirs());
+    String filePath = dir.getAbsolutePath() + "/test.rf";
+
+    try (RFileWriter writer = RFile.newWriter().to(filePath).withFileSystem(fs).build()) {
+      writer.append(data.entrySet());
+    }
+
+    fs.deleteOnExit(new Path(dir.getAbsolutePath()));
```
Comment (DomGarguilo) [inline test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java:362]: This could be a good spot for Junits `@TempDir` potentially. Doesn't make a big difference but it'll do the setup and cleanup for us. 

You would just need to add to the top:
```java
  @TempDir
  private static File tempDir;
```
```suggestion
    File testFile = new File(tempDir, "test.rf");
    String filePath = testFile.getAbsolutePath();

    try (RFileWriter writer = RFile.newWriter().to(filePath).withFileSystem(fs).build()) {
      writer.append(data.entrySet());
    }
    
```

File: test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java (hunk 1 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java:206]: I can look into generally improving test when I look at #5500.  I was just thinking of RFileScanner when  I opened that issue, but I can look at making it more general.

File: test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java [hunk 3]
```diff
@@ -71,121 +92,123 @@ public void configureMiniCluster(MiniAccumuloConfigImpl cfg, Configuration hadoo
...
    */
-  private static void testEnv(IteratorScope scope, Map<String,String> opts,
-      IteratorEnvironment env) {
-    TableId expectedTableId = TableId.of(opts.get("expected.table.id"));
+  private static void testEnv(IteratorScope scope, Map<String,String> opts, IteratorEnvironment env,
+      boolean checkCompactionShouldThrow) {
+    String expTableIdString = opts.get(EXPECTED_TABLE_ID_OPT);
+    TableId expectedTableId = expTableIdString == null ? null : TableId.of(expTableIdString);
+
+    if (checkCompactionShouldThrow) {
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java:166]: Could use the scope instead of adding the new boolean.

```suggestion
    if (scope != majc) {
```

**Review by keith-turner — APPROVED** [review]
