### PR TITLE
Modified ScanServer to correctly handle tablet failures

### LINKED ISSUE #3144: Scan server not properly handling not finding tablet for batch scan
**Describe the bug**

While working on #3143 and running [these test](https://gist.github.com/keith-turner/f2159111b025e600a6e0abbaba1d92f3) I saw the following exception in the scan server that caused a scan to fail with a server side error.

```
2022-12-29T15:03:16,443 [tserver.ScanServer] INFO : RFFS 169171 extent not found in metadata table 1;000139510<
2022-12-29T15:03:16,443 [tserver.ScanServer] ERROR: Error starting scan
org.apache.accumulo.core.tabletserver.thrift.NotServingTabletException: null
	at org.apache.accumulo.tserver.ScanServer.reserveFilesInner(ScanServer.java:503) ~[accumulo-tserver-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.accumulo.tserver.ScanServer.reserveFiles(ScanServer.java:641) ~[accumulo-tserver-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.accumulo.tserver.ScanServer.startMultiScan(ScanServer.java:884) ~[accumulo-tserver-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:202) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.sun.proxy.$Proxy34.startMultiScan(Unknown Source) ~[?:?]
	at org.apache.accumulo.core.tabletserver.thrift.TabletScanClientService$Processor$startMultiScan.getResult(TabletScanClientService.java:855) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.accumulo.core.tabletserver.thrift.TabletScanClientService$Processor$startMultiScan.getResult(TabletScanClientService.java:831) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:54) ~[accumulo-server-base-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129) ~[accumulo-server-base-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-12-29T15:03:16,443 [thrift.ProcessFunction] ERROR: Internal error processing startMultiScan
org.apache.accumulo.core.tabletserver.thrift.NotServingTabletException: null
	at org.apache.accumulo.tserver.ScanServer.reserveFilesInner(ScanServer.java:503) ~[accumulo-tserver-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.accumulo.tserver.ScanServer.reserveFiles(ScanServer.java:641) ~[accumulo-tserver-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.accumulo.tserver.ScanServer.startMultiScan(ScanServer.java:884) ~[accumulo-tserver-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$0(TraceUtil.java:202) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.sun.proxy.$Proxy34.startMultiScan(Unknown Source) ~[?:?]
	at org.apache.accumulo.core.tabletserver.thrift.TabletScanClientService$Processor$startMultiScan.getResult(TabletScanClientService.java:855) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.accumulo.core.tabletserver.thrift.TabletScanClientService$Processor$startMultiScan.getResult(TabletScanClientService.java:831) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:147) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:54) ~[accumulo-server-base-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:492) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:129) ~[accumulo-server-base-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.thrift.server.Invocation.run(Invocation.java:18) ~[libthrift-0.17.0.jar:0.17.0]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
``` 

Looking into this, the ScanSever is not properly handling not finding a tablet in the metadata table for a batch scan.  For normal scans when a tablet is not found the thrift RPC throws a NotServingTabletException.  Batch scans process multiple tablets in a single RPC and do not throw this exception.  A batch scan RPC can process a subset of the requested tablets, so the RPC returns a list of the extents that it did not process.  The scan server does not do this, it throws the NotServingTabletException which is not declared on the startMultiscan RPC and therefore ended up looking like a server side error the the client.  This is where the [problems happens](https://github.com/apache/accumulo/blob/f7a62bf46bff438c1f77c62d6261f33fa9c0beb3/server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java#L884) in the scan server code.  For batch scans, the scan server need to return the list of failed tablets for ones it could not find.

**To Reproduce**

Run the tests mentioned earlier for a while.

### PR DESCRIPTION
**Pull request by dlmarion**
The ScanServer was throwing a NotServingTabletException in both the scan and batch scan cases when there was a failure in loading the tablet. Modified the batch scan case to return the failed tablets in the response instead of throwing the exception.

Closes #3144

### CODE REVIEW

**Comment by dlmarion** [comment]
Full IT build passed successfully

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 1]
```diff
@@ -444,16 +444,22 @@ class ScanReservation implements AutoCloseable {
...
+    ScanReservation(Map<KeyExtent,TabletMetadata> tabletsMetadata, long myReservationId,
+        Map<TKeyExtent,List<TRange>> failures) {
       this.tabletsMetadata = tabletsMetadata;
+      this.failures = failures;
       this.files = tabletsMetadata.values().stream().flatMap(tm -> tm.getFiles().stream())
           .collect(Collectors.toUnmodifiableSet());
       this.myReservationId = myReservationId;
     }
 
+    /* This constructor is called when continuing a scan */
```
Comment (DomGarguilo) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:459]: It seems helpful to have these comments about when each constructor is used. I wonder if creating new methods (maybe `startScan` or `continueScan`) which would use the respective constructor would be helpful or not. Might not make much of a difference, just an observation

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 2]
```diff
@@ -896,6 +918,10 @@ public InitialMultiScan startMultiScan(TInfo tinfo, TCredentials credentials,
           ssio, authorizations, waitForWrites, tSamplerConfig, batchTimeOut, contextArg,
           executionHints, getBatchScanTabletResolver(tablets), busyTimeout);
 
+      if (!reservation.getFailures().isEmpty()) {
+        ims.result.setFailures(reservation.getFailures());
+      }
+
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:924]: I was wondering if we need to handle the case of the delegate having already set some failures.   Digging around to answer that question I found [this code](https://github.com/apache/accumulo/blob/af6b4978d42e7a1f9102a7ec9605be51c67bb595/server/tserver/src/main/java/org/apache/accumulo/tserver/scan/LookupTask.java#L108-L113).  Looking at that I think as long the tablet resolver does not return anything that failed then it will naturally be added to the failure by delegate.startMultiScan().  I added comments elsewhere about getting the tablet resolver to not contain failures.  

```suggestion
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 3]
```diff
@@ -500,13 +510,13 @@ private Map<KeyExtent,TabletMetadata> reserveFilesInner(Collection<KeyExtent> ex
...
         LOG.info("RFFS {} extent not found in metadata table {}", myReservationId, extent);
-        throw new NotServingTabletException(extent.toThrift());
+        failures.add(extent);
       }
 
       if (!AssignmentHandler.checkTabletMetadata(extent, null, tabletMetadata, true)) {
         LOG.info("RFFS {} extent unable to load {} as AssignmentHandler returned false",
             myReservationId, extent);
-        throw new NotServingTabletException(extent.toThrift());
+        failures.add(extent);
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:519]:
```suggestion
        failures.add(extent);
        tabletsMetadata.remove(extent);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 4]
```diff
@@ -881,7 +903,7 @@ public InitialMultiScan startMultiScan(TInfo tinfo, TCredentials credentials,
       batch.put(extent, entry.getValue());
     }
 
-    try (ScanReservation reservation = reserveFiles(batch.keySet())) {
+    try (ScanReservation reservation = reserveFiles(batch)) {
 
       HashMap<KeyExtent,TabletBase> tablets = new HashMap<>();
       batch.keySet().forEach(extent -> {
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:909]: The following should be the set of non failure tablets.

```suggestion
      reservation.tabletMetadata.keySet().forEach(extent -> {
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 5]
```diff
@@ -489,7 +499,7 @@ public void close() {
   }
 
   private Map<KeyExtent,TabletMetadata> reserveFilesInner(Collection<KeyExtent> extents,
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:501]:
```suggestion
  /*
   * All extents passed in should end in either the returned map or the failures set, but no extent should be in both.
   */
  private Map<KeyExtent,TabletMetadata> reserveFilesInner(Collection<KeyExtent> extents,
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 6]
```diff
@@ -592,11 +602,12 @@ private Map<KeyExtent,TabletMetadata> reserveFilesInner(Collection<KeyExtent> ex
             getContext().getAmple().deleteScanServerFileReferences(refs);
             LOG.info("RFFS {} extent unable to load {} as metadata no longer referencing files",
                 myReservationId, extent);
-            throw new NotServingTabletException(extent.toThrift());
+            failures.add(extent);
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:605]:
```suggestion
            failures.add(extent);
            tabletsMetadata.remove(extent);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 7]
```diff
@@ -633,17 +644,24 @@ private Map<KeyExtent,TabletMetadata> reserveFilesInner(Collection<KeyExtent> ex
...
 
     long myReservationId = nextScanReservationId.incrementAndGet();
 
-    Map<KeyExtent,TabletMetadata> tabletsMetadata = reserveFilesInner(extents, myReservationId);
+    Set<KeyExtent> failedReservations = new HashSet<>();
+    Map<KeyExtent,TabletMetadata> tabletsMetadata =
+        reserveFilesInner(extents.keySet(), myReservationId, failedReservations);
     while (tabletsMetadata == null) {
-      tabletsMetadata = reserveFilesInner(extents, myReservationId);
+      tabletsMetadata = reserveFilesInner(extents.keySet(), myReservationId, failedReservations);
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:656]:
```suggestion
      failedReservations.clear();
      tabletsMetadata = reserveFilesInner(extents.keySet(), myReservationId, failedReservations);
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java [hunk 8]
```diff
@@ -633,17 +644,24 @@ private Map<KeyExtent,TabletMetadata> reserveFilesInner(Collection<KeyExtent> ex
...
     }
+    // Convert failures
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:658]: We could add a validation on the return.

```suggestion
    if(!Collections.disjoint(tabletsMetadata.keySet(), failures) || !extents.keySet().equals(Sets.union(tabletsMetadata.keySet(), failures)) {
        throw new AssertionError("bug in reserverFilesInner "+extents.keySet()+" "+tabletsMetadata.keySet()+" "+failures);
    }

    // Convert failures
```

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 1 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:459]: Do you mean create static methods (e.g. ScanReservation.startScan() and ScanReservation.continueScan()), that call a private constructor and return the ScanReservation object? I'm not sure we need that level of indirection, IMO the comments are enough.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 2 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java]: Addressed in 381dac3

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 3 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:527]: Addressed in 381dac3

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 4 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java]: Addressed in 381dac3

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 6 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:614]: Addressed in 381dac3

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 7 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:667]: Addressed in 381dac3

File: server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java (hunk 8 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/ScanServer.java:678]: Addressed in 381dac3

**Comment by dlmarion** [comment]
Full IT build passed

**Review by keith-turner — APPROVED** [review]
@dlmarion  pulled your branch down to look at it locally in an IDE.  While looking at it I added a few validations.  Below is a patch for that and I also pushed the changes to github at [this branch](https://github.com/keith-turner/accumulo/tree/3144-scan-server-failures)

Update : after posting this comment I spun up some test and found a bug.  I pushed a fix for that bug to my branch mentioned above.  The bug was the scan server was trying to modify an immutable map in failure conditions.  In the bug fix I tried to only copy the map when there was a failure.

Update 2: saw another bug when running test.  A NPE.   Pushed another bug fix to branch mentioned above and restarted test.

Update 3: saw another bug and pushed a fix for it.  One of the validations I added made an incorrect assumption. Assumed all failures would be seen in startMultiScan RPC, but since not all tablets may be processed not all failures may be seen.  So removed the validation and going to start test again.

**Comment by dlmarion** [comment]
@keith-turner - I don't see the patch you mentioned. Is this good to merge without the patch?

**Comment by ctubbsii** [comment]
This was backported to 2.1.1 in #3163
