### PR TITLE
Change shell 'config' command to display sorted output

### LINKED ISSUE #2149: Properties from 'config' command return unordered
**Describe the bug**
The `config` command inside the accumulo shell returns the properties unordered.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-SNAPSHOT. Appears to be from commit: 4ea9bf1ac916d66896eaaba329da04714a1e8cba

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. With the commit mentioned above, start-up an accumulo instance.
2. Go into the accumulo shell
3. Run the `config` command

**Expected behavior**
The properties should be returned ordered alphabetically. 

**Screenshots**
image

**Additional context**
Each new instance has a different order of properties.

### PR DESCRIPTION
**Pull request by foster33**
Fixes #2149 

Fixes the bug where the `config` command inside the accumulo shell returns the properties unordered by using `ImmutableSortedMap.copyOf`.

There is only one instance that the shell output is directly effected by this so the other TreeMaps that were replaced I left alone and did not want to import additional things if it was not needed.

If there are other spots in the commit [4ea9bf1](https://github.com/apache/accumulo/commit/4ea9bf1ac916d66896eaaba329da04714a1e8cba) that would directly benefit from the `ImmutableSortedMap.copyOf` change, I can make those changes as well.

### CODE REVIEW

**Comment by foster33** [comment]
I noticed that there were two parts in the previously linked commit, in `Admin.java` where TreeMaps were replaced in `printNameSpaceConfiguration` and `printTableConfiguration` . I am not sure where these would be printed but maybe these would benefit from a change.

**Comment by DomGarguilo** [comment]
Looks like the change from 4ea9bf1 in `TableOperationsHelperTest.check()` may benefit from being changed back to treemap since there is a comparison to a treemap.

**Comment by Manno15** [comment]
From my testing, `Admin.java` is fine as is. I tested both with and without the change and received the same results from the `dumpConfig` command.

**Comment by EdColeman** [comment]
@Manno15 - can you explain why the results would be the same?  Looking at the dump configuration command implementation there does not seem to be any sorting - could it be just an accident that they matched and with either different values or values created in a different order that they would differ?  It seems safest to assume that where a TreeMap was used there might be underlying code somewhere that was built using that assumption - unless it can be determined that is not the case.

**Comment by Manno15** [comment]
@EdColeman I figured out where my confusion came from. I should have paid closer attention, the `printTableConfiguration` checks first to make sure it is a table property. Therefore, the entire file was correct in that everything was ordered by table (the format for dump config is different than the regular config command. It follows the format `config -t accumulo.metadata -s table.split.threshold=64M`).  Everything after the `-s` wasn't in sorted order as it was in older versions. 

@foster33 So yes, both of those print functions should have the same change as the `ConfigCommand`, my mistake on not catching that earlier.

**Comment by ctubbsii** [comment]
There were a few places where #2122 changed the TreeMap to a non-sorted Map:

1. NamespaceOperationsHelper - this is only used for looping to update another data structure, and the order doesn't matter, so this is fine
2. TableOperationsHelper - same as NamespaceOperationsHelper; order doesn't matter, so this is fine
3. TableOperationsHelperTest - does matter, because the map equality assertion it is checking will succeed whether or not the map is sorted (it only matters that the maps contain the same mapping, regardless of order)
4. Admin class - this one matters for presentation; both printTableConfiguration and printNamespaceConfiguration should use the ImmutableSortedMap.copyOf, to ensure the order is preserved
5. ConfigCommand - this one matters for the shell

File: core/src/test/java/org/apache/accumulo/core/clientImpl/TableOperationsHelperTest.java [hunk 1]
```diff
@@ -267,7 +269,7 @@ void check(TableOperationsHelper t, String tablename, String[] values) throws Ex
       String[] parts = value.split("=", 2);
       expected.put(parts[0], parts[1]);
     }
-    Map<String,String> actual = Map.copyOf(t.getConfiguration(tablename));
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/clientImpl/TableOperationsHelperTest.java:270]: This one doesn't matter. Map equality doesn't depend on order, only equivalent mappings. It'd be better to avoid the use of Guava's method here.

**Review by ctubbsii — CHANGES_REQUESTED** [review]
Looks good, but the TableOperationsHelperTest change isn't necessary, and it's best to avoid Guava when possible (fewer uses of Guava means fewer potential conflicts later).

**Review by ctubbsii — APPROVED** [review]
