### PR TITLE
Modified Fate TransactionRunner to exit normally when shut down

### LINKED ISSUE #6014: Stopping manager can potentially fail fate operations
**Describe the bug**

When running `accumulo-cluster stop` when fate operations are actively running this can cause those threads to be interrupted . When the threads are interrupted fate will make the fate operation as failed in progress.

Saw this happen with a compaction fate operation that was scanning the metadata table.  When the cluster was shutdown the compaction was failed.

**Expected behavior**
No fate operations are failed when `accumulo-cluster stop` is run.

### PR DESCRIPTION
**Pull request by dlmarion**
Modified the Fate TransactionRunner threads to allow them to exit their run loop normally when an InterruptedException is raised due to Fate being shut down.

Closes #6014

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/fate/Fate.java [hunk 1]
```diff
@@ -99,10 +99,25 @@ public void run() {
...
+                // may not do the right thing with an
+                // InterruptedException.
+                if (Thread.currentThread().isInterrupted()) {
+                  throw new InterruptedException("Fate Transaction Runner thread interrupted");
+                }
               } else {
                 continue;
               }
-
+            } catch (InterruptedException e) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/Fate.java]: Could move this check down into the `catch(Exception e){` block and there can see if the exception or its cause is an interrupted exception.   Like [this function](https://github.com/apache/accumulo/blob/960bd08820d2f1477ba7241a04dd576fbd78fb20/core/src/main/java/org/apache/accumulo/core/util/ShutdownUtil.java#L39) does does for IOException.  Sometimes code will wrap an Interrupted exception w/ some kind of runtime exception.

Also, I do not know if when this catch block rethrows the exception if it will go to the next catch block, do not think it will but not sure.  If not then it will not transition to failed.  That could be another reason to move the check into the `catch (Exception e)` block.  When it is in that block it can decide if tansition to failed should be called or not.

File: core/src/main/java/org/apache/accumulo/core/fate/Fate.java [hunk 2]
```diff
@@ -99,10 +99,25 @@ public void run() {
                   store.setStatus(tid, IN_PROGRESS);
                 }
                 op = executeCall(tid, op);
+                // It's possible that a Fate operation impl
+                // may not do the right thing with an
+                // InterruptedException.
+                if (Thread.currentThread().isInterrupted()) {
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/Fate.java:123]: It does not hurt to look for this, but we may not need to.  As long as we do not call transition to failed when the thread pool is shutdown, then its ok.  Normally the process will die soon, so it does not matter if the threads do not die as soon as they could.

File: core/src/main/java/org/apache/accumulo/core/fate/Fate.java [hunk 3]
```diff
@@ -129,8 +144,28 @@ public void run() {
...
+            // If we are shutting down then Fate.shutdown was called
+            // and ExecutorService.shutdownNow was called resulting
+            // in this exception. We will exit at the top of the loop,
+            // so continue this loop iteration normally.
+            Thread.interrupted();
+          }
         } catch (Exception e) {
-          runnerLog.error("Uncaught exception in FATE runner thread.", e);
+          // ZooStore wraps InterruptedException's with a RuntimeException
+          if (!keepRunning.get() && e instanceof RuntimeException && e.getCause() != null
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/Fate.java]: If we had a method like `isInterruptedException(Exception e)` like mentioned above then could potentially simplify and collapse these two catch blocks.

File: core/src/main/java/org/apache/accumulo/core/fate/Fate.java [hunk 4]
```diff
@@ -421,6 +458,7 @@ public Exception getException(long tid) {
    * Flags that FATE threadpool to clear out and end. Does not actively stop running FATE processes.
    */
   public void shutdown(boolean wait) {
+    log.info("Shutdown called on Fate");
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/Fate.java]: Could log the wait argument.

File: core/src/main/java/org/apache/accumulo/core/fate/Fate.java [hunk 5]
```diff
@@ -421,6 +458,7 @@ public Exception getException(long tid) {
...
     keepRunning.set(false);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/Fate.java:476]:
```suggestion
    // important this is set before shutdownNow is called as the background threads will check this to see if shutdown related errors should be ignored.
    keepRunning.set(false);
```

File: test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java [hunk 6]
```diff
@@ -448,6 +448,62 @@ public void testRepoFails() throws Exception {
...
+
+    // wait for call() to be called
+    callStarted.await();
+    assertEquals(IN_PROGRESS, getTxStatus(zk, txid));
+
+    // shutdown fate
+    fate.shutdown(true);
+
+    // tell the op to exit the method
+    finishCall.countDown();
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java]: may not need to make this call because the thread was interrupted

Could change the inCall() method to set a static boolean sawInterrupt to true when an InterruptedException happens.  Then this method could wait for that to be true here.

File: test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java [hunk 7]
```diff
@@ -448,6 +448,62 @@ public void testRepoFails() throws Exception {
...
+    finishCall = new CountDownLatch(1);
+
+    long txid = fate.startTransaction();
+    assertEquals(TStatus.NEW, getTxStatus(zk, txid));
+    fate.seedTransaction("TestOperation", txid, new TestOperation(NS, TID), true, "Test Op");
+    assertEquals(TStatus.SUBMITTED, getTxStatus(zk, txid));
+
+    fate.startTransactionRunners(config, new ScheduledThreadPoolExecutor(2));
+    // Wait for the transaction runner to be scheduled.
+    UtilWaitThread.sleep(3000);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java]: Is this need w/ the call to await() below?

File: test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java [hunk 8]
```diff
@@ -190,6 +192,7 @@ public Repo<Manager> call(long tid, Manager environment) throws Exception {
   private static CountDownLatch callStarted;
   private static CountDownLatch finishCall;
   private static CountDownLatch undoLatch;
+  private static AtomicReference<Throwable> interruptedException = new AtomicReference<>();
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/fate/zookeeper/FateIT.java:195]: Could set this to null in a junit before each method to get it ready for each test.

File: core/src/main/java/org/apache/accumulo/core/fate/Fate.java [hunk 9]
```diff
@@ -261,6 +309,7 @@ public void startTransactionRunners(AccumuloConfiguration conf,
       ScheduledThreadPoolExecutor serverGeneralScheduledThreadPool) {
     final ThreadPoolExecutor pool = ThreadPools.getServerThreadPools().createExecutorService(conf,
         Property.MANAGER_FATE_THREADPOOL_SIZE, true);
+    log.debug("Starting Fate Transaction Running pool with {} threads", pool.getCorePoolSize());
```
Comment (kevinrr888) [inline core/src/main/java/org/apache/accumulo/core/fate/Fate.java]:
```suggestion
    log.debug("Starting Fate Transaction Runner pool with {} threads", pool.getCorePoolSize());
```
