### PR TITLE
Retry new Bulk import on merge. Fixes #471

### LINKED ISSUE #471: Retry when conncurrent merge happens in bulk import.
This is follow up work to #436.  Currently, the new bulk import API detects concurrent merges and throws an exception.   It would be better to retry.

### PR DESCRIPTION
**Pull request by milleruntime**

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 1]
```diff
@@ -325,14 +325,21 @@ private void finishFateOperation(long opid) throws ThriftSecurityException, TExc
...
-      return doFateOperation(FateOperation.TABLE_BULK_IMPORT2, args, Collections.emptyMap(),
-          tableName);
-    } catch (TableExistsException | NamespaceExistsException e) {
-      // should not happen
-      throw new AssertionError(e);
-    } catch (NamespaceNotFoundException ne) {
-      throw new TableNotFoundException(null, tableName, "Namespace not found", ne);
+    // It is possible a tablet merged before the tablet was locked so retry until we are
+    // either successful or another error happens
+    while (true) {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: This retry loop could be pushed down into the doFateOperation implementation, to get it closer to the RPC. That way, if you add a new enum type to TableOperationExceptionType, you can check it before it is wrapped. This also prevents the thrift types from spreading too far away from the RPC code.

Something like the following in `doFateOperation` would work:
```java
    boolean retry = false;
    do {
      try {
        // ... do fate RPC calls here
      } catch (ThriftTableOperationException e) {
        switch (e.getType()) {
          // ... existing code
          case BULK_WHILE_CONCURRENTLY_MERGING_SO_RETRY: // pick a better name for the enum
             // log msg
             retry = true;
             break;
          // ... existing code
        }
      }
    } while(retry);

**Comment by milleruntime** [comment]
Updated based on feedback but it looks like this change causes infinite retries if the load plan is bad.  I am seeing NewBulkIT.testBadLoadPlans() go forever.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 2]
```diff
@@ -348,54 +348,59 @@ String doFateOperation(FateOperation op, List<ByteBuffer> args, Map<String,Strin
...
-    } finally {
-      Tables.clearCache(context);
-      // always finish table op, even when exception
-      if (opid != null)
-        try {
-          finishFateOperation(opid);
-        } catch (Exception e) {
-          log.warn("Exception thrown while finishing fate table operation", e);
+    // keep retrying bulk import if a concurrent merge happens. all other ops throw error or return
+    while (true) {
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: This looks like it will infinitely retry on successful completion also. I think you want a `do...while(retry)` loop instead of `while(true)`.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: The do while left with nothing to return at the bottom.  I guess I could just return null since it should never reach there.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java [hunk 3]
```diff
@@ -348,54 +348,59 @@ String doFateOperation(FateOperation op, List<ByteBuffer> args, Map<String,Strin
...
+          case NAMESPACE_EXISTS:
+            throw new NamespaceExistsException(e);
+          case NAMESPACE_NOTFOUND:
+            throw new NamespaceNotFoundException(e);
+          case OFFLINE:
+            throw new TableOfflineException(Tables.getTableOfflineMsg(context,
+                Tables.getTableId(context, tableOrNamespaceName)));
+          case BULK_CONCURRENT_MERGE:
+            log.info("Concurrent merge happened. Retrying Bulk Import to " + e.tableName);
+            break;
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: I think this is the wrong place to retry.  I think the load plan needs to be recomputed.  Could throw an internal (non-API) runtime exception here and catch that exception in the bulk code.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 2 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: I was wrong about it looping on successful. I misread the code.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java (hunk 3 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: Ah yeah... good point about the plan being recomputed.  How do we handle the case where the user generates the plan?  I guess the plan will be different if we generate it, but the user plan will still be the same.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: > How do we handle the case where the user generates the plan?

Depends on the range types in the LoadPlan the user provided.  If the RangeType is TABLET, then an error needs to be thrown.  If the RangeType is FILE, then those could be recomputed.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java]: OK thanks.  I think this is a good spot to throw a custom exception though, based on this Thrift type.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/AccumuloBulkMergeException.java [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+package org.apache.accumulo.core.clientImpl;
+
+import org.apache.accumulo.core.client.AccumuloException;
+
+/**
+ * Internal class indicating a concurrent merge occurred during the new bulk import.
+ */
+public class AccumuloBulkMergeException extends AccumuloException {
+
+  public static final String Msg = "Concurrent merge happened";
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/AccumuloBulkMergeException.java]:
```suggestion
  private static final String MSG = "Concurrent merge happened";
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/AccumuloBulkMergeException.java [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+
+  public AccumuloBulkMergeException(final Throwable cause) {
+    super(Msg, cause);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/AccumuloBulkMergeException.java]:
```suggestion
    super(MSG, cause);
```

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java [hunk 6]
```diff
@@ -125,21 +126,47 @@ public void load()
...
+
+      List<ByteBuffer> args = Arrays.asList(ByteBuffer.wrap(tableId.canonical().getBytes(UTF_8)),
+          ByteBuffer.wrap(srcPath.toString().getBytes(UTF_8)),
+          ByteBuffer.wrap((setTime + "").getBytes(UTF_8)));
+      try {
+        tableOps.doBulkFateOperation(args, tableName);
+        retry = false;
+      } catch (AccumuloBulkMergeException ae) {
+        if (plan != null) {
+          checkPlanForSplits();
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: Might be a good idea to pass `ae` down, and add it as a suppressed exception later.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java [hunk 7]
```diff
@@ -125,21 +126,47 @@ public void load()
...
-    new TableOperationsImpl(context).doBulkFateOperation(args, tableName);
+  /**
+   * Check if splits were specified in plan when a concurrent merge occurred. If so, throw error
+   * back to user since retrying won't help. If not, then retry.
+   */
+  private void checkPlanForSplits() throws AccumuloException {
+    for (Destination des : plan.getDestinations()) {
+      if (des.getRangeType().equals(RangeType.TABLE)) {
+        throw new AccumuloException(
+            "The splits provided in Load Plan do not exist in " + tableName);
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: Could pass in `ae` from above code, and include it as a suppressed exception here... or even a cause.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: I was thinking it wouldn't be useful to the user but I guess it wouldn't hurt to include the AccumuloBulkMergeException

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java [hunk 8]
```diff
@@ -125,21 +126,47 @@ public void load()
...
+          ByteBuffer.wrap(srcPath.toString().getBytes(UTF_8)),
+          ByteBuffer.wrap((setTime + "").getBytes(UTF_8)));
+      try {
+        tableOps.doBulkFateOperation(args, tableName);
+        retry = false;
+      } catch (AccumuloBulkMergeException ae) {
+        if (plan != null) {
+          checkPlanForSplits();
+        }
+        log.info(ae.getMessage() + ". Retrying bulk import to " + tableName);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: Could mention why its retrying, because a concurrent merge happened.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java [hunk 9]
```diff
@@ -125,21 +126,47 @@ public void load()
...
+      List<ByteBuffer> args = Arrays.asList(ByteBuffer.wrap(tableId.canonical().getBytes(UTF_8)),
+          ByteBuffer.wrap(srcPath.toString().getBytes(UTF_8)),
+          ByteBuffer.wrap((setTime + "").getBytes(UTF_8)));
+      try {
+        tableOps.doBulkFateOperation(args, tableName);
+        retry = false;
+      } catch (AccumuloBulkMergeException ae) {
+        if (plan != null) {
+          checkPlanForSplits();
+        }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: This will retry immediately.  Could use an Accumulo Retry object to sleep between retries.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java (hunk 8 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: That is what ```ae.getMessage()``` should print.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: I missed that.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java (hunk 9 above)
Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: I added a retry similar to the one in TableOperationsImpl.locate() in cebc776 but will have to setup a cluster to test it.

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: > but will have to setup a cluster to test it.

Yeah this would be hard to test in at IT since its a concurrency issue.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java [hunk 10]
```diff
@@ -127,9 +131,13 @@ public void load()
 
     SortedMap<KeyExtent,Bulk.Files> mappings;
     TableOperationsImpl tableOps = new TableOperationsImpl(context);
+    Retry retry = Retry.builder().infiniteRetries().retryAfter(100, MILLISECONDS)
+        .incrementBy(100, MILLISECONDS).maxWait(2, SECONDS).backOffFactor(1.5)
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: I would set the max to a minute or two.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: I don't see a way to set a max total time with Retry... we either have to use ```infiniteRetries()``` or set a number of retries with ```maxRetries(long max)```

Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: I was thinking of setting `maxWait(` higher

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java]: Ah I see.  Yeah that would be better

**Comment by milleruntime** [comment]
I confirmed that the client will retry using Rwalk locally with multiple concurrent tests running.
