### PR TITLE
Use custom Transport Factory to set Transport message and frame size

### LINKED ISSUE #3731: TabletServerBatchReaderIterator gets into infinite loop
When TabletServerBatchReaderIterator gets the following exception:

org.apache.thrift.transport.TTransportException: MaxMessageSize reached
    at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator.doLookup:913
    at org.apache.accumulo.core.clientImpl.TabletServerBatchReaderIterator$QueryTask.run:401

this failed scan will be added to the failures and the processFailures routine will requeue
the scan.  Given the tserver will simply create the same results for the scan, this will happen
indefinitly.

Accumulo 2.1.2
OS CenOS 7.7
Java 11

1) a MaxMessageSize reached issue should probably not be retried indefinitly.
2) we need a way to set the thrift max message size.

### PR DESCRIPTION
**Pull request by dlmarion**
Use a custom TFramedTransport.Factory implementation so that when getTransport is called, the frame and message size are set on the underlying configuration.

Fixes #3731

### CODE REVIEW

**Comment by dlmarion** [comment]
Created as `draft` because I think a test needs to be added to confirm that the message and frame sizes are getting set. While looking at this I found several things:

1. Not all Thrift server types use the framed transport

2. According to [this](https://github.com/apache/thrift/blob/master/doc/specs/thrift-tconfiguration.md#maxframesize) all current implementations send one message in one frame, which begs the question why are we using framed transports.

3. The Accumulo servers have properties for their max message size, which falls back to the general max message size when not defined. The remaining places where Thrift connections are created are using a maxMessageSize of `Integer.MAX_VALUE`. As mentioned, the Accumulo max message properties were not setting the Thrift `maxMessageSize`, they were setting the `maxFrameSize`. The default Thrift `maxMessageSize` is 100MB, so any frame size over that will get lowered to 100MB. This change sets the Thrift maxMessageSize, I'm unsure what will happen when the client and server have different values.

4. Ideally, we should get reduce the max message size Accumulo properties to 1 and default it to a large value (2GB?).

**Comment by dlmarion** [comment]
Full IT build passed.

**Review by cshannon — APPROVED** [review]
LGTM, nice find. I hadn't looked at the Thrift code in a while and only saw references to maxFrameSize when setting in the constructor so didn't think maxMessageSize would be easily configurable but this is a great solution.

**Comment by ivakegg** [comment]
This is a great find.  Thank you @dlmarion.  I would like to point out that this only resolves half of the issue.  The other side of this issue is that the when this exception is thrown on the client side of the scan, the underlying logic will retry indefinitely leaving the process hung.  Granted that this PR will fix avoid the problem for the most part, but I worry that some other situation will cause the scan (or batch writer) to hang indefinitly.

**Comment by dlmarion** [comment]
@ivakegg - I overlooked that part of the issue in #3731, I'll look at that also.

**Comment by dlmarion** [comment]
> @ivakegg - I overlooked that part of the issue in #3731, I'll look at that also.

Looks like when it's thrown from [here](https://github.com/apache/thrift/blob/v0.17.0/lib/java/src/main/java/org/apache/thrift/transport/TEndpointTransport.java) the type is set to END_OF_FILE. aed8516 throws a subclass of IOException in this case, which is handled differently in the calling code so that it does not retry.

**Comment by ctubbsii** [comment]
I merged 2.1 into this PR's branch, just to get it up-to-date before I finish reviewing.

File: core/src/test/java/org/apache/accumulo/core/rpc/ThriftUtilTest.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+    AccumuloTFramedTransportFactory factory = new AccumuloTFramedTransportFactory(MB1);
+    TTransport framedTransport = factory.getTransport(underlyingTransport);
+    assertEquals(framedTransport.getConfiguration().getMaxFrameSize(), MB1);
+    assertEquals(framedTransport.getConfiguration().getMaxMessageSize(), MB1);
+
+    // Unable to write more than 1MB to the TByteBuffer
+    byte[] writeBuf = new byte[MB1 + 100];
+    Arrays.fill(writeBuf, (byte) 1);
+    framedTransport.write(writeBuf);
+    assertThrows(TTransportException.class, () -> framedTransport.flush());
```
Comment (ctubbsii) [inline core/src/test/java/org/apache/accumulo/core/rpc/ThriftUtilTest.java:117]: This method isn't actually testing the frame size... the exception being thrown is one about the read buffer being too small. It doesn't seem related to the frame size. So, I'm not sure this test is testing what it needs to test.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 2]
```diff
@@ -91,14 +91,16 @@ protected abstract class TestMaxFrameSize {
     @Test
     public void testMaxFrameSizeLargerThanDefault() throws Exception {
 
+      int maxSize = TConfiguration.DEFAULT_MAX_FRAME_SIZE;
+      // make sure we go even bigger than that
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:95]: I tried to modify this test to use the maxSize of the defaults (so it should end up being the 100MB value), as the basis for this test.

However, that didn't work. I couldn't get past the memory errors.

**Review by ctubbsii — APPROVED** [review]
Overall, this looks like a good set of changes. However, I could not find a good way to test any of it.

File: core/src/test/java/org/apache/accumulo/core/rpc/ThriftUtilTest.java (hunk 1 above)
Comment (dlmarion) [reply core/src/test/java/org/apache/accumulo/core/rpc/ThriftUtilTest.java:117]: I realized that my MB1, MB10, and MB100 variables were the same value due to copy/paste. I have fixed this and modified the test to confirm that the read does fail. Will push commit shortly.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java (hunk 2 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:95]: So, on the client side, `ThriftUtil.transportFactory()` is using a hardcoded size on `Integer.MAX_VALUE`. On the server side, with no other properties specified, it's using `GENERAL_MAX_MESSAGE_SIZE` which defaults to `1GB`. I modified the test to set `GENERAL_MAX_MESSAGE_SIZE` to `TConfiguration.DEFAULT_MAX_FRAME_SIZE` and changed `ourSize` to twice that. The tests fails and the following is in the tserver log:

```
2023-08-31T16:44:36,001 [server.TThreadPoolServer] DEBUG: Error processing request
org.apache.thrift.transport.TTransportException: Socket is closed by peer.
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:100) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.transport.layered.TFramedTransport.readFrame(TFramedTransport.java:132) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.transport.layered.TFramedTransport.read(TFramedTransport.java:100) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:100) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:622) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.protocol.TCompactProtocol.readMessageBegin(TCompactProtocol.java:479) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.thrift.TMultiplexedProcessor.process(TMultiplexedProcessor.java:104) ~[libthrift-0.17.0.jar:0.17.0]
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:50) ~[classes/:?]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:254) [libthrift-0.17.0.jar:0.17.0]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) [classes/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```


I'm going to push the changes with this test broken so you can see it.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:97]: Upon further testing, setting `GENERAL_MAX_MESSAGE_SIZE` is not enough. The other max message size properties have default values. All max message size properties will need to be specified by the user, likely to the same value.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:143]: IT fixed!

File: test/pom.xml [hunk 3]
```diff
@@ -206,6 +206,11 @@
       <groupId>org.junit.jupiter</groupId>
       <artifactId>junit-jupiter-engine</artifactId>
     </dependency>
+    <dependency>
+      <groupId>org.opentest4j</groupId>
+      <artifactId>opentest4j</artifactId>
+      <version>1.2.0</version>
+    </dependency>
```
Comment (ctubbsii) [inline test/pom.xml:213]: You don't need this. You can just expect AssertionError, it's parent type.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 4]
```diff
@@ -32,19 +37,20 @@
...
 
 public class ThriftMaxFrameSizeIT extends AccumuloClusterHarness {
 
   private ThriftServerType serverType;
 
-  @Override
-  protected Duration defaultTimeout() {
-    return Duration.ofMinutes(1);
-  }
-
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:44]: I still think we should have a timeout on the ITs.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 5]
```diff
@@ -32,19 +37,20 @@
...
   @Override
   public void configureMiniCluster(MiniAccumuloConfigImpl cfg, Configuration hadoopCoreSite) {
+    cfg.setNumTservers(1);
     cfg.setProperty(Property.GENERAL_RPC_SERVER_TYPE, serverType.name());
+    cfg.setProperty(Property.GENERAL_MAX_MESSAGE_SIZE,
+        Integer.toString(TConfiguration.DEFAULT_MAX_FRAME_SIZE));
+    cfg.setProperty(Property.TSERV_MAX_MESSAGE_SIZE,
+        Integer.toString(TConfiguration.DEFAULT_MAX_FRAME_SIZE));
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:53]: So, you're fundamentally altering the purpose of this test.

The purpose of this test was to make sure that we could pass messages larger than the 16MB max frame size that was the default. We are inherently relying on the fact that our default values for these on the server side are greater than this max, and we are passing messages that exceed the 16MB, to make sure that the configuration on the server-side worked as expected.

Your changes, however, make it so the server side is configured back to the default, making it indistinguishable from our server-side configuration being ignored, and verifying that the client hangs (except for SSL, which is weird), because it can *not* pass messages larger than the 16MB.

I don't think the changes to this IT are good here.

The situation I ran into when I was looking at this IT, was that I didn't just want to try to pass messages larger than 16MB... I wanted to try to pass messages larger than 100MB, to make sure that the changes in this PR correctly set the max message size when it set the max frame size. I was unable to modify the test to do that, because 100MB is huge, and I kept getting out of memory errors.

Rather than test that we can set it larger than 100MB, we can just test that we're overriding the default of 100MB to something like 20MB. We can then test that we can pass messages over 16MB, but less than 20MB, and we can verify that messages larger than 20MB won't work. But that doesn't tell us anything about whether they failed because they hit the max frame size or because they hit the max message size.

We also still might not be able to easily distinguish in the IT the reason why messages larger than 20MB won't work... it could be because of an OutOfMemoryError on the server, rather than exceeding the max message size. What I found interesting in these changes you made, was that you were basically testing that the client hung, and not that the client failed. Based on the EOFException change in TabletServerBatchReaderIterator, I had expected to see a hard failure, rather than a hang due to retries, but I guess we're hitting this max message issue in more places than that iterator and that change was a very specific change to address a related bug, rather than a general fix for retrying Thrift messages that are too big at the RPC layer.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 6]
```diff
@@ -56,50 +62,95 @@ class TestDefault extends TestMaxFrameSize {
...
     }
+
+    @Test
+    public void testDefaultServerFrameSize() throws Exception {
+      AtomicBoolean succeeded = new AtomicBoolean(false);
+      assertThrows(AssertionFailedError.class,
+          () -> assertTimeoutPreemptively(Duration.ofSeconds(30),
+              () -> testMaxFrameSizeLargerThanDefault(succeeded)));
+      assertFalse(succeeded.get());
+    }
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:73]: The succeeded boolean is only ever false when the method that sets it is interrupted... which also would throw the assertion failure. So, adding that boolean doesn't actually add more information... it's always false on the interrupt case, and it's always true on the non-interrupt case. So, it's just a proxy for whether or not we used the assertTimeoutPreemptively method. It can be removed.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 7]
```diff
@@ -56,50 +62,95 @@ class TestDefault extends TestMaxFrameSize {
...
   }
 
   @Nested
   class TestThreadedSelector extends TestMaxFrameSize {
     TestThreadedSelector() {
       serverType = ThriftServerType.THREADED_SELECTOR;
     }
+
+    @Test
+    public void testThreadedSelectorServerFrameSize() throws Exception {
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:83]: Making these separate tests in each separate `@Nested` class starts defeating the reason these are nested. Plus, all of them except the Ssl one (which I don't understand why it works) has the same implementation. So it can just stay in the base class. The Ssl one could just be made to use a different base class that doesn't have the same method.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 8]
```diff
@@ -56,50 +62,95 @@ class TestDefault extends TestMaxFrameSize {
...
+              () -> testMaxFrameSizeLargerThanDefault(succeeded)));
+      assertFalse(succeeded.get());
+    }
   }
 
   @Nested
   class TestSsl extends TestMaxFrameSize {
     TestSsl() {
-      serverType = ThriftServerType.THREADPOOL;
+      serverType = ThriftServerType.SSL;
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:127]: Well, that one was an interesting typo. We'll want to keep that fix.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 9]
```diff
@@ -56,50 +62,95 @@ class TestDefault extends TestMaxFrameSize {
...
+    }
+
+    @Test
+    public void testSslServerFrameSize() throws Exception {
+      AtomicBoolean succeeded = new AtomicBoolean(false);
+      testMaxFrameSizeLargerThanDefault(succeeded);
+      assertTrue(succeeded.get());
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:134]: I'm really not sure why this is still working. I guess Ssl transports don't care about the max message size for some reason? That's weird.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java [hunk 10]
```diff
@@ -56,50 +62,95 @@ class TestDefault extends TestMaxFrameSize {
...
       // Ingest with a value width greater than the thrift default size to verify our setting works
-      // for max frame wize
+      // for max frame size
       try (AccumuloClient accumuloClient = Accumulo.newClient().from(getClientProps()).build()) {
-        String table = getUniqueNames(1)[0];
-        ReadWriteIT.ingest(accumuloClient, 1, 1, TConfiguration.DEFAULT_MAX_FRAME_SIZE + 1, 0,
-            table);
-        ReadWriteIT.verify(accumuloClient, 1, 1, TConfiguration.DEFAULT_MAX_FRAME_SIZE + 1, 0,
-            table);
+        String table = getUniqueNames(1)[0] + serverType.name();
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java:149]: I am not sure why this was modified to add the server type name to the table name. If the `@Nested` naming is working correctly, these already have unique names per test.

**Review by ctubbsii — CHANGES_REQUESTED** [review]
So, I think the changes to the IT aren't good, for the reasons I say below. I'm going to spend a little time trying to polish it up, but I do think the non-test stuff is pretty much good.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java (hunk 9 above)
Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java]: After refactoring the test, I don't see the ssl case being an exception... though it does seem to fail with slightly different messages.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java (hunk 10 above)
Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java]: As it turns out, the naming wasn't unique. It's actually worse than that, though... minicluster reuses directories from other tests, because the test naming for nested classes are not unique enough for it to use a separate test directory. I'm not exactly sure how to fix that, as I'm not super familiar with the nested test concept, but as long as the test is passing, and they aren't being run concurrently, it's not really a big deal.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java (hunk 7 above)
Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java]: I pushed another commit that refactors this test further to address this and other issues.

File: test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java (hunk 5 above)
Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/functional/ThriftMaxFrameSizeIT.java]: My test refactoring addresses pretty much all this. The cause of the larger messages not working is still not easily distinguishable, though. But, at least there's coverage for both cases now. I did spend quite a bit of time trying to find a good configuration size and sizes of messages to send, that would make sure the test passed okay. I'm still not sure why some smaller values don't work.

File: core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java [hunk 11]
```diff
@@ -407,7 +408,8 @@ public void run() {
             failures.putAll(tsFailures);
           }
         }
-
+      } catch (EOFException e) {
+        fatalException = e;
```
[the remark this answers is not in the document]
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java:412]: Eh, this is really just one of many places where the code may not handle the error thrown from the RPC layer well. I don't think it uniquely stands out. I only noticed the MetadataLocationObtainer one because it receives the new EOFException, but then just treats it the same as other IOExceptions.

**Comment by ctubbsii** [comment]
Okay, I updated the IT to test for messages that are smaller than the configured amount (which should work), but also included the checks that @dlmarion had to verify it failed if the message was larger than the configured amount. So, we have both now. But, there are a few remaining issues:

* The ssl case does not seem to have the same failure characteristics as the other server types. In some cases, when a message is sent that is larger than what is configured, it still works. I'm not sure why. In other cases, it seemed to not work, like we'd expect, but it would fail with a different message. I had to refactor the test to ensure MiniAccumuloCluster gave it separate directories so this can be debugged further. I don't think it's critical, though. For now, I've ignored the ssl case in the IT.
* The more interesting thing is that if I reduce the configured max size to a lower amount (say, 20MB), the tests that send a smaller message (even if it is substantially smaller than 20MB) seem to fail with messages in the tserver logs saying that it received a message that was larger. I'm not sure how, since I never sent one that big, and I don't expect Accumulo to natively be sending itself large messages from another server. This one doesn't make sense. I got the IT to pass with 80MB... I haven't found the precise threshold where it stops working, though. Hopefully, having separate directories for the tests now will make it easier to troubleshoot each one separately.

**Review by ctubbsii — APPROVED** [review]

**Comment by dlmarion** [comment]
I wrote a test using what I think is the correct stack on the client side to see the number of bytes that it ends up writing for a Mutation. It's not exhibiting the symptoms described above. Test:

```
  @Test
  public void testThriftMessageSize() throws Exception {
    ByteBuffer buf = ByteBuffer.allocate(MB10);
    
    ByteBufferOutputStream bbos = new ByteBufferOutputStream(buf);
    
    TIOStreamTransport stream = new TIOStreamTransport(bbos);
    
    AccumuloTFramedTransportFactory factory = new AccumuloTFramedTransportFactory(Integer.MAX_VALUE);
    TTransport framedTransport = factory.getTransport(stream);
    assertEquals(framedTransport.getConfiguration().getMaxFrameSize(), Integer.MAX_VALUE);
    assertEquals(framedTransport.getConfiguration().getMaxMessageSize(), Integer.MAX_VALUE);
    
    TCompactProtocol protocol = new TCompactProtocol(framedTransport);
    
    Mutation m = new Mutation(new Text(FastFormat.toZeroPaddedString(0 + 0, 10, 10, "row_".getBytes(UTF_8))));
    byte[] value = new byte[MB1];
    Arrays.fill(value, (byte) 1);
    m.put(new Text("colf_colf"), new Text(FastFormat.toZeroPaddedString(0, 7, 10, "colf_".getBytes(UTF_8))),
        new ColumnVisibility(), System.currentTimeMillis(), new Value(value, true));

    TMutation tmut = m.toThrift();
    tmut.write(protocol);
    
    framedTransport.flush();
    assertEquals(MB1, buf.position());
    buf.flip();
    assertEquals(0, buf.position());
    assertEquals(MB1, buf.limit());

  }

```

**Comment by ctubbsii** [comment]
I think it's related to the issue of the max message size counter not being reset when the transport is reused for some new messages. So, you won't see it for only a single message. I'm not sure how to verify this at the moment, though.
