### PR TITLE
Fix MiniAccumuloClusterImpl.getProcesses

### LINKED ISSUE #6070: NullPointerException in MiniAccumuloClusterImpl.getProcesses()
**Describe the bug**
`MiniAccumuloClusterImpl.getProcesses()` throws `NullPointerException` when `managerProcess` is null due to missing null check, while other similar fields (`zooKeeperProcess`, `gcProcess`) have proper null checks.

**Root Cause Analysis**

The `getProcesses()` method has inconsistent null handling for process references:

```java
public Map<ServerType,Collection<ProcessReference>> getProcesses() {
    Map<ServerType,Collection<ProcessReference>> result = new HashMap<>();
    MiniAccumuloClusterControl control = getClusterControl();
    result.put(ServerType.MANAGER, references(control.managerProcess));  // BUG: No null check!
    result.put(ServerType.TABLET_SERVER,
        references(control.tabletServerProcesses.toArray(new Process[0])));
    if (control.zooKeeperProcess != null) {  // Has null check
      result.put(ServerType.ZOOKEEPER, references(control.zooKeeperProcess));
    }
    if (control.gcProcess != null) {  // Has null check
      result.put(ServerType.GARBAGE_COLLECTOR, references(control.gcProcess));
    }
    return result;
}
```

When `managerProcess` is null (e.g., before cluster starts or after manager is stopped), it gets passed to `references()` which creates a `ProcessReference`:

```java
List<ProcessReference> references(Process... procs) {
    return Stream.of(procs).map(ProcessReference::new).collect(toList());
}
```

The `ProcessReference` constructor enforces non-null:

```java
ProcessReference(Process process) {
    this.process = Objects.requireNonNull(process);  // Throws NPE if null
}
```

**Stack Trace**

```
Caused by: java.lang.NullPointerException
    at java.base/java.util.Objects.requireNonNull(Objects.java:209)
    at org.apache.accumulo.miniclusterImpl.ProcessReference.<init>(ProcessReference.java:30)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at org.apache.accumulo.miniclusterImpl.MiniAccumuloClusterImpl.references(MiniAccumuloClusterImpl.java:776)
    at org.apache.accumulo.miniclusterImpl.MiniAccumuloClusterImpl.getProcesses(MiniAccumuloClusterImpl.java:782)
```

**Proposed Fix**

Add null check for `managerProcess` consistent with handling of `zooKeeperProcess` and `gcProcess`:

```java
public Map<ServerType,Collection<ProcessReference>> getProcesses() {
    Map<ServerType,Collection<ProcessReference>> result = new HashMap<>();
    MiniAccumuloClusterControl control = getClusterControl();
    if (control.managerProcess != null) {  // ADD NULL CHECK
      result.put(ServerType.MANAGER, references(control.managerProcess));
    }
    result.put(ServerType.TABLET_SERVER,
        references(control.tabletServerProcesses.toArray(new Process[0])));
    if (control.zooKeeperProcess != null) {
      result.put(ServerType.ZOOKEEPER, references(control.zooKeeperProcess));
    }
    if (control.gcProcess != null) {
      result.put(ServerType.GARBAGE_COLLECTOR, references(control.gcProcess));
    }
    return result;
}
```
**Additional context**
Happy to send a PR for this

### PR DESCRIPTION
**Pull request by dlmarion**
Adds missing processes to the function and guards
against possible NullPointerExceptions.

Closes #6070, #6071

### CODE REVIEW

File: minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java [hunk 1]
```diff
@@ -789,7 +789,18 @@ List<ProcessReference> references(Process... procs) {
...
+    }
+    if (control.coordinatorProcess != null) {
+      result.put(ServerType.COMPACTION_COORDINATOR, references(control.coordinatorProcess));
+    }
+    result.put(ServerType.COMPACTOR,
+        references(control.compactorProcesses.toArray(new Process[0])));
+    result.put(ServerType.SCAN_SERVER,
+        references(control.scanServerProcesses.toArray(new Process[0])));
+    result.put(ServerType.TABLET_SERVER,
+        references(control.tabletServerProcesses.toArray(new Process[0])));
```
Comment (keith-turner) [inline minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java]: The next line is also putting tablet servers.

Comment (kevinrr888) [inline minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java]: Could make this more future-proof by iterating through all `ServerType`s and using a switch statement

Comment (dlmarion) [reply minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java]: Doh! Must have been a copy paste error on my part
