### PR TITLE
fixes #449 fix two bugs with WAL recovery

### LINKED ISSUE #449: Seeing more data loss when running continuous ingest with agitation.
With the fixes for #432 and #441 applied to 1.9.0-SNAPSHOT I ran conitunuous ingest for 24hrs with agitation.  I ran the agitator as follows.  

```
nohup ./tserver-agitator.pl 1:10 1:10 1 3 &> logs/tserver-agitator.log &
```

The above command sleeps 1 to 10 minutes randomly between killing tserver processes and randomly kills 1 to 3 tablets servers.  I think in the past I have run with a non random period, but not sure.   I suspect the random period may be uncovering some new bugs.

After running verify I saw the following data UNDEFINED count, which indicates data was lost.   This count is much lower than what I saw before #441 (saw ~600K).  I am going to attempt to track the cause of this down.

```
        org.apache.accumulo.test.continuous.ContinuousVerify$Counts
                REFERENCED=22559054297
                UNDEFINED=6176
                UNREFERENCED=8007075
```

### PR DESCRIPTION
**Pull request by keith-turner**
* Fix bug where tablet is unloaded, reloaded on tserver, and then tserver dies
 * Fix bug with out of order logs.  Recovery code assumed logs were passed in
   time order.  However, since 1.8.0 they have been passed in random order. Rewrote
   recovery code to handle out of order logs.  The fix was to read all logs in
   a sorted merged way.

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java [hunk 1]
```diff
@@ -0,0 +1,241 @@
...
+import java.util.Iterator;
+import java.util.List;
+import java.util.Map.Entry;
+
+import org.apache.accumulo.server.fs.VolumeManager;
+import org.apache.accumulo.tserver.logger.LogEvents;
+import org.apache.accumulo.tserver.logger.LogFileKey;
+import org.apache.accumulo.tserver.logger.LogFileValue;
+import org.apache.hadoop.fs.Path;
+import org.mortbay.log.Log;
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java]: mortbay log is probably not the Log you want

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java [hunk 2]
```diff
@@ -0,0 +1,241 @@
...
+ */
+public class RecoveryLogsIterator
+    implements Iterator<Entry<LogFileKey,LogFileValue>>, AutoCloseable {
+
+  private List<MultiReader> readers;
+  private UnmodifiableIterator<Entry<LogFileKey,LogFileValue>> iter;
+
+  private static class MultiReaderIterator implements Iterator<Entry<LogFileKey,LogFileValue>> {
+
+    private MultiReader reader;
```
Comment (milleruntime) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java]: The name MultiReader should be renamed.  Then the MultiReaderIterator as well.

Comment (milleruntime) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java]: Perhaps this Iterator could be moved into "MultiReader"

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 3]
```diff
@@ -16,132 +16,79 @@
...
-    Status compactionStatus = Status.INITIAL;
-    String tserverSession = "";
-
-    private void update(long newFinish) {
-      this.seq = this.lastStart;
-      if (newFinish != -1)
-        lastFinish = newFinish;
-    }
+  private int findMaxTabletId(KeyExtent extent, List<Path> recoveryLogs) throws IOException {
+    int tid = -1;
```
Comment (milleruntime) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Should use less abstract name than "tid".  We use this name for different things throughout the code.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 4]
```diff
@@ -151,126 +98,155 @@ private String getPathSuffix(String pathString) {
...
+    return Collections2.transform(recoveryLogs, new Function<Path,String>() {
+      @Override
+      public String apply(Path input) {
+        return input.getName();
+      }
+    });
   }
 
-  private void playbackMutations(MultiReader reader, int tid, LastStartToFinish lastStartToFinish,
+  public void recover(KeyExtent extent, List<Path> recoveryLogs, Set<String> tabletFiles,
```
Comment (milleruntime) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Personal preference to have public methods and entry points at the top of classes.  Unlike binary data, humans read from the top down :)

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 5]
```diff
@@ -151,126 +98,155 @@ private String getPathSuffix(String pathString) {
...
-    KeyExtent alternative = extent;
-    if (extent.isRootTablet()) {
-      alternative = RootTable.OLD_EXTENT;
+    long lastStart = 0;
+    long recoverySeq = 0;
+
+    try (RecoveryLogsIterator rli = new RecoveryLogsIterator(fs, recoveryLogs, COMPACTION_START,
+        tid)) {
+
+      DeduplicatingIterator ddi = new DeduplicatingIterator(rli);
```
Comment (milleruntime) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Could DeduplicatingIterator be Autoclosable as well?

Comment (milleruntime) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: If not, looks like you need to close it.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 6]
```diff
@@ -151,126 +98,155 @@ private String getPathSuffix(String pathString) {
...
+        // in the metadata table, so the compaction finished.
+        log.debug("Considering compaction start {} {} finished because file {} in metadata table",
+            tid, lastStart, getPathSuffix(lastStartFile));
+        recoverySeq = lastStart;
+      }
     }
+    return recoverySeq;
+  }
+
+  private void playbackMutations(List<Path> recoveryLogs, MutationReceiver mr, int tid,
```
Comment (milleruntime) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Nice improvement... this method now becomes a lot more clear.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java [hunk 7]
```diff
@@ -0,0 +1,241 @@
...
+/**
+ * Iterates over multiple recovery logs merging them into a single sorted stream.
+ */
+public class RecoveryLogsIterator
+    implements Iterator<Entry<LogFileKey,LogFileValue>>, AutoCloseable {
+
+  private List<MultiReader> readers;
+  private UnmodifiableIterator<Entry<LogFileKey,LogFileValue>> iter;
+
+  private static class MultiReaderIterator implements Iterator<Entry<LogFileKey,LogFileValue>> {
```
Comment (mikewalch) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java]: Default method 'remove' should be overridden

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java [hunk 8]
```diff
@@ -0,0 +1,241 @@
...
+        }
+      } catch (IOException e) {
+        throw new UncheckedIOException(e);
+      }
+
+      return entry;
+    }
+  }
+
+  static class SortCheckIterator implements Iterator<Entry<LogFileKey,LogFileValue>> {
```
Comment (mikewalch) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java]: Default method 'remove' should be overridden

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java [hunk 9]
```diff
@@ -0,0 +1,241 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.apache.accumulo.tserver.log;
+
+import static org.apache.accumulo.tserver.logger.LogEvents.OPEN;
+
+import java.io.IOException;
+import java.io.UncheckedIOException;
```
Comment (mikewalch) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java]: This is a Java 8 exception

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 10]
```diff
@@ -151,126 +98,155 @@ private String getPathSuffix(String pathString) {
     return path.getParent().getName() + "/" + path.getName();
   }
 
-  int findLastStartToFinish(MultiReader reader, int fileno, KeyExtent extent,
-      Set<String> tabletFiles, LastStartToFinish lastStartToFinish)
-      throws IOException, EmptyMapFileException, UnusedException {
+  static class DeduplicatingIterator implements Iterator<Entry<LogFileKey,LogFileValue>> {
```
Comment (mikewalch) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Default method 'remove' should be overridden

File: server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java [hunk 11]
```diff
@@ -106,12 +106,12 @@ private int findMaxTabletId(KeyExtent extent, List<Path> recoveryLogs) throws IO
         checkState(key.event == DEFINE_TABLET); // should only fail if bug elsewhere
 
         if (key.tablet.equals(extent) || key.tablet.equals(alternative)) {
-          checkState(key.tid >= 0, "Tid %s for %s is negative", key.tid, extent);
-          checkState(tabletId == -1 || key.tid >= tabletId); // should only fail if bug in
+          checkState(key.tabletId >= 0, "Tid %s for %s is negative", key.tabletId, extent);
```
Comment (ctubbsii) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java]: Could update the log messages to refer to "tabletId" instead of "Tid", too.

**Comment by keith-turner** [comment]
Using these changes, a ~24hr test of CI w/ agitation completed with no data loss.  There were 8 nodes runnning tservers and tservers were killed 279 times during the test.

```
        org.apache.accumulo.test.continuous.ContinuousVerify$Counts
                REFERENCED=24169811377
                UNREFERENCED=7532412
```
