### PR TITLE
Remove active FateTx constraint for bulk import

### LINKED ISSUE #4047: Bulk Import Flags use an indeterministic constraint
**Describe the bug**
When creating Bulk Import Flags mutation, a constraint is used to ensure the BulkImport FateTX id is found in zookeeper. 
If the FateTX is not found, the constraint is violated and the mutation is rejected. 

This does not seem like a valid use of a constraint as the mutation itself can be valid or invalid at different points in time. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.x, 3.1.x
 - OS: [e.g. CentOS 7.5] Centos 7 
 - Others:

**Expected behavior**
If a constraint is used, it should validate the data in question and not be indeterministic. 
A conditional mutation is probably a better fit for this scenario.

### PR DESCRIPTION
**Pull request by ddanielr**
Removes the active FateTx ID constraint for metadata mutations when creating bulk import file markers.

Also changes the MutationsRejectedException to return the violation type code.
closes #4047

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java [hunk 1]
```diff
@@ -59,8 +60,11 @@ public MutationsRejectedException(Instance instance, List<ConstraintViolationSum
       Map<TabletId,Set<SecurityErrorCode>> hashMap, Collection<String> serverSideErrors,
       int unknownErrors, Throwable cause) {
     super(
-        "# constraint violations : " + cvsList.size() + "  security codes: " + hashMap.toString()
-            + "  # server errors " + serverSideErrors.size() + " # exceptions " + unknownErrors,
+        "# constraint violations : "
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java:63]:
```suggestion
        "constraint violation codes : "
```

File: core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java [hunk 2]
```diff
@@ -82,9 +86,13 @@ public MutationsRejectedException(Instance instance, List<ConstraintViolationSum
   public MutationsRejectedException(AccumuloClient client, List<ConstraintViolationSummary> cvsList,
       Map<TabletId,Set<SecurityErrorCode>> hashMap, Collection<String> serverSideErrors,
       int unknownErrors, Throwable cause) {
-    super("# constraint violations : " + cvsList.size() + "  security codes: "
-        + format(hashMap, (ClientContext) client) + "  # server errors " + serverSideErrors.size()
-        + " # exceptions " + unknownErrors, cause);
+    super(
+        "# constraint violations : "
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/MutationsRejectedException.java:90]:
```suggestion
        "constraint violation codes : "
```

**Review by keith-turner — APPROVED** [review]
