### PR TITLE
Fixes #1867. Move authentication before attempting to create new Client object

### LINKED ISSUE #1867: Small bug in change user command of the shell
**Describe the bug**
I discovered a small bug while investigating other issues. Entering the wrong credentials when changing users in the shell will properly give an `AccumuloSecurityException` but visually it still shows the user being changed (i.e from root to jeff). This is just a visual glitch though, behind the scenes the user doesn't properly change and no commands can be run except for `whoami` which will return the current user still. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0
 From my testing, the 1.10 branch does not have this bug. 

**To Reproduce**
See the image below of what I did to produce the bug.  Note, when changing users, I entered the incorrect password. 
image

**Expected behavior**
User should not be visually changed when the wrong credentials are entered and the original user should still be the active user.

**Additional context**
I believe the issue is the user is authenticated after the new client is set up with the new user's credentials. The simple fix is to authenticate the new user's credentials before trying to update the client with the new user.
See: [Shell.java](https://github.com/apache/accumulo/blob/bdcab448b5c4fb44118197615fe2e231816da01c/shell/src/main/java/org/apache/accumulo/shell/Shell.java#L1188)

### PR DESCRIPTION
**Pull request by Manno15**
There are a few possible options on where we could authenticate so if anyone has feedback on a better way, let me know. 

Results after the change: 
image
The user stays as root since the wrong credentials were entered for the user 'jeff'. 

Closes #1867

### CODE REVIEW

File: shell/src/main/java/org/apache/accumulo/shell/Shell.java [hunk 1]
```diff
@@ -1181,11 +1182,14 @@ public ConsoleReader getReader() {
...
+
     if (accumuloClient != null) {
+      if (!accumuloClient.securityOperations().authenticateUser(principal, token)) {
+        throw new AccumuloSecurityException(principal, SecurityErrorCode.BAD_CREDENTIALS);
+      }
       accumuloClient.close();
     }
     accumuloClient = Accumulo.newClient().from(clientProperties).as(principal, token).build();
-    accumuloClient.securityOperations().authenticateUser(principal, token);
     context = (ClientContext) accumuloClient;
```
Comment (ctubbsii) [inline shell/src/main/java/org/apache/accumulo/shell/Shell.java:1193]: I was thinking about the case where accumuloClient is null. No authentication of the use is performed in that case. That might be okay, because that only happens on startup and there might already be an earlier failure that would prevent startup with incorrect credentials. However, I'm not sure about that without looking into it more.

An alternative implementation, that doesn't rely on assumptions about how/when this method is used is to use a local variable for the client, while it is being authenticated, and only swapping it out, if it passes authentication, as in:

```java
var newClient = Accumulo.newClient().from(clientProperties).as(principal, token).build();
newClient.securityOperations().authenticateUser(principal, token);
var oldClient = accumuloClient;
accumuloClient = newClient; // swap out old client if the new client has authenticated
context = (ClientContext) accumuloClient; // update the context with the new client
if (oldClient != null) {
  // clean up the old client
  oldClient.close();
}
```

Comment (Manno15) [reply shell/src/main/java/org/apache/accumulo/shell/Shell.java:1193]: You bring up good points. I did think about those cases when I made this change but from what I saw, this function was only called for change user and the update password command. I could be wrong on that. I will look to implementing your suggestion as I agree that being on the safe side of things is best.

Comment (Manno15) [reply shell/src/main/java/org/apache/accumulo/shell/Shell.java:1193]: I am running into a warning about an unreferenced accumulo client without calling close. Looking into it now.

File: shell/src/main/java/org/apache/accumulo/shell/Shell.java [hunk 2]
```diff
@@ -1181,12 +1182,20 @@ public ConsoleReader getReader() {
...
   public void updateUser(String principal, AuthenticationToken token)
       throws AccumuloException, AccumuloSecurityException {
-    if (accumuloClient != null) {
-      accumuloClient.close();
+    var newClient = Accumulo.newClient().from(clientProperties).as(principal, token).build();
+    try {
+      newClient.securityOperations().authenticateUser(principal, token);
+    } catch (AccumuloSecurityException e) {
+      newClient.close();
+      throw new AccumuloSecurityException(principal, SecurityErrorCode.BAD_CREDENTIALS);
```
Comment (ctubbsii) [inline shell/src/main/java/org/apache/accumulo/shell/Shell.java:1190]:
```suggestion
      // new client can't authenticate; close and discard
      newClient.close();
      throw e;
```

File: shell/src/main/java/org/apache/accumulo/shell/Shell.java (hunk 1 above)
Comment (ctubbsii) [reply shell/src/main/java/org/apache/accumulo/shell/Shell.java]: > I am running into a warning about an unreferenced accumulo client without calling close. Looking into it now.

Were you able to solve that with your more recent changes?

Comment (Manno15) [reply shell/src/main/java/org/apache/accumulo/shell/Shell.java]: Yes, the newClient.close() resolves this.

File: shell/src/main/java/org/apache/accumulo/shell/Shell.java [hunk 3]
```diff
@@ -62,6 +62,7 @@
 import org.apache.accumulo.core.clientImpl.ClientContext;
 import org.apache.accumulo.core.clientImpl.ClientInfo;
 import org.apache.accumulo.core.clientImpl.Tables;
+import org.apache.accumulo.core.clientImpl.thrift.SecurityErrorCode;
 import org.apache.accumulo.core.conf.ClientProperty;
```
Comment (ctubbsii) [inline shell/src/main/java/org/apache/accumulo/shell/Shell.java:66]:
```suggestion
import org.apache.accumulo.core.conf.ClientProperty;
```

**Comment by Manno15** [comment]
Thanks, @ctubbsii  for fixing the build issue. I pushed while running out of the office so I didn't do a fully `-Psunny` build. Is this good to merge or is there more to be done?

**Review by ctubbsii — APPROVED** [review]
LGTM
