### PR TITLE
Fixes lock check for prune exclude actions

### LINKED ISSUE #6076: Prune always removes GC lock
**Describe the bug**
The GC lock format includes additional information along with the host and port `GC_CLIENT=<HostAndPort>`
This causes the ZooZap code to always fail the hostPortPredicate check for the GC and attempt to remove the service lock on `prune` operations. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.4

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. start a running GC process
2. run ./accumulo-cluster prune --dry-run --gc
3. See the log message showing the lock will be deleted.

**Expected behavior**
The GC lock is correctly excluded

**Additional context**
This can be handled in the ZooZap code for removing the GC lock 
See #6073 for additional info.

### PR DESCRIPTION
**Pull request by ddanielr**
Correctly checks the lock format so that exclude options for the prune command work correctly.

Closes #6076

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java [hunk 1]
```diff
@@ -783,6 +784,22 @@ public static void deleteLock(ZooReaderWriter zk, ServiceLockPath path)
...
+      Predicate<HostAndPort> hostPortPredicate, Consumer<String> messageOutput, Boolean dryRun)
+      throws KeeperException, InterruptedException {
+    var lockData = ServiceLock.getLockData(zoo.getZooKeeper(), ServiceLock.path(path));
+    if (lockData != null) {
+      String lockContent = new String(lockData, UTF_8);
+      String[] parts = lockContent.split("=");
+      if (parts.length == 2 && hostPortPredicate.test(HostAndPort.fromString(parts[1]))) {
+        messageOutput.accept("Deleting " + path + " from zookeeper");
+        if (!dryRun) {
+          zoo.recursiveDelete(path, NodeMissingPolicy.SKIP);
```
Comment (ddanielr) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java:797]: The original SingletonLock code uses zapDirectory(zoo, path, ops) which just performs a recursive delete on the path after printing a log message.

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java [hunk 2]
```diff
@@ -783,6 +784,22 @@ public static void deleteLock(ZooReaderWriter zk, ServiceLockPath path)
 
   }
 
+  public static void removeGCLock(ZooReaderWriter zoo, String path,
+      Predicate<HostAndPort> hostPortPredicate, Consumer<String> messageOutput, Boolean dryRun)
+      throws KeeperException, InterruptedException {
+    var lockData = ServiceLock.getLockData(zoo.getZooKeeper(), ServiceLock.path(path));
+    if (lockData != null) {
+      String lockContent = new String(lockData, UTF_8);
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Could the ServerServices code be used here to extract the address?  Like this code

https://github.com/apache/accumulo/blob/64741921c5f5a520dc99ae5d630753585f356662/server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java#L443-L444

Comment (ddanielr) [reply core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Yes that would probably work. I'll look at making that change so we aren't going down multiple lock removal paths again

**Comment by ddanielr** [comment]
Pushing this change up for now. Going to see if ServerServices can be used to consolidate more of the lock code.

**Comment by dlmarion** [comment]
The code in main is sufficiently different. I don't think the changes here or in #6073 should be merged to main.

File: core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java [hunk 3]
```diff
@@ -821,6 +785,21 @@ public static void deleteLock(ZooReaderWriter zk, ServiceLockPath path)
 
   }
 
+  public static void removeLock(ZooReaderWriter zoo, String path,
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ServiceLock.java]: Suggest naming this `deleteLock` like the other methods. This is just a different variant.
