### PR TITLE
User compaction not retried after failure

### LINKED ISSUE #3553: User initiated compactions that throw an exception may hang
**Describe the bug**

A user initiated compactions that throw an exception may hang.

**To Reproduce**

Would like to try to recreated this with an integration test.  Maybe something like the following.

 1.  Create a an iterator that throws an IOException if file X exists in DFS
 2. Create file X
 3.  Initiate a user compaction with the above iterator configured.
 4. Sleep a bit (or devise a way to know if the iterator has run once and failed, it could create file Y when it fails and instead of sleeping wait for file Y to exist)
 5. Delete file X
 6. Wait for compaction to complete

**Expected behavior**

Compactions that throw an exception retry.

### PR DESCRIPTION
**Pull request by dlmarion**
When a user compaction failed CompactionManager.completed
was not called with a null output file to unreserve the compaction
files and the compactable was not put on the queue for recheck.

Fixes #3553

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 1]
```diff
@@ -280,6 +280,27 @@ public void testUserCompactionCancellation() throws Exception {
...
+      client.tableOperations().create(table1);
+      try (BatchWriter bw = client.createBatchWriter(table1)) {
+        for (int i = 1; i <= MAX_DATA; i++) {
+          Mutation m = new Mutation(Integer.toString(i));
+          m.put("cf", "cq", new Value());
+          bw.addMutation(m);
+          bw.flush();
+          client.tableOperations().flush(table1, null, null, true);
+        }
+      }
```
Comment (ctubbsii) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:296]: Do you need to flush the table for every mutation? Are you trying to create separate files for each mutation? If so, this could use a comment. Otherwise, this can be simplified:

```suggestion
        }
      }
      client.tableOperations().flush(table1, null, null, true);
```

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:296]: I just copied the test above and modified to add the iterator. I presume that it's flushing so frequently to create separate files for the compaction tests. Otherwise, it would likely just create one file and the compaction test would really do nothing.

Comment (ctubbsii) [reply test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:296]: In that case, this PR looks good to me, but I still think a comment that says `// create separate files` would be helpful inline. If you copied from another test, then putting it there would be nice, too.

**Comment by dlmarion** [comment]
Full IT build passed

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java (hunk 1 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java]: Comments added in fa410ed

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java [hunk 2]
```diff
@@ -1247,20 +1247,21 @@ private Optional<CompactionInfo> reserveFilesForCompaction(CompactionServiceId s
...
+      Optional<StoredTabletFile> metaFile) {
     synchronized (this) {
       Preconditions.checkState(removeJob(job));
-      if (successful) {
-        fileMgr.completed(job, jobFiles, metaFile);
-      }
+      // If the compaction failed, then metaFile will be null.
+      // This is expected and the set of files for the compaction
+      // will be released so that it can be retried.
+      fileMgr.completed(job, jobFiles, metaFile);
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java:1264]: This successful flag was an attempt to handle a special case.  The special case is that compaction can be successful and produce an empty file.  This happens when a compaction produces no data, like its iterators filter out all data.  So can not assume an empty output file means failure.

Not completely sure, but I think to handle this special case we want to keep the successful flag and pass it like `fileMgr.completed(job, jobFiles, metaFile, successful)`.  Then inside that method there is an if stmt, maybe add a check for successful to the following if stmt.

```java
 if (successful && (job.getKind() == CompactionKind.USER || job.getKind() == CompactionKind.SELECTOR)) {
        selectedCompactionCompleted(job, jobFiles, newFile);
      }
```

Could also add a precondition arg check that newFile is empty when successful is false.

CompactionIT has a test testMultiStepCompactionThatDeletesAll that may test this case, not completely sure.  With user compactions a set of files is selected and we only want to remove from the selected set when the compaction is successful.

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 3]
```diff
@@ -280,6 +283,28 @@ public void testUserCompactionCancellation() throws Exception {
...
+          bw.addMutation(m);
+          bw.flush();
+          // flush often to create multiple files to compact
+          client.tableOperations().flush(table1, null, null, true);
+        }
+      }
+      IteratorSetting setting = new IteratorSetting(50, "error", ErrorThrowingIterator.class);
+      setting.addOption(ErrorThrowingIterator.TIMES, "3");
+      client.tableOperations().attachIterator(table1, setting, EnumSet.of(IteratorScope.majc));
+      client.tableOperations().compact(table1, new CompactionConfig().setWait(true));
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:304]: Would be good to read the data in the table after.  Thing it would be good to run this test twice with an additional iterator.  Run the test with an additional iterator that filters a subset of data and after the compaction verify it was filtered.   Run the test another time with an additional iterator that filters all data and verify the scan is empty and the tablet has no files.

File: test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+import org.apache.accumulo.core.iterators.SortedKeyValueIterator;
+import org.apache.accumulo.core.iterators.WrappingIterator;
+
+public class ErrorThrowingIterator extends WrappingIterator {
+
+  public static final String TIMES = "error.throwing.iterator.times";
+
+  private static final String MESSAGE = "Exception thrown from ErrorThrowingIterator";
+  private static final RuntimeException ERROR = new RuntimeException(MESSAGE);
+  private static final AtomicInteger timesThrown = new AtomicInteger(0);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java:40]: Using this static var means this iterator will only work once in tserver.  So if two test use the iterator, the 2nd test will see the increments from the first test.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java:40]: That's correct. If I don't make this static, then the iterator continues to fail forever. Likely a new instance of the class is created when the compaction fails and the compaction is restarted. I added a comment on ErrorThrowingIterator that it must be used with a test that starts a new MAC for each test, like CompactionIT does.

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java (hunk 3 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:304]: It seems like you want to test some condition other than an error with this suggestion - the case where the compaction succeeds but there is no output? I could write a different test for this.

Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:314]: Modified CompactionIT in 8d3072d . I modified this test method to read the data after compaction and confirm the number of files. I added an additional test that completes a compaction with no resulting data and confirms that there is no file in the tablet metadata.

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java (hunk 2 above)
Comment (dlmarion) [reply server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java]: I reverted the removal of the successful parameter in 8d3072d. I added an IT that runs a compaction that produces no data and confirms that the tablet has no file.

File: test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+
+  private static int threshold = 0;
+
+  @Override
+  public void init(SortedKeyValueIterator<Key,Value> source, Map<String,String> options,
+      IteratorEnvironment env) throws IOException {
+    super.init(source, options, env);
+    threshold = Integer.parseInt(options.get(TIMES));
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java:52]: Wondering if we can add this w/o causing problems for test that working as expected.

```suggestion
    threshold = Integer.parseInt(options.get(TIMES));
    Preconditions.checkState(threshold <= timesThrown.get());
```

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java [hunk 6]
```diff
@@ -280,6 +292,64 @@ public void testUserCompactionCancellation() throws Exception {
...
+      tm = tms.iterator().next();
+      assertEquals(1, tm.getFiles().size());
+
+      ReadWriteIT.verify(client, MAX_DATA, 1, 1, 0, table1);
+
+    }
+  }
+
+  @Test
+  public void testSuccessfulCompactionNoOutput() throws Exception {
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java:326]: We already have a test `testMultiStepCompactionThatDeletesAll()` that has a compaction delete everything.  Would it be possible to have this test delete everything and have an error?  Could add the ErrorThrowingIterator to this test in addition to the AgeOffFilter.

**Review by keith-turner — COMMENTED** [review]
The changes to the code look good, just had some comments about the tests.  We should probably add the new tests to the external compaction IT test suite also.  That is one nice thing in the elasticity branch we will not have two compaction code paths to test.

**Comment by dlmarion** [comment]
I had seen a comment somewhere else that we were going to merge CompactionIT and the ExternalCompaction ITs in the elasticity branch at some point.

File: test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java (hunk 5 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java:52]: This won't work as on the initial use of this iterator, timesThrown is zero.

File: test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java (hunk 6 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java]: renamed test and added ErrorThrowingIterator. The ErrorThrowingError will throw an error 3 times, then allow the AgeOff filter to proceed, which will remove all of the data and succeed with no output.

File: test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java (hunk 5 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java:52]: oh right, what about the following

```java
Preconditions.checkState(timesThrown.get() <= threshold);
```

**Comment by keith-turner** [comment]
> I had seen a comment somewhere else that we were going to merge CompactionIT and the ExternalCompaction ITs in the elasticity branch at some point.

Yeah opened #3525 for that.  In 2.1 we have two different code paths for an iterator failing.  When a compaction iterator fails in an internal compaction it will take a different code path than one failing in an external compaction, but the behavior should be the same for both paths.  That is why I was thinking it would be good to cover both code paths in test.

File: test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java (hunk 5 above)
Comment (dlmarion) [reply test/src/main/java/org/apache/accumulo/test/functional/ErrorThrowingIterator.java:54]: see f45a9f5

**Comment by dlmarion** [comment]
> When a compaction iterator fails in an internal compaction it will take a different code path than one failing in an external compaction, but the behavior should be the same for both paths.

Ok, I knew the code paths diverged at some point, but wasn't sure where. I added the ITs - good news - they pass without further modification. commit incoming.

**Comment by ddanielr** [comment]
LGTM, 

Ran CompactionIT, ReadWriteIT, and ExternalCompaction4_IT locally and all completed without errors.

**Comment by dlmarion** [comment]
Full IT build passed too.
