### PR TITLE
Fix ErasureCodeConfigurer bug

### LINKED ISSUE #5960: ErasureCodeConfigurer encounters an error with table.file.ec=inherit
**Describe the bug**
Using the `ErasureCodeConfigurer` with a default `table.file.ec=inherit` causes an error when attempting to compact files greater than the size threshold. The compaction error states the `table.ec.policy` has not been set.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Accumulo 2.1.4

**To Reproduce**
1. Create a new table `test`.
1. Import r-files into `test` that are greater than 123M.
1. Set property `config -t test -s table.compaction.configurer=org.apache.accumulo.core.client.admin.compaction.ErasureCodeConfigurer`
1. Set property `config -t test -s table.compaction.configurer.opts.erasure.code.size.conversion=123M`
1. Run `compact -t test`.
1. Check the Accumulo monitor for compaction errors. The error states `Blank or empty value set for table.file.ec.policy`.

**Expected behavior**
A table with a `table.file.ec=inherit` will use the HDFS volume configuration when the `ErasureCodeConfigurer` evaluates an estimated size that is greater than the `erasure.code.size.conversion` threshold.

**Screenshots**
N/A

**Additional context**
The error occurs due to code in the following method when `byPassEC` is false (i.e. default value):
```java
  public Overrides override(InputParameters params) {
    Map<String,String> overs = new HashMap<>(super.override(params).getOverrides());
    if (this.byPassEC) {
      // Allow for user initiated compactions to pass an options to bypass EC.
      overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "disable");
    } else {
      long inputsSum =
          params.getInputFiles().stream().mapToLong(CompactableFile::getEstimatedSize).sum();
      if (inputsSum >= this.ecSize) {
        overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "enable");
        if (ecPolicyName != null) {
          overs.put(Property.TABLE_ERASURE_CODE_POLICY.getKey(), ecPolicyName);
        }
      } else {
        overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "disable");
      }
    }
    return new Overrides(overs);
  }
```

The `byPassEC` else block sets an override that the `table.file.ec=enable`, which potentially overrides the `inherit` value. In the `inherit` case, the table may not have an `table.file.ec.policy` defined. 

An error is raised later on when the RFileWriter sees the `table.file.ec` is enabled but a check fails because the table does not have a `table.file.ec.policy` defined (i.e. the inherit case).

```java
        switch (ecEnable) {
          case ENABLE:
            String ecPolicyName =
                options.getTableConfiguration().get(Property.TABLE_ERASURE_CODE_POLICY);
            // The default value of this property is empty string. If empty string is given to this
            // builder it will disable erasure coding. So adding an explicit check for that.
            Preconditions.checkArgument(!ecPolicyName.isBlank(), "Blank or empty value set for %s",
                Property.TABLE_ERASURE_CODE_POLICY.getKey());
            builder = builder.ecPolicyName(ecPolicyName);
            break;
```

### PR DESCRIPTION
**Pull request by kevinrr888**
Using the ErasureCodeConfigurer with a default table.file.ec=inherit caused an error when attempting to compact files greater than the size threshold. Now correctly inherits the EC from DFS when the size threshold is exceeded.

closes #5960

### CODE REVIEW

File: core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java [hunk 1]
```diff
@@ -85,9 +85,12 @@ public Overrides override(InputParameters params) {
       long inputsSum =
           params.getInputFiles().stream().mapToLong(CompactableFile::getEstimatedSize).sum();
       if (inputsSum >= this.ecSize) {
-        overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "enable");
-        if (ecPolicyName != null) {
-          overs.put(Property.TABLE_ERASURE_CODE_POLICY.getKey(), ecPolicyName);
+        if (!params.getEnvironment().getConfiguration(params.getTableId())
```
Comment (dlmarion) [inline core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java]: @kevinrr888 - I didn't notice that you were assigned #5960 , so I put up a quick fix in #5995. I'm fine with closing my PR, but I think we might need to check the table configuration for the presence of the Property.TABLE_ERASURE_CODE_POLICY. If it's not set in the table configuration and not set in the configuration for this class, then the error will still be raised I think.

File: core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java [hunk 2]
```diff
@@ -85,9 +85,12 @@ public Overrides override(InputParameters params) {
...
+            .get(Property.TABLE_ENABLE_ERASURE_CODES.getKey()).equals("inherit")) {
+          overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "enable");
+          if (ecPolicyName != null) {
+            overs.put(Property.TABLE_ERASURE_CODE_POLICY.getKey(), ecPolicyName);
+          }
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java]: If a policy was set for the plugin, then probably want to always use that. For the case where where no policy was set for the plugin, could look and see if a policy was set for the table and then set `inherit` vs `enable` based on that.

```suggestion
        var tableConfig = params.getEnvironment().getConfiguration(params.getTableId());
        if(ecPolicyName != null){
          overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "enable");
          overs.put(Property.TABLE_ERASURE_CODE_POLICY.getKey(), ecPolicyName);
        } else if(tableConfig.get(Property.TABLE_ERASURE_CODE_POLICY.getKey()) == null) { // TODO maybe check for blank string in addition to null?
          // Assume EC is configured at the DFS directory level, because no policy was set in plugin or table config
          overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "inherit");
        } else {
          // enable and use the policy set on the table
          overs.put(Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "enable");
```

File: core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java (hunk 1 above)
Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/client/admin/compaction/ErasureCodeConfigurer.java]: Addressed in 8b0a1cbc822403f38da98ced74a8ba2e6bc67427

File: test/src/main/java/org/apache/accumulo/test/compaction/ErasureCodeIT.java [hunk 3]
```diff
@@ -122,12 +123,11 @@ public void test() throws Exception {
           Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "enable");
       c.tableOperations().create(table1, new NewTableConfiguration().setProperties(options));
 
-      var options2 = Map.of(Property.TABLE_ERASURE_CODE_POLICY.getKey(), policy1,
-          Property.TABLE_ENABLE_ERASURE_CODES.getKey(), "inherit");
-      c.tableOperations().create(table2, new NewTableConfiguration().setProperties(options2));
+      // defaults to "inherit"
+      c.tableOperations().create(table2);
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/compaction/ErasureCodeIT.java:127]: Could add the following to check this test assumption.

```
assertEquals("inherit", Property.TABLE_ENABLE_ERASURE_CODES.getDefaultValue())
```

**Review by dlmarion — APPROVED** [review]
