### PR TITLE
Validate ZNode ACLs prior to upgrade, log unexpected values and fail

### LINKED ISSUE #2890: ZooKeeper nodes with incorrect ACLs found on 2.1 upgrade
**Describe the bug**

During system testing upgrades on a small cluster, the upgrade code for 2.1 to convert to the new configuration scheme was failing with ZooKeeper ACL permission denied to write transform lock node.

Not sure if this an Accumulo issue, but wanted to document that some version(s) of Accumulo might be setting incorrect ZooKeeper ACLs, It may be Accumulo, or could be an interaction with older ZooKeeper versions that were used by earlier versions.  For example, the upgrade to Accumulo 2.1 might have used a ZooKeeper from 1.9.3 (3.4.x) and then ZooKeeper was upgraded when the 2.1 upgrade failed.  The table nodes with incorrect ACLs were create prior to the 2.1 upgrade, 2.1 did not create these nodes.

The upgrade fails because ZooKeeper nodes have incorrect ACL permissions set that prevent an accumulo client from modifying nodes - the ZooKeeper lock during the conversion could not be created - failing the upgrade process.

The incorrect ACL permissions on the "locked" nodes:

```
'auth,'
: cdrwa
'world,'anyone
: r
```

The ACLs on nodes with correct ACLs:

```
'world,'anyone
: r
'digest,'accumulo:*[digest hidden]*
: cdrwa

```

There were four tables (out of 28) that had the same, incorrect ACLs.  There were not the first, nor last tables created on the cluster.  There is at least 1 wal node with the same incorrect permissions.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - 2.1-SNAPSHOT (Aug 22)
 - Others: ZooKeeper 3.5.9 (migrated from an earlier version  at some point)

**To Reproduce**
Unknown - do not know when how tables were created or the upgrade progression. Likely the upgrade was 1.9.x -> 2.0.1 -> 2.1-SNAPSHOT, but may not been done as a single sequence. And 3.4.x and 3.5.x ZooKeeper versions may be involved.

**Additional context**

To fix, used ZooKeeper DigestAuthenticationProvider to set a "super user" and then used zkCli.sh setAcl command.

Enabled ZooKeeper super user capability for the zkCli utility by adding the following to the zoo.cfg on on zk node and restart that server. Other zk processes on other hosts were left alone:

`DigestAuthenticationProvider.superDigest=accumulo:*[digest hidden]*`

The digest value can be determined using the ZooKeeper utility

``` 
java -cp ./lib/*[zookeeper jars]* org.apache.zookeeper.server.auth.DigestAuthenticationProvider accumulo:*[secret]*

or

using the zkCli, authenticating with `addauth digest accumulo:*[secret]*` and the using getAcl on a correct node - the digest value will be included in the command output.

```
To set the correct permissions, the setAcl command was of the form

```
setAcl -R /accumulo/f45e9d51-ec2d-46bf-8661-064d1157d2da/tables/y world:anyone:r,auth:accumulo:cdrwa
```

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #2890

### CODE REVIEW

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java [hunk 1]
```diff
@@ -133,6 +141,40 @@ public void upgradeZookeeper(ServerContext context) {
...
+    try {
+      ZKUtil.visitSubTreeDFS(zk, rootPath, false, (rc, path, ctx, name) -> {
+        try {
+          final Stat stat = new Stat();
+          final List<ACL> acls = zk.getACL(path, stat);
+
+          if (((path.equals(Constants.ZROOT) || path.equals(Constants.ZROOT + Constants.ZINSTANCES))
+              && !acls.equals(ZooDefs.Ids.OPEN_ACL_UNSAFE))
+              || (!ZooUtil.PRIVATE.equals(acls) && !ZooUtil.PUBLIC.equals(acls))) {
+            log.error("ZNode at {} has unexpected ACL: {}", path, acls);
```
Comment (EdColeman) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java:160]: Could strengthen this message to indicate that upgrade failed and that the permissions need to be corrected so that the reason and action required are clear.

**Review by EdColeman — COMMENTED** [review]
It may also be desirable to check all paths, keeping a list of any nodes that are incorrect and then failing if the list size is > 0 and providing the complete list.  That way they may be able to correct things once and the re-try the upgrade instead of needing to "find" each node individually.

In the case that was seen in https://github.com/apache/accumulo/issues/2890 had three table id nodes as well as some wal log entries that were incorrect,

**Comment by dlmarion** [comment]
> It may also be desirable to check all paths, keeping a list of any nodes that are incorrect and then failing if the list size is > 0 and providing the complete list. That way they may be able to correct things once and the re-try the upgrade instead of needing to "find" each node individually.

That's what should happen. It should log all of them, then throw the exception at the end after the visit method.

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java [hunk 2]
```diff
@@ -133,6 +141,40 @@ public void upgradeZookeeper(ServerContext context) {
...
+            asyncErrorOccurred.set(true);
+          } else {
+            log.info("ZNode at {} has expected ACL.", path);
```
Comment (EdColeman) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java:163]: Should this be at trace level - other than development it does not seem that I would care the path had the correct ACls

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java (hunk 1 above)
Comment (dlmarion) [reply server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java:160]: Added troubleshooting doc at https://github.com/apache/accumulo-website/pull/338. Once / if that is merged, then I will update this PR

**Review by EdColeman — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java [hunk 3]
```diff
@@ -133,6 +141,42 @@ public void upgradeZookeeper(ServerContext context) {
     createScanServerNodes(context);
   }
 
+  private static final AtomicBoolean aclErrorOccurred = new AtomicBoolean(false);
+
+  private void validateACLs(ServerContext context) {
+
```
Comment (keith-turner) [inline server/manager/src/main/java/org/apache/accumulo/manager/upgrade/Upgrader9to10.java:147]:
```suggestion

  private void validateACLs(ServerContext context) {

    final AtomicBoolean aclErrorOccurred = new AtomicBoolean(false);
```

Seems like this only used in the method.  Wondering if could be declared in the method.
