### PR TITLE
Replace logic for determining whether a Tablet is in use

### LINKED ISSUE #3907: Flaky Test: OnDemandTabletUnloaderIT.testTabletUnloader
I have seen this test succeed and fail. I added modified `TabletServer.isTabletInUse` with:

```
     t.updateRates(System.currentTimeMillis());
     if (t.ingestRate() != 0.0 && t.queryRate() != 0.0 && t.scanRate() != 0.0) {
+      // ELASTICITY_TODO: It appears these rates may never reach 0, the appear asymptotic
+      log.debug("inUse? extent: {}, ingest: {}, query: {}, scan: {}", extent, t.ingestRate(), t.queryRate(), t.scanRate());
       // tablet is ingesting or scanning
       return true;
     }
```

and found the following in the logs when the test fails:

```
2023-10-30T20:28:33,727 [tserver.TabletServer] DEBUG: inUse? extent: 2;f<, ingest: 0.05698860227954414, query: 0.05698860227954414, scan: 0.05698860227954414
2023-10-30T20:28:33,727 [tserver.TabletServer] DEBUG: inUse? extent: 2;m;f, ingest: 0.06648670265946816, query: 0.06648670265946816, scan: 0.06648670265946816
2023-10-30T20:28:33,727 [tserver.TabletServer] DEBUG: inUse? extent: 2;t;m, ingest: 0.06648670265946816, query: 0.06648670265946816, scan: 0.06648670265946816
2023-10-30T20:28:33,727 [tserver.TabletServer] DEBUG: inUse? extent: 2<;t, ingest: 0.04749050189962012, query: 0.04749050189962012, scan: 0.04749050189962012
2023-10-30T20:28:43,728 [tserver.TabletServer] DEBUG: inUse? extent: 2;f<, ingest: 7.123575284943035E-6, query: 7.123575284943035E-6, scan: 7.123575284943035E-6
2023-10-30T20:28:43,728 [tserver.TabletServer] DEBUG: inUse? extent: 2;m;f, ingest: 8.310837832433541E-6, query: 8.310837832433541E-6, scan: 8.310837832433541E-6
2023-10-30T20:28:43,728 [tserver.TabletServer] DEBUG: inUse? extent: 2;t;m, ingest: 8.310837832433541E-6, query: 8.310837832433541E-6, scan: 8.310837832433541E-6
2023-10-30T20:28:43,728 [tserver.TabletServer] DEBUG: inUse? extent: 2<;t, ingest: 5.936312737452531E-6, query: 5.936312737452531E-6, scan: 5.936312737452531E-6
2023-10-30T20:28:53,729 [tserver.TabletServer] DEBUG: inUse? extent: 2;f<, ingest: 8.904469106178817E-10, query: 8.904469106178817E-10, scan: 8.904469106178817E-10
2023-10-30T20:28:53,729 [tserver.TabletServer] DEBUG: inUse? extent: 2;m;f, ingest: 1.0388547290541954E-9, query: 1.0388547290541954E-9, scan: 1.0388547290541954E-9
2023-10-30T20:28:53,729 [tserver.TabletServer] DEBUG: inUse? extent: 2;t;m, ingest: 1.0388547290541954E-9, query: 1.0388547290541954E-9, scan: 1.0388547290541954E-9
2023-10-30T20:28:53,729 [tserver.TabletServer] DEBUG: inUse? extent: 2<;t, ingest: 7.420390921815683E-10, query: 7.420390921815683E-10, scan: 7.420390921815683E-10
2023-10-30T20:29:03,730 [tserver.TabletServer] DEBUG: inUse? extent: 2;f<, ingest: 1.1130586382723552E-13, query: 1.1130586382723552E-13, scan: 1.1130586382723552E-13
2023-10-30T20:29:03,730 [tserver.TabletServer] DEBUG: inUse? extent: 2;m;f, ingest: 1.2985684113177478E-13, query: 1.2985684113177478E-13, scan: 1.2985684113177478E-13
2023-10-30T20:29:03,730 [tserver.TabletServer] DEBUG: inUse? extent: 2;t;m, ingest: 1.2985684113177478E-13, query: 1.2985684113177478E-13, scan: 1.2985684113177478E-13
2023-10-30T20:29:03,730 [tserver.TabletServer] DEBUG: inUse? extent: 2<;t, ingest: 9.275488652269628E-14, query: 9.275488652269628E-14, scan: 9.275488652269628E-14
2023-10-30T20:29:13,730 [tserver.TabletServer] DEBUG: inUse? extent: 2;f<, ingest: 1.3913232978404478E-17, query: 1.3913232978404478E-17, scan: 1.3913232978404478E-17
2023-10-30T20:29:13,730 [tserver.TabletServer] DEBUG: inUse? extent: 2;m;f, ingest: 1.623210514147189E-17, query: 1.623210514147189E-17, scan: 1.623210514147189E-17
2023-10-30T20:29:13,730 [tserver.TabletServer] DEBUG: inUse? extent: 2;t;m, ingest: 1.623210514147189E-17, query: 1.623210514147189E-17, scan: 1.623210514147189E-17
2023-10-30T20:29:13,730 [tserver.TabletServer] DEBUG: inUse? extent: 2<;t, ingest: 1.1594360815337068E-17, query: 1.1594360815337068E-17, scan: 1.1594360815337068E-17
2023-10-30T20:29:23,731 [tserver.TabletServer] DEBUG: inUse? extent: 2;f<, ingest: 1.7391541223005643E-21, query: 1.7391541223005643E-21, scan: 1.7391541223005643E-21
2023-10-30T20:29:23,731 [tserver.TabletServer] DEBUG: inUse? extent: 2;m;f, ingest: 2.0290131426839915E-21, query: 2.0290131426839915E-21, scan: 2.0290131426839915E-21
2023-10-30T20:29:23,731 [tserver.TabletServer] DEBUG: inUse? extent: 2;t;m, ingest: 2.0290131426839915E-21, query: 2.0290131426839915E-21, scan: 2.0290131426839915E-21
2023-10-30T20:29:23,731 [tserver.TabletServer] DEBUG: inUse? extent: 2<;t, ingest: 1.4492951019171373E-21, query: 1.4492951019171373E-21, scan: 1.4492951019171373E-21
```

This test evaluates Tablets for unload every ten seconds, and every test seconds the ingest, query, and scan rates get smaller.  However, all three need to equal 0.0 for the tablet to unload. The `Rate` class has a smoothing function so that when `update` is called the metric does not swing wildly. Should we continue to increase the timeout? Or, should we have a non-zero threshold that we use for the Tablet not being in use?

### PR DESCRIPTION
**Pull request by dlmarion**
The previous logic used the ingest and scan rates and would say a Tablet was not in use when the rates were zero. However, due to a smoothing function on the Rate class, this may not happen or would take a really long time. The logic was modified to use the internal Tablet activeScans and writesInProgress variables to determine if activity was currently happening instead of using the Rate-based metrics.

Fixes #3907

### CODE REVIEW

File: server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java [hunk 1]
```diff
@@ -1597,4 +1597,12 @@ public void setLastAccessTime() {
     this.lastAccessTime = System.nanoTime();
   }
 
+  public boolean isInUse() {
```
Comment (keith-turner) [inline server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java:1600]: The activeScan set is a hashset and writesInProgress is not volatile.  To go with the rest of the tablet code, need to sync to ensure getting latest data.

```suggestion
  public synchronized boolean isInUse() {
```

**Review by keith-turner — APPROVED** [review]
