### PR TITLE
Handle FileNotFoundException during failed compaction cleanup

### LINKED ISSUE #5087: Failed compaction file cleanup error when tablet does not exist in volume
**Describe the bug**

When the manager detects a failed compaction it attempts to clean up any files the compaction may have been writing.  To do this it looks for a file w/ the compaction uuid in the tablet diretcory in all volumes.  If a tablet has never written to a volume it will not have a directory there.  When a table does not have a directory in a volume [this code fails](https://github.com/apache/accumulo/blob/3c65bef27397f8e8ae4e45615a0054ea861dd9b4/server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java#L855-L857) with a FileNotFoundException.

When the FileNotFoundException happens this causes the search through the volumes to stop.  It also causes a noisy error log message that is not useful.

**To Reproduce**

Kill a compaction on tablet in an accumulo system where the tablet does not have dirs on all volumes in the system.

**Expected behavior**

When a tablet does not have a directory in a volume the search for dead compaction files continues and logs no errors.  Could log a trace message.

### PR DESCRIPTION
**Pull request by cshannon**
Stops a directory not being found from preventing the search through the volumes from continuing

This closes #5087

### CODE REVIEW

**Review by keith-turner — APPROVED** [review]

File: server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java [hunk 1]
```diff
@@ -852,10 +852,14 @@ public boolean test(TabletMetadata tabletMetadata) {
...
-                    FileStatus[] files = fs.listStatus(new Path(volPath), (path) -> {
-                      return path.getName().endsWith(fileSuffix);
-                    });
-                    if (files.length > 0) {
+                    FileStatus[] files = null;
+                    try {
+                      files = fs.listStatus(new Path(volPath),
+                          (path) -> path.getName().endsWith(fileSuffix));
+                    } catch (FileNotFoundException e) {
+                      LOG.trace("Failed to list tablet dir {}", volPath, e);
```
Comment (dlmarion) [inline server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java:860]: Could just `continue` here?

Comment (cshannon) [reply server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/CompactionCoordinator.java:860]: You could, the result is going to be the same either way so if you want to use continue instead in the catch that's fine. There was already an if statement checking the size files.length > 0 so i just switched that to check for null.
