### PR TITLE
Fixes some createtable bugs:

### LINKED ISSUE #5976: Creating table with copy config may always add or always remove default iterators
**Describe the bug**

When creating a table in the shell using the option to copy config from another table, it may always add versioning iterators or always remove them.  There may not be a way to only use what the table has set or not set with no additional action.  This is a potential bug based on examining the code, not 100% sure if its an actual bug yet.  

**To Reproduce**

These steps will confirm if the bug exists or not.

Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Create table A
2. Remove the versioning iterator setting from table A
3. Create table B copying table A's config
4. See if table B has versioning iterators

Another test is the following.
1. Create table A
2. Create table B copying table A's config and specify the option not to create iterators
3. See if table B has versioning iterators

**Expected behavior**

There is a way to create a new table using the exact configuration of an existing table w/ no additions or removals of properties.

### PR DESCRIPTION
**Pull request by kevinrr888**
- Fixes bugs with `--copy-config` (`-cc`) and `--no-default-iterators` (`-ndi`) options of `createtable` Shell command:
	- Changes to default iterator settings on src table are now carried over to dest table using `-cc`
	- `-ndi` option did not work. Tables were still created with default iterator props. Now works as expected.
	- Results of using `-cc` and `-ndi` in conjunction were incorrect (e.g., copy config of src table (which has default iters) to dest table (specify `-ndi`) would result in a table with default iters)
	- Deprecated `-ndi` in favor of new `--no-default-table-props` (`-ndtp`) which functions the same, but better describes the functionality.
- Fixes bugs with `NewTableConfiguration`
	- `NewTableConfiguration` now considers conflicts with default iterators and iterators set (either through `attachIterator()` or `setProperties()`). Previously could set an iterator with the same priority or name as the default iterator (`VersioningIterator`).
	- Deprecated `NewTableConfiguration.withoutDefaultIterators()` in favor of new `NewTableConfiguration.withoutDefaults()` which functions the same, but better describes the functionality.
- New tests to verify expected functionality of createtable command with `-cc` and `-ndi`, creating tables with same config as another table via Java API, and `NewTableConfiguration` with iterator conflicts with default iterators

closes #5976

### CODE REVIEW

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java [hunk 1]
```diff
@@ -517,6 +517,38 @@ public void testNtcChaining() throws AccumuloException, AccumuloSecurityExceptio
     }
   }
 
+  @Test
+  public void testIteratorConflictsWithDefault() throws Exception {
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: While looking at NewTableConfiguration, noticed default iterators were not added to iteratorProps set and only that is checked for iterator conflicts. This seems like it may be a bug, but wasn't sure. This test demonstrates the potential bug.

File: shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java [hunk 2]
```diff
@@ -150,29 +152,30 @@ public int execute(final String fullCommand, final CommandLine cl, final Shell s
...
+      srcTableConfig.entrySet().stream()
+          .filter(entry -> Property.isValidTablePropertyKey(entry.getKey()))
+          .forEach(entry -> initProperties.put(entry.getKey(), entry.getValue()));
     }
 
     // if no defaults selected, remove, even if copied from configuration or properties
     if (cl.hasOption(createTableNoDefaultIters.getOpt())) {
-      Set<String> initialProps = IteratorConfigUtil.generateInitialTableProperties(true).keySet();
+      // handles if default props were copied over
+      Set<String> initialProps = IteratorConfigUtil.getInitialTableProperties().keySet();
```
Comment (kevinrr888) [inline shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java:183]: keeping same functionality for now, but this is deleting the DefaultKeySizeConstraint when no default iterators is set, not sure if this is intentional

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 3]
```diff
@@ -454,4 +456,72 @@ public void getTimeTypeTest() throws TableNotFoundException, AccumuloException,
         "specified table does not exist");
   }
 
+  @Test
+  public void testTablePropsEqual() throws Exception {
+    // Want to ensure users can somehow create a table via the Java API that has exactly
+    // the same properties of another table (including changes to default properties), similar to
+    // the copy config option of the create table Shell command. Cloning the table is expected to
+    // be one way and modifying the properties after creation is expected to be another way.
```
Comment (kevinrr888) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: Wanted to test the Java API equivalent to --copy-config but doesn't seem like there is one. NewTableConfiguration doesn't appear to have any such functionality (closest is setProperties() but that isn't quite the same), and no TableOperation to create the table with same config as another table. Best way I could think of accomplishing --copy-config via the Java API is modifying the props after the table is created or clone (but obviously clone does more than just copy the config).

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java [hunk 4]
```diff
@@ -168,7 +168,7 @@ public Map<String,String> getProperties() {
     Map<String,String> propertyMap = new HashMap<>();
 
     if (limitVersion) {
-      propertyMap.putAll(IteratorConfigUtil.generateInitialTableProperties(limitVersion));
+      propertyMap.putAll(IteratorConfigUtil.getInitialTableProperties());
     }
```
Comment (kevinrr888) [inline core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: Currently also adds DefaultKeySizeConstraint, so if `withoutDefaultIterators()` is specified, DefaultKeySizeConstraint won't be added to config. Is this intended?

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 5]
```diff
@@ -454,4 +456,72 @@ public void getTimeTypeTest() throws TableNotFoundException, AccumuloException,
...
+
+      client.tableOperations().create(table2);
+      client.tableOperations().modifyProperties(table2, props -> {
+        try {
+          props.clear();
+          props.putAll(client.tableOperations().getTableProperties(table1));
+        } catch (AccumuloException | TableNotFoundException e) {
+          throw new RuntimeException(e);
+        }
+      });
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]:
```suggestion
    // create table using exact properties from table1 w/o adding the default iterators.
     client.tableOperations().create(table2, new NewTableConfiguration().withoutDefaultIterators().setProperties(client.tableOperations().getTableProperties(table1)));
```

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 3 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: Its super confusing, but there may be a way. I made another comment w/ a suggestion on how to do this.    Maybe we could improve this API in 4.0 to make it less confusing.

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java (hunk 1 above)
Comment (keith-turner) [reply test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: It would be good to make the code in NewTableConfiguration that checks if inputs are disjoint detect this case and fail.  That may make code that was previously working fail, but there is a good chance that code was buggy.

File: shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java [hunk 6]
```diff
@@ -150,29 +152,30 @@ public int execute(final String fullCommand, final CommandLine cl, final Shell s
...
       initialProps.forEach(initProperties::remove);
```
Comment (keith-turner) [inline shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java:184]: This behavior is so confusing that I think we would be better off throwing an exception here.  I think the intent of this property is not to add default iterators to a new table, but removing them makes this command  non deterministic.  Would be good to be able to always predict what the create table command will do for a given set of options.  Seems to me throwing an exception would be better than being unpredictable.  Also throwing an exception does not silently change the behavior of the command in the background which is really hard to detect for any automation using this command.


```suggestion
      if(!Collections.disjoint(initialProps, initProperties.keySet())){
        throw //something
      }
```

File: shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java [hunk 7]
```diff
@@ -185,6 +188,18 @@ public int execute(final String fullCommand, final CommandLine cl, final Shell s
...
+    // Need to remove these after table creation.
+    if (cl.hasOption(createTableOptCopyConfig.getOpt())) {
+      var defaultProps = IteratorConfigUtil.getInitialTableProperties().keySet();
+      Preconditions.checkState(srcTableConfig != null);
+      for (var defaultProp : defaultProps) {
+        if (srcTableConfig.get(defaultProp) == null) {
+          shellState.getAccumuloClient().tableOperations().removeProperty(tableName, defaultProp);
+        }
+      }
+    }
```
Comment (keith-turner) [inline shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java]: Could remove this

```suggestion
```

and before creating the table add the following..

```java
   // TODO maybe do this for the createTableOptInitPropFile option also?
    if (cl.hasOption(createTableOptCopyConfig.getOpt())) {
      // copy table config exactly w/o setting any default table props
      ntc = ntc.withoutDefaultIterators();
    }
```

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java (hunk 4 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: This was probably not intended.  

A good way to handle this would be to deprecate the `withoutDefaultIterators()` method and leave its current confusing behavior and add a new `withoutDefaults()` method to replace it that has much nicer behavior.  This avoids silently changing behavior behind an API and also it makes the method names align better with actual behavior.  Not sure about doing this in a bug fix release, but it may be the best way to fix this bug w/o making things worse.

**Review by keith-turner — COMMENTED** [review]
This could be a follow on issue, looking at this PR I think we should impose the following restrictions on the create table shell command options.

 * the `--copy-config` option is mutually exclusive with any other option that sets per table props (like `--propFile`, --prop`, `--iter`, etc)
 * the `--propFile` option is mutually exclusive with any other option that sets per table props.

Thinking this would be good for the same reason mentioned on another comment, that the behavior is non-deterministic.  It depends on the order that the shell command applies these options to a shared map and that order could changes.  This leads to the possibility that the command could behave differently for the same input and options over time which makes it hard to reason about.  Otherwise we should document the order that options are applied and test it, but I do not think that is worthwhile.

Going for the behavior that `--copy-config` or `--propFile` exactly specify the tables initial config w/ no surprises or caveats.

**Comment by keith-turner** [comment]
The two options `--copy-config` and `--exclude-parent-properties` are so confusing we should probably deprecate both and introduce a new `--copy-properties` option that has the same behavior as specifying both of those options.

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java (hunk 4 above)
Comment (keith-turner) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: If we deprecate API methods, may want to deprecate the shells `-ndi` option and replace with a `--no-default-table-props` option or something like that, to get the behavior and the option names to align.

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java (hunk 1 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: Addressed in 797e39102700e1d187635fdd7d0fe0c0a8d1c721

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 3 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: Added suggestion in 797e39102700e1d187635fdd7d0fe0c0a8d1c721. Leaving unresolved for now in case we want to open 4.0 issue for new API

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java (hunk 4 above)
Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: I deprecated `withoutDefaultIterators()` and `-ndi` option and added `withoutDefaults()` and `-ndtp` in 797e39102700e1d187635fdd7d0fe0c0a8d1c721 and 18914a58d1206bed87cc2d6e8e299d629607a3c2 (same functionality as before, but more appropriate name)

Also considered deprecating `withoutDefaultIterators()` and:
* adding both `withoutDefaults()` and `withoutDefaultIters()` but thought that would probably add too much bloat (probably fine if there's desire for it)
* adding only `withoutDefaultIters()`, but like you said we probably don't want to change functionality

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 5 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: Added in 797e39102700e1d187635fdd7d0fe0c0a8d1c721

File: shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java (hunk 7 above)
Comment (kevinrr888) [reply shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java]: Yeah good point, changed in 797e39102700e1d187635fdd7d0fe0c0a8d1c721

File: shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java (hunk 6 above)
Comment (kevinrr888) [reply shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java:184]: I agree. This code was broken before these changes, and using -ndi and -cc in conjunction is a bit contradictory and confusing anyways.

**Comment by kevinrr888** [comment]
I believe all the remaining comments pertain to enforcing mutual exclusion for some of the createtable ops and also https://github.com/apache/accumulo/pull/5990#discussion_r2566636847. These should probably be done in a separate issue/PR, so I think this PR is good for re-review

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java [hunk 8]
```diff
@@ -167,7 +188,8 @@ public NewTableConfiguration setProperties(Map<String,String> props) {
   public Map<String,String> getProperties() {
     Map<String,String> propertyMap = new HashMap<>();
 
-    if (limitVersion) {
+    if (includeDefaults) {
+      checkIteratorConflictsWithDefaults();
```
Comment (keith-turner) [inline core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: This code does not check the for conflicts with the default constraints.  It also does not check for conflicts with iterators set via properties instead of the attachIter method.  Could do something like the following after everything is added to `propertyMap` and look for default props with different values.  We could ignore cases where the user set the default prop w/ the same value (that may avoid errors w/ some current cases of copying existing config).

```java
    if (includeDefaults) {
      var defaults = IteratorConfigUtil.getInitialTableProperties();
      defaults.forEach((dk,dv)->{
        var value = propertyMap.get(dk);
        if(value != null && !value.equals(dv)) {
          throw new IllegalStateException("For property "+dk+" value conflicts with default : "+dv+" != "+value);
        }
      });
      propertyMap.putAll(defaults);
    }
```

One problem with this vs the current code in this PR is that its checks for the iterators are not as strong.

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java [hunk 9]
```diff
@@ -454,4 +456,65 @@ public void getTimeTypeTest() throws TableNotFoundException, AccumuloException,
...
+          .setProperties(client.tableOperations().getTableProperties(table1)));
+      // another option is cloning the table
+      client.tableOperations().clone(table1, table3, CloneConfiguration.empty());
+
+      Wait.waitFor(() -> {
+        var table1Props = client.tableOperations().getTableProperties(table1);
+        var table2Props = client.tableOperations().getTableProperties(table2);
+        var table3Props = client.tableOperations().getTableProperties(table2);
+        return table1Props.entrySet().equals(table2Props.entrySet())
+            && table1Props.entrySet().equals(table3Props.entrySet());
```
Comment (DomGarguilo) [inline test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]:
```suggestion
        var table3Props = client.tableOperations().getTableProperties(table3);
        return table1Props.equals(table2Props) && table1Props.equals(table3Props);
```
I think there was a copy paste bug from the line above. It was using `table2` instead of `table3`. Also I'm pretty sure we can just to `.equals()` on the map instead of `.entrySet().equals()` for the same effect and simpler code.

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java [hunk 10]
```diff
@@ -312,6 +347,7 @@ public NewTableConfiguration attachIterator(IteratorSetting setting,
       // verify that the iteratorProps assigned and the properties do not share any keys.
       checkDisjoint(properties, iteratorProps, "iterator");
     }
+    iteratorSettings.put(setting, scopes);
```
Comment (DomGarguilo) [inline core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: I think there may be a bug here. I think this will just replace any existing scopes in the map that have the same setting as key when attachIterator is called multiple times with a matching key. I think we need to merge the incoming `scopes` with the existing scopes so that when things are checked in checkIteratorConflictsWithDefaults(), it has everything instead of just the last one set to check against.

Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: I think you're right, I didn't consider that use case.
Either way, `iteratorSettings` was removed in db8d7f5221cddd5bf04952f4e578994e90b9f3ec so isn't a problem anymore

File: test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java (hunk 9 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java]: good spot on the typo. Fixed in db8d7f5221cddd5bf04952f4e578994e90b9f3ec. Also removed the entrySet calls, not sure why I had those

File: core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java (hunk 8 above)
Comment (kevinrr888) [reply core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java]: Added in db8d7f5221cddd5bf04952f4e578994e90b9f3ec

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java [hunk 11]
```diff
@@ -517,6 +518,23 @@ public void testNtcChaining() throws AccumuloException, AccumuloSecurityExceptio
...
+    String[] tableNames = getUniqueNames(2);
+    String table1 = tableNames[0];
+    String table2 = tableNames[1];
+    try (AccumuloClient client = Accumulo.newClient().from(getClientProps()).build()) {
+      // add an iterator with same priority as the default iterator
+      var iterator1 = new IteratorSetting(20, "foo", "foo.bar");
+      assertThrows(IllegalArgumentException.class, () -> client.tableOperations().create(table1,
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: Not sure if this test will still pass w/ the changes that checks for exact props w/ different values. If not, may need to relax the test to use exact props or make the check more strict.

**Review by keith-turner — APPROVED** [review]

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java (hunk 11 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: I opted to make the checks stricter. Added in 10e10795c3610f8a6d1a787fd0db8dd0cb29bd8d

Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: @keith-turner could you take one last look at new commit? Then I'll merge this in and create the follow on tickets

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java [hunk 12]
```diff
@@ -519,19 +521,66 @@ public void testNtcChaining() throws AccumuloException, AccumuloSecurityExceptio
...
+      props.clear();
+      // add an iterator with same name as the default iterator
+      for (IteratorScope iterScope : IteratorScope.values()) {
+        props.put(Property.TABLE_ITERATOR_PREFIX + iterScope.name() + ".vers", "10,foo.bar");
+      }
+      exception = assertThrows(IllegalStateException.class, () -> client.tableOperations()
+          .create(table, new NewTableConfiguration().setProperties(props)));
+      assertTrue(exception.getMessage().contains("iterator name conflict"));
+      props.clear();
+      // try to attach the exact default iterators
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: Wondering if this case should create the table w/o failing.   The impl could create a tmp map that removes exact matches of the defaults for its check.  Seems like it would be ok to do that, wondering if there are downsides I am not considering.

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java [hunk 13]
```diff
@@ -519,19 +521,66 @@ public void testNtcChaining() throws AccumuloException, AccumuloSecurityExceptio
...
+      exception = assertThrows(IllegalStateException.class,
+          () -> client.tableOperations().create(table, new NewTableConfiguration()
+              .setProperties(IteratorConfigUtil.getInitialTableIterators())));
+      assertTrue(exception.getMessage().contains("iterator name conflict")
+          || exception.getMessage().contains("iterator priority conflict"));
+
+      /*
+       * conflicts with default, non-iterator properties
+       */
+      props.put(Property.TABLE_CONSTRAINT_PREFIX + "1", "foo");
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java:585]: Could have another test case that passes the constraint w/ the default value and that should not fail.

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java (hunk 12 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java]: That seems good to me as the final properties map will be the same regardless.
addressed in b343417af8f133f92a73d3fdee07e2af9be2cae8

File: test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java (hunk 13 above)
Comment (kevinrr888) [reply test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java:585]: added in b343417af8f133f92a73d3fdee07e2af9be2cae8

**Review by keith-turner — APPROVED** [review]
