### PR TITLE
fixes clearing suspension for offline tables

### LINKED ISSUE #3314: Suspension may not be properly cleared for tablets in some cases
**Describe the bug**
While working on #3284 I noticed this code :

https://github.com/apache/accumulo/blob/15c9f55280f4ce28a80b800f1e05128f33c85db3/server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataStateStore.java#L140-L151

Tracing back what calls this method, AFAICT its only passed TabletLocationState objects with a non-null suspend. If my analysis is correct then this method ignores all of its input.

Seems like the code should be :

```java
      for (TabletLocationState tls : tablets) {
        if (tls.suspend != null) {
          tabletsMutator.mutateTablet(tls.extent).deleteSuspension().mutate();

        }
     }
```

This need a bit more investigation.  Took a quick look at 1.10 code and it seems to be the same there.

**Expected behavior**
The suspension is properly cleared.

### PR DESCRIPTION
**Pull request by keith-turner**
There was code in the manager that seemed to have the intent of clearing suspension markers in tablets for an offline table.  This code was not working or tested.  This commit fixes this code and adds a tests that validates that suspension markers are removed when a table is taken offline.

fixes #3314

### CODE REVIEW

**Comment by EdColeman** [comment]
With these changes.  What is the suspend state when:

1. A tablet server is stopped.
2. A tablet server crashes (killed)

In both of those cases when the tablet(s) are reloaded, is the suspend state still set and subject to the timeout?

**Comment by keith-turner** [comment]
> In both of those cases when the tablet(s) are reloaded, is the suspend state still set and subject to the timeout?

Yeah I think so and the existing test was checking for this.  I added the following line to the test after tservers were killed to be sure that tablets were in the suspended state.

```
assertTrue(ds.suspendedCount > 0);
```

File: test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java [hunk 1]
```diff
@@ -300,27 +255,43 @@ private void suspensionTestBody(TServerKiller serverStopper) throws Exception {
...
+
+      if (action == AfterSuspendAction.OFFLINE) {
+        client.tableOperations().offline(tableName, true);
+
+        while (ds.suspendedCount > 0) {
+          Thread.sleep(1000);
+          ds = TabletLocations.retrieve(ctx, tableName);
+          log.info("Waiting for suspended {}", ds.suspended);
+        }
+      } else if (action == AfterSuspendAction.RESUME) {
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java:269]: The code in this else block was not changed except for indentation.

File: test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java [hunk 2]
```diff
@@ -330,6 +301,95 @@ void eliminateTabletServers(ClientContext ctx, TabletLocations locs, int count)
         throws Exception;
   }
 
+  private class ShutdownTserverKiller implements TServerKiller {
+
+    @Override
+    public void eliminateTabletServers(ClientContext ctx, TabletLocations locs, int count)
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java:307]: The code in the method was copied w/o change from an existing lambda in the test.  This copy was done for reuse.

File: test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java [hunk 3]
```diff
@@ -330,6 +301,95 @@ void eliminateTabletServers(ClientContext ctx, TabletLocations locs, int count)
...
+      }
+      throw new IllegalStateException("Tablet servers didn't die!");
+
+    }
+  }
+
+  private class CrashTserverKiller implements TServerKiller {
+
+    @Override
+    public void eliminateTabletServers(ClientContext ctx, TabletLocations locs, int count)
```
Comment (keith-turner) [inline test/src/main/java/org/apache/accumulo/test/manager/SuspendedTabletsIT.java:374]: The code in this methos was also copied w/o change from an existing lambda in the test

**Review by EdColeman — APPROVED** [review]
The changes look okay.  As long as this preserves the behavior that the suspend duration can be used for rolling restarts with tservers either stopped by command or by a kill (crash).  

Mainly, with the suspend delay set to some value and when a tserver is stopped by command or is killed, the tablets assigned will not be reassigned until the expiration of the suspend duration.  When a tserver with suspended tablets comes back online, the suspended tablets are reassigned to that same server.

As long as this holds, I approve then changes.

**Comment by keith-turner** [comment]
> As long as this preserves the behavior that the suspend duration can be used for rolling restarts with tservers either stopped by command or by a kill (crash).

I did not change that behavior in this PR.
