### PR TITLE
Fix NPE in BCFile. Fixes #1021

### LINKED ISSUE #1021: Tablet server failed to load Root tablet during 2.0 upgrade
Found this while trying to upgrade from `1.9.3-SNAPSHOT` to `2.0.0-SNAPSHOT`

```
2019-03-08 15:25:19,166 [tserver.TabletServer] INFO : Root tablet loaded: +r<<
2019-03-08 15:25:19,342 [tserver.FileManager] ERROR: Failed to open file hdfs://localhost:8020/accumulo/tables/+r/root_tablet/A000001b.rf null
2019-03-08 15:25:19,347 [scan.LookupTask] WARN : lookup failed for tablet +r<<
java.io.IOException: Failed to open hdfs://localhost:8020/accumulo/tables/+r/root_tablet/A000001b.rf
        at org.apache.accumulo.tserver.FileManager.reserveReaders(FileManager.java:361)
        at org.apache.accumulo.tserver.FileManager.access$600(FileManager.java:63)
        at org.apache.accumulo.tserver.FileManager$ScanFileManager.openFiles(FileManager.java:526)
        at org.apache.accumulo.tserver.FileManager$ScanFileManager.openFileRefs(FileManager.java:511)
        at org.apache.accumulo.tserver.FileManager$ScanFileManager.openFiles(FileManager.java:536)
        at org.apache.accumulo.tserver.tablet.ScanDataSource.createIterator(ScanDataSource.java:182)
        at org.apache.accumulo.tserver.tablet.ScanDataSource.iterator(ScanDataSource.java:140)
        at org.apache.accumulo.core.iterators.system.SourceSwitchingIterator.seek(SourceSwitchingIterator.java:226)
        at org.apache.accumulo.tserver.tablet.Tablet.lookup(Tablet.java:603)
        at org.apache.accumulo.tserver.tablet.Tablet.lookup(Tablet.java:757)
        at org.apache.accumulo.tserver.scan.LookupTask.run(LookupTask.java:116)
        at org.apache.accumulo.tserver.session.ScanSession$ScanMeasurer.run(ScanSession.java:54)
        at org.apache.accumulo.tserver.TabletServerResourceManager.executeReadAhead(TabletServerResourceManager.java:936)
        at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler.continueMultiScan(TabletServer.java:842)
        at org.apache.accumulo.tserver.TabletServer$ThriftClientHandler.startMultiScan(TabletServer.java:812)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$8(TraceUtil.java:235)
        at com.sun.proxy.$Proxy21.startMultiScan(Unknown Source)
        at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$startMultiScan.getResult(TabletClientService.java:2757)
        at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$startMultiScan.getResult(TabletClientService.java:2736)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:65)
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
        at org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:112)
        at org.apache.thrift.server.Invocation.run(Invocation.java:18)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at org.apache.accumulo.core.crypto.CryptoUtils.writeParams(CryptoUtils.java:65)
        at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Reader.serializeMetadata(BCFile.java:585)
        at org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile$Reader$BCFileLoader.load(CachableBlockFile.java:229)
        at org.apache.accumulo.core.file.blockfile.cache.lru.SynchronousLoadingBlockCache.getBlock(SynchronousLoadingBlockCache.java:127)
        at org.apache.accumulo.core.file.blockfile.cache.lru.SynchronousLoadingBlockCache.resolveDependencies(SynchronousLoadingBlockCache.java:64)
        at org.apache.accumulo.core.file.blockfile.cache.lru.SynchronousLoadingBlockCache.getBlock(SynchronousLoadingBlockCache.java:109)
        at org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile$Reader.getMetaBlock(CachableBlockFile.java:385)
        at org.apache.accumulo.core.file.rfile.RFile$Reader.<init>(RFile.java:1156)
        at org.apache.accumulo.core.file.rfile.RFile$Reader.<init>(RFile.java:1251)
        at org.apache.accumulo.core.file.rfile.RFileOperations.getReader(RFileOperations.java:53)
        at org.apache.accumulo.core.file.rfile.RFileOperations.openReader(RFileOperations.java:68)
```

### PR DESCRIPTION
**Pull request by milleruntime**
I tested this upgrading from 1.9-snapshot to 2.0-snapshot

### CODE REVIEW

**Comment by keith-turner** [comment]
It would be nice if a test showed this problem.  There is a unit test that ensures older versions of RFile work.  I wonder if it needs to use cahce or something to have this failure.

File: core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java [hunk 1]
```diff
@@ -634,6 +635,7 @@ public long getRawSize() {
       // backwards compatibility
       if (version.equals(API_VERSION_1)) {
         LOG.trace("Found a version 1 file to read.");
+        decryptionParams = new NoFileEncrypter().getDecryptionParameters();
```
Comment (ctubbsii) [inline core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java]: Should probably just call "this.decrypter.getDecryptionParameters()" after the next line instead of constructing "NoFileEncrypter" twice.

Comment (milleruntime) [reply core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java]: The NoFileEncrypter class is only used to get the "no crypto" decryption params.  The next line uses NoFile**D**ecrypter and stores that locally to pass around.

**Comment by milleruntime** [comment]
> It would be nice if a test showed this problem. There is a unit test that ensures older versions of RFile work. I wonder if it needs to use cahce or something to have this failure.

I am not sure if we can replicate it but I will give it a try.

File: core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java (hunk 1 above)
Comment (ctubbsii) [reply core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java]: Oh my mistake. I misread both objects as the same class.

**Comment by milleruntime** [comment]
@keith-turner I was able to add cache to the old version tests in 80129d0
